### ISSUE TITLE
affected code doesn't get jsonified correctly

### ISSUE THREAD

**Issue by sils** [coala/coala#1117]
Important bug which we should fix ASAP! Example:

```
{
  "logs": [],
  "results": {
    "docs": [],
    "pythoncheck": [
      {
        "affected_code": [
          {
            "file": "/home/lasse/prog/coala/coalib/results/TextPosition.py"
          }
        ],
        "debug_msg": "",
        "diffs": null,
        "id": 4361759378109163843252483817076909021,
        "message": "Line is longer than allowed. (82 > 79)",
        "origin": "LineLengthBear",
        "severity": 1
      }
    ]
  }
}
```

As you can see there's no `start` or `end` property in the JSON.
- [x] @Makman2 can you look into this also? You broke it with the TextRange thing I guess.
- [ ] We need a test against our JSON output.

**Comment by sils1297** [comment]
(I love gitmate autolabelling.)

**Comment by sils1297** [comment]
might be solvable with https://github.com/coala-analyzer/coala/issues/1024

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1118 fixes the bug so we only need a test after that is merged.

**Comment by sils1297** [comment]
fixed the bug, test remains to do

**Comment by sils1297** [comment]
This needs a simple integration test to be added in `coalaTest.py` or so, that's newcomer friendly.

**Comment by sils1297** [comment]
@rresol still interested in dpoing this?

**Comment by rresol** [comment]
go on with fixing it . I will get back to work on some other ones.

**Comment by Adrianzatreanu** [comment]
is this still valid @sils1297 ? since bears are no longer here.

**Comment by sils1297** [comment]
Tests need to be written here, not newcomer, but this is a coala issue, the bears just spit out results coala should have tests for the JSON output coverig this.

**Comment by sils** [comment]
ok the main issue has been fixed due to nobody having time I'm closing this without adding a testcase :/
