### ISSUE TITLE
Add bear binary

### ISSUE THREAD

**Issue by sils1297** [coala/coala#1304]
we want to move bears out of the coala main repository into own pip packages. That means we probably want some binary like `coala-bears` that allows you to search pypi for coala bear packages and install them. (Essentially only a wrapper aroiund pip, it shouldn't be more since they can do that stuff better than we can.)

**Comment by sils1297** [comment]
This project would end up in an own repository

**Comment by AbdealiJK** [comment]
Atom has done something similar where they have a `apm` which is built on top of `npm`.

**Comment by AbdealiJK** [comment]
We may want to use `conda` for something like this ? It would seem that conda is considerably better when non-python packages are involved. Something that our bears are increasingly doing

http://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda#20994790

**Comment by AbdealiJK** [comment]
@sils1297 can you make a repository ?

**Comment by sils1297** [comment]
@AbdealiJK sure give me a name

**Comment by sils1297** [comment]
created https://github.com/coala-analyzer/coala-bears

**Comment by AbdealiJK** [comment]
Im confused - why is this in an own repository ? I thought the repository was for https://github.com/coala-analyzer/coala/issues/1047

Or do you want a new repo for each bear like `PEP8Bear.py` ?
I was thinking it'd be easier to simply make a single repo with all bears (each having it's own `setup.py`)
We'd have about 30 repositories if we make 1 repo per bear

**Comment by sils1297** [comment]
No the repository should contain all the bears, you're getting it right.

**Comment by AbdealiJK** [comment]
Related discussion going on on google group - https://groups.google.com/forum/#!topic/coala-devel/p7lfVyg3nV4

**Comment by Adrianzatreanu** [comment]
i guess this calls for me

**Comment by Adrianzatreanu** [comment]
hooray
