### ISSUE TITLE
Settings Guessing

### ISSUE THREAD

**Issue by sils** [coala/coala#1348]
We want coala to be able to generate a config from some source code. Possible means to do that are written down in https://github.com/coala-analyzer/coala/issues/1079 and https://github.com/coala-analyzer/coala/issues/568 . This needs a proper concept first.

**Comment by sils1297** [comment]
Possible approach:

---

yeah, so this is more about providing a generic way to detect settings, that could be e.g. that a bear can suggest a number of possible reasonable default values
and coala would run that bear on the project multiple times
with different settings
and check which settings yield a lower result count
this one is totally generic to any analysis routine

**Comment by AbdealiJK** [comment]
I think asking the bear for possible values is a bit far fetched... Imagine a bear that gives 4 possible values - running coala 4 times on a project is a bad idea and would be too slow!
It is a nice method in theory, but really doesn't work out in practice.

I remember there is a linter which has settings guessing (css or js or html ? linters) [We have a bear for this linter]. We can see how they implement it and get better ideas

**Comment by sils1297** [comment]
I think jscs did it this way with it's checkers

**Comment by hypothesist** [comment]
From the discussion on gitter, there are multiple approaches to solve this (I'll list all the solutions and bold the agreed upon one for documentation purposes):

* Running coala multiple times on the entire code base.
* Implementing a coalib library for bears to estimate the variations in code style and return back to the main program.
* Giving a single sample file (that is not a part of the code base) and guessing the best settings.
* **Giving sampling globs on which coala will be run multiple times.**

Going forward with the 4th option (as it's fast, customizable, and reliable at the same time): something like 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`coala --guess=needed --sample-size=3 --files=**/*.py --bears=PyImportSortBear`

 would basically sample from the first three `.py` files. The sample size can be made optional.

To give the user the choice of using a different standard, after sampling the files, we could prompt the user for his choice among the variations.

However a better and a smoother approach is to have the **variation settings** (the ones that are not the most frequent) placed in the generated coafile **as comments** for the user to choose from. This way it gives the user the power, yet automates the whole task. We could also include a brief description of each alternative setting to educate the user.

I'll keep looking into more approaches implemented elsewhere too.

**Comment by hypothesist** [comment]
We also discussed about having style packages for each language. For instance, in C/C++,

```
while (x == y) {
    something();
    somethingelse();
}
```

is called the K&R style. There are several alternatives like the GNU style:

```
while (x == y)
  {
    something();
    somethingelse();
  }
```

the Allman style:

```
while (x == y)
{
    something();
    somethingelse();
}
```

... and so on. We could prompt the user to choose one style and populate the coafile appropriately.

**Comment by hypothesist** [comment]
I reasearched similar features implmented elsewhere for more approaches we can discuss:

* [jscs](https://github.com/jscs-dev) - They have gone with [approach 1](https://github.com/jscs-dev/node-jscs/issues/797) - basically run the linter for each preset (in their project, a preset is a pre-defined set of rules) and get the violations for each. They display this to the user and allow them to choose. So it's not entirely automated. Also I suspect this will be slow on a big project. Another problem is that this will scale really badly as the number of bears increases.

I'll keep adding more stuff to this as I find out more.

**Comment by Adrianzatreanu** [comment]
assigned @hypothesist as its his project :p

**Comment by Adrianzatreanu** [comment]
@adtac maybe you'll consider doing this at some point

**Comment by adtac** [comment]
thanks, @Adrianzatreanu

**Comment by adtac** [comment]
@Adrianzatreanu I will, maybe I'll do a GSoC on this project! That's a good idea!

**Comment by adtac** [comment]
Closing in favour of https://github.com/coala/coala/issues/1348

**Comment by adtac** [comment]
Sorry, this was closed in favour of https://github.com/coala/coala-quickstart/issues/129 :P
