### ISSUE TITLE
No matching bears found message can be improved

### ISSUE THREAD

**Issue by sils** [coala/coala#1476]
currently it says e.g. `No bears were found matching 'pyLintBear'.` I think it reads more nicely if we just say `No bears matching 'pyLintBear' were found.` Anyone disagree?

difficulty/newcomer

**Comment by Makman2** [comment]
I have no problems with the current message^^

**Comment by Makman2** [comment]
nvm^^

**Comment by AbdealiJK** [comment]
Fixing this, as im in the vicinity and it's irritating :/

**Comment by mayank26saxena** [comment]
@sils1297 can you assign this issue to me? I'm a newcomer and I'm working on this.

**Comment by sils1297** [comment]
Please don't ping me specifically. I get pinged for everything around here and I'm actually on vacation. If you ping me everyone will think "oh @sils1297 will do it" and you'll actually have to wait longer.

**Comment by mayank26saxena** [comment]
Oh, I'm sorry. I will not do this again.

**Comment by sils1297** [comment]
no problem, you couldn't know. Spread the word :P

**Comment by mayank26saxena** [comment]
Haha, sure. Sorry once again :P
