### ISSUE TITLE
coala-ci Show patch by default

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1526]
Earlier, we gave coala-ci some output and letting it show affected files.
It would be even more awesome to let users use the default action - `ShowPatchAction`

With this we'd also be able to see the patch proposed making things simpler.

**Comment by Makman2** [comment]
:+1:

**Comment by AbdealiJK** [comment]
There is no method to override the `default_actions` of all the sections :(
We need some method to "override a setting from all section" in the cli args

**Comment by sils1297** [comment]
I actually don't think we want to reuse that mechanism as it doesn't work like this, we can just hardcode the "show patch if one is there" into the noninteractive console interaction output maybe? That's twoish NCLOC.

**Comment by Makman2** [comment]
@AbdealiJK you can just pass `default_actions` over CLI. @sils1297 wasn't it anyway planned to support some `all` bear, so `default_actions = all: ApplyPatchAction` or else would be possible?

**Comment by AbdealiJK** [comment]
@Makman2 passing it over cli is not good, because if another section uses `default_action` it will override it and try a patch or something else

**Comment by Makman2** [comment]
doesn't CLI override coafile settings?

**Comment by sils1297** [comment]
I just don't want a setting for that. Setting default actions isn't the right thing because those are suppressed anyway. We have:

```python
    if interactive:
        acquire_actions_and_apply(console_printer,
                                  log_printer,
                                  section,
                                  file_diff_dict,
                                  result,
                                  file_dict)
```

and we can just add an else that just applies the ShowPatchAction in the noninteractive case. That's literally two lines of code and not complicating the settings further.

**Comment by AbdealiJK** [comment]
@Makman2 my understanding is `-S default_actions=value` overrides default section settings, not all sections

**Comment by AbdealiJK** [comment]
@sils1297 I dislike the adding `else` ... I would prefer allowing certain actions in `coala-ci` and setting all of them to `ShowPatchAction` - seems cleaner to me.

**Comment by AbdealiJK** [comment]
Maybe we want to add the `if-else` for now as I don't think https://github.com/coala-analyzer/coala/issues/1546 is going to get solved any time soon as it requires quite a bit of revamping.

The `if-else` would make things like autopep8, MarkdownBear, etc much easier to use with coala-ci (The ones where we don't have good descriptions)

**Comment by Makman2** [comment]
we got now auto-show for bears that match a glob!
```
default_actions = *: ShowPatchAction
```

**Comment by AbdealiJK** [comment]
But coala-ci doesn't even try to execute actions as it's NonInteractive
right?

**Comment by Makman2** [comment]
ah is that the problem? just tried and it seems so :3
sorry then :+1:

**Comment by Makman2** [comment]
From @sils1297 
> We currently print the patch in `coala` by default, can't we just copy the functionality?

**Comment by sils1297** [comment]
@chauffer just had this as well, I think we should do this ASAP.

**Comment by Udayan12167** [comment]
I don't gather where do you want the put the if-else? in the coala-ci binary itself?

**Comment by sils** [comment]
ConsoleInteraction, or maybe just do https://github.com/coala/coala/issues/1526#issuecomment-223872379 ?

**Comment by Udayan12167** [comment]
Hmm so the `*` means that it overrides all sections?

**Comment by sils** [comment]
* matches all possible bears

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment]
Does the commit fix the issue? Imo this still doesn't display the patch :O

**Comment by sils** [comment]
oh that's right indeed!

**Comment by sils** [comment]
@Udayan12167 you need to set the default action by default to show patches!

**Comment by sils** [comment]
@Udayan12167 taking over
