### ISSUE TITLE
circleci: Use docker

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1622]

**Comment by AbdealiJK** [comment]
I was trying this for some time now - and realized that there are a fair number of issues.
First, docker image cache is not good. We need to export the containers into a tar file and then cache th directory. And even when we do that, docker will not use it as the time modified on the file is messed up.

All in all, it's pretty complicated - there are pretty ugly hacks like http://tschottdorf.github.io/cockroach-docker-circleci-continuous-integration/
But the cache, import,export takes time.
All in all, I'd suggest to not transition right now - we'd rather do it after circleci's docker support gets out of beta.

**Comment by AbdealiJK** [comment]
Marking as blocked by upstream as circleci needs to get better docker support before we try this

**Comment by jayvdb** [comment]
We definitely do not need docker just for normal builds of the coalib package.  On bears, maybe.  I am sure our options on Circle/Travis/etc would need to be re-evaluated.
Closing this blocked upstream task.

**Comment by jayvdb** [comment]
> We definitely do not need docker just for normal builds of the coalib package. 

I should clarify ... that is for normal builds.  However, for complex changes which impact bears, I think we need this.  See https://github.com/coala/coala/issues/4115
