### ISSUE TITLE
help(coalib) isnt very helpful

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1663]
Currently `import coalib` followed by `help(coalib)` is not very useful. It just gives a list of packages inside. We should ideally have a description of coala/coalib there too.

I think we need to add a doc-comment  in coalib.__init__.py which gives better information.

We could also use this in the `setup.py` maybe ?

**Comment by AdeshAtole** [comment]
Can I do this?

**Comment by sils1297** [comment]
@AdeshAtole hey, you've got an invitation to our team. Accept at github.com/coala-analyzer and we can assign you.

**Comment by sils1297** [comment]
thanks for your interest :)

**Comment by AdeshAtole** [comment]
@sils1297 I have accepted the invite

**Comment by AbdealiJK** [comment]
@AdeshAtole I've assigned this to you

**Comment by AdeshAtole** [comment]
@AbdealiJK Please unassign me from this issue. I already have a PR merged for a newcomer issue.

**Comment by AbdealiJK** [comment]
done

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#54

**Comment by wimpykid26** [comment]
Can I work on this?

**Comment by sils1297** [comment]
Sure! Let us know if you need anything or if the issue is unclear!

**Comment by wimpykid26** [comment]
@sils1297 I am a complete newbie to coala. Where do I find the coalib.init.py file? and what description needs to be shown after running help(coalib)?. Thanks in advance!

**Comment by sils1297** [comment]
For the `help` thingie you'll have to google how python does that. The file you want to look at is probably `coalib/__init__.py`

**Comment by wimpykid26** [comment]
@sils1297 What does 'description of coala/coalib' mean in the issue statement. A general overview of what the library does?
