### ISSUE TITLE
Don't build_manpage for windows

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1694]
Man pages aren't needed for windows - let's not build them and waste time there (Apparently it has issues in appveyor sometimes too)

**Comment by souravsingh** [comment]
I would like to help in the issue.How do I start?

**Comment by sils1297** [comment]
Hi, all you need should be in setup.py, we have some methods to detect platform but I have lost track @Makman2 can help you. Otherwise you're assigned and free to work on this :)

THanks for your support.

**Comment by AbdealiJK** [comment]
We use `platform.system()` to find the OS.

**Comment by sils1297** [comment]
@souravsingh are you still/have you started/do you still intend working on this?

**Comment by souravsingh** [comment]
@sils1297 I have started the work on the issue.

**Comment by sils1297** [comment]
Thanks!

**Comment by sils1297** [comment]
We just sometimes check up especially on new participants, that doesn't mean you need to work faster. We just want a ping sometimes :)

**Comment by AbdealiJK** [comment]
@souravsingh still on this ?

**Comment by souravsingh** [comment]
@AbdealiJK I am working on it.

**Comment by Adrianzatreanu** [comment]
@souravsingh need help :) ?

**Comment by Adrianzatreanu** [comment]
Unassigning due to inactivity. Feel free to message me if you want me to re-assign you at any time, @souravsingh :)

**Comment by souravsingh** [comment]
@Adrianzatreanu I would like to work on the issue.

**Comment by Makman2** [comment]
@souravsingh ping

**Comment by souravsingh** [comment]
pong

**Comment by Makman2** [comment]
@souravsingh any progress? :)

**Comment by souravsingh** [comment]
I am working on the PR. Will send it real quick

**Comment by Adrianzatreanu** [comment]
ping @souravsingh

**Comment by souravsingh** [comment]
@Adrianzatreanu I was away for a while.I will work on the issue

**Comment by Adrianzatreanu** [comment]
ping @souravsingh

**Comment by souravsingh** [comment]
@Adrianzatreanu I will start work on the issue

**Comment by nemaniarjun** [comment]
Assign me this. I don't think @souravsingh is working on it
