### ISSUE TITLE
Error in acquiring settings, while running coala-ci 

### ISSUE THREAD

**Issue by abhsag24** [coala/coala#1709]
so here is the bear that i run 

```
from coalib.bears.LocalBear import LocalBear

class Errorbear(LocalBear):

    def run(self,
            filename,
            file,
            indent_types: dict,
            comments: dict,
            tab_width: int=4):
            pass
```

and running `coala-ci -L DEBUG` gives the following error and traceback 

```
ERROR][00:58:32] During execution, we found that some required settings were not provided. They are:
comments (from Errorbear) - No description given.indent_types (from Errorbear) - No description given.
[ERROR][00:58:32] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][00:58:32] Exception was:
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev0-py3.4.egg/coalib/coala_main.py", line 69, in run_coala
    autoapply=autoapply)

  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev0-py3.4.egg/coalib/settings/ConfigurationGathering.py", line 251, in gather_configuration
    log_printer)

  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev0-py3.4.egg/coalib/settings/SectionFilling.py", line 38, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev0-py3.4.egg/coalib/settings/SectionFilling.py", line 90, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings)

  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev0-py3.4.egg/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError

```

it should be noted that i did not provide any values for this setting in the coafile 

difficulty/low

**Comment by sils1297** [comment]
Preferred solution is simply raising SystemExit and introducing a new exitcode in the appropriate docs.

**Comment by vidhan13j07** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
sure :)

**Comment by rresol** [comment]
@vidhan13j07  are you still working on the issue ?

**Comment by Adrianzatreanu** [comment]
Assigning @rresol if @vidhan13j07 doesnt respond within a day.

**Comment by Makman2** [comment]
@rresol ping

**Comment by Adrianzatreanu** [comment]
Hi,

do you need help figuring this out? We're all happy to help you on [our gitter channel](https://gitter.im/coala-analyzer/coala), just drop by and ask us anything :)

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity, feel free to message me and get assigned back as soon as you respond @rresol :)

**Comment by mgracer48** [comment]
Ill do this if i get help :)

**Comment by sils1297** [comment]
Probably best to ask for help on gitter, usually people read it and try to
figure it out and you'll receive only responses from people who have
figured out something helpful

**Comment by sils1297** [comment]
Changing the AssertionError to SystemExit and addint a debug print would be sufficient I think

**Comment by nemaniarjun** [comment]
Is this still required? I can take this up.

**Comment by sils** [comment]
@mgracer48 ? Haven't seen him around lately.

**Comment by jiteshpabla** [comment]
I can take this up, if @mgracer48 is busy.

**Comment by Makman2** [comment]
reassigning because of inactivity :+1:

**Comment by RJ722** [comment]
@jiteshpabla You still up on this?

**Comment by jiteshpabla** [comment]
@RJ722 I'm back on this.

**Comment by RaiVaibhav** [comment]
@Makman2  @sils @Adrianzatreanu, I would like to work on this, If I am correct then to recreate a error I have to create a  `.coafile` which consist
```
[Default]
files = mycheck.py
bears = Errorbear
```

and A create a bear `Errorbear` and I have to integrate it locally for testing, and after that I have to raise `SystemExit ` instead of `AssertionError` if setting is not there and print a small message that `setting not provided`or something like that and accordingly change the `test`.

Note: `mycheck.py` is default python file for testing.

**Comment by ishanSrt** [comment]
Unable to recreate this error

**Comment by Makman2** [comment]
Highly probable that we fixed it during the last 2 years. If somebody still encounters this with the latest master, please comment.

**Comment by RaiVaibhav** [comment]
@Makman2 Yes It may be a chance that It get fixed but, what if someone don't give any input to through command line( just pressed enter) then [.coafile will be like something this](https://pastebin.com/W38StbVb) . There have to be some `error` like `no setting provided`  and system exit, doesn't `fail_acquire_settings` have to be called there to check.?

**Comment by Makman2** [comment]
I mean if you can't reproduce the bug should be gone, shouldn't it? :smile: 
In case you think there's a bug, try to reproduce it and write your report here if you think it's the same issue. If not, open a new issue :)
