### ISSUE TITLE
Whitespace-highlighting: Also highlight newline

### ISSUE THREAD

**Issue by Makman2** [coala/coala#1841]
We could use `↲`, or `¶` or something else :)

Blocked by https://github.com/coala-analyzer/coala/issues/1840.

**Comment by SanketDG** [comment]
@Makman2 In what situations might this be helpful to the user?

I can't think of anything other than for aesthetic reasons.

**Comment by Makman2** [comment]
this can be implemented after #1840, I'm refactoring the bullet printing, it took me really too much time to understand what to provide for `tab_dict` and `index` arguments.
When #1840 is done the function is general-purpose, it makes sense to print also newlines for such a function (though coala can indeed disable it). And it can be helpful to detect missing \n at EOF, SpaceConsistencyBear already checks for that^^

**Comment by Makman2** [comment]
Should be fairly easy to adapt a pygments filter to allow to print those^^

**Comment by Sanny26** [comment]
@Makman2  Could you please help me understand where I'm going wrong?
When I run py.test after making necessary changes, it fails for the multiple ranges test and I can't really understand why. Is it because of the SourceRange.from_values() ? I attached the image here
![coala](https://cloud.githubusercontent.com/assets/16081303/22079011/4aa4d436-dde0-11e6-8fec-4bdc741d4094.png)
I need help to understand why the pilcrow symbol comes before n? Is it because the start_column is assigned to 3 for the test case?

**Comment by Makman2** [comment]
Could be. Would be good if you open a PR so me or somebody else can look at your specific code. Especially as this is not directly relevant for issue discussion ;)

**Comment by Sanny26** [comment]
@Makman2  I opened a PR. Could you please help me with this?

**Comment by Makman2** [comment]
Btw by default this shall be disabled. It makes only sense to highlight when having a missing \n at EOF.

**Comment by Sanny26** [comment]
@Makman2  Correct me if I'm wrong, one part of the issue is to highlight the missing \n at EOF by default and another part of it is to give the user a choice to enable printing a special character whenever it encounters a \n .
And sorry for not reading the issue properly.

**Comment by Makman2** [comment]
actually I remember we have an issue open and already worked on to support printing missing \n's in the `Diff`. Actually I'm not sure we still need the feature described in the issue here. @Sanny26 what do yo u think?

**Comment by Sanny26** [comment]
@Makman2 I agree with you, I think it is not necessary. So, I have to provide a feature that prints special character for every \n when it is enabled? Is this feature helpful?
I had another doubt, not sure if its relevant, in what all cases does coala print code snippets to console?

**Comment by Makman2** [comment]
affected source code of a result is always printed. And for patches: when they are small enough they get printed automatically, otherwise you have to choose to display the patch manually.

As you agree, I close this issue :+1: :)
