### ISSUE TITLE
use unittest.mock

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1882]
Would be nice to use https://docs.python.org/3/library/unittest.mock.html

It would make our tests more unit test like - modularised and independent of the rest of the code

**Comment by Makman2** [comment]
ouh yeah this is cool, let's do that :+1:

**Comment by sils1297** [comment]
ok apparently @Makman2 has started using it, we need to identify places where we override stuff and use mock there to make it clean

**Comment by Makman2** [comment]
Checklist on tests to check for this. If a file is checked, I (or someone else
can) tick it. If possible refactors are found, post them or I edit them into
the task list.

Every file is relative to the `tests` folder.

- [ ] `bearlib/abstractions/LintTest.py`
- [ ] `bearlib/abstractions/SectionCreatableTest.py`
- [ ] `bearlib/languages/documentation/DocstyleDefinitionTest.py`
- [ ] `bearlib/languages/documentation/DocumentationCommentTest.py`
- [ ] `bearlib/languages/documentation/DocumentationExtractionTest.py`
- [ ] `bearlib/languages/LanguageDefinitionTest.py`
- [ ] `bearlib/spacing/SpacingHelperTest.py`
- [ ] `bears/BearTest.py`
- [ ] `bears/GlobalBearTest.py`
- [ ] `bears/LocalBearTest.py`
- [ ] `collecting/CollectorsTest.py`
- [ ] `collecting/DependenciesTest.py`
- [ ] `collecting/ImportersTest.py`
- [ ] `misc/BuildManPageTest.py`
- [ ] `misc/ContextManagersTest.py`
- [ ] `misc/DecoratorsTest.py`
- [ ] `misc/DictUtilitiesTest.py`
- [ ] `misc/EnumTest.py`
- [ ] `misc/ExceptionsTest.py`
- [ ] `misc/ShellTest.py`
- [ ] `misc/StringConverterTest.py`
- [ ] `output/dbus/BuildDbusServiceTest.py`
- [ ] `output/dbus/DbusAppTest.py`
- [ ] `output/dbus/DbusDocumentTest.py`
- [ ] `output/dbus/DbusServerTest.py`
- [ ] `output/dbus/DbusTest.py`
- [ ] `output/printers/EspeakPrinterTest.py`
- [ ] `output/printers/HTMLWriterTest.py`
- [ ] `output/printers/ListLogPrinterTest.py`
- [ ] `output/printers/LogPrinterTest.py`
- [ ] `output/printers/StringPrinterTest.py`
- [ ] `output/ConfWriterTest.py`
- [ ] `output/ConsoleInteractionTest.py`
- [ ] `output/InteractionsTest.py`
- [ ] `output/JSONEncoderTest.py`
- [ ] `output/TaggingTest.py`
- [ ] `parsing/StringProcessing/EscapeTest.py`
- [ ] `parsing/StringProcessing/InBetweenMatchTest.py`
- [ ] `parsing/StringProcessing/LimitTest.py`
- [ ] `parsing/StringProcessing/MatchTest.py`
- [ ] `parsing/StringProcessing/NestedSearchInBetweenTest.py`
- [ ] `parsing/StringProcessing/SplitTest.py`
- [ ] `parsing/StringProcessing/TrimEmptyMatchesTest.py`
- [ ] `parsing/StringProcessing/UnescapedSearchForTest.py`
- [ ] `parsing/StringProcessing/UnescapedSearchInBetweenTest.py`
- [ ] `parsing/StringProcessing/UnescapedSplitTest.py`
- [ ] `parsing/StringProcessing/UnescapedStripTest.py`
- [ ] `parsing/StringProcessing/UnescapeTest.py`
- [ ] `parsing/CliParsingTest.py`
- [ ] `parsing/ConfParserTest.py`
- [ ] `parsing/GlobbingTest.py`
- [ ] `parsing/LineParserTest.py`
- [ ] `processes/communication/LogMessageTest.py`
- [ ] `processes/BearRunningTest.py`
- [ ] `processes/LogPrinterThreadTest.py`
- [ ] `processes/ProcessingTest.py`
- [ ] `results/result_actions/ApplyPatchActionTest.py`
- [ ] `results/result_actions/OpenEditorActionTest.py`
- [ ] `results/result_actions/PrintDebugMessageActionTest.py`
- [ ] `results/result_actions/ResultActionTest.py`
- [ ] `results/result_actions/ShowPatchActionTest.py`
- [ ] `results/result_actions/Test.py`
- [ ] `results/DiffTest.py`
- [ ] `results/HiddenResultTest.py`
- [ ] `results/LineDiffTest.py`
- [ ] `results/ResultFilterTest.py`
- [ ] `results/ResultTest.py`
- [ ] `results/RESULT_SEVERITYTest.py`
- [ ] `results/SourcePositionTest.py`
- [ ] `results/SourceRangeTest.py`
- [ ] `results/TextPositionTest.py`
- [ ] `results/TextRangeTest.py`
- [ ] `settings/ConfigurationGatheringTest.py`
- [ ] `settings/DocumentationCommentTest.py`
- [ ] `settings/FunctionMetadataTest.py`
- [ ] `settings/SectionFillingTest.py`
- [ ] `settings/SectionTest.py`
- [ ] `settings/SettingTest.py`
- [ ] `coalaCITest.py`
- [ ] `coalaDbusTest.py`
- [ ] `coalaDeleteOrigTest.py`
- [ ] `coalaFormatTest.py`
- [ ] `coalaJSONTest.py`
- [ ] `coalaTest.py`
- [ ] `MakeTempTest.py`

I hope this is no overkill, but then we don't miss something^^
I know we often use `old_` or similar to prefix such function patching, but not everytime^^

**Comment by AbdealiJK** [comment]
I really don't think this is worth it ...
We should just change things we find when we're refactoring things. Let it be a "tracking" task

**Comment by Makman2** [comment]
I think then we forget the stuff from `unittest.mock` again :P

**Comment by AbdealiJK** [comment]
Well, the reviewers need to remember it. I think that's alright

**Comment by AbdealiJK** [comment]
I began using it in https://github.com/coala-analyzer/coala/commit/f1eb9a3225766632db7204d1121ff4dc99de79fc and https://github.com/coala-analyzer/coala/commit/1708f5572dc3306862e1cfaee668d761e351c443

This is actually pretty great because earlier, if I do `from module1.module2 import func1` it is not possible to override the `func1()`. Only `from module1.module2 import class1` was overridable.
But the `patch` can do functions as well, which I think is awesome.

**Comment by jayvdb** [comment]
We are using mock in places, and most coders and reviewers are familiar with it by now.

The tracking list is very out of date.  Create separate issues if there are specific areas which need to be rewritten to use mock.

Otherwise, we improve as we go along.
