### ISSUE TITLE
Add more strings to Constants

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#1969]
Our Constants are located in coala/coalib/misc/Constants.py and there we hold options for ``TRUE_STRINGS``. I think we should expand these true strings with more options, such as : ``yep``,``ja`` or even ``hell yeah`` (who knows what the user might come up with). Feel free to add your own suggestions if you think they fit.

**Comment by rubdos** [comment]
`ya`, `da`

No side:

`njet`, `nee`, `nein`

As long as one doesn't mean the other in another language, you're fine :p

**Comment by Adrianzatreanu** [comment]
``njet`` ?

**Comment by rubdos** [comment]
`нет`, if you wish and if your .coafile supports unicode ^^.

**Comment by yashhsethiya** [comment]
want to get assigned

**Comment by Adrianzatreanu** [comment]
Sure thing! Good luck on it.

**Comment by Adrianzatreanu** [comment]
hey @yashhsethiya are you still working on this :)? if you need help feel free to contact us on gitter! https://gitter.im/coala-analyzer/coala

**Comment by erickzhao** [comment]
Newcomer here: would like to be assigned to this since @yashhsethiya doesn't seem to be working on it.

**Comment by sils** [comment]
@erickzhao there you go! Feel free to take up existing work. If you do, make sure to mention @yashhsethiya as co author.

**Comment by Makman2** [comment]
what about `hai` (`はい`) and `iie` (`いいえ`)? :P
