### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2019]
IntelliJ is great, we definitely should do that.

**Comment by meetmangukiya** [comment]
IntelliJ is a Java IDE. So do we want `coala` plugin to only lint Java stuff?

**Comment by sils1297** [comment]
Not sure, can you look at the eclipse plugin as well as the atom plugin? CC @AbdealiJK @arafsheikh

**Comment by Makman2** [comment]
isn't IntelliJ the base IDE for all other descendants, like PyCharm and CLion?

**Comment by sils1297** [comment]
I think so, IMO we should do it generically and make sure it works properly
with all jetbrains IDEs.

**Comment by AbdealiJK** [comment]
IntelliJ **Idea** is the Java IDE.
IntelliJ is the old name for JetBrains, the company behind Idea

IntelliJ idea is technically a Java IDE, but it has evolved to be pretty much everything. It currently supports [Python](https://plugins.jetbrains.com/plugin/?idea&pluginId=631), [AppleScript](https://plugins.jetbrains.com/plugin/8149), [Angular JS](https://plugins.jetbrains.com/plugin/6971), [CoffeeScript](https://plugins.jetbrains.com/plugin/7723), [Dart](https://plugins.jetbrains.com/plugin/6351), etc. through plugins.

It has variants like Idea, PHPStorm, PyCharm, WebStorm, RubyMine, CLion, etc. which are essentially the base IntelliJ idea with more plugins specific to the corresponding language. i.e. you can use any of the languages in any of the IDEs by installing plugins.

If you make a plugin for any of these, it's available in all the others, as it uses the same plugin store - https://plugins.jetbrains.com/

**Comment by Makman2** [comment]
That was my intention :)

**Comment by meetmangukiya** [comment]
I see, that's nice, I'll take a look at that link.

**Comment by gaocegege** [comment]
After https://github.com/coala/coala/issues/2685 is done, I would take a look, at least I'll do a feasibility study. 🤔

**Comment by gaocegege** [comment]
I have put this issue to [projects.coala.io](https://projects.coala.io) as a GSoC and RGSoC project.

Jetbrains IDEs are more complex than visual studio code, sublime text and many other editors. 

It's hard to hook into file save or change logic. So we should find a way to interact with editors. [Can I hook into the file save logic?](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206790685-Can-you-tie-into-the-file-save-logic-) could help us.

## Useful links

* [Plugin Development Guidelines - IntelliJ IDEA 2016.3 Help](https://www.jetbrains.com/help/idea/2016.3/plugin-development-guidelines.html)
* [Creating Your First Plugin - IntelliJ Platform SDK DevGuide](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html)
* [Plugin Development FAQ - IntelliJ Platform SDK DevGuide](http://www.jetbrains.org/intellij/sdk/docs/faq.html)
* https://github.com/coala/projects/pull/139

**Comment by anctartica** [comment]
@traff I am developer at coala and interested in this project to develop plugin that is able to support coala as well as mypy and pylint integration. 
So, the community is looking for a general way on writing a static code analysis plugin?
I have started looking into the plugins development process for the JetBrains IDE and will be able to draft a proposal in a day or two.

**Comment by jayvdb** [comment]
We have https://projects.coala.io/#/projects?project=plugin_for_jetbrains_ides

I dont think we need this issue any more.  It wont be solved by anything being done in this repo.

**Comment by pheanex** [comment]
Is there any way to track progress on this then if we close this here?

**Comment by Makman2** [comment]
Once implementation is going to start, it will happen in a new repository. We would track progress/issues/... there immediately :+1:

**Comment by Makman2** [comment]
It's now an official coala project, so we won't forget it ;)

**Comment by jayvdb** [comment]
@pheanex , are you interested in being a mentor on that project?  It would have been started this year, but the assigned mentor wasnt responsive to the students.

**Comment by jayvdb** [comment]
If so, edit https://github.com/coala/projects/blob/master/_projects/jetbrains-ide-plugin.md

**Comment by shivank1234** [comment]
Can I work upon this idea for GSOC'19?

**Comment by shivank1234** [comment]
Hey , would anyone like to mentor this project this year GSOC?
