### ISSUE TITLE
Move out decorators into packages

### ISSUE THREAD

**Issue by sils1297** [coala/coala#2027]
I'd love to use them in other projects.

The following people have acknowledged that changing the license to MIT is fine:

- @fneu 
- @AbdealiJK 
- @Makman2 
- @sils1297

According to git blame no more people need to be consulted for the change.

**Comment by sils1297** [comment]
@laxmena @djkonro hey, you have worked on the decorators.py, are you fine with us relicensing your work to MIT?

**Comment by djkonro** [comment]
@sils1297 No problem, that is fine with me. I would be happy to help with further contribution when I am done with some pressing school work I am occupied with right now.

**Comment by Adrianzatreanu** [comment]
closing with https://pypi.python.org/pypi/coala-decorators/0.1

**Comment by sils1297** [comment]
This isn't closed as the decorators module still exists in coala. This is resolved when we *use* that module.

**Comment by Adrianzatreanu** [comment]
also done.
