### ISSUE TITLE
Support editorconfig

### ISSUE THREAD

**Issue by sils** [coala/coala#204]
http://editorconfig.org/

Would be nice if we could generate a coafile from that.

**Comment by sils1297** [comment]
i.e. just write a EditorConfigParser or so (although we don't want parsers to be objects anymore). Should be easy but it's not a priority, accepting patches.

**Comment by sims1253** [comment]
Was asked for at Linuxwochen so I reopen this.

**Comment by satwikkansal** [comment]
Generating coafile seems like a coala-quickstart thing and looks like this issue was created before quickstart even existed. Should we consider moving it to quickstart? (maybe club this with https://github.com/coala/coala-quickstart/issues/79)

**Comment by Makman2** [comment]
Yeah that really sounds like a coala-quickstart issue.

**Comment by Makman2** [comment]
I think https://github.com/coala/coala-quickstart/issues/79 is the right issue to refer to :)

Closing as the issue already exists in coala-quickstart.
