### ISSUE TITLE
Delete Lint Class

### ISSUE THREAD

**Issue by sils1297** [coala/coala#2049]
May happen only after the next release, so for 0.7 we can do this.

**Comment by AbdealiJK** [comment]
Can't this be done yet ? Why is this blocked ?

**Comment by sils1297** [comment]
Yes this can be done, it had a deprecation notice I think so if there was anyone who would still be using it he should have switched by now I hope.

**Comment by Makman2** [comment]
not yet, there are a few bears in `coala-bears` that still use `Lint`:
- XMLBear
- PyDocStyleBear
- RLintBear
- InferBear
- AlexBear

**Comment by Makman2** [comment]
rebased my old branch and opened PR: https://github.com/coala-analyzer/coala-bears/pull/722
Though the issues that arised that time are still not fixed^^

**Comment by Makman2** [comment]
got 2/5 working, the remaining three are here: https://github.com/coala-analyzer/coala-bears/pull/723

**Comment by sils1297** [comment]
uh oh!

**Comment by Makman2** [comment]
Every bear is refactored :)

**Comment by sils1297** [comment]
@Makman2 wanna do the removal?

**Comment by Makman2** [comment]
gimme a couple of days, need to get my project done, deadline is approaching^^
