### ISSUE TITLE
Linter: Warn on using capturing groups

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2070]
Capturing groups are superfluous, slightly slower and consume a bit more memory. They aren't taken anyway from the linter, so I think it's good to raise a warning that tells to use non-capturing-groups (so `(?:...)` instead of `(...)`) instead :+1:

**Comment by meetmangukiya** [comment]
If this issue is still relevant, I'd like to work on this.

**Comment by meetmangukiya** [comment]
hacktoberfest

**Comment by meetmangukiya** [comment]
Why not let coala convert the capturing groups into non-capturing groups ?

**Comment by meetmangukiya** [comment]
I need a bit more info @Makman2 , which regex have to be checked for not including capture groups, initially I assumed that this issue addressed the usage of capture groups in `output_regex` parameter, but as I read here https://github.com/coala/coala/blob/master/coalib/bearlib/abstractions/Linter.py#L675 it seems to be very well appreciated to use the capture groups -- that are specified.

So which regex are we talking about particularly in this issue :confused:

**Comment by sils** [comment]
@Makman2 can't we just assume the user uses linter responsibly?

**Comment by sils** [comment]
I'm not a fan of wasting performance and mind capacity to "protect the user from himself"

**Comment by sils** [comment]
I vote for closing this and the PR @meetmangukiya @Makman2

**Comment by Makman2** [comment]
This is no performance waste, the linter classes are loaded once, thus the check also happens once. Imo it's an improvement step (though a small one), we want the users to write performant bears (you told me that too).

> "protect the user from himself"

Many people coming here are asking many trivial things, we need to protect them^^

**Comment by meetmangukiya** [comment]
Whats the final vote @sils @makman2 ?

**Comment by sils** [comment]
@meetmangukiya what's yours?
