### ISSUE TITLE
Linter: Warn for named capturing groups which names are not used

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2071]
E.g. `(?P<filename>...)` is not used by the linter and should be replaced with `(?:...)`

**Comment by Asnelchristian** [comment]
can i work on this ?

**Comment by AbdealiJK** [comment]
This seems to be merged in coala-bears but the PR is still open because `Fixes` was not used.
Closing it.

**Comment by Makman2** [comment]
@AbdealiJK don't understand you :O this is about modifying `@linter` to make additional checks for unused capturing groups. And this isn't implemented yet^^

**Comment by Makman2** [comment]
@Asnelchristian still wanna work on this? :)

**Comment by Makman2** [comment]
btw. also positional matching groups shall be replaced with `(?: ...)` :+1:

**Comment by AbdealiJK** [comment]
Ah, sorry. I thought it was about modifying current LinterBears to not use it (which was done in the PR)

**Comment by Makman2** [comment]
no problem I've seen that this issue was not really well phrased :D

**Comment by nemaniarjun** [comment]
Would like to take this up, If no ones on it. Also will need a bit of help.

**Comment by Makman2** [comment]
@nemaniarjun oh sorry I think @meetmangukiya has it picked up implicitly on https://github.com/coala/coala/pull/2895 .
