### ISSUE TITLE
Readthedocs domain changes

### ISSUE THREAD

**Issue by sils** [coala/coala#2085]
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.

**Comment by hypothesist** [comment]
You may use this for reference: https://github.com/coala-analyzer/coala/search?utf8=%E2%9C%93&q=readthedocs

**Comment by jschwarzwalder** [comment]
On the homepage in the footer there is a link to ReadtheDocs.org

Does that need to be changed 

http://prntscr.com/bbzzas

**Comment by sils1297** [comment]
Yes, you can edit it at https://github.com/coala-analyzer/website

@d6e are you still working on this btw.? You closed your PR, do you need help?

**Comment by sils1297** [comment]
@jschwarzwalder oh that footer, that is generated I think so I don't think we can influence that. I thought you meant the links on coala-analyzer.org

**Comment by infi-pc** [comment]
looks like somebody fixed that, but didn't merge. @sils1297

**Comment by sils1297** [comment]
cool, feel free to take this on. If you reuse the changes from the other
author, keep his author information and add yourself as coauthor to the
commit message. Or just redo it, then you're author.

**Comment by hypothesist** [comment]
@infi-pc assigned you :+1:

**Comment by infi-pc** [comment]
sorry, I didn't have time to fix that during the workshop, i will leave it on somebody else

**Comment by hypothesist** [comment]
@infi-pc alright then, unassigning you

Feel free to come back to this when you feel like it :)

**Comment by vemurisaurabh** [comment]
I will take this up :+1:

**Comment by adtac** [comment]
@vemurisaurabh assigned you :+1:

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by madan96** [comment]
I would like to take up this issue.
