### ISSUE TITLE
Remove code duplication in printers

### ISSUE THREAD

**Issue by sils** [coala/coala#2109]
area/codestyle difficulty/low

```
coalib/output/printers/ListLogPrinter.py
|  22| ••••def•log_message(self,•log_message,•**kwargs):
|  23| ••••••••if•not•isinstance(log_message,•LogMessage):
|  24| ••••••••••••raise•TypeError("log_message•should•be•of•type•LogMessage.")
|  25| 
|  26| ••••••••if•log_message.log_level•<•self.log_level:
|  27| ••••••••••••return
|  28| 
|  29| ••••••••self.logs.append(log_message)

coalib/output/printers/LogPrinter.py
| 123| ••••def•log_message(self,•log_message,•**kwargs):
| 124| ••••••••if•not•isinstance(log_message,•LogMessage):
| 125| ••••••••••••raise•TypeError("log_message•should•be•of•type•LogMessage.")
| 126| 
| 127| ••••••••if•log_message.log_level•<•self.log_level:
| 128| ••••••••••••return
| 129| 
| 130| ••••••••self._print_log_message(
```

**Comment by ventris** [comment]
Assign me to this.

**Comment by Makman2** [comment]
@sils1297 so this is about removing the duplication? Don't understand your title^^

**Comment by sils1297** [comment]
Yes the title is wrong this is about duplication

**Comment by ventris** [comment]
Welp, that did not hit the mark... Will squash the commits.

**Comment by ventris** [comment]
Should one of them really be removed? They are not doing the same thing, and if the ListLogPrinter one is removed you get an recursion loop while running the tests.

**Comment by ventris** [comment]
This issue can be closed, the code is not duplicated as it calls for different things in the definition.

**Comment by sils1297** [comment]
The code is partially duplicated. You can't just remove the duplication, you have to adapt the code! :( In this case you can override `_print_log_message` to call the append to get rid of the duplication.
