### ISSUE TITLE
Wrong order for PEP and PyImportSort

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#2174]
So in my file I had: ``from coala_decorators.decorators import generate_repr, generate_eq`` and 2 newlines afterwards to comply to PEP8

I ran ``coala`` and it turned it into:

"""
from coala_decorators.decorators import generate_eq
from coala_decorators.decorators import generate_repr

@generate_eq("manager", "package", "version")
"""

It either did not put them both in a single line, and it also has cut one newline. This way it didnt comply to PEP8 anymore when i pushed
I dont think it should work like this.
probably pyimportsortbear should be ran instead of autoPEPbear?

**Comment by tylfin** [comment]
I'd like to be assigned this!

**Comment by Makman2** [comment]
I've sent out an invitation to you :)
After you've accepted I'll assign you, best is you ping me for that on the [gitter channel](https://gitter.im/coala/coala) :)
If you need help with anything in coala, you can get help there too :D

**Comment by tylfin** [comment]
@Adrianzatreanu I'm having difficulties recreating this issue, can you send the command you used or the .coafile?

**Comment by Adrianzatreanu** [comment]
i simply ran coala with the .coafile on the ``coala`` repository (that was at the time). maybe this was fixed in the mean time then involuntarily ^^ closing for now then
