### ISSUE TITLE
`coala --help` main description should wrap at 80 cols

### ISSUE THREAD

**Issue by underyx** [coala/coala#2258]
Pretty difficult/uncomfortable to read currently:

![](https://i.imgur.com/O3kI3TN.png)

**Comment by sils1297** [comment]
@scottbelden any idea? I'm not sure we might need your custom class for this :/

**Comment by scottbelden** [comment]
Probably will need to put it in the custom formatter, but that shouldn't be too hard

**Comment by Ronald-Rojas** [comment]
![terminal-image](https://cloud.githubusercontent.com/assets/11780188/17742815/84470582-646f-11e6-8627-b50880253fa7.png)

Is this still a problem? In my terminal window the text wraps well now.

**Comment by srisankethu** [comment]
The text wraps perfect now. The issue must have been resolved.

**Comment by underyx** [comment]
Indeed seems to be resolved.
