### ISSUE TITLE
coala Google Results

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/coala#2263]
When you google coala to learn about the project, there are images of Koala Bears and the main website http://coala-analyzer.org/ is the third link.

The first link is  the Github repository for coala https://github.com/coala-analyzer/coala

The second link is unrelated company with error message on the home page.

**Comment by AbdealiJK** [comment]
@tushar-rishav can you add this to your project plan? SEO for website

**Comment by hypothesist** [comment]
The first three results I now get are

* https://github.com/coala-analyzer/coala
* https://github.com/coala-analyzer/coala-bears
* https://github.com/coala-analyzer
* the image results

But this might just be based on my history of searches?

**Comment by AbdealiJK** [comment]
The way that I normally check google results not biased by my own profile from google is to search in https://encrypted.google.com/ with incognito.
According to this, the list is:
 - coala-analyzer.org
 - https://github.com/coala-analyzer/coala
 - https://github.com/coala-analyzer
 - https://github.com/coala-analyzer/coala-bears
 - And then images on koalas.

Also, apparently adding `&gl=<country code>`  can customize it based on country. [read more](https://www.distilled.net/blog/seo/non-personalized-search-google-global-results-chrome-1201/). The sites related to that country are more prominent.
I can see that:
 - UK, US, Spain, India, Germany, etc.: The coala-analyzer website is always above the koala images / other websites
 - Australia: The first link is http://coala.global/ , then images, then coala-analyzer

Example link I used: IN results: https://encrypted.google.com/#hl=en&q=coala&pws=0&gl=in

PS: I only did the country codes I could remember. But it seems like Other than australia we have a fairly decent ranking (Which makes intuitive sense)

**Comment by hypothesist** [comment]
> And then images on koalas

yay! :P

From Wikipedia:

>The koala is an arboreal herbivorous marsupial native to Australia

that explains it I guess

**Comment by jayvdb** [comment]
For Australian results, coala github repos are first, then website, and the coala.global doesnt appear on the first page at all - everything is our coala.

In Indonesia, coala.global is the last entry on the first page - everything else is our coala.

I think we've done enough to warrant closing this.  Nothing we can do about the koalas. They are going away any time soon.
