### ISSUE TITLE
Available Bears - No details

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/coala#2271]
As a new user I clicked on the [Available Bears ](https://github.com/coala-analyzer/coala-bears/wiki/Available-bears) and didn't know which bears I needed.

With the bullet icon being a check icon I thought I would need to select which bears to download but I couldn't click on the checkmark.

This made me confused.

I still don't know how to figure out which Bear I might need to use. I'm assuming at this point that it might just autodect the language. I was particularly curious if the spellcheck Bear works for all languages you could have written you code in. Also If the language isn't listed can I use a Generic Bear?

**Comment by Shreyas94** [comment]
Another newbie here. The choice of bears is upto you. It depends on the standards you would like your code/text to conform to. Posting that here might be helpful.  In the wiki page, bears listed under the generic bear can be applied to all languages. To determine which bears can be used for your language use the following command(in this example C):
`$coala --show-language-bears C`

**Comment by sils1297** [comment]
Hey @Shreyas94 what exactly are you suggesting?

**Comment by Shreyas94** [comment]
@sils1297  The user has raised an issue of missing documentation. I am merely providing her the information she needs while this issue is fixed.

**Comment by sils1297** [comment]
Ah :) thanks

**Comment by Adrianzatreanu** [comment]
I think that this is the problem of many - not knowing which bear to use exactly. I think we need that table you started @sils1297 that gives information about each bear, and probably some more documentation on the docs or readme, regarding: Which bear should I pick?

**Comment by sils1297** [comment]
@Adrianzatreanu I think the solution to this will be the new interactive coala website by @tushar-rishav which will then contain a browsable index of official bears.

**Comment by Adrianzatreanu** [comment]
sounds great

**Comment by sils** [comment]
We're planning to deploy a test version of the new website today

**Comment by sgsh123** [comment]
This issue is closed due to this (https://github.com/coala/bear-docs/blob/master/README.rst) documentation right?

Or does something else need to be added?

**Comment by Techievena** [comment]
aspects :tada: :tada:

**Comment by jayvdb** [comment]
@sgsh123 , yup, thanks.
And also https://coala.io/#!/languages is better than the wiki page.
The wiki on this repo is also gone, so the wiki cant be fixed ;-)
