### ISSUE TITLE
Unite outputs to one binary

### ISSUE THREAD

**Issue by sils** [coala/coala#2279]
_From @sils1297 on June 4, 2016 18:23_

It's confusing for users to have `coala-...`.

We probably wanna have a `--json` argument instead because all those outputs are not different functionality.

_Copied from original issue: coala-analyzer/coala-bears#494_

**Comment by sils1297** [comment]
_From @gitmate-bot on June 4, 2016 18:23_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by underyx** [comment]
`coala` ➡️ `coala`
`coala-ci` ➡️ `coala --non-interactive`
`coala-json` ➡️ `coala --json`
`coala-format "{foo}: {bar}"` ➡️ `coala --format=""{foo}: {bar}""`
`coala-dbus` ➡️ `coala-dbus`
`coala-delete-orig` ➡️ `coala-clean`

**Comment by sils** [comment]
@underyx do you have time to work on this? I wonder if we could make this happen in a few days to get it into the release, providing the okd binaries as legacy with a warning. I think this could be doable.

**Comment by tulphoon** [comment]
@Udayan12167 you still on this or can i take it? :D

**Comment by sils** [comment]
He's not responding since Sunday and it's urgent, it you guy time, take it
now
