### ISSUE TITLE
Rewrite the project abstract/description

### ISSUE THREAD

**Issue by underyx** [coala/coala#2281]
> Coala provides a common command-line interface for linting and fixing all your code, regardless of the programming languages you use.

@treyhunner — https://github.com/coala-analyzer/engagement/blob/4f8b5a0c57ae5dd27d6e3ad376fa92587fea53b8/trigger-statements.txt

---

> Extensible, language-independent code analysis. coala makes static code analysis easy and convenient for any programming language you want.

@singingwolfboy — https://pyconsprints.slack.com/archives/coala/p1465064158000004

**Comment by hypothesist** [comment]
From gitter:

> coala provides a common multiplatform interface for linting and fixing all your code, regardless of the programming language you use. Its convenient user interface eliminates a lot of common tasks for the developer. coala also facilitates people entering the world of open source by providing them valuable feedback on coding standards and formatting. In a nutshell coala is a useful abstraction for static code analysis that is applicable to any text based language.

@Udayan12167

**Comment by jayvdb** [comment]
The README & repo description is now what @treyhunner provided.

If text can be improved or anything else needs updating in this repo or elsewhere it should be raised as separate more specific issues.
