### ISSUE TITLE
Allow bear names to be used without the "Bear" suffix

### ISSUE THREAD

**Issue by sils** [coala/coala#2290]
and remove `Bear` from the names, useless

**Comment by sils1297** [comment]
Maybe let the user type `--bears=Clang` and coala will search for a ClangBear so he doesn't have to type so much?

CC @underyx @sims1253 for his discussion

**Comment by sims1253** [comment]
I think giving the bears the tool they use as an attribute is enough, as one can list them as needed then.
Then maybe just name the bears after what they are doing. Although i don't have an idea what to do with multible bears doing the same for different/same languages.

**Comment by Makman2** [comment]
so every bear expression shall be expanded to `bear-wanted(Bear|bear)?` (regex style)

**Comment by Makman2** [comment]
and I'm not sure whether removing `Bear` from the class names is useless, just calling stuff `Clang` or `Alex` is not cool :O

**Comment by Makman2** [comment]
at least it helps us organizing our stuff better^^

**Comment by fneu** [comment]
Now we're getting to where the bodies are burried... [Because of the koala's resemblance to a bear, it is often called the koala bear, although it is a marsupial, and not a true bear.](https://en.wikipedia.org/wiki/Koala#Etymology)

**Comment by jayvdb** [comment]
I've put this at medium difficulty as I dont know how difficult it might be.
But if this issue is only about the Bear suffix in CLI/config, a low difficulty approach would be to add the missing Bear suffix in the CLI/config loading phase, so that the internal data structures all continue to have the same Bear suffix and thus should not break.

**Comment by anctartica** [comment]
please assign this to me
