### ISSUE TITLE
Add test for `([` in GlobbingTest

### ISSUE THREAD

**Issue by adtac** [coala/coala#2297]
There is nothing that tests that `([xy])` works as expected

**Comment by robkau** [comment]
I would like to take this one over

**Comment by Pratik151** [comment]
@sils1297  Hello If this is still open I would like to fix it.  What name should I give to test? test_single_character_match?

**Comment by adtac** [comment]
@robkau are you still working on this? If not, can I unassign you and assign @Pratik151 ?

**Comment by adtac** [comment]
@Pratik151 there should already be several tests in the test file. IMO you should add it in among those.

**Comment by sils1297** [comment]
FWIW more small tests with good names are usually better than bigger ones

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by OctavianGuzu** [comment]
Assign me this!

**Comment by sils** [comment]
@OctavianGuzu there you go

**Comment by Sanny26** [comment]
@sils If this issue isn't still fixed, can I try to fix it?

**Comment by Makman2** [comment]
@OctavianGuzu still working on it?

@Sanny26 assigning you for now, if @OctavianGuzu wants to solve this issue I'm assigning him back :+1:

**Comment by Sanny26** [comment]
To fix this issue, one needs to add a test with ([xy]) as a pattern,  'x' or 'y' as matches and [xy] as a non-match.
@Makman2  Could you tell if I'm heading in the right direction so that I can start working on it?

**Comment by Makman2** [comment]
sounds good :+1:
