### ISSUE TITLE
Use the editor set in $EDITOR if available

### ISSUE THREAD

**Issue by underyx** [coala/coala#2299]

**Comment by Makman2** [comment]
though that could be tricky in windows :3

**Comment by sils1297** [comment]
we could do it on linux at least

**Comment by underyx** [comment]
And OS X :D

**Comment by sils1297** [comment]
So the problem is, *if* there is an `$EDITOR` we want it to be the default value, otherwise we don't want it to be the default value; for that to work we'll have to fiddle with the metadata after creation I guess...

**Comment by ThomasWaldmann** [comment]
I imagine that if I put editor in a project's .coafile, some devs will be unhappy because they use another editor. So just using $EDITOR (if set) seems a good solution.

**Comment by sils1297** [comment]
@ThomasWaldmann you could also put it in `~/.coarc`

**Comment by ThomasWaldmann** [comment]
I just did that (even before reading your comment). It's no big problem, but somehow a duplication of existing settings.
