### ISSUE TITLE
Glob.fnmatch: Don't return True if no globs provided

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2302]
Imo this doesn't make sense at all:

> :return: Boolean: Whether or not name is matched by pattern

but we do inside:

``` python
if len(patterns) == 0:
    return True
```

if I don't provide any glob, `name` can't be matched because there's no glob.

CC @fneu

**Comment by sils1297** [comment]
I think we use this as a feature, not a bug, somewhere, not sure why but we need to be careful with this.

**Comment by fneu** [comment]
That sound weird indeed, no idea what the idea behind that was. It got seemingly introduced by @AbdealiJK in e89fc3bd when he changed `fnmatch` to support matching against several patterns at once. 

note especially @sils1297 that this is another case complicating the switch to builtin globs. 

In general I'm not against switching back for the sake of simplification, but if we wrap the builtin globs and put all of our features and alterations in the wrapper, we will most likely not get a performance benefit. That's all I'm saying.

back on topic:

```
commit e89fc3bd4ce46fe45b88171e10fa0d264a470edd
Author: AbdealiJK <abdealikothari@gmail.com>
Date:   Tue Feb 16 06:24:11 2016 +0530

    Globbing: Allow list of patterns in fnmatch()
    
    fnmatch matches if a filename matches a specific pattern or not.
    This commit modifies this to check if it matches a list of
    patterns given.

diff --git a/coalib/parsing/Globbing.py b/coalib/parsing/Globbing.py
index f6729d1..6a9b2e8 100644
--- a/coalib/parsing/Globbing.py
+++ b/coalib/parsing/Globbing.py
@@ -172,13 +172,13 @@ def translate(pattern):
     return regex + '\\Z(?ms)'
 
 
-def fnmatch(name, pattern):
+def fnmatch(name, patterns):
     """
     Tests whether name matches pattern
 
-    :param name:    File or directory name
-    :param pattern: Glob string with wildcards
-    :return:        Boolean: Whether or not name is matched by pattern
+    :param name:     File or directory name
+    :param patterns: Glob string with wildcards or list of globs
+    :return:         Boolean: Whether or not name is matched by pattern
 
     Glob Syntax:
     '[seq]':         Matches any character in seq. Cannot be empty.
@@ -191,13 +191,19 @@ def fnmatch(name, pattern):
     '*':             Matches everything but os.sep.
     '**':            Matches everything.
     """
+    if isinstance(patterns, str):
+        patterns = [patterns]
+    if len(patterns) == 0:
+        return True
+
     name = os.path.normcase(name)
-    for pat in _iter_alternatives(pattern):
-        pat = os.path.expanduser(pat)
-        pat = os.path.normcase(pat)
-        match = re.compile(translate(pat)).match
-        if match(name) is not None:
-            return True
+    for pattern in patterns:
+        for pat in _iter_alternatives(pattern):
+            pat = os.path.expanduser(pat)
+            pat = os.path.normcase(pat)
+            match = re.compile(translate(pat)).match
+            if match(name) is not None:
+                return True
     return False
```

@AbdealiJK : what's this about?
```

**Comment by palash25** [comment]
the `fnmatch` mentioned in this thread is outdated. It now looks like this
```
def fnmatch(name, globs):
        globs = (globs,) if isinstance(globs, str) else tuple(globs)

        if len(globs) == 0:
            return True

        name = os.path.normcase(name)

        return any(compiled_pattern.match(name)
                   for glob in globs
                   for compiled_pattern in _compile_pattern(glob))
```
But it still is ambiguous. It can return `True` for bath a match and also no matches if no globs are provided.

**Comment by palash25** [comment]
Could be easily solved by removing the if statement. But would this break anything (I'm guessing this is the reason that it hasn't been done already)?

ping @Makman2

**Comment by palash25** [comment]
I looked into the codebase and found the following 4 instances of  `fnmatch()`:
- `autoapply_actions()` in `Processing.py`
- `check_result_ignore()` in `Processing.py`
- `icollect()` in `Collectors.py`
- `collect_files()` in `Collectors.py`

By just looking at the code I don't think they would break if the `globs` argument is empty and we don't return anything.
