### ISSUE TITLE
Use subcommands instead of binaries

### ISSUE THREAD

**Issue by sils** [coala/coala#2321]
We should do that!

`coala cli` can ne the usual coala run
`coala delete-orig`
`coala dbus`
`coala html`

**Comment by hypothesist** [comment]
Also add `coala quickstart` :P

**Comment by sils1297** [comment]
we may wanna have a simple coala executable that just takes the first argument and runs `coala-{arg}` like git?

**Comment by AbdealiJK** [comment]
Not sure about you, but my `git` doesn't seem to do that:
```
$  # All commands  available to me starting with git:
$ git
git                 gitk                git-shell           
git2gv              git-receive-pack    git-upload-archive  
github-pages        git-review          git-upload-pack   
$ git-clone
git-clone: command not found
$ git clone
You must specify a repository to clone.
...
```

**Comment by sils1297** [comment]
at least git has some mechanism to register commands and IIRC it was possible to throw a binary there with git-something. But that didn't work on every platform. Not fully sure.

**Comment by AbdealiJK** [comment]
Right, that is indeed true - `git-review` and `git review` do work for me. (git review is a third party command not in the default git, similar to `git-bz`/`git bz`)

**Comment by arafsheikh** [comment]
I used http://chase-seibert.github.io/blog/2014/03/21/python-multilevel-argparse.html once.

**Comment by sils1297** [comment]
so argparse does have subcommands anyway, the only question is do we want to allow people registering commands dynamically, like coala-quickstart and html

**Comment by Makman2** [comment]
alright, though I think "cli" is a bad name for just running coala, something like "run" or "check" or so would be better imo, as a beginner I won't use "cli" at all :O

**Comment by Makman2** [comment]
first I thought registering dynamically is bad (because we need to maintain that and you can just invoke your script/exe name), but coala-html and other modules are not inside the coala core repository, so it makes sense to allow that for easier+better modularization :+1:

**Comment by hypothesist** [comment]
There's the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy), which this would kinda "violate".

**Comment by Makman2** [comment]
in this case the UNIX philosophy is not our philosophy :P

**Comment by sils1297** [comment]
Yeah I'm pretty sure we want subcommands, we have identified that people
won't look for other binaries but they'll rather fond subcommands

**Comment by sils** [comment]
or https://github.com/coala/coala/issues/2279

**Comment by sils** [comment]
ok we're going for https://github.com/coala/coala/issues/2279 for now
