### ISSUE TITLE
tests on master fail if dbus cannot be launched

### ISSUE THREAD

**Issue by fneu** [coala/coala#2335]
on docker, the following tests crash with something like:

```
Stdout:
Creating session bus ...

Stderr:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/lib/python3.5/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.5/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.5/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```
- DbusTest.test_dbus
- DbusServerTest.test_on_name_lost
- DbusServerTest.test_on_disconnected
- DbusServerTest.test_docs
- DbusServerTest.test_dbus_methods
- DbusServerTest.test_apps
- coalaDbusTest.test_main

idealy, we should check whether dbus works and _not_ crash if it doesn't work. Tests should be skipped. Test on master should not fail when the dependencies from `requirements.txt` and `test-requirements.txt` are installed

**Comment by Makman2** [comment]
if dbus tests can't be run, then tests aren't run, then we don't want to pass^^

**Comment by sils1297** [comment]
we want them skipped

**Comment by mgracer48** [comment]
ill do it

**Comment by Nosferatul** [comment]
@mgracer48 are you still on it?

**Comment by Makman2** [comment]
Invalid, dbus interface was removed.
