### ISSUE TITLE
Requirement classes method ``is_installed()`` need better design for windows

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#2401]

**Comment by sils1297** [comment]
elaborate please? Or are the current ones not working?

**Comment by Adrianzatreanu** [comment]
The current one works properly, but @Makman2 said that using ``cmd`` is not the ideal solution, so he had some ideas that he wants to try and asked me to assign him on this issue :)

**Comment by Makman2** [comment]
`cmd` is unsafe as it performs shell expansion^^ @sils1297

**Comment by Makman2** [comment]
Moved to https://gitlab.com/coala/package_manager/issues/52.
