### ISSUE TITLE
supported languages on mobile

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/coala#2418]
On my Android  phone i wanted to look up what itests i can use on my php code. I went to coala-analyzer.org and clicked on supported  languages.  I could see a list of languages  but when i click on the languages i get no details.  I think this is because im using  mobile github.

**Comment by sils1297** [comment]
Really? That should definitely work, we should check that out. CC @hypothesist who wrote the bear-docs.

**Comment by hypothesist** [comment]
@sils1297 we should link to the README.rst page instead of the repo? @jschwarzwalder do you still face the issue when you view README.rst?

**Comment by sils1297** [comment]
ah do we link to the repo? I think at least in most places I link to the readme directly.

**Comment by jschwarzwalder** [comment]
On http://coala-analyzer.org/ it links to the repo, but when I go to https://github.com/coala-analyzer/bear-docs/blob/master/README.rst the same action happens.

I'm not sure if there is another url I'm supposed to use to access the README on mobile.

I"m using an Android Phone Samsung Galaxy S6 Android 6.0.1

**Comment by hypothesist** [comment]
I can reproduce this bug. Seems like an issue with github. @jschwarzwalder file it at support@github.com ?

**Comment by meetmangukiya** [comment]
Why is this open then @adtac ? Close it :confused: ?

**Comment by sils1297** [comment]
This is a GitHub issue. We can't do anything about it. Thanks for reporting anyway!
