### ISSUE TITLE
GemRequirementTestCase fails for me

### ISSUE THREAD

**Issue by sils** [coala/coala#2444]
```
________________________________________________________________________________ GemRequirementTestCase.test_installed_requirement ________________________________________________________________________________

self = <GemRequirementTest.GemRequirementTestCase testMethod=test_installed_requirement>

    def test_installed_requirement(self):
>       self.assertTrue(GemRequirement('gem').is_installed())
E       AssertionError: False is not true
```

should be skipped.

CC @Adrianzatreanu @Asnelchristian , can you resolve this quickly? It's a oneliner anyway.

**Comment by Adrianzatreanu** [comment]
skip when? https://github.com/coala-analyzer/coala/blob/master/tests/bears/requirements/GemRequirementTest.py 
the whole class is already skipped if theres no gem installed.

**Comment by sils1297** [comment]
actually it's not a missing skip, the test fails for me and I don't see how it could ever pass.

**Comment by Makman2** [comment]
it looks like installs across systems of ruby is not really consistent. There were already problems with finding a package (like `gem` itself) that gets installed everytime, but it seems to depend on the installation procedure of ruby if even those packages are recognized as actual `gem` packages^^

I'm not sure if I'm completely wrong, though I remember @Adrianzatreanu and me having problems with that^^

**Comment by jayvdb** [comment]
I am 99% sure we've licked this one, in https://gitlab.com/coala/package_manager/issues/49 and maybe a few other MRs.
