### ISSUE TITLE
Fix typo: LogPrinter.py: occured -> occurred

### ISSUE THREAD

**Issue by adtac** [coala/coala#2486]

**Comment by pasta-driven** [comment]
I'd like to take this one.

**Comment by Pratik151** [comment]
@Makman2  can you assign this to me? I want to contribute and this looks good to learn development workflow.

**Comment by Makman2** [comment]
alright, looks like @pasta-driven is not there. But @Pratik151 please ping the person already assigned before / tell us to do so, he could have just forgotten this issue and still wants to do it^^

**Comment by Makman2** [comment]
@Pratik151 I've sent out an invitation, tell me if you've accepted then I'm assigning you :+1:

**Comment by Pratik151** [comment]
@Makman2  Ok sure will keep that in mind from next time. and yes I accepted the request.
