### ISSUE TITLE
coalib/parsing/DefaultArgParser: Add more options in --filter-by

### ISSUE THREAD

**Issue by mr-karan** [coala/coala#2509]
I think we should have more options such as 
- `--show-bears --filter-by-can_fix`
- `--show-bears --filter-by-can_detect`
- `--show-bears --filter-by-use_stdin`
  The point being, why filter by only one parameter when we can do so for all other Bear variables? 

If this makes sense, I would like to work on it.

**Comment by mr-karan** [comment]
@sils1297 @Makman2 @AbdealiJK  your thoughts on this?

**Comment by sils1297** [comment]
More importantly: we can't filter by bear name at all ATM.

Also don't mix underscores and dashes.

**Comment by AbdealiJK** [comment]
I don't understand. This seems like you're trying to provide a complex UI in CLI - which is not a good idea, because CLI is a bad UI.

Would it not be better to launch a web browser with a nice searchable table of bears ? with every property you could ever want ? (I think this was discussed at some point)

**Comment by sils1297** [comment]
@AbdealiJK I totally agree. There's two points though:

- some people *want* to do it on the CLI
- You *need* the CLI if you're looking for e.g. own bears that are not official

**Comment by AbdealiJK** [comment]
@sils1297 

 - Some people *want* to do it with CLI
  - I agree, makes sense. But it may be wise to get some data on number of people (possibly a poll? Preferably a recommendation from an org that uses coala/agrees to use coala soon)
  - But yeah, having both is a good way to cater to both if time allows.

 - Own bears that are not official
  - What I was talking about is a locally created web page like the coala-html stuff which just generated nice information about bears and gives it to a html page which shows it with eye-candy.
  - The "official" bear webpage is an extension to this idea which is a hosted version of this generated page made from the officially supported bears (So, UI is same and hence easy to use)

**Comment by Makman2** [comment]
I think we should still provide some CLI interface, it doesn't harm.

**Comment by Makman2** [comment]
but maybe we should introduce some kind of "search-language" instead of having an own flag for each kind of field^^

**Comment by mr-karan** [comment]
I agree with the point that *it doesn't harm*. More options never harm, it just increases your help texts and available number of commands ;)

I like the idea of launching a web browser with a searchable table too. I think we first need to implement the functionality in our API and only then think of which UI to go for? :)

**Comment by Makman2** [comment]
so let's make a new issue for implementing some web UI?

**Comment by mr-karan** [comment]
https://github.com/coala-analyzer/coala/issues/2564

**Comment by hypothesist** [comment]
I just saw this PR. So instead of `n` different `--filter-by-this`, `--filter-by-that`, I think that we should have one `--filter-by "value"`. This would make it easily extensible to other params if needed and wouldn't clutter our `--help` too

**Comment by Makman2** [comment]
@hypothesist yeah like that :+1: :)

**Comment by shreyans800755** [comment]
@Makman2 
Approach suggested by @adtac looks much cleaner and feasible.
I have doubt regarding the present filter available based on language. Should we remove that to maintain consistency, or just keep it for backward compatability.
It will also degrade the code quality by putting if/else conditions inside https://github.com/coala/coala/blob/master/coalib/coala.py#L43.

**Comment by Makman2** [comment]
We keep it and deprecate it if the new filter-language handles it. After a few releases we remove the option then :+1: That's generally the procedure for official features so people don't wonder why suddenly something doesn't work any more :)

PS: adtac's name was "hypothesist" earlier, so I was already agreeing with him ;)
