### ISSUE TITLE
Show PEP8 error description

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [coala/coala#2511]
### Overview Description

Coala doesn't give a description of the error what PEP8 does.
# Steps to Reproduce

Files:

example.py

```
# After this comment there should be two lines but I'll only put one.

class Faker:

    def __init__():
        pass
```

.coafile

```
[Default]
bears = PEP8Bear
files = *.py
```
# Actual Results

```
$ coala
Executing section Default...

example.py
|   1| #•After•this•comment•there•should•be•two•lines•but•I'll•only•put•one.
|    | [NORMAL] PEP8Bear:
|    | The code does not comply to PEP8.
|----|    | /home/alan/europython/by_day/friday/coala_contribution/example.py
|    |++++| /home/alan/europython/by_day/friday/coala_contribution/example.py
|   1|   1| # After this comment there should be two lines but I'll only put one.
|    |   2|+
|   2|   3| 
|   3|   4| class Faker:
|   4|   5| 
|    | The following actions are applicable to this result:
|    |  0: Apply no further actions.
|    |  1: Open the affected file(s) in an editor.
|    |  2: Apply the patch automatically.
|    | Please enter the number of the action you want to execute (Ctrl-D to exit). 

```
# Expected Results

It would be nice to get the error description which PEP8 gives somewhere.

```
$ pep8 example.py 
example.py:3:1: E302 expected 2 blank lines, found 1
```

**Comment by doctorBeast** [comment]
I am new to developing so I dont know if its okay to advice that it would be better to print out:
Please enter the number corresponding to the action you want to execute (Ctrl-D to exit).

**Comment by Makman2** [comment]
@doctorBeast please file a new issue, this one addresses something else :)

**Comment by JohnMoutafis** [comment]
Would modying the `PEP8Bear` be a good design for this issue?

**Comment by meetmangukiya** [comment]
I don't understand the issue. If pep8 gives that message, coala will give that message. If you want to get different message from pep8, this issue is for pep8, not coala :confused:

**Comment by JohnMoutafis** [comment]
As I see it, @TheMeaningfulEngineer want's the message to be printed with the diff in order for the operation to be more verbose.

Instead of just:
```
The code does not comply to PEP8.
 ... rest of the diff ...
```
Get something like this:

```
The code does not comply to PEP8:
- E302 expected 2 blank lines, found 1
... rest of the diff ...
```

**Comment by yukiisbored** [comment]
Shouldn't this be on coala-bears and **not** coala!?

**Comment by yukiisbored** [comment]
Also, I think this doesn't require the `need design` label just need a better description.

**Comment by JohnMoutafis** [comment]
@yukiisbored Should I work this on coala-bears and reference this issue in the commit message, or it would be better to transfer the issue there?

**Comment by yukiisbored** [comment]
I think it's better to transfer the issue there. I'll do it in a sec.

**Comment by yukiisbored** [comment]
Closing this issue, Transferred to https://github.com/coala/coala-bears/issues/1897
