### ISSUE TITLE
Add option to include all bears from a language in a coafile

### ISSUE THREAD

**Issue by adtac** [coala/coala#2529]

**Comment by Adrianzatreanu** [comment]
but wouldnt there be conflicts? like id never want ALL python bears.. some do the absolute same thing as others in some points.

**Comment by sils1297** [comment]
agree, vote for won't fix not happening

**Comment by Adrianzatreanu** [comment]
please remove the label and arguemnt with in case someone else thinks otherwise.

**Comment by Makman2** [comment]
also `not happening` from my side^^

**Comment by adtac** [comment]
Maybe we should look into providing some 'packages' of language bears that don't have conflicting functionalities? Kinda like what coala-quickstart is doing at the moment - see [here](https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/Constants.py). But this won't go with this issue, I guess.

**Comment by adtac** [comment]
BTW this was a suggestion from a complete outside during the code sprints at EuroPython, so maybe we could categorize this along usability.
