### ISSUE TITLE
Add `noqa` to the keywords to start ignoring bears

### ISSUE THREAD

**Issue by adtac** [coala/coala#2533]
Some other linters use that so this will make coala backwards compatible

**Comment by sils1297** [comment]
Nice idea, I like that - could be even simple to do.

**Comment by sils1297** [comment]
that sounds like something simple, can we have it for this release?

**Comment by RohanVB** [comment]
id like to try this one

**Comment by hypothesist** [comment]
@RohanVB assigned you :+1:

**Comment by yash-nisar** [comment]
Are you still working on this @RohanVB ?

**Comment by RohanVB** [comment]
Yes, I am. Got delayed, sorry.

**Comment by jayvdb** [comment]
the flake8 series of linters use this, but it must appear:

* in a comment at the end of the line to be ignored. This does **not** cover the 'next' line.
* in the *first* comment in the file.  This covers the entire file. (not all flake8 series linters support this)

pylint uses a different syntax.

What other linters use this?

**Comment by RohanVB** [comment]
- > in a comment at the end of the line to be ignored. This does not cover the 'next' line.
Currently, this is what `noqa` does. Also, if you specify a bear, `noqa` would run only for that specific one. 

I see CoffeeLint uses this as : 
> You can also use # noqa as a shortcut for # coffeelint: disable-line
