### ISSUE TITLE
Linter: Documentation for default severity map not complete

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2537]
Here: https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/abstractions/Linter.py#L686

though this is the map currently supported:

```
severity_map=MappingProxyType({
                    "critical": RESULT_SEVERITY.MAJOR,
                    "c": RESULT_SEVERITY.MAJOR,
                    "fatal": RESULT_SEVERITY.MAJOR,
                    "fail": RESULT_SEVERITY.MAJOR,
                    "f": RESULT_SEVERITY.MAJOR,
                    "error": RESULT_SEVERITY.MAJOR,
                    "err": RESULT_SEVERITY.MAJOR,
                    "e": RESULT_SEVERITY.MAJOR,
                    "warning": RESULT_SEVERITY.NORMAL,
                    "warn": RESULT_SEVERITY.NORMAL,
                    "w": RESULT_SEVERITY.NORMAL,
                    "information": RESULT_SEVERITY.INFO,
                    "info": RESULT_SEVERITY.INFO,
                    "i": RESULT_SEVERITY.INFO,
                    "suggestion": RESULT_SEVERITY.INFO}),
```

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala-analyzer/documentation#25

**Comment by Makman2** [comment]
Actually I just recognize I've meant the API documentation :)

**Comment by Makman2** [comment]
@morganpdx wanna do this too now? This is the original issue for changing the API docs inside linter to contain the complete severity map? :)

**Comment by morganpdx** [comment]
Sure I can...but is there anything else that needs to be done?

**Comment by Makman2** [comment]
Nope :)

**Comment by peey** [comment]
please assign this issue to me

**Comment by Yomojet** [comment]
Get  me assigned!

**Comment by Makman2** [comment]
Ah sorry @Yomojet I forgot to assign @morganpdx , hes has already taken up on this issue (https://github.com/coala/coala/pull/2807)

**Comment by morganpdx** [comment]
@Makman2 Thanks!  I seem to be having some trouble linting the changes properly, and it's giving me some heartburn...any advice?  If I run coala on the local repo, it shows a bunch of missing bears (including 'GitCommitBear', which might be telling) so I'm not sure if there's something I'm doing wrong?

<img width="523" alt="screen shot 2016-10-07 at 1 53 00 pm" src="https://cloud.githubusercontent.com/assets/49012/19205137/6a480156-8c95-11e6-80be-8ede40f8862e.png">

**Comment by Makman2** [comment]
Did you install `coala-bears`? You won't get any bear with the default `coala`(-core) package^^

**Comment by morganpdx** [comment]
Thanks @Makman2, I'll give that a shot.

**Comment by morganpdx** [comment]
I installed cola-bears, and ran coala on the repo, and there appears to be no issues:

![screen shot 2016-10-12 at 5 14 58 pm](https://cloud.githubusercontent.com/assets/49012/19332296/7144a38e-909f-11e6-9e93-d9338ecb494d.png)

However the PR is still showing issues.  Is there something I'm still missing?

**Comment by Makman2** [comment]
PR related, I commented there :)
