### ISSUE TITLE
implement web ui

### ISSUE THREAD

**Issue by mr-karan** [coala/coala#2564]
The idea is to create a searchable list of coala-bears and have some nice filterable options by the parameters, generated locally from the command line. 

On another thoughts, how about creating a RESTful API for coala so that we can use it to make a website and other cool stuff also?

**Comment by Makman2** [comment]
see also https://github.com/coala-analyzer/coala/issues/2509

**Comment by sils1297** [comment]
This issue belongs to the new website repo - can you move it?

**Comment by Makman2** [comment]
@sils1297 does it? this is about having a web-reporter inside the coala main application (afaik) :)

**Comment by mr-karan** [comment]
Yes this is separate from website repo stuff

**Comment by sils1297** [comment]
that sounds like doing double work why can't we reuse the other thing? Its the same thing. Though shalt not duplicate.

**Comment by Makman2** [comment]
wait coala-analyzer/website is the main website that everyone can approach via coala-analyzer.org, while this idea aims at having an html reporter for a coala run, imo these are two (almost) different things.

**Comment by Makman2** [comment]
nvm I missed the main description above...
we should indeed try to reuse the stuff from the coala website. Though this is still a coala issue :)

**Comment by SanketDG** [comment]
This is already done?

Can be closed with relevant info.

**Comment by Makman2** [comment]
Yep think so.
http://coala.io/#!/languages
