### ISSUE TITLE
Mention which section in the question when a required setting is missing

### ISSUE THREAD

**Issue by adtac** [coala/coala#2589]

**Comment by Nosferatul** [comment]
From where should I start? :D

**Comment by adtac** [comment]
@Nosferatul ConsoleInteraction.py - `require_setting` :+1:

**Comment by Nosferatul** [comment]
Thx @adtac  👍

**Comment by Nosferatul** [comment]
Can you explain to me how this should work?

**Comment by Nosferatul** [comment]
Should I include the `section` param to the `require_setting`

**Comment by SanketDG** [comment]
@adtac What if we return the name of the bear itself? I get sections contain settings too, but bears have settings, so the bear name appearing at the prompt seems to be more useful IMHO.

Thoughts?

**Comment by adtac** [comment]
@Nosferatul sorry for the really late response :( Seems like you've got some work going, great job!

But to answer your question, I'm really unsure - I have very little experience with the console interaction part of coala.
