### ISSUE TITLE
DocstyleDefinition.load: Allow to supply 'c++' for 'cpp'

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2616]
`c++` and `cpp` are synonyms.

There's the possibility to duplicate the settings for `cpp` under a new tag `c++` inside the coalang files, but yes, this is duplication.

Another idea: Defining some kind of language-dict which automatically maps `c++` to `cpp`.

**Comment by adtac** [comment]
related to https://github.com/coala/coala/issues/2927 ? (that one seems more well defined to me)

**Comment by Makman2** [comment]
yes indeed :+1:
--> duplicate of #2927
