### ISSUE TITLE
DocumentationComment: Only accept `position` instead of `range` in `__init__`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2646]
As `indent` is already implemented as a field, the complete range is fully constructable now when giving a start position.

So this in `__init__` should do the trick:

``` python
        self._assembled = self.assemble()
        self.range = TextRange.from_values(
            position.line,
            position.column,
            position.line + self._assembled.count('\n'),
            len(self._assembled) + self._assembled.rfind('\n'))
```

As `assemble()` needs to be executed for that, this value could be cached and used on call:

``` python
def __init__(...):
    self._assembled = self._assemble()

def assemble(self):
    return self._assembled

def _assemble(self):
    # here lies now the code that does the assembling from the original `assemble()`
```

**Comment by damngamerz** [comment]
@Makman2 I still couldn't understand about the complete constructible full range, can you like explain me with an example. Right now i understand how `TextRange` works.

**Comment by Makman2** [comment]
I think I meant instead of taking a `range` in `DocumentationComment.__init__`, just take in a `position` instead. It's enough to describe what `TextRange` the comment will occupy.

> ```
> self.range = TextRange.from_values(
>             position.line,
>             position.column,
>             position.line + self._assembled.count('\n'),
>             len(self._assembled) + self._assembled.rfind('\n'))
> ```

**Comment by Makman2** [comment]
So it's just a simplification for the constructor.

**Comment by Makman2** [comment]
I hope this issue is still valid^^

**Comment by damngamerz** [comment]
@Makman2 I doubt the validity of this issue.Anyway I tried amending it, Works well check this https://github.com/damngamerz/coala/commit/ccb7b6555de341bb1cf6606b865d67137e98fe1d
This majorily will break all the tests of `DocumentationComment` & `DocumentationExtraction` I have to re-write them. That's not the issue, issue is do we really need this ??

**Comment by Makman2** [comment]
I think providing a full range means we throw away information from it or stuff does break inside DocumentationComment if something is wrong. Ideally this would be good to have.

I'm usually the type of guy that gets angry when he needs to pass obsolete information, as often it's not directly available ;)
