### ISSUE TITLE
Diff: `add_line` function

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2649]
it's already possible to add several lines at once, to delete several ones and to delete a single one.

`add_line` should be implemented too.

**Comment by Nosferatul** [comment]
Hello, I wanna work on this!

**Comment by sils1297** [comment]
Hey - nice that you came back :)! You know how it goes, if you need help, we'll be there for you :)

**Comment by Nosferatul** [comment]
Sure, thank you!

**Comment by Nosferatul** [comment]
What differences should be between 'add_line' and 'add_lines' ?

**Comment by Makman2** [comment]
`add_line` for just adding a single line without the need for creating a list^^

**Comment by Nosferatul** [comment]
I don't know where is created a list :(. `linediff = self._get_change(line_nr_before, min_line=0)` create a new object of type DiffLine if doesn't exist an object with key = line_nr_before in list __changes_. I believe that `linediff.add_after` is just a variable from DiffLine.

**Comment by sils1297** [comment]
ahm @Makman2 I'm not so sure if we don't just want to remove add_line and delete_line altogether, passing a list with one element is quite trivial

**Comment by Nosferatul** [comment]
If we want to remove delete_line, it will change delete_lines also.

**Comment by Makman2** [comment]
I wouldn't remove `delete_line` (after some thinking), as it's a bit redundant to do:
```
delete_lines(3, 3)
```
this is a bit nicer to write and to read:
```
delete_line(3)
```
and to be consequent it's maybe good to have also `add_line`? not sure any more...

**Comment by ashwini0529** [comment]
Is anyone working on this issue?

**Comment by sils** [comment]
@Nosferatul ?

**Comment by Nosferatul** [comment]
sorry, you can take it @ashwini0529 .

**Comment by ashwini0529** [comment]
@Nosferatul Alright. I'll start working on it after 30th Nov.

**Comment by ashwini0529** [comment]
@sils Can you please guide me like what should exactly be done and brief me about the issue?

**Comment by Makman2** [comment]
@ashwini0529 please don't ping sils for such generic questions, other people can answer too. Especially those who filed the issue ;)

For what's to be done: Please read the first and uppermost comment at the top

**Comment by ashwini0529** [comment]
Hey. Can you explain me how the `add_line` functionality would work? And which files do I need to change?

**Comment by Nosferatul** [comment]
check Diff.py. `add_line` needs to add a single line, we have already the `add_lines`

**Comment by ashwini0529** [comment]
So, I've tried. Will this work or something more needs to be added?

![selection_026](https://cloud.githubusercontent.com/assets/8419333/21079126/bc3cdc84-bfad-11e6-9947-27cb3d26e675.png)

**Comment by sils** [comment]
@Makman2 I think I disagree and I'd rather not have this function, same for delete_line. This is just unneeded API clutter that we have to maintain with no additional benefit for the user.

**Comment by ashwini0529** [comment]
@sils For `add_line` we're using the same function as `add_lines` :smile:

**Comment by Makman2** [comment]
@sils I personally dislike packing something into a single-item-list. Also when I want to delete a single line (which is common), I would need to provide an obsolete argument: `delete_lines(3, 3)`.
But I also get your point, feel free to file another issue for removal, we should discuss that^^

**Comment by sils** [comment]
I don't have time for it but when it comes to me, we should not introduce
such functions that do "things you don't like" because those things still
happen, it's just less transparent, one layer more (less performance), more
API (harder backwardcompatability)

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/
