### ISSUE TITLE
`Diff`: Behaves weird in general

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2653]
``` python
>>> my_string = """
... A
... B
... C
... D"""
>>> d = Diff(my_string.splitlines(True))
>>> d.add_lines(2, ["1\n", "2\n"])
>>> print(''.join(d.modified))

A
1
2
B
C
D
>>> # Adding now lines between the added ones.
... 
>>> d.add_lines(3, ["3\n", "4\n"])
>>> print(''.join(d.modified))

A
1
2
B
3
4
C
D
>>> d.add_lines(2, ["5\n", "6\n"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/coalib/results/Diff.py", line 370, in add_lines
    raise ConflictError("Cannot add lines after the given line since "
coalib.results.LineDiff.ConflictError: Cannot add lines after the given line since there are already lines.
>>> 
```

If you add a line, I expect that the offsets of all other lines do change. Otherwise this gets confusing, especially when also deleting lines.

Not sure though, as the old behaviour is also useful as you don't need to adjust offsets (if you add more lines than there were before).

**Comment by sils** [comment]
if you add something after line two and then do the same again - should the new lines before the first lines you added or after? IMO this is a valid exception, I'd close this as notabug.

**Comment by Makman2** [comment]
yeah in fact it works :+1:
