### ISSUE TITLE
Make exception tracebacks default

### ISSUE THREAD

**Issue by adtac** [coala/coala#2660]
Instead of asking the user to run coala with `-L DEBUG`

**Comment by Makman2** [comment]
Not `difficulty/newcomer`, as we don't want to execute coala always in debug-mode.

**Comment by mgracer48** [comment]
Ill work on this
just more details please

**Comment by sils1297** [comment]
CC @Uran198 does it make sense to address this issue before your PR is merged?

**Comment by mgracer48** [comment]
@Makman2 then what do we want?

**Comment by Makman2** [comment]
Change exception tracebacks and related information from DEBUG to ERROR :+1:

**Comment by Uran198** [comment]
@sils1297 I think it does. There are a lot of places where the current logging will be exchanged for default one, so this does not really change that number, so not adding more work, while I like this feature and I think it might be useful.

**Comment by sils1297** [comment]
Ok @mgracer48 take a look at LogPrinter, it has a method to log exceptions. The traceback is debug by default, we probably want to make it info or something like that at least. You'll probably have to change a few tests as well.

**Comment by mgracer48** [comment]
Sorry i havent gotten to this u have been reading python books to improve my python and also havent had the time

**Comment by mgracer48** [comment]
which test files?

**Comment by Makman2** [comment]
the ones that will fail when you've done your changes :P

**Comment by mgracer48** [comment]
```
E       AssertionError: '' != '[DEBUG][18:36:51] 4 r34l ch4ll3n63: 123 Ä[35 chars]n→ d'
E       + [DEBUG][18:36:51] 4 r34l ch4ll3n63: 123 ÄÖü ABc @€¥ §&% {[( ←↓→↑ ĦŊħ ß°^ \
E       + → d

tests/output/printers/LogPrinterTest.py:60: AssertionError

```

**Comment by mgracer48** [comment]
Help?

**Comment by Makman2** [comment]
@mgracer48 got a link to your commit / PR? :)

**Comment by mgracer48** [comment]
https://github.com/coala/coala/pull/2782

**Comment by mgracer48** [comment]
@Makman2
