### ISSUE TITLE
ConfigurationGathering: Add missing ``the``

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala#2661]
[here](https://github.com/coala-analyzer/coala/blob/master/coalib/settings/ConfigurationGathering.py#L50)

**Comment by AbdealiJK** [comment]
Don't seem to understand,

```
    :raises SystemExit: Exits when given filename is invalid and is not the
                        default coafile. Only raised when ``silent`` is
                        ``False``.
```
seems correct grammar

**Comment by Makman2** [comment]
I think @Asnelchristian means 
> Exits when ***the*** given filename...

though I think too that this is valid grammar currently, you don't need to be explicit with 'the' (imo).

**Comment by hato221** [comment]
I would like to do this.
