### ISSUE TITLE
DistributionRequirement needs an upgrade

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2676]
Thesee are some issues concerning DistributionRequirement:
- We should add mac. It's quite simple, as it uses `brew` or `port` normally
- We should have a link for windows which people can simply click on to learn how to install it on windows.
- Multiple possible package managers for the same OS (Example: Mac has port, brew. Fedora has yum, dnf. Ubuntu has apt, apt-get). This is kind of important because otherwise slightly older fedora users, or some versions of ubuntu users may have issues.
- This is a cornercase: But some packages are named differently between Ubuntu versions. For example, in Ubuntu 12.04 opencv-data does not exist, but it's important in 16.04+. Also, java versions change frequently, `java-7-openjdk` is not available in Fedora 24, and `java-8-openjdk` is not available in older versions

**Comment by AbdealiJK** [comment]
We also might need to provide links for linux/mac - as some deps aren't easy to install unless done from source like `facebook infer`

**Comment by Makman2** [comment]
I think we could add as a pseudo-package-manager "msi" for Windows which requires a complete link to the msi installer. As msi's have the same flags and work the same this would be some reliable installation target^^

**Comment by AbdealiJK** [comment]
Mac is being handled in the separate issue https://github.com/coala-analyzer/coala/issues/2678

**Comment by jayvdb** [comment]
We have brew support now, and I've filed https://gitlab.com/coala/package_manager/issues/131 for MacPorts.

We have pacman support on Windows, and https://gitlab.com/coala/package_manager/issues/30 and https://gitlab.com/coala/package_manager/issues/31 to create proper native package management to Windows.

I've created

1. https://gitlab.com/coala/package_manager/issues/132 about the java dependency problem, and
2. https://gitlab.com/coala/package_manager/issues/133 about the multiple package manager problem.

As a result, I think this can now be closed, as the critical problems have been fixed, and these important features are now raised in the new repository.
