### ISSUE TITLE
DistributionRequirement doesn't have brew support

### ISSUE THREAD

**Issue by sils** [coala/coala#2678]
we really should do that! CC @Adrianzatreanu ?

**Comment by Adrianzatreanu** [comment]
my mac agrees :D

**Comment by AbdealiJK** [comment]
Brew and Port

**Comment by mr-karan** [comment]
I'd like to take this up 👍 

I have submitted a PR for the same https://github.com/Homebrew/homebrew-core/pull/6651

I was wondering do we have to create a package for `coala-bears` as well?

**Comment by jayvdb** [comment]
This was done in https://gitlab.com/coala/package_manager/issues/105
