### ISSUE TITLE
to_snakecase undefined behaviour with periods

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2696]
When there are periods in a name, how should `to_snakecase` work ?
Currently it seems to be doing `a.B` -> `a._b` which may or may not be wrong.
What's the rule here ?

Note that with respect to code practice, in Python the `dot` is a operator, and hence the variables are actually `a` and `b` - so, `a.b` makes sense.
In R, the `dot` is not a operator, and variable names can have dots ! so, what is the correct convention then ? `a_.b` or `a._b` or just `a.b` or should the `.` be replaced with `_` for `a_b` ?

Note that it would be meaningful to also check what happens in things like `$abc` and `%abc%` which are how you define variables in PHP, Bash and Batch.
Maybe the functions needs the language being used to understand this better ?

CC @Asnelchristian (thought you might be interested)

**Comment by AbdealiJK** [comment]
Related issue in coala-bears which is being affected by this https://github.com/coala-analyzer/coala-bears/issues/693

**Comment by sils1297** [comment]
IMO we should make sure that underscores are only inserted between
alphanumeric characters, otherwise omit them

**Comment by Asnelchristian** [comment]
i am gonna try :)

**Comment by RohanVB** [comment]
Hey is the code duplication issue to be added to this PR or do we want it in a separate PR?
Reference from @Makman2 's comment on #2881

**Comment by Makman2** [comment]
yes this PR! thanks @RohanVB  :D
