### ISSUE TITLE
Open editor at the right line

### ISSUE THREAD

**Issue by liberforce** [coala/coala#2698]
With 'editor = vim' in my .coafile, the editor won't open at the right line. Either it's not handled and it's a must-have feature, or the documentation needs to make this obvious on how to setup this basic feature. FWIW, with vim, one can open the file 'foo' at line 10 using:
  vim +10 foo

**Comment by sils1297** [comment]
@liberforce coala doesn't have this feature yet but I think it can be added pretty easily, we just have to find out for as many editors as possible how to open a specific line directly. Thanks for the suggestion, this is ATM not possible with coala.

**Comment by sils1297** [comment]
So we could probably add the argument here easily https://github.com/coala-analyzer/coala/blob/master/coalib/results/result_actions/OpenEditorAction.py#L8 with the python format string syntax and then use .format with the line number below.

**Comment by ThomasWaldmann** [comment]
For vim it is "vim file.py +42".

**Comment by sils1297** [comment]
@liberforce @ThomasWaldmann would any of you be interested in making this happen?

We probably want to have a list of editors and if the user gives an editor that isn't present there we just fallback to `{editor} {filename}`. Here the ones I know:

- `vim {filename} +{line}`
- `gedit -s {filename}`
- `subl --wait {filename}:{line}:{column}`
- `atom --wait {filename}:{line}`

(If line/column isn't given in the SourceRange object we can just default it to 1.)

**Comment by SanketDG** [comment]
About `gedit` I don't know what `-s` does, but a certain line can be opened by:

`gedit {filename} +{line}`

Also to keep uniformity, I did only open on the line and not the column because some editors can. :smile:

**Comment by sils1297** [comment]
IMO let's include the column where possible, we need a format string anyway, for those who can't do line/column it won't be replaced, for the others it's great. If line or column is not given default to 1. The `-s` in gedit is like `--wait` for atom and makes sure that it doesn't open the file in an already existing process and ends the process so coala knows when the editor was closed.

**Comment by Makman2** [comment]
`gedit -s` opens up a new standalone window, we definitely want that @SanketDG :+1:

**Comment by mayank26saxena** [comment]
Can I take up this issue? I'd like to work on this!

**Comment by sils** [comment]
Nice @mayank26saxena please do, this is much demanded and we should definitely have this :)

@chauffer since nothing happened I assume you found other things to do and I hope it's ok that I unassigned you bluntly.

**Comment by nemaniarjun** [comment]
Can i do this ?

**Comment by Mixih** [comment]
@mayank26saxena checkin if you have any work on this and wish to continue, otherwise I'm reassigning to @nemaniarjun

**Comment by mayank26saxena** [comment]
Sorry for the delay. I have been busy with my uni exams. I wish to continue to work on this and I'll be sending in a PR by the end of the coming week. Thanks.

**Comment by Nosferatul** [comment]
@mayank26saxena still on it?

**Comment by Nosferatul** [comment]
unassigned due inactivity

**Comment by madan96** [comment]
I would like to take up this issue.

**Comment by NiklasMM** [comment]
For [xed](https://github.com/linuxmint/xed), the new default text editor in Linux Mint (version 18 and higher) has the following format `xed --new-window {filename} +{line}`

**Comment by jayvdb** [comment]
Some tips on handling different editors at https://github.com/wikimedia/pywikibot-core/blob/master/pywikibot/editor.py#L35
