### ISSUE TITLE
Shorten action descriptions

### ISSUE THREAD

**Issue by sils1297** [coala/coala#2701]
- Do nothing
- Open in editor
- Apply patch
- Show patch

**Comment by sils1297** [comment]
`The following actions are applicable to this result:` is way too long, maybe remove that line completely

**Comment by adtac** [comment]
What do you think about having something like this:

![Yeoman](https://camo.githubusercontent.com/592fdfd145978b98a1ac4b04ec22d25cf19ee6b4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3137303237302f3739343530302f34316532643439382d656361322d313165322d386466352d3936326639666139346336332e706e67)

The user can use the arrow keys to move between the options and choose. In the image, multiple options are selected, but we can just implement for one option. (Or multiple options if we find it useful.)

**Comment by adtac** [comment]
I don't know any library that provides this out of the box, but we can do some research.

**Comment by sils1297** [comment]
This is not about the interface, just shortening the descriptions. People don't read the long ones, I have had people asking me where ... is and I just pointed at their screen.

**Comment by Nosferatul** [comment]
I wanna work on this!

**Comment by sils1297** [comment]
Oh yes! @Nosferatul great :)
