### ISSUE TITLE
"you might want to get in contact with the writer of the bear" change writer to author

### ISSUE THREAD

**Issue by sils** [coala/coala#2707]
just git grep for the phrase and change it, I think it's nicer :)

difficulty/newcomer

**Comment by Satyam-Bharadwaj** [comment]
@sils1297 Does the bug fix require change of all occurrences of "writer" to "author" ? Or only the one occurrence in the phrase "you might want to get in contact with the writer of the bear" ?

**Comment by sils1297** [comment]
Not sure, what makes most sense to you

**Comment by Satyam-Bharadwaj** [comment]
I'm sorry I'm quite new to git so this is taking quite a few attempts .

**Comment by sils1297** [comment]
That's normal, we have the newcomer issues so you can take your time to learn so don't worry :)

**Comment by anshuman73** [comment]
Hi, @Satyam-Bharadwaj , are you still working on this ?

**Comment by anshuman73** [comment]
It seems assignees has stopped working on this.
Reference - https://github.com/coala/coala/pull/2722

**Comment by Satyam-Bharadwaj** [comment]
Hi,
I was working on it but my text editor would chnage a bit more than the
words required. Hence i shall not be able to provide a commit.
Thank you

**Comment by tanvibhakta** [comment]
Hey, I'd like to work on this. Will submit PR in the next few hours. :)

**Comment by anshuman73** [comment]
Hi, just a heads up, I have already submitted a PR for the same. I just
need to resolve the git issues. I haven't exactly got a straight shot at
it. I should be able to do that in a few hours as well. If you want, you
can resolve me git issue. As far as I know, there's only a small typo in
the commit message and other guidelines have been mentioned in the PR
request, for which you should be able to find a link above, I think I did
refer it here.

**Comment by tanvibhakta** [comment]
Ooh, okay. I'll take a look at it. Thanks. :)

**Comment by tanvibhakta** [comment]
Ooh okay, I'll have a look at this. Thanks. :D

Edit: I looked at the ticket you referenced that @Satyam-Bharadwaj submitted. It looks like there's just an amend to be made on a commit message from his side which we can do nothing about. What have you done? What is left for me to do?

**Comment by amrandahvur** [comment]
Assign me this

**Comment by Cosmopal** [comment]
Assign me this issue

**Comment by RoshanAji** [comment]
Please assign me to this issue

**Comment by virresh** [comment]
I'd like to work upon this issue

**Comment by RoshanAji** [comment]
I would like to have this issue assigned upon me

**Comment by sils** [comment]
assigned @amrandahvur , that comment was first.

**Comment by amrandahvur** [comment]
So, I have found three files in the coala repository that contain "writer" in it, should i change them all to "author" ? Also, should i create a separate branch for these changes considering that it isnt a major change ?
