### ISSUE TITLE
How do I refer the parent in Linters ?

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2713]
I want to create a custom check_prerequisite which cannot be done with the current linter API.
How do I do this using the linter decorator ? I would normally refer to the parent `Lint.check_prerequisite()` to do it's normal checking and add more of mine. But now, the parent class is locally defined inside the decorator and so not accessible.

I believe I can do this using the `super()` but we had a discussion to not use super() a long time ago

CC @Makman2

**Comment by Makman2** [comment]
hmmm indeed...

there's was already the idea from mine to deprecate the `prerequisite_check_command` and `prerequisite_check_fail_message` parameters, and use instead an override based approach:

```
@linter(...)
class X:
    check_prerequisites = PrerequisiteCheck('executable') # <-- this would be set normally from linter
    # if you want to change behaviour:
    check_prerequisites = JavaModuleCheck('mymodule')
    # if you want completely custom behaviour:
    class MyCheck(PrerequisiteCheck):
        def __init__(self, TNTamount):
            self.TNT = TNTamount
        def check(...):
            return shutil.which("kernel-exploder" + self.TNT) is not None or "Can't detonate kernel."

    check_prerequisites = MyCheck('3000tons')

# Or maybe we could instead specify an instance of this check-class to prerequisite_check_command parameter
```
This `PrerequisiteCheck` class would be itself callable somehow (and also allow the staticmethodness somehow, I don't have a specific implementation right now :/)

For now you need to use `super` it seems, as you don't have a way to refer to the base class. As `super` tracks it down via the class instance, this is the only choice^^

**Comment by sils** [comment]
@Makman2 will the linter based check prerequisites even be much needed now that we have the requirements checked automatically?

**Comment by Makman2** [comment]
no not really \+ it's possible via `super` :+1:

maybe it's possible to use some ABC type (though I don't really understand currently how they work), but let's just use `super` :)

reopen @AbdealiJK if you disagree :)
