### ISSUE TITLE
coala GitHub org name

### ISSUE THREAD

**Issue by sils** [coala/coala#2729]
We're trying to get away from being coala-analyzer, towards just being coala. On GitLab we have the coala organization, now we have coala.io so we stop relying on coala-analyzer.org.

Any ideas on another username for the org? We could try something like coala-io.

Also possibly the @coala user on GitHub might be willing to rename his account so we could use his name for this organization. He has no email address associated with his account but possibly he gets an email about this issue.

**Comment by sils1297** [comment]
CC @chauffer

**Comment by adtac** [comment]
Is it possible to talk to the people over at Github? This is a legitimate query and that account is abandoned from the looks of it.

And please tell me you created https://github.com/coala-io to temporarily hold it.

**Comment by sils1297** [comment]
yes, we created coalaio and coala-io temporarily.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by sils1297** [comment]
I don't think github will free an account like this for us.

**Comment by adtac** [comment]
https://help.github.com/articles/name-squatting-policy/

**Comment by meetmangukiya** [comment]
:thought_balloon: 
Also, after moving to another user, I think we should not abandon this account now and make its repos' the mirror of the repos of the new account

**Comment by iwfweb** [comment]
Hi there,

we're the owner of the "coala" account on Github.

We just decided to rename our account to "iwfweb", because our company also went through some transitions. 

I hope it's possible for you to use the name now. 

Happy coding,
Jens

**Comment by sils1297** [comment]
Hey @iwfweb thanks so much! I have the coala account now so we can use it. This is great!

Does anyone have experiences with organization renaming? I fear it might break things like CI; pull and push URLs will continue to work.

**Comment by sils1297** [comment]
See also https://help.github.com/articles/renaming-an-organization/

**Comment by adtac** [comment]
Wow, this is really amazing. Thanks to @iwfweb for understanding :)

**Comment by meetmangukiya** [comment]
That was a quick response :D

**Comment by sils1297** [comment]
The rename has happened. We're now fixing up everything that doesn't work anymore :P

**Comment by sils1297** [comment]
Gitter channel renamings: CC @MadLittleMods

Old Name | New Name
---|---
coala-analyzer/coala | coala/coala
coala-analyzer/coala-bears | coala/coala-bears
coala-analyzer/performance | coala/performance
coala-analyzer/documentation | coala/documentation
coala-analyzer/conferences | coala/conferences
coala-analyzer/coala/workshops | coala/workshops
coala-analyzer/coala/artwork-corner | coala/design
coala-analyzer/coala/offtopic | coala/offtopic
coala-analyzer/freelancers | coala/freelancers
coala-analyzer/maintainers | coala/maintainers
coala-analyzer/coala/gsoc | coala/gsoc
coala-analyzer/gsoc-mentors | coala/gsoc-mentors

**Comment by sils1297** [comment]
After the renaming I'll have to update the sameroom.io mirrorings to IRC and telegram as well as cobot.

**Comment by sils1297** [comment]
I'll also need to update the website, we should grep everything for coala-analyzer in general.

**Comment by MadLittleMods** [comment]
@sils1297 Renaming on Gitter is done, https://gitter.im/orgs/coala/rooms

**Comment by Makman2** [comment]
@MadLittleMods thank you very much :)

@sils1297 something left to adapt?
