### ISSUE TITLE
PackageRequirment.install_command: Return tuple instead of complete shell string

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2730]
... and let handle shlex handle the rest when printing to user:
```python
shlex.quote(' '.join(command))
```
though this is only linux shell compatible. But if needed we can write also windows shell compatible `quote` algorithms for *coala-utils* (though windows shells are way more limited than linux shells, and I hate them ... :/ )

Maybe we could also introduce a member function for `PackageRequirement` that does this string assembling^^

The advantage is that we can feed the `install_command()` into `subprocess.call` (or into our calling helper routines) without having to worry about shell expansion :+1:

CC @Adrianzatreanu what do you think about that? :)

**Comment by Adrianzatreanu** [comment]
if you think its helpful im for it, but i still dont understand what it improves?

**Comment by Makman2** [comment]
1. Users don't have to return the command that will be sometimes only suited for a single shell terminal
2. We can execute the install command ourselves directly via `subprocess.call` (without `shell=True`!), so we don't need to take care about escaping and stuff

**Comment by Makman2** [comment]
This is already implemented.
