### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by sils** [coala/coala#2735]
With only a comment explaining what info there should be, not forcing the user or scaring him off.

difficulty/low

**Comment by meetmangukiya** [comment]
You mean GitHub issues, right? If yes, am in complete agreement with you. We should have a issue template just as we have a commit template.

**Comment by sils1297** [comment]
but only consisting out of optional and commented out things so by default people should be able to ignore it; I sometimes feel scared off by long templates, too much work :P

**Comment by vyasgiridhar** [comment]
Can i take this issue up?

**Comment by mayank26saxena** [comment]
Could you please elaborate on what exactly needs to be done to resolve this issue? I would love to give it a shot.

**Comment by capellini** [comment]
@mayank26saxena I also contribute to a project called [Hoodie](https://github.com/hoodiehq/) that has the following issue template: https://github.com/hoodiehq/camp/blob/gh-pages/ISSUE_TEMPLATE.md.  I think that this issue is referring to creating something like this.

@sils1297 -- is that right? The above link is for a "first timers" template, so it may be overkill for more experienced coalaians, but maybe a good start?

**Comment by Makman2** [comment]
@capellini yeah right, though I think this one is a bit too much for our purpose :3

@mayank26saxena see also https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by sils1297** [comment]
We don't want the template to force you, you should still be able to file
issues really quick. But it should help you doing it right. I'd use
markdown comments only so you *can* ignore it

**Comment by peey** [comment]
Please assign this issue to me

**Comment by peey** [comment]
Is an elaborate structure required or just a simple comment?

For example, the issue template in CONTRUBUTING.rst reads:

```
### Overview Description

# Steps to Reproduce

1.
2.
3.

# Actual Results

# Expected Results

# Reproducibility

# Additional Information:
```

A simpler one could look like : 
```
<!-- Hello! If you're filing a bug, please include every step so as to help us reproduce it on our machines. For any help regarding the usage of coala, hit us up on gitter.im/coala/coala -->
```

**Comment by sils** [comment]
How about:

```
<!--

Hello! If you're filing a bug, please include every step so as to help us reproduce it on our machines. For any help regarding the usage of coala, hit us up on coala.io/chat

If you want help, just uncomment the template. If you're in a hurry or feel like you could explain it better without, just ignore or delete it.

### Overview Description

# Steps to Reproduce

1.
2.
3.

# Actual Results

# Expected Results

# Reproducibility

# Additional Information:
-->
```
