### ISSUE TITLE
Go through newcomer issues and close the ones that are solved

### ISSUE THREAD

**Issue by beatrix-bodo** [coala/coala#2740]
Some of the newcomer issues that are already solved are still open, we should probably close them.

**Comment by sils1297** [comment]
Any progress on this?

**Comment by sils1297** [comment]
IIRC you already looked through some. Would be a shame to loose the progress.

**Comment by beatrix-bodo** [comment]
Since I "misdiagnosed" that fork I'm kind of unsure of which one is really an issue and which one should I leave D: I'm not sure how to determine if something really should be closed. Later today if I have some time I'll try to figure github out but this seems so confusing right now.

**Comment by beatrix-bodo** [comment]
OK, that makes sense, thanks!

**Comment by jayvdb** [comment]
Are you planning on doing this cleanup?
Google Code-in begins on 28 November, and it would be nice to have cleared up the issues.
Also I have noticed a few open newcomer PRs which have already been solved, as the issue was re-assigned due to inactivity.

**Comment by sils** [comment]
Unassigning due to beatrix' request

**Comment by jayvdb** [comment]
Stale
