### ISSUE TITLE
GoRequirement.is_installed fails with Ubuntu precise and trusty go

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#2752]
On Ubuntu precise, `go doc` does not work.

```
$ go doc anything

go: unknown subcommand "doc"

Run 'go help' for usage.
```

It always returns exit code 1, so `GoRequirement.is_installed` returns false for anything.

That is a reasonable result, as it cant detect if a package is installed, and it might be reasonable to not support that version anyway for other reasons (like if the vet tool doesnt work).

But the more immediate problem is that the test `GoRequirementTestCase.test_installed_requirement` fails, because the following does succeed.

```
@unittest.skipIf(shutil.which('go') is None, "Go is not installed.")
```

Note: Ubuntu precise [does have](http://packages.ubuntu.com/precise/amd64/golang-go/filelist) a `godoc` binary, which could be a suitable replacement.

**Comment by jayvdb** [comment]
Looks like the same problem on Travis trusty images.

**Comment by sils1297** [comment]
CC @Adrianzatreanu :P

**Comment by fneu** [comment]
@jayvdb may I ask which version of go you are using? 

"doc" doesn't appear in the output of `go help`?

I suppose that in this case `go help doc` would return an error code, right? that could at least skip the `skipIf` thing and then we'd have to figure outanother way to look for installed packages.

**Comment by fneu** [comment]
actually, looking at the doc right now, is `go list` available?
```
fabian ~ > go list github.com/golang/lint/golint
can't load package: package github.com/golang/lint/golint: cannot find package "github.com/golang/lint/golint" in any of:
        /usr/lib64/go/src/github.com/golang/lint/golint (from $GOROOT)
        /home/fabian/go/src/github.com/golang/lint/golint (from $GOPATH)
[1] fabian ~ > go get github.com/golang/lint/golint                                                                                                                                       :(
fabian ~ > go list github.com/golang/lint/golint
github.com/golang/lint/golint
fabian ~ > 
```

this could work instead

**Comment by jayvdb** [comment]
`go help` didnt list `doc`.

I'll take another look at this tomorrow, including verifying the version used, etc.
Using `go help doc` for the `skipIf` would be a good approach, if we cant find a way to get this old go .. going.

**Comment by fneu** [comment]
ok so docker is offering me a debian jessie right now with go1.3.3.

that one indeed does not have the `doc` command

it *does* have the `list` command though, so that should correctly show whether or not a package is installed. Interestingly, I couldn't test it right now because all of our GoBears require a version of Go higher than that. This in itself is not our problem though....


I have to add that debian jessie also offers pip 1.5 or something which cannot install coala.

**Comment by fneu** [comment]
to add insult to injury, I now do have go isntalled and the test still fails.

`self.assertTrue(GoRequirement('go').is_installed())`

someone wanted to be funny. Are we not testing this on CI?
```
fabian ~/devel/coala ⎇master  > go doc go                                                                                                                                             
doc: no buildable Go source files in /home/fabian/devel/coala
exit status 1
```

mind you it works with the builtin tool fmt:
```
fabian ~/devel/coala ⎇master  > go doc fmt
package fmt // import "fmt"

Package fmt implements formatted I/O with functions analogous to C's printf
and scanf. The format 'verbs' are derived from C's but are simpler.

[...]
```

**Comment by jayvdb** [comment]
This isnt fixed for [precise golang 2:1-5](https://travis-ci.org/jayvdb/coala/jobs/182524961#L255) or trusty [golang 2:1.2.1](https://travis-ci.org/jayvdb/coala/jobs/182525735#L446).

**Comment by jayvdb** [comment]
I think the boat has sailed on this one.

The code has moved to gitlab, and precise is dead, and trusty is on its last legs.
If someone encounters it, they can re-raise the problem.
