### ISSUE TITLE
Remove deprecated link in the document string from the `Lint` class in the `Lint.py` file

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#2774]
http://coala.readthedocs.io/en/latest/Users/Tutorials/Linter_Bears.html is the link in the file, it is 404'd, it needs to be updated.

Complete path of the file : `coala/coalib/bearlib/abstractions/Lint.py`

difficulty/newcomer

**Comment by Dawny33** [comment]
Should be updated with the following link:
 https://coala.readthedocs.io/en/stable/Users/Tutorials/Linter_Bears.html

**Comment by Makman2** [comment]
Doesn't harm to have it, though `Lint` is deprecated and will be soon removed :+1:

**Comment by abhishekbundela** [comment]
hey @sils. Assign me this issue.

**Comment by sils** [comment]
@Dawny33 are you still working on this? If not, could you fill coala.io/newform and tell us how we could have helped you better?

@abhishekbundela this issue is assigned ATM.

**Comment by abhishekbundela** [comment]
@sils I created a pull request #2972 to fix this issue.

**Comment by sils** [comment]
@abhishekbundela we'll give @Dawny33 a day or so to respond ok?

**Comment by Makman2** [comment]
Actually the file does not exist any more, issue is invalid by now^^

**Comment by Makman2** [comment]
@abhishekbundela  created a new issue for `Linter.py` and assigned you
https://github.com/coala/coala/issues/2976
