### ISSUE TITLE
CI: Don't use DEBUG log level for coala run

### ISSUE THREAD

**Issue by sils1297** [coala/coala#2777]
It's hard to find the relevant information in there.

difficulty/newcomer, this can probably be solved in our .circle.yml (or some filename like this, it's already there in project root)

**Comment by AbdealiJK** [comment]
Note that now we are using `coala-ci -V`, hence we need to remove the -V flag which shows a lot of info that we don't need making the important info difficult to find.

**Comment by sils1297** [comment]
I think we already have an issue for this

**Comment by AbdealiJK** [comment]
@sils1297 That was a comment on the issue you created a day ago. Not a new issue. (Probably confused by github emails?)

**Comment by ankitjavalkar** [comment]
I'd like to work on this, if it's not being worked on or dependent on any existing PR or issues.

**Comment by SanketDG** [comment]
@ankitjavalkar You are assigned :+1:

**Comment by ankitjavalkar** [comment]
@SanketDG Thanks

**Comment by sils1297** [comment]
sorry, confused by emails...
