### ISSUE TITLE
Wrong quotes used

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#2779]
In coala/coalib/results/result_actions/OpenEditorAction.py, function ``apply``'s docstring is with ``'''`` isntead of ``"""``. I think its a mistake and not on purpose, and should be changed for consistency.

**Comment by Pratik151** [comment]
Same with ShowPatchAction - https://github.com/coala/coala/blob/master/coalib/results/result_actions/ShowPatchAction.py 
Should I change it?

**Comment by Adrianzatreanu** [comment]
should be changed, yes.
