### ISSUE TITLE
Few document string corrections

### ISSUE THREAD

**Issue by raul1991** [coala/coala#2789]
I found out few document strings that needs attention. Additionally, along the way i found a method without a document string.

Attaching a snapshot of the diff view of the corrections.
![screen shot 2016-09-25 at 8 50 22 pm](https://cloud.githubusercontent.com/assets/1281636/18816186/e69e94a0-8361-11e6-9dc5-8a354a787fd9.png)

**Comment by sils1297** [comment]
Hey, usually you want `Print` instead of `Prints` actually (imperative tense is kind of standard though we're not complying to the standard yet properly)

Can you file single newcomer issues for other typos you found and close this?

**Comment by raul1991** [comment]
So you want me to file a single issue for all the typos ? As in all those that i encounter in the whole code ? Am i understanding it correctly ?

**Comment by Adrianzatreanu** [comment]
@raul1991 yes, we'd like to have an issue for each typo you find :D thats what newcomer issues are mostly for :)

**Comment by raul1991** [comment]
Closing this to reopen more by segregating this one into more newcomer issues.
