### ISSUE TITLE
Remove period from the settings print

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#2798]
Right now if you execute SpaceConsistencyBear you will see this:

`Please enter a value for the setting "use_spaces" (True if spaces are to be used instead of tabs.) needed by SpaceConsistencyBear:`

i honestly think that the period afteR "tabs" is not fit there and should be removed.

**Comment by bctaucsd** [comment]
Would love to give this a shot!

**Comment by Adrianzatreanu** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by raul1991** [comment]
assign it me @Adrianzatreanu

**Comment by sils1297** [comment]
Unassigning you @raul1991 as you're already assigned to another newcomer issue - we only have a limited number of those available. After doing a newcomer issue, please advance to low! Newcomer issues are a hell lot of work for us.

**Comment by kshitij10496** [comment]
Hello,
I would like to work on this.

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by kshitij10496** [comment]
@sils1297 Thanks for the invitation.
I'm raring to go :smile:

**Comment by sils1297** [comment]
:+1: let us know if you need anything :)

**Comment by nikssardana** [comment]
Hi! I am new to open source and would like to contribute to this community. I've locally made changes as required, but can't create a pull request. Please help!

**Comment by sils1297** [comment]
Hi @nikssardana ! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**This issue is already assigned to @kshitij10496 who is already working on it so could you please look out for another issue?**

**Comment by nikssardana** [comment]
@sils1297 I got your email. I'll find some other newcomer bug. Thanks!

**Comment by segunfamisa** [comment]
Hi, new comer here. Is this issue still open? 
If yes, I would love to try out this one.

Cheers :)

**Comment by sils** [comment]
@kshitij10496 still working on this?

**Comment by rajdeep1008** [comment]
@sils i would like to help with this if no one else is working on it
And please add me in the community too. :)

**Comment by sils** [comment]
Unassigning @kshitij10496 due to inactivity.

@rajdeep1008 
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by sils** [comment]
@rajdeep1008 assigning you

**Comment by Warewolf96** [comment]
hi @sils ,

Dunno if this is resolved or not... can u invite me and assign this to me... thanks

**Comment by sils** [comment]
@rajdeep1008 any progress? @Warewolf96 try to keep it with one newcomer issue, then go for low, ok? :)

**Comment by rajdeep1008** [comment]
@sils still fighting with the codebase, documentation and college exams.
Will still need a couple more days to fix this issue but its fine with me if @Warewolf96  wants to work on it.
Your call. :)

**Comment by sils** [comment]
It's totally good, we're just sometimes asking to make sure that the assignment is still valid, don't feel rushed

**Comment by dileepsankhla** [comment]
I would like to be assigned!

**Comment by Warewolf96** [comment]
@sils I'll find some other newcomer issue.. its cool

**Comment by dileepsankhla** [comment]
@Warewolf96 No you should wait to be assigned. You are the right person :) Me not.

**Comment by adtac** [comment]
@rajdeep1008 ping :) Any progress?

**Comment by Projjol** [comment]
If this is open may I take it up? :)

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by sils** [comment]
Unassigning @rajdeep1008 due to inactivity.

**Comment by rajdeep1008** [comment]
@sils 
Sorry, was almost off from this.
Its totally cool with me, i'll catch up with some other newcomer issue after exams.
