### ISSUE TITLE
Broken Documentation link : Bears that make suggestions and corrections

### ISSUE THREAD

**Issue by raul1991** [coala/coala#2800]
![image](https://cloud.githubusercontent.com/assets/1281636/18979691/e5966510-86ea-11e6-98f6-0889e0e60b8a.png)

Link to this document : http://coala.readthedocs.io/en/latest/Developers/Self_Correcting_Bears.html#bears-that-can-suggest-and-make-corrections
The highlighted link should be changed

**Comment by ventris** [comment]
I'll give this a shot.

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by ventris** [comment]
Assign me

**Comment by SanketDG** [comment]
@ventris You are assigned!

**Comment by ventris** [comment]
This is no longer an issue due to `95a6b1d` where the documentation that this issue is in is removed from the wiki.

**Comment by sils1297** [comment]
Thanks a lot @ventris ! Closing then. Feel free to pick up something else.
