### ISSUE TITLE
ConsoleInteraction.py : Correct afected to affected in the method `print_affected_files` 

### ISSUE THREAD

**Issue by raul1991** [coala/coala#2808]
Typo in the method's docstring ie afected needs to change to affected.

![screen shot 2016-10-02 at 2 56 07 pm](https://cloud.githubusercontent.com/assets/1281636/19019771/6492a6be-88b0-11e6-8340-d3c22cea5276.png)

**Comment by raul1991** [comment]
@Adrianzatreanu  , Can you assign it to me.

**Comment by Makman2** [comment]
Closing in favor of #2836 as it's more recent.
