### ISSUE TITLE
ConsoleInteraction.py : Invalid parameter mentioned in the docstring

### ISSUE THREAD

**Issue by raul1991** [coala/coala#2809]
The parameter name should be result instead of result_list.

![screen shot 2016-10-02 at 3 00 47 pm](https://cloud.githubusercontent.com/assets/1281636/19019793/17a8c864-88b1-11e6-91a6-a49f05061e89.png)

**Comment by raul1991** [comment]
assign it to me @Adrianzatreanu . TSHIRT TSHIRT TSHIRT :D

**Comment by nikssardana** [comment]
Please assign this issue to me @sils1297

**Comment by sils1297** [comment]
Hi,

please don't ping me personally for such things. Everyone can do them - and almost everyone pings me. If you don't address a person specifically you'll likely get help faster from other people!

(Don't worry, this is not a problem but keeping things general is usually a good policy :))

**Comment by nikssardana** [comment]
Oops...Sorry! I'll keep that in mind from now on!

**Comment by sils1297** [comment]
no issue :)

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/
