### ISSUE TITLE
Fix typo: ConsoleInteracion.py: od -> of

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#2812]
_:param setting_name: Name od the setting missing_

**Comment by sils1297** [comment]
@lqaz assigned you as you seem to be workin on it

**Comment by prafful002** [comment]
@sils if the assignee is not working on it currently may I take it up ?

**Comment by sils** [comment]
please ping him about it and don't take it over "behind his back" without
asking it

**Comment by prafful002** [comment]
@lqaz if you're no longer working on this may I take it up?

**Comment by Adrianzatreanu** [comment]
assigned @prafful002
