### ISSUE TITLE
Change coala-analyzer to coala in the docs

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#2813]
http://coala.readthedocs.io/en/latest/Developers/Writing_Bears.html

**Comment by sils1297** [comment]
@yash-nisar if you mention labels in the body when creating issues, gitmate will autolabel them

**Comment by yash-nisar** [comment]
Okay @sils1297 :+1:

**Comment by yash-nisar** [comment]
Okay @sils1297 :+1:

**Comment by mohit3011** [comment]
I am a newcomer here and would like to work on this issue.

**Comment by srisankethu** [comment]
@mohit3011 As you can see someone is already working on this issue. Check out our newcomer guide -> http://docs.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by akashfoss** [comment]
I am a newbie in coala and would to fix this issue. Can anyone assign me to this issue ?

**Comment by jayvdb** [comment]
@akashfoss , see above.

**Comment by sils1297** [comment]
Hey @simobasso ! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

Ping us if you're not working on ths anymore but *please* get an assignment, this has already confused two other newcomers.

**Comment by simobasso** [comment]
Hey @sils1297! assign it to me! update in a couple of hours! Thanks

**Comment by sils1297** [comment]
@simobasso you need to accept theinvitation first.

**Comment by simobasso** [comment]
@sils1297 I did it.

**Comment by sils1297** [comment]
@simobasso thanks, this is yours :)
