### ISSUE TITLE
#Ignore LineLengthBear: Error caused when used.

### ISSUE THREAD

**Issue by RohanVB** [coala/coala#2833]
**Reproducing the error:**
I wanted to test out the 'Ignore Bear' feature which is already in coala which can ignore the checks of a bear by typing something like `#Ignore LineLengthBear` so I created a file which violates the linelength condition which is when I got the error below:

```

`[ERROR][08:09:59] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][08:09:59] Exception was:
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coalib/coala_main.py", line 91, in run_coala
    log_printer=log_printer)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coalib/processes/Processing.py", line 697, in execute_section
    log_printer),

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coalib/processes/Processing.py", line 526, in process_queues
    ignore_ranges = list(yield_ignore_ranges(file_dict))

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coalib/processes/Processing.py", line 460, in yield_ignore_ranges
    len(file[line_number])))

IndexError: tuple index out of range`

```

**Comment by sils1297** [comment]
@RohanVB can you debug it?

**Comment by RohanVB** [comment]
@sils1297 sure I'll try to.

**Comment by RohanVB** [comment]
Error only reproducible in a particular case, may not require attention.

According to documentation:
> http://docs.coala.io/en/latest/Users/Tutorial.html?highlight=ignore

_Examples:_ 
**Case-1 (_LineLengthBear works properly when there is a line succeeding the # Ignore_)**
```
def func():
    print("Some really super long line by which LineLengthBear should be activated under normal conditions but we ignored it here so it will be ignored.")# Ignore LineLengthBear
func()
```

**Case-2 (_Error thrown due to no lines succeeding the # Ignore_)**

```
def func():
    
    print("Some really super long line by which LineLengthBear should be activated under normal conditions but we ignored it here so it will be ignored.") # Ignore LineLengthBear

```

**Further notes:**  In Case-1, the # Ignore LineLengthBear is repositioned to the beginning of the line when coala is run (as shown in documentation example). In Case-2, this does not occur, and error is thrown.

**Comment by Makman2** [comment]
Why did you close? Was this fixed?

**Comment by RohanVB** [comment]
It wasn't an issue in the first place. According to the documentation, the #Ignore would act on the preceding line, which is exactly what it does.

**Comment by sils** [comment]
uhm but you get an exception don't you? That should never happen

**Comment by RohanVB** [comment]
Ok. What should happen in this case? An error message stating improper placement of #Ignore bear-name?

**Comment by sils** [comment]
it should still work, the `#ignore` should work for both the line it appears in and the following. If there is no following line that should be ignored. I guess somewhere we add +1 to the index and then access the line which doesn't exist. This will be easy to fix. @RohanVB wanna fix?

**Comment by RohanVB** [comment]
Yep. Thanks.

**Comment by RohanVB** [comment]
I'm unable to reproduce the error anymore.
Requesting someone else to take over that can reproduce the above error or to close this issue.

**Comment by Makman2** [comment]
then let's close :)
