### ISSUE TITLE
fixture 'mocker' not found error when running py.test

### ISSUE THREAD

**Issue by ma3lstrom** [coala/coala#2839]
Running py.test fails as the fixture 'mocker' is not found for the disable_bears fixture at coala/tests/settings/conftest.py. 
![mocker_bug](https://cloud.githubusercontent.com/assets/1377982/19155605/ee45937c-8b93-11e6-90c6-74162b518aa3.png)

labels: difficulty/low, hacktoberfest

**Comment by ma3lstrom** [comment]
I suspect that this might be because the mocker python library is not installed

**Comment by virresh** [comment]
I'd like to work on this. Please assign this to me.

**Comment by victor-torres** [comment]
Cannot reproduce @ OS X.

Maybe lack of `pip install -r test-requirements.txt`?

**Comment by sils** [comment]
Yes @ma3lstrom that looks like a typical `pip install -r test-requirements.txt` missing. Closing as invalid, if you have a suggestion on how we can make it more intuitive feel free to open an issue. If this doesn't fix your issue, of course reopen it.
