### ISSUE TITLE
PackageRequirement: Add `install_command()`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2847]
`install_command` is something that is not necessary bound to a `DistributionRequirement` only. `PackageRequirement` should have it too with a not-implemented version.

**Comment by sils** [comment]
@Makman2 are you working on this already on #2843 ? Is @fneu aware of this? He's doing a refactoring in that area as well. Also please clarify on why this is needed and synch up with each other and @vreethesh .

**Comment by fneu** [comment]
@Makman2 `install_command` might as well go, I removed it locally as cob won't need it and it's hard to do cross-distro.

**Comment by sils** [comment]
@vreethesh plase stop working on this right now. Maybe pick it up later, when discussions are resolved but this stuff is likely to vanish.

**Comment by vreethesh** [comment]
@sils OK

**Comment by sils** [comment]
@Adrianzatreanu can this be continued in package_management or is it already resolved?

**Comment by jayvdb** [comment]
This was completed in https://gitlab.com/coala/package_manager/merge_requests/21
