### ISSUE TITLE
LocalBearTestHelper: Provide mechanism to get dependencies

### ISSUE THREAD

**Issue by abhsag24** [coala/coala#2860]
_From @abhsag24 on May 28, 2016 13:9_

right now LocalBearTesterHelper is not usable when a bear has other bears as dependencies, this should not be the case.

_Copied from original issue: coala/coala-bears#466_

**Comment by abhsag24** [comment]
_From @gitmate-bot on May 28, 2016 13:10_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by SarthakNijhawan** [comment]
@abhsag Can I work on this?

**Comment by abhsag24** [comment]
@SarthakNijhawan assigned!

**Comment by SarthakNijhawan** [comment]
@abhsag24 but while running the `bears` with other bears as dependencies , they do have a check write that the dependencies are fulfilled or not. So, what are we exactly looking forward to?

**Comment by SarthakNijhawan** [comment]
@abhsag24 can u elaborate a bit please?

**Comment by abhsag24** [comment]
@SarthakNijhawan yes but we just run the `execute_bear` context manager in the `LocalBearTestHelper` which doesn't get the dependencies.

**Comment by SarthakNijhawan** [comment]
Can u tell me that, while performing code linting with coala, what does in general checks these dependencies for a bear?
Like, which method is run before the `run` method for covering the dependencies ?

**Comment by abhsag24** [comment]
@SarthakNijhawan if you want me to point you towards the entry point it's the `run_coala` method in `coala_main.py` but there are a lot of things happen before the `run` method gets called and i'm sure i can't explain everything. Though some inspection from here and the `Bear` class might lead you to the answer your looking for ;)

**Comment by SarthakNijhawan** [comment]
OK, thnks a lot... That is wat I was lookin for... 😃

**Comment by Makman2** [comment]
Nextgen core would simplify things a lot, as it takes over dependency instantiation itself, and you would just do
```python
results = []
def on_result(result):
    # Here you can collect results and put them into a list or whatever
    results.append(result)

Core.run([my_bear], on_result)

# The bear instance gets set its dependency results inside the bear instance
self.assertEqual(my_bear.dependency_results,
                 ...)
```

**Comment by refeed** [comment]
@SarthakNijhawan are you still working on this?

**Comment by refeed** [comment]
Oh okay..

Btw @Makman2 how we can assign argument like file, settings kwargs to a bear in `bears` arg in `coalib.core.Core.run()`. I think it just accepts bear instances and a callback method, right?
Is there a way to assign file and settings kwargs when we instantiate a bear?

**Comment by Makman2** [comment]
Yes you assign those when instantiating a bear :) The new bear is called `coalib.core.Bear` instead of `coalib.bears.Bear`.
```
bear = MyBear(file_dict, section) # <-- section contains all the settings for the bear
```
