### ISSUE TITLE
Make LocalBearTestHelper robust

### ISSUE THREAD

**Issue by abhsag24** [coala/coala#2862]
_From @sils on February 21, 2016 15:8_

_From @AbdealiJK on December 8, 2015 13:31_

Currently, `LocalBearTestHelper` simply checks if there are results that are yielded or not.
Would be considerably better is we give it a list of line, cols where the result should yield in a given file.

_Copied from original issue: coala-analyzer/coala#1111_

_Copied from original issue: coala/coala-bears#36_

**Comment by abhsag24** [comment]
_From @sils on February 21, 2016 15:8_

@AbdealiJK I think we should support both, it's nice to have those simple tests sometimes IMO

**Comment by abhsag24** [comment]
_From @sils on February 21, 2016 15:8_

_From @AbdealiJK on December 8, 2015 13:59_

Yes, i meant it as an optional thing

**Comment by abhsag24** [comment]
_From @sils on February 21, 2016 15:8_

The helper should also create the actual files so it can be used well with linters that use file input.

**Comment by abhsag24** [comment]
_From @SanketDG on March 27, 2016 4:49_

What would be the best way to specify the line and column numbers for each invalid file?

**Comment by abhsag24** [comment]
_From @AbdealiJK on March 27, 2016 5:21_

Simple list of line,col tuple?


-----Original Message-----

**Comment by abhsag24** [comment]
_From @SanketDG on March 27, 2016 6:21_

So something like:
```
    valid_files=(valid_xml_file, valid_xml_chars),
    invalid_files=(invalid_xml_file, invalid_xml_chars),
    positions=([(start_line, end_line, start_col, end_col), ...], [....])
```

**Comment by abhsag24** [comment]
@SanketDG @AbdealiJK  i have an `assertRange`  function in  #227 's tests that does exaclty this, you might want to have a look at that

**Comment by abhsag24** [comment]
_From @Makman2 on March 27, 2016 15:26_

I think we should check against `Results`, then we can check for everything yielded, like severity etc.

**Comment by sils** [comment]
@SanketDG any news?

**Comment by sgsh123** [comment]
Hi,

Isn't the param lines in the check_results() module already allowing one to send in a list of strings of the lines that need to yeild results as this issue asks for or am I misunderstanding things?

**Comment by Makman2** [comment]
actually we have `LocalBearTestHelper.check_results` which allows to check against `Result`s for a given file / lines of a file, so imo we can close the issue :+1:

Thx @sgsh123 for bringing this up :)
