### ISSUE TITLE
Extract code blocks from documentation and process using appropriate bears

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#2867]
Idea sparked from https://github.com/coala/coala-bears/issues/902

It would be good to use the various python libraries for reStruturedText (docutils, Sphinx), Markdown, AsciiDoc, etc to extract the code blocks where they identify a code language, and push the code block through the relevant bears.

**Comment by sils** [comment]
@jayvdb I think you may want to close this in favour of https://github.com/coala/coala/issues/2538

**Comment by Makman2** [comment]
yes :+1:

**Comment by jayvdb** [comment]
In this case the language is not known in advance. But happy enough that the high level design part is a dup.

**Comment by sils** [comment]
Yep we would write bears using that design pattern achieving your functionality.
