### ISSUE TITLE
to_snakecase and others don't handle periods well

### ISSUE THREAD

**Issue by sils** [coala/coala#2881]
if you pass something like `Something.ElseIsGreen` you would expect `something.else_is_green` in the snake case example, however the actual result is `something._else_is_green`.

This probably also affects the other casing conversion functions.

**Comment by Makman2** [comment]
To implement this, I would additionally propose some general parsing function which would produce a list of terms and the file ending. Then we can control the interpretation way better, while the individual `to_snakecase`, `to_camelcase` etc. function write to the right format.

```
my_file_is_cool.cpp
['my', 'file', 'is', 'cool'] and 'cpp'
build.cpp.in
['build'] and 'cpp.in'
```
why? currently every casing function takes over the reading and interpreting of the string on its own --> code duplication --> bad

for example:
```python
def parse(string):
    ...

def to_snakecase(string):
    terms, ending = parse(string)
    # simple example, not sure this covers all cases:
    return '_'.join(term.lower() for term in terms) + ending
```

**Comment by d1ndra** [comment]
This seems interesting. Should I work on this?

**Comment by Makman2** [comment]
you should be invited, as soon as you accept I'll assign you :) If you want you can already start working :+1:

**Comment by d1ndra** [comment]
So I shouldn't be working on this?

**Comment by Makman2** [comment]
@Adrianzatreanu why did you assign @RohanVB ? :O

**Comment by RohanVB** [comment]
@d1ndra requested to be assigned to another issue, so he was assigned to that issue @Makman2

**Comment by sils** [comment]
oh actually this is a dupe of https://github.com/coala/coala/issues/2696 and @Asnelchristian is already working quite actively on that. I hope you don't mind if I close this?

**Comment by sils** [comment]
Tell us on the other issue if you want to collaborate.

**Comment by RohanVB** [comment]
Yeah, I talked to @Asnelchristian about this. We were thinking that #2696 could be for handling periods and then this PR could be for stopping the code duplication. Or maybe you could add the code-duplication part in #2696 aswell.
