### ISSUE TITLE
Add Ignore action

### ISSUE THREAD

**Issue by sils** [coala/coala#2882]
we should have an action that allows ignoring a result, that would place an "ignore" comment right there generated with coalang information.

This is doable but would mean a significant bump in usability!

**Comment by Nosferatul** [comment]
How this should be?

**Comment by sils** [comment]
What do you mean?

**Comment by Nosferatul** [comment]
I missunderstand

**Comment by sils** [comment]
@Nosferatul how's this going? Can we get that by today ish?

**Comment by Nosferatul** [comment]
I'm positive that I can make a pr today

**Comment by sils** [comment]
yesyesyes!
