### ISSUE TITLE
coala-ci should error if there is no .coafile

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#2888]
When there is no `.coafile` , `coala-ci` exit code is 0 and the output is:

```
[WARNING][09:35:55] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.

[WARNING][09:35:55] coala will not run any analysis. Did you forget to give the `--files` argument?

[WARNING][09:35:55] coala will not run any analysis. Did you forget to give the `--bears` argument?

Executing section Default...
```

**Comment by sils** [comment]
yeah right, if no analysis is performed the exitcode of all binaries should be nonzero right? Let's add an exitcode for that and document it. That should be fairly easy, modifying the coala main routine and changing docs. Marking difficulty/low.

**Comment by sils** [comment]
@jayvdb if you think it's critical I'll pick this up.

**Comment by sils** [comment]
I'll reuse exitcode 2 according http://docs.coala.io/en/latest/Users/Exit_Codes.html

**Comment by sils** [comment]
Heh, not so simple after all

**Comment by sils** [comment]
Alright the fix is simple (see commit referenced) but it destroys like all tests which just ignore the warning and don't pass valid configs there...

**Comment by sils** [comment]
I feel like we're starting to patch around the real problem. Because this won't catch e.g. if I give wrong bear names but only if I give no bears and arguments. Needs some architectural design thinking. I think we'll want to run the sections and print the warnings at the nothing_done hook and raise the systemexit there or something.

**Comment by adtac** [comment]
```diff
diff --git a/coalib/coala_main.py b/coalib/coala_main.py
index 8c82f30..4363fcf 100644
--- a/coalib/coala_main.py
+++ b/coalib/coala_main.py
@@ -116,6 +116,8 @@ def run_coala(console_printer=None,
         if cache:
             cache.write()
 
+        if [str(x) for _, x in sections.items()] == ['Default {}']:
+            did_nothing = True
         if did_nothing:
             nothing_done(log_printer)
         elif yielded_unfixed_results:
```

I know this looks really hacky, but this really describes the scenario. If there is exactly one sections and that is `Default` and it has no settings, it basically means there was no `.coafile`. Or the user had one and its content was just the section header:

```
[Default]
```

which is pretty useless anyway and we should probably warn them, I think.

**Comment by sils** [comment]
it looks pretty hacky and only covers one case of this error, I'll just cherry pick and write a test for https://github.com/coala/coala/commit/751328f87adc9126101a5f3f287f4e3eeb601202
