### ISSUE TITLE
Classes for Collectors.py

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#2890]
Maybe we should make classes inside Collectors.py so that the code wouldn't be global?
Something like:
`class CollectorsBear:`
`methods that are for bears`

Not so sure.
CC @sils

**Comment by Makman2** [comment]
What do you mean? We have already a `Bear` base class, `Collectors.py` is for collecting files the user selects via his coafile.

**Comment by Makman2** [comment]
And what do you mean with
> ... so that the code wouldn't be global?

**Comment by sils** [comment]
actually I'd rather refactor some of our classes like Parser and stuff
into functions

**Comment by sils** [comment]
what would that solve? Our current design is leaned towards the design of
the python standard library: use classes where they make sense, function
where those make sense.

**Comment by Nosferatul** [comment]
@Makman2 I saw it, I've been thinking only to encapsulate it. But I now understand the concept of how our code is designed. I see your point @sils 👍 . I'm closing this because of the descussion and open a new issue for refactor classes to talk about it
