### ISSUE TITLE
Constants.py: coalib.BUS_NAME imported but unused

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#2902]
We don't need this `from coalib import BUS_NAME`

**Comment by rohan097** [comment]
I would like to work on this issue. How do I proceed ?

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by tusharmakkar08** [comment]
Any updates @Adrianzatreanu ?

**Comment by sils** [comment]
lets do  #2949 indeed
