### ISSUE TITLE
ResultTest.py: local variable expected_file is assigned to but never used

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#2915]
`expected_file` variable isn't necessary in `test_json_diff`

**Comment by mei-li** [comment]
Can I get assigned this issue?

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)
