### ISSUE TITLE
Documentation: Current page's link in sidebar should be highlighted on coala.readthedocs.io

### ISSUE THREAD

**Issue by beatrix-bodo** [coala/coala#2925]
On http://coala.readthedocs.io the current page's link is not highlighted in the sidebar so when someone wants to click on the next page, it's difficult to find what page they are on currently.

**Comment by sils** [comment]
Thanks so much, good point. @Mariatta you had a master issue to track further design suggestions somewhere, right? That sounds like something that shuold be easy to add as well.

**Comment by Adrianzatreanu** [comment]
This issue was moved to coala/documentation#262
