### ISSUE TITLE
Language alias dictionary

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2927]
Often languages are commonly known under synonyms, like `C#`, `c#`, `cs`, `csharp` etc etc.
Some kind of internal mapping to a single language identifier would be very useful.

-->
If you have suggestions for aliases, post them here :+1:

**Comment by Makman2** [comment]
What also needs consideration is letter casing^^

**Comment by Makman2** [comment]
My first suggestions:
```
c#, cs, csharp
c (no further aliases)
c++, cpp, cplusplus
java (no further aliases)
javascript, js
visual basic, vb
bash, sh, shell
batch, bat
python, py (what about python2 and 3? not sure ...) 
```

**Comment by adtac** [comment]
Is this in coalang?

**Comment by sils** [comment]
An initial dictionary is already avail. for coalang. As for the docstyle definitions: we should merge them into coalang, maintaining both seperately is just going to bite us long term

**Comment by satwikkansal** [comment]
@sils I think all the aliases mentioned my @Makman2 are implemented in the `Language` class definitions. Should we close the issue?

**Comment by Makman2** [comment]
seems like, thanks @satwikkansal :)
