### ISSUE TITLE
README: Prerequisites `pip` should be >=6

### ISSUE THREAD

**Issue by chauffer** [coala/coala#2934]
It's 8.0 and 8.1 right now in different places.

difficulty/newcpmer

**Comment by AbdealiJK** [comment]
Sorry, what ? Could you elaborate this more ?

**Comment by AbdealiJK** [comment]
Ah in readme.rst in the prerequisite section ?

Why is it 8.x anyway ? I believe coala works fine for anything above 6.x

**Comment by chauffer** [comment]
dunno :D

**Comment by Makman2** [comment]
Then let's change to 6.x :+1:

**Comment by mamakancha** [comment]
I would like to get this issue assigned.

**Comment by chauffer** [comment]
@mamakancha done! reach us at https://coala.io/chat if you need any sort of help

**Comment by mamakancha** [comment]
I have fixed the issue and made the pull request.

**Comment by AbdealiJK** [comment]
You seem to have closed your pull request

**Comment by mamakancha** [comment]
Sorry. Just noticed it now. I have reopened my pull request. Thanks for pointing out.

**Comment by sils** [comment]
hey, your issue url in commit message contains a `#event....` can you remove that?

**Comment by mamakancha** [comment]
Sure. Will do that too.

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by todeadarius** [comment]
Assign me this issue, please.
