### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by rafidaslam** [coala/coala#2935]
There is a typo in `README.rst` especially in line 149.
```markdown
If you don't find your langauge there, we've got some
```

"langauge" should be "language" there.

**Comment by sils** [comment]
@anjabeth Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/! Sadly double PRs are happening then and when and we try to avoid you wasting time with this measure.

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by shrutishrm512** [comment]
@sils I want to work on this bug. I want you to assign this bug to me !!

**Comment by sils** [comment]
Hi,

please don't ping me personally for such things. Everyone can do them - and almost everyone pings me. If you don't address a person specifically you'll likely get help faster from other people!

(Don't worry, this is not a problem but keeping things general is usually a good policy :))

**Comment by shrutishrm512** [comment]
Ok, I will take care of this in future!



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=shrutishrm512@gmail.com&idSignature=22>

*Shruti Sharma*

*Pre-final Year Student*
*B.Tech.:Computer Science and Engineering*
*The LNM Institute of Information Technology*
Email ID*:shrutishrm512@gmail.com <shrutishrm512@gmail.com>*
