### ISSUE TITLE
Coala (MarkdownBear and AlexBear) do not ignore node_modules

### ISSUE THREAD

**Issue by plaindocs** [coala/coala#2938]
Using both Coala and Coala-ci with

```
[Default]
bears  = MarkdownBear
files  = **/*.md
ignore = **/node_modules/**,_site/**

[Languages]
bears  = AlexBear
files  = **/*.md
ignore = **/node_modules/**,_site/**
```

And they test `node_modules`. Both Alex and the remark markdow should ignore that dir by default.

**Comment by sils** [comment]
Hm, interesting... I'll try to reproduce it soonish if nobody else tries first

**Comment by sils** [comment]
CC @fneu the glob master

**Comment by sils** [comment]
@plaindocs it looks as if `**/` before `node_modules` is superfluous

**Comment by plaindocs** [comment]
Yep - just reached that conclusion myself. Am testing.

**Comment by adtac** [comment]
@plaindocs the isssue is with the first `/` in `**/node_modules/**` - since node_modules is at the root directory, there would be no `/` in the relative path to it. Hence that glob won't match that `node_modules` (however, it'll match every other node_modules dir).

**Comment by Makman2** [comment]
seems to be resolved :)

**Comment by sils** [comment]
@plaindocs just FYI you can shorten your config a bit:

```ini
[Default]
bears  = MarkdownBear
files  = **.md
ignore = node_modules/**,_site/**

[Languages]
bears  = AlexBear
```

will work as well as the settings from the default section are inherited to all others

**Comment by plaindocs** [comment]
@Makman2 Coala really should not be checking `node_modules` by default though. 
@sils excellent - thanks.

**Comment by sils** [comment]
@plaindocs so far we were like "it would be pretty astonishing if we ignore some stuff by default and the user is super surprised and has no clue why his ... directory isn't analyzed", I'm not sure what's the best decision design wise...

**Comment by plaindocs** [comment]
@sils yeah, but you're sending people to the `remark` docs for comprehensive docs anyway 

> See <https://github.com/wooorm/remark-lint> for details about the tool below.

So I think you really have to leave the defaults in. Maybe add a setting to toggle that?  

Also https://github.com/coala/documentation/issues/268#issuecomment-257856185

**Comment by sils** [comment]
Actually ideally people shouldn't ever need to click that link, we usually put it in in case the documentation of the bear is insufficient (which it certainly seems to be in this case).

"Leaving the default ignores in" of another tool is technically super complicated because deciding what to analyze and what to ignore is one of coala's main functionalities.

**Comment by wooorm** [comment]
@plaindocs `node_modules` is completely valid, and sometimes used. I’ve had issues where people wanted to allow that behaviour.
