### ISSUE TITLE
Ability to disable colour output

### ISSUE THREAD

**Issue by OmegaPhil** [coala/coala#2940]
Please can a setting be made to allow disabling colour output? The blue colour used for source file + location is particularly bad/almost illegible against a black terminal background here.

First time using coala, getting a feel for v0.8.1. The test invocation I'm using is (no coalafile used):

```coala-ci --bears 'CPPCheckBear' --files 'src/**.cpp,src/**.h' --settings 'enable=all'```

Thanks

**Comment by Makman2** [comment]
agreeing :+1:

**Comment by sils** [comment]
Nice idea, a lot of people had the same problem and we were thinking in #2928 about making the colors right somehow but this is way simpler.

**Comment by tulphoon** [comment]
I'd like to work in this issue.

**Comment by sils** [comment]
@tulphoon awesome, let us know if you need any help. This is important, please let us know immediately if you stop working on it (which is fine, just let us know ok?)

**Comment by tulphoon** [comment]
@sils sure, will do. I'm analyzing code right now. If you might guide me where the whole coloring is happening that would be great, but if not i'll try my best to find the way myself, it might just take a little longer.

**Comment by sils** [comment]
take a look at ConsoleInteraction.py , most of the stuff should be in there
somewhere

**Comment by sils** [comment]
Unassigning @tulphoon as per own request - the commit looks certainly promising! For the person who takes over: be sure to either keep @tulphoon as author or mention him as co author in the commit message.
