### ISSUE TITLE
Abandon dbus until there's demand

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2949]
I think the DBus interface should be abandoned.
It was made earlier for gefit plugin but was never used because things like coalaformat coalajson and so on were SO much easier.

It's dead code and a hindrance. Let's just remove it and keep it in a archive/DBus branch and look at it again whenever it's actually needed by someone.

I can't think of a single use case where DBus would be preferable to Json.

**Comment by sils** [comment]
yes yes yes yes yes yes yes!
