### ISSUE TITLE
bearlib: Change `min_line_length` to `max_line_length`

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala#2954]
Check line ``184``

**Comment by sils** [comment]
which file!?

**Comment by badarsh2** [comment]
I found a usage of min_line_length in __init.py__

` ...         AspectSetting(
  ...             "min_line_length",
  ...             "Maximum length allowed for a line.",`

If it is so, can I fix it? 
P.S. I'm a newbie here :)

**Comment by Makman2** [comment]
yeah seems this is the right one :)
@badarsh2 I've invited you to our org, be sure to check out our newcomer guides and feel free to talk to us at our gitter channel :)

As soon as you've accepted invitation, I'll assign you and you can start working :+1:

**Comment by badarsh2** [comment]
Done!
