### ISSUE TITLE
coala: Use a log file by default

### ISSUE THREAD

**Issue by Makman2** [coala/coala#2975]
Imo many information printed to the terminal are debug info which the user shouldn't see immediately so the terminal is not cluttered. I suggest using always a log-file which logs every message (so has LOG_LEVEL=DEBUG), and for example crashes point to the log file which contains the traceback as debug information.

1. Use a log-file together with terminal printing
2. Change some message log-levels to debug or info (like traceback)

**Comment by sils** [comment]
How do others handle this? @underyx might know

**Comment by sils** [comment]
closing in favour of https://github.com/coala/coala/issues/1862
