### ISSUE TITLE
Linter.py: Change docstring

### ISSUE THREAD

**Issue by srisankethu** [coala/coala#2986]
The [docstring](https://github.com/coala/coala/blob/e722d298b4c64d2d9be7b9f03d08a9b70a11e32c/coalib/bearlib/abstractions/Linter.py#L704) describes about RESULT_SEVERITY.MIINOR. Change it to RESULT_SEVERITY.INFO as RESULT_SEVERITY.MINOR does not exist.

area/documentation difficulty/newcomer

**Comment by Makman2** [comment]
Duplicate of https://github.com/coala/coala/issues/2816 :)

**Comment by srisankethu** [comment]
@Makman2 Oops! :+1:
