### ISSUE TITLE
How do you use Rultor?

### ISSUE THREAD

**Issue by amihaiemil** [coala/coala#2988]
Just wondering how do you guys use Rultor? 
I am trying to use it in my repos and when I try the ``merge`` command, the maven build is successful , but
it ultimately fails with:

```
ERROR: Permission to [reponame] denied to rultor.
```
I see [here](https://github.com/yegor256/rultor/issues/1108) that the solution is to invite Rultor as a collaborator with write access... that makes sense (I assume only write-access people should be able to merge branches), but this is not explicetly stated on rultor's documentation.

Did you have this issue/found another solution? - I do not see Rultor in the ``People`` of your org.

I also asked this in rultor's issue tracker, but they didn't answer yet...

**Comment by sils** [comment]
The rultor user needs write access. Please file documentation issues against https://github.com/yegor256/rultor/issues/

**Comment by amihaiemil** [comment]
@sils Thank you :D

**Comment by sils** [comment]
sure! :)

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/
