### ISSUE TITLE
get_filtered_bears forces use of the default arg parser

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3012]
`coalib.parsing.DefaultArgParser.default_arg_parser` is in fact the only arg parser, and all CLI apps that use `coalib` settings are currently invoking this arg parser.  As a result, the default arg parser has custom args in it, for specific CLI apps, such as some args only being available for `coala-json`.  It is not a good structure to require that any CLI using `coalib` must add their CLI args to `coalib`'s "default" arg parser.  Perhaps these should be using parent arg parsers; that needs to be explored.

`coalib.settings.ConfigurationGathering.py.load_configuration` and `coalib.parsing.CliParsing.parse_cli` have an option `arg_parser`, which can be used to provide a different arg parser, however `get_filtered_bears` does not have a `arg_parser` parameter, so it forces use of the default arg parser.  This makes `get_filtered_bears` unusable for any program which has a different set of CLI args (unless they add those args to `coalib`s default arg parser).

**Comment by adtac** [comment]
I'm taking this so that the other issue isn't blocked for long.
