### ISSUE TITLE
Missing param doc for `arg_parser` in `run_coala` in coala_main.py

### ISSUE THREAD

**Issue by adtac** [coala/coala#3016]

**Comment by rahul-kumi** [comment]
hey @adtac , I would like to work on this issue, can I be assigned.

**Comment by sils** [comment]
there you go, CC @tulphoon

**Comment by shubhamswain** [comment]
Hey @sils can I be assigned this if @rahul-kumi isn't working on this now?

**Comment by Nosferatul** [comment]
@shubhamswain please don't ping for such a task, just comment on the issue you want to be assigned 😄 .
@rahul-kumi  are you working on it?

**Comment by Nosferatul** [comment]
@rahul-kumi unassigned because of the long period of inactivity

**Comment by shubhamswain** [comment]
Is this okay? I've taken this from `ConfigurationGathering.py`
```
    :param arg_parser:              Instance of ArgParser that is used to parse
                                    non-setting arguments.
```

**Comment by tulphoon** [comment]
@shubhamswain I think it's okay. You should open a Pull Request referencing this issue though.
