### ISSUE TITLE
Result.apply: When applying multiple patches only the last patch remains in file_dict

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3034]
This is quite questionable behaviour.

**Comment by aptrishu** [comment]
Where did you observe this behaviour ? @Makman2 
Looking at the code It should store the original file_dict that was supplied along with the changes done in-place.

**Comment by Makman2** [comment]
If you do this
```
Result.apply(patch1)
Result.apply(patch2)
```
and both patches affect the same file, `file_dict` contains only the `modified` version of `patch2`. E.g. patches look like this:
```
-A
B
+C
```
and for `patch2`
```
A
-B
-C
```
your `file_dict` will contain only `"A"`, as that's the modified version of patch2 which overrides the patch of `patch1`.

@aptrishu open an interactive shell and try it out :)

**Comment by Makman2** [comment]
Looks like
```
:param diffs:
            A dictionary with filenames as key and a sequence of ``Diff``
            objects associated with them as values.
```
confused me a bit, `Result` does not support sequences of `Diff` objects, just a single `Diff` is supported.

Docstring needs change here:
- https://github.com/coala/coala/blob/master/coalib/results/Result.py#L139
- https://github.com/coala/coala/blob/master/coalib/results/Result.py#L62
