### ISSUE TITLE
misc.Annotations.type_chain: Move into different module

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3049]
This function is highly bear relevant, so it belongs somewhere inside `bearlib`.

**Comment by Yash17Agrawal** [comment]
we can put it in /coalib/bearlib/abstractions

**Comment by Makman2** [comment]
Not sure this annotation is some kind of "abstraction", maybe we should introduce a new `types` module?

**Comment by Makman2** [comment]
In this module we could place btw other useful "types" for bears^^

**Comment by Abhisek-** [comment]
Can I be assigned this issue ?

**Comment by Nosferatul** [comment]
go ahead!

**Comment by Abhisek-** [comment]
as @Makman2 said, I am going to put the `typechain` function in `coalib/bearlib/types/Annotations.py`. I'm not sure what `path` he is talking about ? I didn't find any `path` function which is bear specific! Can you en-light me on this more ?

**Comment by Makman2** [comment]
I mean the one in `coalib.Setting`, though nvm `path`, this looks slightly more complicated than I've thought^^
And as this and other "types" are in the `coalib.Setting` module, maybe `type_chain` belongs there too? I'm really unsure...
Okay decided, let's put `type_chain` into `coalib.Setting`, and not into `coalib.bearlib.types` :+1:
