### ISSUE TITLE
no need for # +ELLIPSIS

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#3065]
many doctests use `# +ELLIPSIS` to support `...` in outputs. This seems to be default and therefore obsolete :)

**Comment by jayvdb** [comment]
how are you planning to remove it?
As far as I am aware, doctest runner will fail unless it exists.

**Comment by Makman2** [comment]
Does not work, `# +ELLIPSIS` is not a default at least for our test setup. Is it possible to set some flag in `setup.cfg`?

**Comment by adtac** [comment]
There's https://github.com/scikit-learn/scikit-learn/blob/master/setup.cfg#L23

**Comment by sils** [comment]
IMO remove it, it works with our test setup and if someone uses another test setup he can still configure it to be default.
