### ISSUE TITLE
Linter api-docs: Missing backtick

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3089]
https://github.com/coala/coala/blob/master/coalib/bearlib/abstractions/Linter.py#L705

After RESULT_SEVERITY_INFO

**Comment by Yash17Agrawal** [comment]
Assign it to me , I will do it . @Makman2

**Comment by tulphoon** [comment]
@Yash17Agrawal to get assigned you must be a coala development group member, join our gitter and write "Hello World!" on main channel, after that i'm going to assign you.

**Comment by Yash17Agrawal** [comment]
@tulphoon  Done.
