### ISSUE TITLE
coala-ci doesn't work

### ISSUE THREAD

**Issue by sils** [coala/coala#3091]
@adtac works on this right?

importance/critical needed for the release *TODAY*

**Comment by adtac** [comment]
should we just go back to the previous file with a logging.warning at the top?

**Comment by adtac** [comment]
see :point_up: [November 21, 2016 7:10 PM](https://gitter.im/coala/coala?at=5832f95ab7cf637f2ac9f1f1)

**Comment by sils** [comment]
IMO no, fix that code, shouldn't be too hard :/

**Comment by sils** [comment]
also coala-format etc btw.

**Comment by sils** [comment]
@adtac got a fix: https://github.com/coala/coala/pull/3090
