### ISSUE TITLE
setup.cfg: [pytest] deprecated, use [tool:pytest] instead

### ISSUE THREAD

**Issue by SanketDG** [coala/coala#3097]
https://github.com/pytest-dev/pytest/pull/1813

Because it conflicts with the pytest in disutils.

difficulty/newcomer
importance/low

**Comment by kefeh** [comment]
i will like to be assigned this issue

**Comment by kefeh** [comment]
i will like to work on this

**Comment by tulphoon** [comment]
@kefeh before doing this issue, try to close your PR https://github.com/coala/coala/pull/3102

**Comment by kefeh** [comment]
@tulphoon i have closed the PR. Can i work on this now?

**Comment by Nosferatul** [comment]
@kefeh you have already 1 newcomer issue done. If that so, please find a difficulty/low one!

**Comment by jasemj** [comment]
Hello, I would like to be assigned this issue if that is possible.

**Comment by aptrishu** [comment]
There you go. :) @jasemj
