### ISSUE TITLE
Bug in terminal coloring

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3121]
![selection_011](https://cloud.githubusercontent.com/assets/7620533/20649814/8e0d00ac-b4ed-11e6-9475-2f9f58911ff4.png)

**Comment by Makman2** [comment]
Propably an upstream bug in pygments.

**Comment by sils** [comment]
@meetmangukiya what's your pygments version?

**Comment by meetmangukiya** [comment]
@sils 2.1.3

**Comment by sils** [comment]
try upgrading to 2.2 please, also this is reported upstream at https://bitbucket.org/birkenfeld/pygments-main/issues/1308/source-code-formatting-misbehaviour-on now

**Comment by meetmangukiya** [comment]
okay.. I'll see if it happens again

**Comment by meetmangukiya** [comment]
Pip tells already up-to-date :/

**Comment by Makman2** [comment]
@meetmangukiya did you use `--upgrade`?

**Comment by Makman2** [comment]
ah yeah there's no 2.2 currently in stable, you could maybe try to use the pre-release^^
