### ISSUE TITLE
BearTest.py: Fails test because BearTest class needs tearDown method

### ISSUE THREAD

**Issue by jasemj** [coala/coala#3132]
### Overview Description
BearTest.py will fail on test_download_cached_file if you execute the py.test command more than once.  It fails on line 191 on self.assertFalse(isfile(join(uut.data_dir, filename))). If you clone down the coala repository and install the test-requirements then run py.test, the first time it will pass, but every time after that it will fail.  BearTest class needs a tearDown method, the assert is failing because after the first execution of the tests the file is not being deleted. It passes on the gitmate tests because it uses a fresh run.
 
# Steps to Reproduce

1. Clone coala repository
2. Setup virtual environment and install test-requirements
3. Run py.test (will pass)
4. Run py.test again (will fail)

# Actual Results
self = <tests.bears.BearTest.BearTest testMethod=test_download_cached_file>

	def test_download_cached_file(self):
    	url = 'https://google.com'
    	filename = 'google.html'
    	uut = TestBear(self.settings, None)
>   	self.assertFalse(isfile(join(uut.data_dir, filename)))
E   	AssertionError: True is not false

tests/bears/BearTest.py:191: AssertionError

# Expected Results
No errors.
# Reproducibility

# Additional Information:
I have created a branch called "coala_issue_tearDown" and added a tearDown method while also removing the tear_down method in the TestBear class. The branch seems to fix the issue as far as I have tested.

 https://github.com/jasemj/coala/tree/coala_issue_tearDown

**Comment by jasemj** [comment]
Hello, I'm wondering if it's possible for me to be assigned this issue once it is verified? Then I can setup a pull request from the branch I have. Unless it is considered a newcomer issue then I will leave it be. Thanks.

**Comment by Mixih** [comment]
@jasemj Hmmm, I have completely rewritten this code segment in an upcoming pull request so it is N/A for now. Thanks for the work you have put into find and fixing this.

**Comment by jasemj** [comment]
@Mixih Okay sounds good, thanks for the quick response. No problem! It's a very cool project and I hope to contribute more.
