### ISSUE TITLE
Issues to be moved from coala/documentation into coala/coala 

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3136]
The following is a list of issues in coala/documentation that is related to Developers section of the docs.
Since the Developers section has been moved to coala/coala, these issues should be moved here and labeled `documentation`

I might miss a few tickets (as I'm not yet 100% familiar with the codebase) but this should be a good start.

- [x] https://github.com/coala/documentation/issues/341
- [x] https://github.com/coala/documentation/issues/331
- [x] https://github.com/coala/documentation/issues/325
- [x] https://github.com/coala/documentation/issues/310
- [x] https://github.com/coala/documentation/issues/304
- [x] https://github.com/coala/documentation/issues/303
- [x] https://github.com/coala/documentation/issues/301
- [x] https://github.com/coala/documentation/issues/290
- [x] https://github.com/coala/documentation/issues/271
- [x] https://github.com/coala/documentation/issues/270
- [x] https://github.com/coala/documentation/issues/265
- [x] https://github.com/coala/documentation/issues/248
- [x] https://github.com/coala/documentation/issues/242
- [x] https://github.com/coala/documentation/issues/239
- [x] https://github.com/coala/documentation/issues/222
- [x] https://github.com/coala/documentation/issues/214
- [x] https://github.com/coala/documentation/issues/193
- [x] https://github.com/coala/documentation/issues/183
- [x] https://github.com/coala/documentation/issues/181
- [x] https://github.com/coala/documentation/issues/169
- [x] https://github.com/coala/documentation/issues/151
- [x] https://github.com/coala/documentation/issues/150
- [x] https://github.com/coala/documentation/issues/149
- [x] https://github.com/coala/documentation/issues/148
- [x] https://github.com/coala/documentation/issues/141
- [x] https://github.com/coala/documentation/issues/106
- [x] https://github.com/coala/documentation/issues/101
- [x] https://github.com/coala/documentation/issues/47
- [x] https://github.com/coala/documentation/issues/46
- [x] https://github.com/coala/documentation/issues/38
- [x] https://github.com/coala/documentation/issues/36
- [x] https://github.com/coala/documentation/issues/32  (can be closed, I think)
- [x] https://github.com/coala/documentation/issues/29
- [x] https://github.com/coala/documentation/issues/20
- [x] https://github.com/coala/documentation/issues/10
- [x] https://github.com/coala/documentation/issues/2

**Comment by Mixih** [comment]
coala/documentation#32 has been closed

**Comment by Mariatta** [comment]
@sils mentioned this app can be used to move issues.
 https://github-issue-mover.appspot.com/ 
Is this something I can do? Or only the maintainers?

**Comment by sils** [comment]
Only maintainers unless you opened the issue

On Dec 4, 2016 05:13, "Mariatta" <notifications@github.com> wrote:

@sils <https://github.com/sils> mentioned this app can be used to move
issues.
https://github-issue-mover.appspot.com/
Is this something I can do? Or only the maintainers?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coala/coala/issues/3136#issuecomment-264683299>, or mute
the thread

**Comment by Mixih** [comment]
I suggest we only move a few at a time so we don't flood the main tracker with tickets

**Comment by sils** [comment]
It's flooded anyway, I've come to accept that.

**Comment by Mariatta** [comment]
All moved! :tada:

**Comment by jayvdb** [comment]
Thank you very much!
