### ISSUE TITLE
Developers/Writing_Good_Commits.rst:139: (INFO/1) Possible title underline, too short for the title.

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3139]
_From @Mixih on November 25, 2016 6:22_

_Copied from original issue: coala/documentation#331_

**Comment by Mixih** [comment]
_From @hemangsk on December 3, 2016 19:7_

Hey @Mixih , I'm new to Coala 😃  looking forward to getting involved with awesome community at coala. 
I just noticed that Developer docs have been moved to the main repo https://github.com/coala/coala.

I would like to solve this issue, will there be a new issue created in the coala/coala repo same as this one?

Thanks

**Comment by Mixih** [comment]
@hemangsk Yes, this will need to be moved. Hey, welcome to this project! To get started, goto the gitter and say hello to everyone there. They'll add you to the org which will let me assign you to an issue!

**Comment by hemangsk** [comment]
Hey @mixih !  I have joined the org 🎉  🎉    I would like to work on #3139, can you assign me this issue.

Thanks 😄

**Comment by aptrishu** [comment]
There you go. :) @hemangsk
