### ISSUE TITLE
Developer Docs: Add information about removing files from commits

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3140]
This is another very common problem in git when people just type `git add -A` after rebasing. We should teach them not to do this and also tell them how to fix this (see  http://stackoverflow.com/questions/18357511/git-remove-commited-file-after-push). This probably can be added to the git basics page.

**Comment by SarthakNijhawan** [comment]
Hey @Mixih , I would like to get assigned on this issue .

**Comment by Mixih** [comment]
@SarthakNijhawan you're on! This is a documentation issue so be warned that review could take a little longer ;)

**Comment by dracarys09** [comment]
@SarthakNijhawan are you still working on this issue ? If not, I would like to work on this...

**Comment by SarthakNijhawan** [comment]
Yea , I'll do ...srry for the late reply though ..

**Comment by SarthakNijhawan** [comment]
@Mixih `git add -A` will add the file to the staging area only , right ?
So what are we exactly planning for, can u be more elaborate please , so that I could write better....
Is it like that they(newcomers) commit thereafter only after rebasing into the master branch or something else. Thanks 😃

**Comment by Mixih** [comment]
Well yes and then they push. I think we'll need a `fixing common git issues` doc so we can outline how to fix a few of the more common ones. Here, you want to show them how to remove files from a commit even after a push.

CC @sils regarding a new doc

**Comment by SarthakNijhawan** [comment]
@Mixih I have created a PR referring this issue ... pls take a look.. 😃
