### ISSUE TITLE
Bear.get_non_optional_settings doesnt check dependencies

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3149]
`KeywordBear` depends on `AnnotationBear`, which has a required parameter `language`.

`KeywordBear.get_non_optional_settings()` doesnt include `language`.

```python
>>> bears.general.KeywordBear.KeywordBear.get_non_optional_settings()
OrderedDict()
>>> bears.general.KeywordBear.KeywordBear.get_metadata().non_optional_params
OrderedDict()
```

This appears to be one of the underlying causes of https://github.com/coala/coala-bears/issues/1012, and thus https://github.com/coala/coala/issues/3128

Perhaps `Bear.get_non_optional_settings` should have a parameter `recursive` which walks the dependency tree.

**Comment by jayvdb** [comment]
I've added a workaround in https://github.com/coala/coala-quickstart/pull/40 .

> This appears to be one of the underlying causes of coala/coala-bears#1012, and thus #3128

Not quite correct; it only causes a decent error message, indicating that `language` isnt set, which at least helps people migrating to 0.9 to understand how to fix the problem.

**Comment by jayvdb** [comment]
If `get_non_optional_settings` and `get_optional_settings` recurse, there needs to be a way to find out the non-recursive per-bear settings.

**Comment by sils** [comment]
@Makman2 any progress? I heard you had a solution? I'm not too eager on merging the workaround from @jayvdb if we can have the full fix with close to equal the effort.

**Comment by Makman2** [comment]
yes in fact we could use my `traverse_graph` function which is already fully tested and working on my branch. If you want we can already merge this part of the core, traverse each dependency and merge the parameters:
```
def merge_param(prev_bear, next_bear):
    pass #...

traverse_graph([self], lambda bear: bear.DEPS, merge_param)
```

**Comment by sils** [comment]
we could just add dependencies in get_optional_settings recursively, that'd
be super easy and doesn't rely on that graph algorithm

**Comment by Makman2** [comment]
oh yes that's for sure easier, let's do this 👍

**Comment by jayvdb** [comment]
Oh look, this didnt make it into 0.9.1 ;-(
