### ISSUE TITLE
Space between package names in import

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3153]
https://github.com/coala/coala-bears/blob/master/tests/general/AnnotationBearTest.py#L9 needs a space removed.

**Comment by srk97** [comment]
I would like to get assigned to this.

**Comment by UMANIAX** [comment]
Please assign me this issue, gonna be my first bug to fix. Cheers!

**Comment by jayvdb** [comment]
@UMANIAX, it is already assigned to someone else, who is working on it in PR #1090.
