### ISSUE TITLE
--format does not work in non-interative mode

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3154]
Using `--ci` and `--format` together discards the --format argument.

**Comment by namanyadav12** [comment]
Hi. Can i be assigned be this issue ?

**Comment by jayvdb** [comment]
I've assigned you to https://github.com/coala/docker-coala-base/issues/34 first.  Once that is done, this would be a good second bug to complete.  Happy hacking.

**Comment by meetmangukiya** [comment]
I digged a bit, and it seems to be a problem in https://github.com/coala/coala/blob/b02883a7a4abb9e98d85d28fa21617def1e88268/coalib/coala.py#L77
The `if` block makes it either `--ci` or `--format`, since they are considered two different modes..

**Comment by shrutishrm512** [comment]
Hello, please assign this bug to me !

**Comment by shrutishrm512** [comment]
Changing line 77 as
`if args.format or args.ci:`
then this statement can be correct?

**Comment by jayvdb** [comment]
line 77 of which file?  Please give a link so I can quickly answer.

**Comment by jayvdb** [comment]
AH; ignore me; I see your PR now.  sorry.

**Comment by shrutishrm512** [comment]
Line 77 in coala/coalib/coala.py
https://github.com/coala/coala/blob/b02883a7a4abb9e98d85d28fa21617def1e88268/coalib/coala.py#L77

**Comment by jayvdb** [comment]
ok, that wont work.  Above it is `if args.non_interactive: return ..` so line 77 is never executed.

**Comment by shrutishrm512** [comment]
`if args.format:` line never executes due to `if args.non_interactive:` so i made changes in if block such that both will execute as per my understanding, but i also want to ask about that
> coala --format=anyfilename(say:README.rst) can be executable one? since i got error in that!

**Comment by jayvdb** [comment]
Anyone picking up this issue, please first do a little analysis before coding.

**Comment by Nosferatul** [comment]
@andreiraduta1101 are you still working on this?

**Comment by Nosferatul** [comment]
unassigned due to inactivity

**Comment by meetmangukiya** [comment]
The PR raised for this issue doesn't allow the user to use both the arguments together, and lets the user know that one of them will be ignored.

**Comment by Nosferatul** [comment]
Closing because 3999 was merged
