### ISSUE TITLE
source lines are not available as a --format placeholder

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3155]
Current `--format` placeholders are: origin, file, line, end_line, column, end_column, severity, severity_str, message .

It would be useful to have the source lines available as a placeholder, as that can be used to specify a custom format that is more similar to the current default UI.

**Comment by sils** [comment]
not too sure this is smart, currently the main assumption is that the format string is a one liner, this'll definitely introduce multiple lines and it's likely badly parsable. At least it shouldn't be active by default IMO

**Comment by jayvdb** [comment]
Ya, I've no intention for it to be active by default. That would be a breaking change.
Also we could use a new line marker instead of `\n`, like pygments uses.

**Comment by Abhisek-** [comment]
If we render everything in on line without using newline, then it will become too confusing to understand as what is wrong with source file. Not sure about the pygments thing
