### ISSUE TITLE
Split result message into constant message and arguments

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3156]
Currently the message can be like `LineLengthBear`'s "Line is longer than allowed. (644 > 79)", which is a formatted string.

If this is split into a constant message with placeholders and arguments, consumers can more easily do operations like grouping similar messages together, and l10n of messages becomes possible.

The constant message and arguments should be emitted in the JSON, and in `--format`, etc.

**Comment by sils** [comment]
we should put this message into the aspects IMO so the bears don't provide a message at all. All the grouping will be made possible with aspects anyway btw.

**Comment by sils** [comment]
CC @razvanch

**Comment by Mixih** [comment]
should be deprecate the old syntax too after a while?
