### ISSUE TITLE
Reported message statistics

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3157]
pycodestyle and flake8 have a `--statistics` argument that prints a summary of messages with counts.
A similar feature would be useful.

To get reasonable results, some messages need to be post-processed, or this needs to wait until #3156 is implemented in the bears.  e.g. the problem is cases like `Line is longer than allowed. (89 > 79)` which cant be grouped together in statistics.

**Comment by Makman2** [comment]
I think this is a dupe of https://github.com/coala/coala/issues/759 . Agree @jayvdb ?

**Comment by jayvdb** [comment]
Yup. Copied relevant comment there.
