### ISSUE TITLE
hasattr on Language instance attribute raises KeyError

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3160]
hasattr doesnt work correctly, as failure to resolve it should raise `AttributeError`

```python
>>> from coalib.bearlib.languages.Language import Language
>>> l = Language['C#']
>>> l.extensions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../coalib/bearlib/languages/Language.py", line 342, in __getattr__
    return self._attributes[item]
KeyError: 'extensions'
>>> hasattr(l, 'extensions')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../coalib/bearlib/languages/Language.py", line 342, in __getattr__
    return self._attributes[item]
KeyError: 'extensions'
```

~~To be backwards compatible, a new exception class is needed, that subclasses both `KeyError` and `AttributeError`.~~

This was released in 0.9, so fixing this is still a minor bug.  Nobody will be relying on this bad behaviour in production yet.

**Comment by hemangsk** [comment]
Progress -  
AttributeError is successfully raised in place of KeyError at `l.extensions`

In `__getattr__` in Language.py, wrapped `return self.attributes[item]` in `try/except`.

```
try:
    return self._attributes[item]
except KeyError:
    raise AttributeError from None
```

![screen shot 2016-12-06 at 5 36 13 pm](https://cloud.githubusercontent.com/assets/13018570/20925217/9993bb1a-bbdb-11e6-93af-10d8a4b172b4.png)

Thoughts?
Also, apart form displaying the text 'AttributeError', it'd be better if it shows a message too?

**Comment by jayvdb** [comment]
Ya, that is what we need.
A test case would be nice.  Use a different attribute , not 'extensions', as that attribute has been added in a recent merge.  A crazy attribute name would be better.
