### ISSUE TITLE
Allow actions to specify their own 'not applicable' messages

### ISSUE THREAD

**Issue by underyx** [coala/coala#3169]
If we have that, instead of

```
[WARNING][15:46:28] Selected default action 'ShowPatchAction' for bear 'AnnotationBear' is not applicable. Action not applied.
```

the warning could say

```
[WARNING][15:46:28] No automatic patch could be generated for this result by 'AnnotationBear'.
```

**Comment by arush0311** [comment]
Can I take this?

**Comment by arush0311** [comment]
Hey! Can you tell me where the resultAction are applied, i mean what class calls the apply method of resultAction?

**Comment by arush0311** [comment]
Nevermind! found it in processing.py

**Comment by arush0311** [comment]
So, I have to first create a not_applicable property in each action class containing the text string to be displayed. is that the right approach?

**Comment by sils** [comment]
I'd rather return the reason as string in the is_applicable function.

**Comment by arush0311** [comment]
What should be the not_applicable messages for all the actions?

**Comment by Makman2** [comment]
yes
