### ISSUE TITLE
Newcomers_Guide.rst: Fix broken links

### ISSUE THREAD

**Issue by Abhisek-** [coala/coala#3179]
Some of the links in *Newcomers_Guide.rst* are broken and it points to old link which is not valid now.

Some of the line of the file are as follows (all from **see also** section)

* Line:97: Writing bears <http://coala.readthedocs.io/en/latest/Developers/Writing_Bears.html>
* Line:139: Executing tests <http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html>
* Line:223: Review Process <http://coala.readthedocs.io/en/latest/Developers/Review.html>

But the domain should be `api.coala.io` instead of `coala.readthedocs.io`.

**Comment by ashwini0529** [comment]
I can take this up.
