### ISSUE TITLE
docs-requirements.txt partially incompatible with pip 6.0.7

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3183]
b3f66025 updated `test-requirements.txt` to include requirements.txt, and pip doesnt like processing these together, and fails to avoid a cyclic inclusion path.

```
pip 6.0.7 from /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (python 3.4)
$ pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt
Double requirement given: appdirs~=1.4 (from -r requirements.txt (line 1)) (already in appdirs~=1.4 (from -r requirements.txt (line 1)), name='appdirs')
```
from https://travis-ci.org/jayvdb/coala/builds/182529779

There are several ways to work around this, and many dont require any changes to the repo, and most people will never encounter this.

Do we have a minimum version of pip we will support?
I expect this can be closed, but it is helpful to log where there are incompatibilities.

**Comment by sils** [comment]
So far we have never thought about a minimum version of pip to support but we definitely wanna use `~=` (which doesn't work with the really old debian pip ones)

**Comment by jayvdb** [comment]
http://docs.coala.io/en/latest/Users/Install.html says "Make sure you have pip >= 8 installed"

**Comment by jayvdb** [comment]
That comes from [this commit](https://github.com/coala/documentation/pull/385/commits/2826f16) authored 29 Oct 2016 and committed in January without any justification provided.

For an unrelated reasons, mostly to do with CI, we now have test-requirements.txt requiring `pip>=9.0.0`.

Anyway, these `-r` are not especially needed now.
