### ISSUE TITLE
Sphinx docs warning

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3199]
Using Sphinx v1.4.9, which we should be doing anyway ...

```
make: Entering directory `/home/travis/build/coala/coala/docs'
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v1.4.9
making output directory...
...
Warning, treated as error:

/home/travis/build/coala/coala/docs/Developers/Writing_Tests.rst:136: WARNING: unknown document: Testing
```
https://travis-ci.org/coala/coala/jobs/182618295#L1867

This is blocking Travis CI.

**Comment by jayvdb** [comment]
I believe the problem is that `Writing_Tests.rst` should be linking to `Executing_Tests.rst`, but that was broken due to a rename somewhere.

```
$ git grep Testing docs
...
docs/Developers/Executing_Tests.rst:Testing
..
docs/Developers/Writing_Tests.rst:        Module :doc:`Executing Tests <Testing>`
```

Also importantly, we should find out why it is broken yet the builds are green, and prevent it occurring again.

**Comment by Mixih** [comment]
I'm on it

**Comment by jayvdb** [comment]
https://github.com/coala/coala/issues/3200 doesnt turn the build red, so there is some other problem with the Circle builds, preventing this RST syntax from being an error.

**Comment by Mixih** [comment]
so it's not an error?

**Comment by Mixih** [comment]
I've pinned down this issue to build #9298 (https://circleci.com/gh/coala/coala/9398) (commit a0f9cba) which first introduced this issue. Even thought he docs started failing to build, circle ignored the exit code. Here is the docs output log from circle: 

````
Warning, treated as error:
/home/ubuntu/coala/docs/Developers/Writing_Tests.rst:136: WARNING: unknown document: Testing

make: *** [html] Error 1
make: Leaving directory `/home/ubuntu/coala/docs'
````

**Comment by jayvdb** [comment]
It is an error. But Circle isnt detecting it.

**Comment by danuker** [comment]
Problem was that this warning does not cause the build to fail:
```
build succeeded, 1 warning.

The HTML pages are in build/html.
$ echo $?
0
```

If you want to turn the warnings into errors, Sphinx supports the `-W` CLI argument. That will cause a nonzero return value, which is detectable by CI.
