### ISSUE TITLE
Upgrade Sphinx to 1.4.9

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3200]
Currently Sphinx is pinned to 1.4.8.  We should be upgrading.

**Comment by jayvdb** [comment]
Hunted down the reason for this.
rstcheck depended on Sphinx, so coala-bears depends on Sphinx
https://pypi.python.org/pypi/Sphinx 1.5 was released a few days ago, and it didnt work with rstcheck (https://github.com/myint/rstcheck/issues/18 ).  So then their version of Sphinx conflicting with our required version of Sphinx.

https://github.com/myint/rstcheck/pull/20 solves that, and they also made Sphinx optional it seems, so that avoids it conflicting in the future.  But .. the new version rstcheck isnt released yet.

**Comment by sils** [comment]
@jayvdb so for now the commit is fine but shouldn't close this issue?
