### ISSUE TITLE
Removal of autoapply in run_coala causes difficulty when using coala in a serverside checking application

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3212]
The removal of auto-apply parameter from run_coala means that coala still auto applies applies it's actions when run from run_coala. We need to have a way for the user to disable auto-patch application so coala can be used to show code errors, not fix them. (This almost broke gitmate)

**Comment by sils** [comment]
marking critical importance because this affects gitmate and thus also us!

**Comment by sils** [comment]
CC @fneu @seblat or anyone really, if you have time, fix this please

**Comment by Mixih** [comment]
decided to add `autoapply` parameter. default it to true, when false, don't apply action.
per gitter https://gitter.im/coala/coala?at=584c5c47c29531ac5d480430

**Comment by Mixih** [comment]
I advise we patch coala-incremental for now as it's critical and testing will be a mess. It's appearently a tiny workaround there that will be easy to implement. https://gitter.im/coala/coala?at=584c59ccaeb49008046ff5d0

**Comment by Mixih** [comment]
https://github.com/coala/coala/pull/3216 closes. Due to a failure on my part, I failed to catch the multiple commit issues before merging. *sigh*
