### ISSUE TITLE
[hotfix] Remove the default_actions settings from the coafile[patched]

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3213]
The latest version of coala has removed support for the apply_patch_action setting. This prevents gitmate from raising issues about patch actions which were applied. Until this gets fixed in coala, we need to remove the default_actions because coala (and thus gitmate) will be applying them. This will need to be rolled back when #3212 is patched.

**Comment by Mixih** [comment]
Open to keep track of this issue

**Comment by sils** [comment]
to readd it once gitmate is fixed?

**Comment by Mixih** [comment]
Yup!
