### ISSUE TITLE
create page about cobot 

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3228]
_From @coala-bot on November 15, 2016 12:45_

Opened via [gitter](https://gitter.im/coala/coala/?at=582b0350bd2f135f1a1e3c5c) by @jayvdb

_Copied from original issue: coala/documentation#303_

**Comment by Mariatta** [comment]
I assume this is for the Developers section?

**Comment by jayvdb** [comment]
yes

**Comment by ashwini0529** [comment]
I can take this up.

**Comment by ashwini0529** [comment]
Do you want a webpage or a `rst`?

**Comment by Mariatta** [comment]
It should be a new section in Developers documentation, so an .rst file :) Thanks.

**Comment by ashwini0529** [comment]
Hey. Can you please share the content with me at [this link](http://collabedit.com/pe9c9) ?

**Comment by Mariatta** [comment]
We don't have any content yet :( so it's part of this issue to come up with the content 
Other maintainers can perhaps clarify further.

**Comment by ashwini0529** [comment]
@coala/coala-admins Please help me with the content. :confused: So that I can proceed further.

**Comment by Makman2** [comment]
@sils you are maintainer of cobot, your duty :)

**Comment by sils** [comment]
I'm maintainer of everything. I'm also sick. I need to relax. I'm certainly
not cobots main contributor. This is not my duty.

On Dec 22, 2016 9:33 PM, "Mischa Krüger" <notifications@github.com> wrote:

@sils <https://github.com/sils> you are maintainer of cobot, your duty :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/coala/coala/issues/3228#issuecomment-268884811>, or mute
the thread

**Comment by sils** [comment]
Also I have no idea what content you want

**Comment by Makman2** [comment]
@sils who's the main contributor currently?

**Comment by sils** [comment]
No idea, use git?

**Comment by Mixih** [comment]
Well, you could start by documenting `cobot help` 's output...

**Comment by sils** [comment]
But don't duplicate it, maybe just enhance the help and tell people to use
that

**Comment by ashwini0529** [comment]
Alright. I'll start by `cobot help`
I'll come up with a `rst` soon

**Comment by ashwini0529** [comment]
```
cobot (invite|inv) <username> [to [team]] - Allows maintainers to invite users to the coala organization
cobot <nevermind|nm> - Doesn't mind.
cobot <wa|wolfram> <question> - Searches Wolfram Alpha for the answer to the question
cobot assign <issue_link> - Assigns issue <issue_link> to user
cobot explain <topic> - Returns the info we have on your topic
cobot ghetto <text> - Real talk yo
cobot help - Displays all of the help commands that Hubot knows about.
cobot help <query> - Displays all help commands that match <query>.
cobot lmgtfy <term> - Searches google for you!
cobot new issue - Creates a GitHub issue given the title and repository
cobot the rules - Make sure hubot still knows the rules.
ship it - Display a motivation squirrel
```
^
For reference.

**Comment by ashwini0529** [comment]
I've started building the `cobot`  page and it's somewhat like this.
<img width="940" alt="screen shot 2016-12-26 at 3 12 08 am" src="https://cloud.githubusercontent.com/assets/8419333/21472990/3a06d856-cb19-11e6-98e6-5468d80bd33f.png">

Is this a good start?

**Comment by nemaniarjun** [comment]
I don't think you need to be a maintainer to invite people, you just need to be a member.
But right now due to an upper limit issue, the new members are unable to use cobot, it straight out ignore them.

**Comment by ashwini0529** [comment]
@nemaniarjun try typing `cobot help` in gitter chat.
It will mention that only maintainers can invite people. I'll change it though.
Btw I was asking about the formatting.

**Comment by nemaniarjun** [comment]
Then the issue I was raising belongs to `cobot help`
The formatting looks good enough to me :+1:

**Comment by ashwini0529** [comment]
Let's raise an issue for `cobot help`?

**Comment by nemaniarjun** [comment]
Go ahead :D 
Will need to make an account on GitLab I suppose

**Comment by ashwini0529** [comment]
Anything for `coala` ! :smile:

**Comment by nemaniarjun** [comment]
Since cobot cant stop us, 
Anything for `Coala` :stuck_out_tongue_winking_eye:  :wink:

**Comment by ashwini0529** [comment]
Hahaha!

**Comment by sils** [comment]
I'm still against writing a help page like this. Rather improve cobot help
and make cobot work for anyone. And yes, invitation is a maintainers only
thing, we wanted to prevent random people from getting an inv and then
abuse it, potentially getting our account locked out.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by ashwini0529** [comment]
Even I'm against duplicating things, but there should be a place where people get to know about `cobot`. Like if I'm new to coala, I've to explicitly search for `cobot`.

**Comment by ashwini0529** [comment]
So a page or improve help page?

**Comment by sils** [comment]
I vote for improving help

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by sils** [comment]
@ashwini0529 @Mariatta I really think this is not leading to anything - lots of discussions an all proposed solutions are introducing documentation that *will* get outdated and just confuse people.

I propose closing this issue and opening one for cobot about improving it's help page and also get that gitter hubot adapter fixed so other people can actually use cobot. Or who knows, maybe @meetmangukiya makes cobot junior reality - written in python.

**Comment by jayvdb** [comment]
Note that https://github.com/coala/coala/pull/3396 is still open.

I notice we also dont have a page about gitter in general.  Maybe a "communication" page would be useful, describing gitter , summaries of the rooms we use and why, and a brief mention of cobot would be suitable on that page?

**Comment by sils** [comment]
@jayvdb coala.io/channels
