### ISSUE TITLE
Update Newcomer guide link from http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html to http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

### ISSUE THREAD

**Issue by ashwini0529** [coala/coala#3232]
Update Newcomer guide link from http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html to http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by ap916** [comment]
Assign this to me, Please.

**Comment by ap916** [comment]
@ashwini0529 I've submitted a pull request. Would you please take a look.
