### ISSUE TITLE
Add review "confirmation" policy to review docs

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3247]
_From @coala-bot on October 31, 2016 8:22_

>  Is there a policy / recommendation about 'affirmative' replies to review comments.  I usually discourage them.  I tell newcomers "unless there has been a technical discussion, there is no need to form consensus with 'ok, affirmative'-style comments - unless you disagree with the review comment, dont be noisy with 'ok, affirmative'-style comments : just do what was requested when you can.  "

yes, that's the policy. Sometimes people want to "check off" items they have addressed while working on it, recommendation is to use thumbs up

difficulty newcomers, see the discussion

Opened via [gitter](https://gitter.im/coala/coala/?at=5816ff620e25dbfa117d4375) by @sils

_Copied from original issue: coala/documentation#265_

**Comment by Mariatta** [comment]
_From @cristinabuciu on November 19, 2016 13:50_

I would like to work on this

**Comment by TheLayman** [comment]
[PR](https://github.com/coala/coala/pull/3851) is here.

**Comment by li-boxuan** [comment]
Unassigned due to inactivity.
