### ISSUE TITLE
Review.rst enumerated list syntax problem

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3249]
_From @jayvdb on October 29, 2016 14:24_

``` bash
$ rstcheck Developers/Review.rst
Developers/Review.rst:2: (INFO/1) Enumerated list start value not ordinal-1: "6" (ordinal 6)
```

The blocks in `5.` are not indented, so it thinks `6.` is a new list.

_Copied from original issue: coala/documentation#242_

**Comment by Mariatta** [comment]
_From @charlesBak on October 30, 2016 6:40_

hi @jayvdb can you please explain the issue?

**Comment by Mariatta** [comment]
_From @jayvdb on October 30, 2016 7:13_

@charlesBak , please look at the relevant section of the file, and try to fix the syntax.  You may need to read about the syntax of reStructuredSyntax to understand the problem.

**Comment by Mariatta** [comment]
_From @mihai-burduselu on November 19, 2016 14:53_

Assign me this!

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on November 19, 2016 15:17_

hey @mihai-burduselu you have not accepted our invitation, please check your mail ( i cannot assign you )

**Comment by Mariatta** [comment]
_From @mihai-burduselu on November 19, 2016 15:21_

done, sorry :)

**Comment by DanRadulescu962** [comment]
Can I be assigned on this?

**Comment by Makman2** [comment]
@mihai-burduselu still working on it?

**Comment by Makman2** [comment]
assigning @DanRadulescu962 for now, @mihai-burduselu if you still want to work on this issue, ping and we change assignment again :+1:
