### ISSUE TITLE
Newcomer guide should invite users to solve difficulty/low issues as well

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3250]
_From @sils on October 29, 2016 10:24_

_From @justuswilhelm on October 29, 2016 7:27_

Lasse suggested this and I agree. Devs that are already familiar with how OSS contribution works can already start hacking on difficulty/low issues!

_Copied from original issue: coala/coala#2916_

_Copied from original issue: coala/documentation#239_

**Comment by Mariatta** [comment]
_From @sils on October 29, 2016 10:24_

_From @justuswilhelm on October 29, 2016 10:20_

Perhaps this issue should be in the documentation repository...

**Comment by Mariatta** [comment]
_From @yash-nisar on October 31, 2016 4:6_

@sils @Adrianzatreanu  There are 2 instances of the following Note: 

> **Do not only fix a newcomer issue!** Supervising newcomers is really a lot of work. We’re all volunteers and we can’t keep this up if you don’t help us in other areas as well!

What about replacing one Note with the following ?

> **Do not only fix a newcomer issue!** It is highly recommmended that you fix one newcommer issue to get familiar with the workflow at coala and then proceed to a **difficulty/low** issue.

**Comment by Mariatta** [comment]
_From @jayvdb on October 31, 2016 7:8_

Experienced devs often dont know how to write good patches.

IMO, rather than jumping to low tasks, IMO experienced devs should jump to reviewing some patches first.  Then they are working beside other reviewers, and will pick up some rules they were not aware of.

**Comment by Mariatta** [comment]
_From @yash-nisar on October 31, 2016 7:15_

@jayvdb I completely agree with you. How about renaming the issue to 

> Newcomer guide should invite users review difficulty/newcomer issues

and then we can move on to a difficulty/low issue.

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on October 31, 2016 8:3_

I've happened to see even experienced devs that struggled with rebases and stuff, so it might not be wise to ask them to start with low.

However, if im not mistaken, we have a PR open that changed the newcomers guide a little and expressed what a newcomer needs to do, quite nicely, and im not sure if it is merged, cuz if it isnt, i think you should wait until it is :)

**Comment by Mariatta** [comment]
_From @yash-nisar on October 31, 2016 8:10_

Sure !

**Comment by rahul-kumi** [comment]
Can I be assigned to the issue. I would love to work on this.

**Comment by Mixih** [comment]
Sure! You're on. See https://api.coala.io/en/latest/Developers/Newcomers_Guide.html to get started. See https://api.coala.io/en/latest/Developers/Development_Setup.html to setup your development environment.

**Comment by rahul-kumi** [comment]
thank you, @Mixih, could you let me know how elaborate should I be in encouraging newcomers to take up `difficulty/low` issues.

**Comment by dracarys09** [comment]
@rahul-kumi are you still working on this ?

**Comment by harshit890** [comment]
@mixih if he is not working on it plzz assign this to me

**Comment by Makman2** [comment]
@rahul-kumi if you still want to work on the issue, just ping :)
For now assigning @harshit890
