### ISSUE TITLE
Be more forceful about using branches

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3253]
_From @jayvdb on October 14, 2016 23:21_

http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#creating-a-new-branch currently says

> To start working on an issue, you first need to create a new branch where you will work.
> 
> ```
> $ git checkout -b branchname
> ```

I think the document should explain why using "master" is a very bad idea, and more importantly include a "make sure you are not using master" check at every step of the process.

Also, it would be helpful to provide examples of useful branch naming schemes instead of `branchname`.  Some common schemes:
- issueXXX
- patchXXX
- gh-XXX

It may also be useful to use "my-first-good-pull-request" as the branch name, as it is the first one which is the most problematic.

Then continue to use that throughout the document, using `git checkout my-first-good-pull-request` at the beginning of each block of example commands, so that our documentation is teaching them what a branch is, and our documentation works even if they have use other git commands they have found on the internet.

_Copied from original issue: coala/documentation#193_

**Comment by Mariatta** [comment]
_From @Cygnus32 on November 13, 2016 16:8_

assign this to me please :)

**Comment by jayvdb** [comment]
Note the URL is now http://api.coala.io/en/latest/Developers/Git_Basics.html#creating-a-new-branch

**Comment by Mixih** [comment]
@Cygnus32 unassigning due to inactivity
