### ISSUE TITLE
Newcomers_Guide.rst: Rephrase note

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3254]
_From @Makman2 on October 12, 2016 19:42_

> ```
> .. note::
> 
>     Reviewing code helps you by watching other people's mistakes and not making
>     them yourself in the future!
> ```

Imo it should also contain something in the direction of "you are improving yourself doing this" :+1:

_Copied from original issue: coala/documentation#183_

**Comment by Mariatta** [comment]
_From @Dayfiri on October 13, 2016 13:53_

Assign me please :)

**Comment by Mariatta** [comment]
_From @sils on October 13, 2016 14:11_

Hey,

you have done two newcomer issues and it seems you're well acquainted with the workflow! That's awesome :)

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://tinyurl.com/coala-low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by Mariatta** [comment]
_From @Dayfiri on October 13, 2016 14:13_

@sils Ok thanks for the info. I will do that in the future 👍 
Just there are `0` problems there so not much for me to help :)

**Comment by Mariatta** [comment]
_From @sils on October 13, 2016 14:17_

See coala.io/low there should be plenty of easy stuff to go on with

**Comment by Mariatta** [comment]
_From @Akki356 on October 16, 2016 18:48_

Please Assign me this :)

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on October 16, 2016 18:51_

hey first please accept the invitation, join us on gitter! https://gitter.im/coala/coala

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on November 19, 2016 14:15_

unassigning due to inactivity

**Comment by Mariatta** [comment]
_From @MihneaVorovenci on November 19, 2016 14:32_

Can I be assigned on this issue?

**Comment by nealkarpe** [comment]
@Mariatta Since this issue has been inactive for quite some time, I was wondering if you could re-assign it to me?

**Comment by Mariatta** [comment]
For sure. Will assign to you.
