### ISSUE TITLE
Developers/Git_Basics.rst: Add MacOS Git installation example

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3256]
_From @sudoankit on October 10, 2016 9:42_

Adding an example for installing `git` using `brew`.

_Copied from original issue: coala/documentation#169_

**Comment by Mariatta** [comment]
_From @ventris on October 10, 2016 10:35_

If this is not classified as newcomer issue please assign me to it.

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on October 10, 2016 10:41_

it is super easy and apparently being worked on by @sudoankit

**Comment by Adrianzatreanu** [comment]
unassigning due to high inactivity

**Comment by blooops** [comment]
Hey, I'm a newcomer. Can I be assigned?

**Comment by sagark123** [comment]
From what I read it seemed like we have to show how to install git on mac os... If my assumption is correct can I be assigned on this issue??
