### ISSUE TITLE
Developers/Writing_Good_Commits.rst: Should have a tag and and a short description separated by a colon

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3257]
_From @Udayan12167 on October 6, 2016 13:50_

"and" is repeated.

_Copied from original issue: coala/documentation#151_

**Comment by Mariatta** [comment]
_From @akashfoss on October 6, 2016 18:20_

Can anyone assign me for this issue ?

**Comment by Mariatta** [comment]
_From @anant3110 on October 6, 2016 18:28_

Assign me this issue

**Comment by Mariatta** [comment]
_From @Akki356 on October 24, 2016 16:38_

please assign me to this issue :)

**Comment by Mariatta** [comment]
_From @sils on October 24, 2016 17:19_

@anant3110 still workig on this?

**Comment by Mariatta** [comment]
_From @anant3110 on October 25, 2016 18:18_

Yes

Anant Sharna
2016129
IIIT Delhi (ECE)

**Comment by Mariatta** [comment]
_From @sils on November 8, 2016 22:24_

Unassigning as per own request

**Comment by Mariatta** [comment]
_From @OctavianGuzu on November 19, 2016 14:45_

Add me this issue !

**Comment by Mariatta** [comment]
_From @Makman2 on November 19, 2016 19:27_

@OctavianGuzu you got already one assigned :)

**Comment by shrutishrm512** [comment]
can I be assigned to this issue?
