### ISSUE TITLE
Developers/Writing_Good_Commits.rst: It should describe only one change and not more. (Reword)

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3258]
_From @Udayan12167 on October 6, 2016 13:49_

Drop Only.

_Copied from original issue: coala/documentation#150_

**Comment by Mariatta** [comment]
_From @YSahil184 on October 6, 2016 18:24_

assign me this

**Comment by Mariatta** [comment]
_From @AshwatKumar on October 6, 2016 18:24_

i will try this out, lets see

**Comment by Mariatta** [comment]
_From @harshit17chaudhary on October 6, 2016 18:24_

assign me this issue

**Comment by Mariatta** [comment]
_From @AshwatKumar on October 6, 2016 18:25_

assign me this

**Comment by Mariatta** [comment]
_From @ishaanbassi on October 6, 2016 18:36_

assign me this

**Comment by Mariatta** [comment]
_From @YSahil184 on October 6, 2016 18:38_

unassign me this

**Comment by yash-nisar** [comment]
Are you working on this @Pranav-Jain ?

**Comment by Adrianzatreanu** [comment]
unassigning due to high inactivity

**Comment by deewanrd** [comment]
@Mariatta assign me this issue.
