### ISSUE TITLE
Developers/Writing_Good_Commits.rst: In order to do that we are ... (Reword)

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3259]
_From @Udayan12167 on October 6, 2016 13:48_

_Copied from original issue: coala/documentation#149_

**Comment by Mariatta** [comment]
_From @apoorvkhattar on October 6, 2016 18:25_

Assign me this issue

**Comment by Mariatta** [comment]
_From @Pranav-Jain on October 6, 2016 18:25_

Kindly assign this issue to me

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on November 19, 2016 13:31_

unassigning due to inactivity

**Comment by Mariatta** [comment]
_From @ioanavoica on November 19, 2016 13:34_

i want to be assigned

**Comment by Nosferatul** [comment]
@sagark123 are you working on this?

**Comment by Nosferatul** [comment]
Unassigned due to innactivity.

**Comment by newbazz** [comment]
I would like to understand the issue properly and would like to work on it.

**Comment by swapagarwal** [comment]
@newbazz Related PR: https://github.com/coala/documentation/pull/212

**Comment by Nickatak** [comment]
Hello, is this still being worked on/open? :o

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by bansalnitish** [comment]
May I work on this if this is still open?  Also no one is assigned this issue currently !

**Comment by MacBox7** [comment]
Does this issue need any more changes? Can it be assigned to me ?

**Comment by pkcod** [comment]
Can you assign this to me

**Comment by Makman2** [comment]
@pkcod I just forgot to assign this issue, it's being worked on actively.
