### ISSUE TITLE
Developers/Writing_Good_Commits.rst: It is obvious that we need good code -> We need good code.

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3260]
_From @Udayan12167 on October 6, 2016 13:46_

_Copied from original issue: coala/documentation#148_

**Comment by Mariatta** [comment]
_From @achetan40 on October 6, 2016 18:24_

Please assign this issue to me

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on November 19, 2016 14:14_

unassigning due to inactivity

**Comment by Mariatta** [comment]
_From @OctavianGuzu on November 19, 2016 15:0_

Assign me to this issue, please!

**Comment by dracarys09** [comment]
@arvind-iyer you are currently not assigned to the issue... please get assigned to the issue first before writing code otherwise this can cause redundant work... 

use ```cobot assign <issue_url>``` on gitter channel to get this issue assigned to you... 
:smile:
