### ISSUE TITLE
Writing_Linter_Bears: Mention default severity map

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3261]
_From @Makman2 on October 3, 2016 0:54_

Nothing is written about the default map which already recognizes quite some words without the need to define a severity-map yourself.

_Copied from original issue: coala/documentation#141_

**Comment by Mariatta** [comment]
_From @Lars-H on October 28, 2016 15:7_

I want to fix this.

**Comment by sils** [comment]
@Lars-H any progress? Do you need help? Should we find someone else? Or just time? It's fine to take some time, we just need to be updated if you're still intending to help out here.

**Comment by Lars-H** [comment]
@sils : Sorry, but I am currently too busy and unfortunately have no time to fix this :/

**Comment by sils** [comment]
@Lars-H no issue, I'll free this up for someone else then :)

**Comment by sils** [comment]
as pointed out by @yash10p this has already been solved - thanks!
