### ISSUE TITLE
Should all the documentation be in docstrings?

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3264]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @Uran198 on March 26, 2016 20:49_

Branched from https://github.com/coala-analyzer/coala/issues/1967

Is it a good idea to have such a large docstrings? Mostly, names are self descriptive and this huge kind of stuff can be added to documentations or references. Then, for some bears we can use `**kwargs` and just pass parameters as they are. Possibly, documenting each of them.

@sils1297 comment:

> I personally really like that you can write all the documentation for the bear in the code and you don't have to think about where to write docs. And coala (i.e. we) takes care of organizing it properly for the user. 

_Copied from original issue: coala-analyzer/coala#1968_

_Copied from original issue: coala/documentation#47_

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @gitmate-bot on March 26, 2016 20:50_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @Makman2 on March 26, 2016 22:19_

I'm in for this, see my comment in #1967.

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @Makman2 on March 26, 2016 22:19_

> I think API-documentation belongs to the code, then you have directly the code beneath. Even if some names are self-descriptive, often types/parameter inputs must be specified, and Error behavior needs also specification. I want them too like we have now^^

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @Uran198 on March 27, 2016 6:57_

My concern is that it is not very convenient to have functions with more than 20 parameters and if you're even familiar with the program that bear uses to do it calculations you will still have to go either the code or huge signature to figure out if everything is the same and what not. They may even have these tools configured, but they will not be able to switch easily.
I also I like error behaviour specified and this can be done right in the description.

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:58_

_From @Makman2 on March 27, 2016 15:21_

But if you are not familiar with the code, it's way easier to read a docstring instead of code (especially if you are new to python).
Function with more than 10 parameters are quite rare in our codebase, they would only likely appear in bear signatures, and that's way easier to have in docstrings than in external files.

**Comment by jayvdb** [comment]
Assigning to some maintainers to get some ideas going, so we can work out what to do with this take issue.

**Comment by Mariatta** [comment]
Thanks @jayvdb. I think there should be docstring. It should contain at least a brief explanation of what it does, and explain the keyword arguments.

However it should not replace the official documentation. More things like code example and how to use it can be added in the documentation, not in docstrings.

**Comment by Makman2** [comment]
Imo everything related to the documented function/whatever directly should be placed into docstrings for the sake of maintainability and quick-look-up-ability. Also doctesting can be performed then.

Larger tutorials, set-ups and feature documentation should be in separated documents.
So regarding this:
> how to use it can be added in the documentation

I would only agree on this when it's about features and incorporated into a "bigger picture" which doesn't fit into a docstring itself because the topic involves more.

**Comment by Makman2** [comment]
I believe we do it already quite good, if I don't miss something I would vote for closing this issue :+1:

**Comment by Mariatta** [comment]
Thanks @Makman2. If we are already doing it, then let's keep it up :)
