### ISSUE TITLE
Suggest usage of `git push --force-with-lease` instead of `git push -f` in rebasing tutorials

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3266]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @underyx on June 3, 2016 19:35_

area/documentation

_Copied from original issue: coala-analyzer/coala#2250_

_Copied from original issue: coala/documentation#38_

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @gitmate-bot on June 3, 2016 19:35_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @sils1297 on June 3, 2016 22:22_

I'm not fully sure about that because you have to explain more to new people.

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @Makman2 on June 4, 2016 0:51_

I'm against this as I agree with @sils1297 , the command looks like it needs more explanation because of the "remote-tip-need-to-be-equal" protection, with our review system there is in principle no possibility to merge such malicious branches (master is protected by GitHub, notification in PR that branch is out-of-date, rultor refuses merge). Our workflow is also more like "that is definitely your branch" and no-one would touch it (unless there are special exceptions if someone wants to take over directly etc, though in fact there's no need for such arrangements).

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @underyx on June 4, 2016 1:1_

Can't really refute all that, but just to reply to this one point:

> Our workflow is also more like "that is definitely your branch"

I've deleted my own commit before with a force push when I forgot I had already changed something with the github.com editor :D

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @Makman2 on June 4, 2016 1:10_

don't do so :3

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @sils1297 on June 17, 2016 8:46_

so what do we do? I'm currently leaning towards the simpler solution. Might also be because I'm lazy and I'm in issue closing mood though :P

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @Makman2 on June 17, 2016 16:26_

maybe we can mention inside a note "if you want more protective behaviour, you can also use `--force-with-lease`" or so^^

**Comment by Mariatta** [comment]
_From @Adrianzatreanu on August 19, 2016 11:52_

_From @sils1297 on June 17, 2016 17:53_

I like adding a note!

**Comment by jayvdb** [comment]
This is only relevant for people who can write to someone elses branch, which isnt newcomers, and we use a branch naming convention that should prevent that anyway.

**Comment by underyx** [comment]
Well,  it's not gonna be an issue for us indeed, but people probably take
this knowledge elsewhere, where it will matter.

Anyway, I'm not firmly against closing this, so whatever :D
