### ISSUE TITLE
Change `tag.gz` to `tar.gz` in `deploy.pypi.sh`

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3268]
At https://github.com/coala/coala/blob/master/.misc/deploy.pypi.sh#L17

`ValueError: Cannot find file (or expand pattern): 'dist/*.tag.gz'` was seen in the rultor log, can be considered a confirmation? 

**Needs confirmation**
CC @sils @AbdealiJK as you're the contributors of the file

difficulty/newcomer type/bug

**Comment by AbdealiJK** [comment]
Yep, that's a bug.
It would be better to loop over every file and upload each using a bash
Loop rather than hardcode these extensions

**Comment by marian-ald** [comment]
you mean writing a script?

**Comment by Mixih** [comment]
no, modifying the existing script in .misc/deploy.pypi.sh

**Comment by marian-ald** [comment]
I will try  to work on this. Could you assign me?

**Comment by Mixih** [comment]
alright. Here you go !
