### ISSUE TITLE
checking the return type of the bear

### ISSUE THREAD

**Issue by arush0311** [coala/coala#3275]
As of now the return type of the bear is not checked right away and a bear can return anything. The return type is checked in result action, IMO it should be checked right in Bear class

**Comment by sils** [comment]
isn't this happening in BearRunning somewhere? @Makman2 I guess for next gen we'll want to do most of the error checking in the Bear class directly if possible. If people override our private methods they suck anyway

**Comment by arush0311** [comment]
@sils It is being checked in BearRunning. Sorry I didn't check this module to see

**Comment by Makman2** [comment]
nextgen allows the bear to pass whatever it wants. The result-callback is responsible for filtering the results it needs and/or emitting warning messages when something is not right. That makes stuff more flexible + tests easier.

**Comment by arush0311** [comment]
@Makman2^ why would we want bears to pass anything other than results?

**Comment by Makman2** [comment]
this makes sense for dependency bears, then you don't need to build up a complete result just to say the next bear for example "L3-L5 is code", instead pass a `SourceRange`.

**Comment by arush0311** [comment]
Ah. ok then
