### ISSUE TITLE
Newcomers_Guide: $ git checkout -b <branchname> doesn't appear as inline code

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3276]
The file can be found [here](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst).

difficulty/newcomer

**Comment by maitreyaverma** [comment]
Hello! Can you assign me this issue?

**Comment by yash-nisar** [comment]
Our maintainers will assign it to you soon. :)

**Comment by ashwani99** [comment]
Hi. Can I work on this?

**Comment by yash-nisar** [comment]
Since @maitreyaverma  asked for it first, she will be assigned.

**Comment by seVen102** [comment]
Can I get assigned on this one please?

**Comment by yash-nisar** [comment]
@Adrianzatreanu Since @maitreyaverma asked for it first, I think she should be assigned.

**Comment by Nosferatul** [comment]
@maykillmore are you working on this?

**Comment by Nosferatul** [comment]
Unassigned due to inactivity.

**Comment by mubaris** [comment]
Can I take this?

**Comment by yash-nisar** [comment]
Sure, assign yourself on our gitter channel with `cobot assign full-issue-url`

**Comment by yash-nisar** [comment]
@Nosferatul Should we close https://github.com/coala/coala/pull/3738 ?

**Comment by JohnMoutafis** [comment]
Can I get this one?

**Comment by yash-nisar** [comment]
Sure, use our bot -> `corobo assign https://github.com/coala/coala/issues/3276` on gitter (https://coala.io/chat)

**Comment by JohnMoutafis** [comment]
Got response:

> You are not eligible to be assigned to this issue.
>  A newcomer cannot be assigned to an issue with a difficulty level higher then newcomer or low difficulty.
