### ISSUE TITLE
Be more verbose about when to use `Fixes` and `Closes`

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3277]
I have seen many newcomers getting confused between `Closes` and `Fixes`. I think we need to perhaps be more clear about using these keywords.

difficulty/newcomer

**Comment by dracarys09** [comment]
@yash-nisar as suggested by others I think we should use ```Closes``` when the work is related to a new feature and use ```Fixes``` when we work around bugs.

**Comment by yash-nisar** [comment]
We as developers know the difference. However, if we try to be more concise about using those keywords, newcomers won't make a mistake while differenciating the two. :)

**Comment by jayvdb** [comment]
More related discussion in an issue created a few hours later :/
https://github.com/coala/coala/issues/3280

**Comment by yash-nisar** [comment]
So, should we close this ? @jayvdb

**Comment by AnaDenisa** [comment]
Hello! I want to be assigned to this project :)

**Comment by Mixih** [comment]
xref #3280. When writing a patch for this issues, also include a closes line for #3280

**Comment by yash-nisar** [comment]
Closing since https://github.com/coala/coala/issues/3280 has the commit merged.
