### ISSUE TITLE
Update links in README.md

### ISSUE THREAD

**Issue by madan96** [coala/coala#3279]
Change all the links containing `readthedocs.io` to `docs.coala.io`.
For links related to Developers Section, use `api.coala.io`

This needs to be done because docs were moved to the new link.

**Comment by ashwani99** [comment]
Hello. I want do this. Can you assign me please?

**Comment by ishanupadhyay** [comment]
Hey guys ,I want to solve this new comer issue . Please assign me.

**Comment by jayvdb** [comment]
I believe this was already done in https://github.com/coala/coala/commit/cdd6386e8a467063bf787022edc167
Find other newcomer bugs using coala.io/new
