### ISSUE TITLE
Invalid error resolution when running coala on dev

### ISSUE THREAD

**Issue by RohanVB** [coala/coala#3281]
Steps to reproduce:
1)Create new virtual environment
2)New clone of coala
3)sudo pip3 install coala-bears
4)Run coala.

Version of coala used:
`$ coala --version
0.10.0.dev99999999999999`

**Note**: The error below is not resolved by creating a separate virtual environment for coala or by running `pip install "libclang-py3==0.2", the same error shows up when both of these are done.

_Here is the error and info:_

```
$ coala
[ERROR][19:33:56] There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or running `pip install "libclang-py3==0.2"`. Be aware that the latter solution might break other python packages that depend on the currently installed version.
[INFO][19:33:56] Exception was:
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/coala_main.py", line 76, in run_coala
    arg_list=arg_list)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/settings/ConfigurationGathering.py", line 365, in gather_configuration
    log_printer)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/settings/SectionFilling.py", line 32, in fill_settings
    bear_dirs = section.bear_dirs()

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/settings/Section.py", line 74, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coala-0.10.0.dev99999999999999-py3.5.egg/coalib/collecting/Collectors.py", line 293, in collect_registered_bears_dirs
    registered_package = ep.load()

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2267, in load
    self.require(*args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2284, in require
    items = working_set.resolve(reqs, env, installer)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 857, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (libclang-py3 3.4.0 (/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libclang_py3-3.4.0-py3.5.egg), Requirement.parse('libclang-py3==0.2'))
```

**Comment by madan96** [comment]
I am facing the same problem.

**Comment by Makman2** [comment]
So you have installed coala from the repo? From which commit?
Did you try to do `sudo pip3 install libclang-py3==0.2`?

**Comment by madan96** [comment]
`sudo pip3 install libclang-py3==0.2` gives the following error in my case.

`Downloading/unpacking libclang-py3==0.2
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement libclang-py3==0.2
Cleaning up...
No distributions at all found for libclang-py3==0.2
`

**Comment by Makman2** [comment]
indeed, the package seems to have been removed.
I would try to install latest coala development version and coala-bears version (removing the old installations before).

**Comment by RohanVB** [comment]
@Makman2 a new virtual env was created, coala dev version and coala-bears version were installed freshly; having removed the old versions.

**Comment by jayvdb** [comment]
fwiw, it is likely https://github.com/coala/coala/commit/f25d48daf5a1f86 that has caused this.
The packages do exist ; see https://pypi.python.org/simple/libclang-py3/ , but the old 0.2 is no longer listed on https://pypi.python.org/pypi/libclang-py3/

**Comment by Makman2** [comment]
Though coala shouldn't require 0.2 explicitly as it does not appear anywhere as a dependency. I have libclang 3.4 installed, and coala works for me currently^^ 
Just tried with a fresh venv, it still picks my globally installed coala package from before. So I uninstalled my global packages, and reinstalled, no errors on coala run. So I can't reproduce :/

**Comment by jayvdb** [comment]
I suspect that there is a globally installed coala-0.9 which depends on ~=0.2, conflicting with the dev version which depends on ~=3.4.
Delete the globally installed coala & bears.

**Comment by Makman2** [comment]
(just as a note: it's possible to uninstall packages with pip *multiple times*, so uninstall until it says that there's nothing more left)

**Comment by jayvdb** [comment]
((further note: do not dp pip uninstall in your coala clone, it will delete your local directory; arnt they smart))

**Comment by RohanVB** [comment]
I think that did it. @madan96 The following steps helped:
```
GLOBALLY:

$ pip3 uninstall coala-bears

Cannot uninstall requirement coala-bears, not installed

$ pip3 uninstall coala
Cannot uninstall requirement coala, not installed

IN VIRTUAL ENV:

pip3 install coala-bears —pre

$ coala --version

0.10.0.dev20161216132435


(coala runs fine at this stage)

sudo python3 setup.py install
$ coala --version

0.10.0.dev99999999999999

Ran coala, it works now.


```

Note: The new installations were done inside the coala clone, within the virtual environment.

**Comment by Makman2** [comment]
cool glad it worked out :)
