### ISSUE TITLE
create man page for coala

### ISSUE THREAD

**Issue by tibi77** [coala/coala#3292]

**Comment by tibi77** [comment]
Hello 
I would like to resolve this bug!

Tibi

**Comment by Mixih** [comment]
@tibi77 can you add a bit of a description to this report so other can know some details about it?

**Comment by tibi77** [comment]
Coala had no man page that works so i updated the script that creates the man page and i have also created a script that adds the man page form coala to the man data base and so somebody can now run "man coala" from the terminal wherever is the shell located.

**Comment by dracarys09** [comment]
@tibi77  still working on this ?

**Comment by sims1253** [comment]
unassigning due to inactivity. If you want to pick this up again, ping us in the chat.

**Comment by GeorgeMD** [comment]
I'd like to continue this. I'm looking at what tibi started right now.

**Comment by meetmangukiya** [comment]
@GeorgeMD please see if you can use his work, it is generally bad to just throw away someone's work :)

**Comment by GeorgeMD** [comment]
@meetmangukiya That's what I'm doing.
