### ISSUE TITLE
Removal of command line argument --format_str broken editor plugins

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3303]
https://github.com/coala/coala/pull/3096 removed `--format_str`, adding `--format` as a replacement.
However at least coala-atom and coala-vim were using `--format_str`, and they now fail if coala 0.9.* is installed.
Recommend re-adding `--format_str`.

**Comment by DanRadulescu962** [comment]
Hi,
Can I take this issue?

**Comment by adtac** [comment]
@DanRadulescu962 sure, assigned you :+1:

IMO we should probably add a deprecation warning if the user uses `--format_str` - so that we can safely remove it again for the next release. Or do we want both settings? (redundant, I'm afraid)

**Comment by sils** [comment]
Hey @DanRadulescu962 I can't see any WIP stuff from you, this is super important right now, I hope you don't mind if we're taking this over.

**Comment by Mixih** [comment]
We should depreciate it IMO, so we need to put in a depreciation warning

**Comment by Mixih** [comment]
not sure whyt he pull isn't linking, but this is the xref https://github.com/coala/coala/pull/3381
