### ISSUE TITLE
List of commits to backport to 0.9

### ISSUE THREAD

**Issue by sils** [coala/coala#3313]
- [x] 7f4edb8 : https://github.com/coala/coala/pull/3314
- [x] 8db4fb7: https://github.com/coala/coala/pull/3384
- [x] 06a772f3b4676e1e4e59d3b1eaa8f87af7fd45ba : https://github.com/coala/coala/pull/3216
- removing setuptools from requirements
  - [x] 49f441bf24
  - [x] bacb0ff3
- [x] https://github.com/coala/coala/pull/3381 (https://github.com/coala/coala/issues/3303 68afd596)
- [x] 39b0a170: needed because pyprint updated deps which breaks stuff

**Comment by Makman2** [comment]
So can this be closed @sils ?

**Comment by jayvdb** [comment]
I've added the setuptools problem, as that is causing us a lot of problems with builds, and our requirement will be causing other packages to have conflicts.

Also the `format_str` problem, as I do not believe we should be breaking editors, and those editor plugins dont have good dependency version management capabilities, so it cant easily be fixed on their side.

**Comment by jayvdb** [comment]
btw, the libclang-py3~=3.4 requirements change is giving people problems, which havent been diagnosed , so IMO that shouldnt be done in 0.9

**Comment by Mixih** [comment]
Oops, we also need to backport the alphabetization commit

**Comment by Mixih** [comment]
7f4edb8 has a dependency hell error

**Comment by Mixih** [comment]
we got an entire travis file pulled in... but it should be ok

**Comment by Mixih** [comment]
xref https://github.com/coala/coala/pull/3382

**Comment by Mixih** [comment]
backport complete
