### ISSUE TITLE
@linter decorator causes ERROR on Windows

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#3323]
@sils See https://github.com/coala/coala-bears/issues/1172 and https://github.com/coala/coala/issues/3322 respectively.

**Comment by sils** [comment]
CC @Makman2

**Comment by Makman2** [comment]
phew... will investigate soon^^

**Comment by userzimmermann** [comment]
@Makman2 Any progress? Just got the same problem with `MarkdownBear`. Feeling lost on Windows... ;)

**Comment by userzimmermann** [comment]
Found some useful info here:

http://stackoverflow.com/questions/26025878/what-is-being-pickled-when-i-call-multiprocessing-process

**Comment by userzimmermann** [comment]
It's all about the pickling when using `multiprocessing`, which doesn't happen on Linux.

Doesn't seem like we can get those `@linter` classes pickled... :(

**Comment by Mixih** [comment]
I think this is done.... Reopen if it isn't
