### ISSUE TITLE
Wrong doc string syntax in coalib.bearlib.aspects.Root

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#3329]
The doc string of the `Root` aspectclass has a formatting issue at https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/__init__.py#L61

You can see the wrongly rendered result at https://api.coala.io/en/latest/coalib.bearlib.aspects.html#module-coalib.bearlib.aspects

**Comment by gRSsomani** [comment]
Hello, I want to work on this.

**Comment by Siddhartha1234** [comment]
Sir,can you assign this bug to me?

**Comment by Makman2** [comment]
@Siddhartha1234 as @gRSsomani was first I would assign him^^
@gRSsomani you haven't accepted your invitation to our org yet, please do so to get assigned :+1:

**Comment by gRSsomani** [comment]
Thank you!! I have accepted the invitation. Please assign.
