### ISSUE TITLE
Sphinx giving warnings on docs

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#3334]
/home/dev/projects/coala-review/3327-review/coala/docs/Developers/coala_settings.rst:14: WARNING: Inline strong start-string without end-string.

is the current warning, which is on a generated file, as coala_settings has only 7 lines

**Comment by Mixih** [comment]
Here is the docstring that the file is gerenerated from
@coalib/parsing/DefaultArgParser.py L35
````
coala provides a common command-line interface for linting and fixing all your
code, regardless of the programming languages you use.

To find out what kind of analysis coala offers for the languages you use, visit
<https://github.com/coala/bear-docs/blob/master/README.rst#supported-languages>
or run:

    $ coala --show-bears --filter-by-language C Python

To perform code analysis, simply specify the analysis routines (bears) and the
files you want it to run on, for example:

    $ coala --bears SpaceConsistencyBear --files **.py

coala can also automatically fix your code:

    $ coala --bears SpaceConsistencyBear --files **.py --apply-patches

To run coala without user interaction, run the `coala --non-interactive`,
`coala --json` and `coala --format` commands.
````
IMO, it look like the ** in `$ coala --bears SpaceConsistencyBear --files **.py --apply-patches` or `$ coala --bears SpaceConsistencyBear --files **.py` are being interpreted  as the start of a "strong" element

**Comment by Siddhartha1234** [comment]
Surrounding the function with double backticks should do the trick , can  i be assigned this?

**Comment by Mixih** [comment]
Makman2 advises codeblocks instead which I agree with. Just add a double colon on the sentence before each of the statements that might gives issues(there are 2).
