### ISSUE TITLE
Coala banner too big on pypi page.

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3340]
It's so large that it creates a scroll bar(shouldn't pypi be resizing this anyways)?
(confirmed on safari and firefox)

![issue](https://cloud.githubusercontent.com/assets/5818750/21316665/76027146-c5c7-11e6-8f0b-6cf767ea15c3.PNG)

Also the ascii cinema is messed up:

![issue2](https://cloud.githubusercontent.com/assets/5818750/21317030/07272148-c5c9-11e6-94ac-499e54973246.PNG)

Monitor: 1920x1080p

**Comment by Mixih** [comment]
As you've submitted a patch, you now have ownership of this ;)

**Comment by RohanVB** [comment]
@Mixih please reopen this issue or start a new one since the coala banner size has been resolved, but the ascii cinema part has not.

**Comment by jayvdb** [comment]
I created https://github.com/coala/coala/issues/3385
