### ISSUE TITLE
affected_code place holder of --format option should produce more verbose results

### ISSUE THREAD

**Issue by Abhisek-** [coala/coala#3355]
When run coala with `--format "affected_code: {affected_code}", it produces results with unnecessary information.

### Steps to reproduce
Create a file with with some affected lines in it. In this case we will use `something.py` as our file name and trailing white spaces to make our code affected.
Now run `coala -I --bears SpaceConsistencyBear --files something.py -S use_spaces=True --format "affected_code: {affected_code}"`

### Actual Results
The following line is printed

    affected_code: (<SourceRange object(start=<SourcePosition object(file='/home/abhisek/Github/coala/something.py', line=4, column=None) at 0x7fef45c76780>, end=<SourcePosition object(file='/home/abhisek/Github/coala/something.py', line=4, column=None) at 0x7fef45c76c88>) at 0x7fef45c76d30>,)

### Expected Results
Maybe something like the following

    affected_code: <<file_name>>:
                               FROM: line_number: column_number
                               TO:   line_number: column_number
In this case

    affected_code: /home/abhisek/Github/coala/something.py:
                               FROM: 4: None
                               TO:   4: None

**Comment by Makman2** [comment]
I would use a format that does not contain `\n`s (simplifies often parsing with regexes), but generally I like the idea :+1:

**Comment by Abhisek-** [comment]
But I have not used any `\n` in my format. The source code contains `\n`s.

**Comment by Makman2** [comment]
don't understand you :O
I mean your expected format should look like
```
affected_code: /home/abhisek/Github/coala/something.py: FROM 4: None TO: 4: None
```
instead of
```
affected_code: /home/abhisek/Github/coala/something.py:
                           FROM: 4: None
                           TO:   4: None
```

**Comment by Abhisek-** [comment]
Oh I misunderstood you. I thought you are talking about the format `--format "affected: {affected}"`, hence I thought I've not used any `\n`.

The expected result *may* look something like the following.

    affected_code: /home/abhisek/Github/coala/something.py:
                   From: 4: None
                   To:   4: None

but It doesn't necessarily have to be that way. The idea is to make the information more verbose. I thought it will be useful for the user if we print the line and column information in a separate line. If we print on a separate line it is easy to see, where exactly the problem is and it is more clean. And yes, as you said it will add some extra work for us, but at the end it'll be more useful.

**Comment by Makman2** [comment]
`--format` is primarily for printing results in a simple parsable format. For humans you can use our default cli without `--format` :)

**Comment by Abhisek-** [comment]
Oh.. that is also right :). I over thought about that. thanks

**Comment by vijeth-aradhya** [comment]
I'd like to work on this isuue. Would you mind assigning it to me?

**Comment by Makman2** [comment]
@vijeth-aradhya before you start, how do you think the format for `affected_code` should look like?

**Comment by vijeth-aradhya** [comment]
@Makman2 I'm assuming `{affected_code}` will be listed as one of the placeholders, as it is not a part of it yet.
And, about the format for it -
`affected_code: /home/abhisek/Github/coala/something.py: FROM 4: None TO: 4: None` 
I think this would be a good enough representation :+1:

**Comment by Makman2** [comment]
okay cool, some ideas:
```
FROM 4: None TO: 4:NONE
```
I would remove the spaces after the colon:
```
FROM 4:None TO 4:NONE
```
(and also the colon after `TO` :D)

Also when we have `NONE` for columns, this means the complete line is meant, not sure if you want to compress the format then to
```
FROM 4 TO 4
```

**Comment by vijeth-aradhya** [comment]
@Makman2 I think the way to go about this is _not_ to give all the attributes of the Result Class, since some of the variables there are **NOT** in the list of placeholders like {diffs}, {confidence} ( they still work if I give them in `--format` )
If you think all of them are required, and we have to just add `{affected_code}`, then we have to remove the existing tuple representation of `affected_code` somehow, and add a string like the one you suggested above

**Comment by Makman2** [comment]
sorry can't follow you what you mean exactly, especially with

>  I think the way to go about this is not to give all the attributes of the Result Class

:/
