### ISSUE TITLE
After adding an ignore comment, the option should not be available any more.

### ISSUE THREAD

**Issue by Udayan12167** [coala/coala#3375]

**Comment by Udayan12167** [comment]
See https://github.com/coala/coala/issues/3366

**Comment by adtac** [comment]
@mrtes From gitter:

> how about this: have a successful_actions set similar to failed_actions that will be appended the name to every time an action is successfully. Then allow IgnoreResultAction.is_applicable to take another parameter: successful_actions. If successful_name is in the list, make is_applicable return False.

>the difficulty is just a label - anyone is welcome to tackle any issue (provided you can)
you can solve the coala/coala#3377 with the other method too
you might need to tweak things a little bit
the reason I prefer the method I mentioned: this way we make our changes mostly on the *Action.py files instead of the core itself
