### ISSUE TITLE
remove format_str for real this time

### ISSUE THREAD

**Issue by Mixih** [coala/coala#3379]
This legacy setting needs to go badly..... give people a few releases to clean up their code before removing it.

**Comment by sils** [comment]
it's already deprecated, needs removal, right?

**Comment by Mixih** [comment]
yeah, by the next version or two. We restored it to give people a grace period

**Comment by sils** [comment]
@Mixih let's remove it now in the development version since we have the 0.9 release with the deprecation, remove it for 0.10?

**Comment by Mixih** [comment]
Sure, at best 0.10 will only come out in a month so that is enough grace period

**Comment by Mixih** [comment]
postponed
