### ISSUE TITLE
PyPI ascinema messed up

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3385]
Split from https://github.com/coala/coala/issues/3340 :

Also the ascii cinema is messed up:

![issue2](https://cloud.githubusercontent.com/assets/5818750/21317030/07272148-c5c9-11e6-94ac-499e54973246.PNG)

Monitor: 1920x1080p

**Comment by jiteshpabla** [comment]
It opens up fine now
![screenshot from 2017-01-08 04-04-33](https://cloud.githubusercontent.com/assets/12662272/21745734/d84f9406-d557-11e6-9989-d4f37d0410e8.png)
Monitor: 1920x1080p

**Comment by HitRam** [comment]
I would like to work on this. Can I be assigned?

**Comment by jayvdb** [comment]
If we can not change the width of the images hosted by https://asciinema.org , we should put a reduced width image into https://github.com/coala/artwork and use that.

**Comment by HitRam** [comment]
Ok, so how do I put that image into https://github.com/coala/artwork?
Do I need to fork that repo as well and add image into that?

**Comment by jayvdb** [comment]
Yes
