### ISSUE TITLE
Document default_coafile

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3388]
`default_coafile` can be used to solve problems like https://github.com/coala/coala/issues/3131 .  How and when it is used & modified should be in the dev docs.

```
$ git grep default_coafile
...
```

**Comment by jayvdb** [comment]
@Siddhartha1234 , are you still working on this?

**Comment by Siddhartha1234** [comment]
@jayvdb I was unavailable for few weeks , ill contribute regularly from today after a few hours .I'll work on this and try to finish it immediately.If that's not okay for you ,you may re assign this to someone else.

**Comment by jayvdb** [comment]
ok, I am looking forward to your resolution of this issue.  Come onto https://coala.io/chat if you need help.

**Comment by newbazz** [comment]
I would like to work on this issue

**Comment by Makman2** [comment]
@Siddhartha1234 still working on it?

**Comment by newbazz** [comment]
Can I start working on this?

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by Makman2** [comment]
The relevant place to document this more lies at our [documentation](https://github.com/coala/documentation) repo.

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/documentation/issues/480.
