### ISSUE TITLE
Change default_coafile naming convention.

### ISSUE THREAD

**Issue by nemaniarjun** [coala/coala#3389]
Should we change the name of `default_coafile` in `coalib` to `system_coafile`?
It will avoid confusion due to the following lines in `Constants.py`
```
system_coafile = os.path.join(coalib_root, 'default_coafile')

user_coafile = os.path.join(os.path.expanduser('~'), '.coarc')

default_coafile = '.coafile'
```

**Comment by Makman2** [comment]
voting for this :+1:

I'm also thinking about `base_coafile` or something into this direction, but `system_coafile` is definitely an improvement we should take :+1:

**Comment by nemaniarjun** [comment]
`base_coafile` sounds great.

Also should we change a bit of naming convention in `ConfigurationGathering.py`?
The following part could be clearer:

```
    else:
        default_sections = load_config_file(Constants.system_coafile,
                                            log_printer)
        user_sections = load_config_file(
            Constants.user_coafile,
            log_printer,
            silent=True)

        default_config = str(
            default_sections['default'].get('config', '.coafile'))
        user_config = str(user_sections['default'].get(
            'config', default_config))
        config = os.path.abspath(
            str(cli_sections['default'].get('config', user_config)))
```

I say we change `default_sections` to `base_sections` or similar.

**Comment by Makman2** [comment]
yeah default sections is definitely bad^^

**Comment by nemaniarjun** [comment]
There are just so many `defaults` :p

**Comment by LeafyLi** [comment]
Can I work on this?

**Comment by nemaniarjun** [comment]
Sure :) send a message on the gitter channel so one of the maintainers can assign you.

**Comment by Makman2** [comment]
> Also should we change a bit of naming convention in ConfigurationGathering.py?
> The following part could be clearer:
>   ```
>    else:
>        default_sections = load_config_file(Constants.system_coafile,
>                                            log_printer)
>        user_sections = load_config_file(
>            Constants.user_coafile,
>            log_printer,
>            silent=True)
>
>        default_config = str(
>            default_sections['default'].get('config', '.coafile'))
>        user_config = str(user_sections['default'].get(
>            'config', default_config))
>        config = os.path.abspath(
>            str(cli_sections['default'].get('config', user_config)))
>   ```
> I say we change default_sections to base_sections or similar.

Migrated into separate issue: https://github.com/coala/coala/issues/3395

**Comment by Techievena** [comment]
@lohani2280 Are you still working on the issue?

**Comment by jack17529** [comment]
@nemaniarjun is someone working on this issue if not assign me.

**Comment by Makman2** [comment]
@jack17529 feel free to take over ;) don't let the PR be wasted ;)

**Comment by acashmkj** [comment]
@nemaniarjun @Makman2 Can this issue be reassigned to me ?

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by newbazz** [comment]
I would like to work on this issue

**Comment by pradeepgangwar** [comment]
@acashmkj I would like to work on this if you are not working? Seems like PR has gone stale.

**Comment by Makman2** [comment]
Reassigning due to inactivity.
