### ISSUE TITLE
Change variable name `default_sections` to `base_sections`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3395]
From @nemaniarjun :
> Also should we change a bit of naming convention in ConfigurationGathering.py?
> The following part could be clearer:
>   ```
>    else:
>        default_sections = load_config_file(Constants.system_coafile,
>                                            log_printer)
>        user_sections = load_config_file(
>            Constants.user_coafile,
>            log_printer,
>            silent=True)
>
>        default_config = str(
>            default_sections['default'].get('config', '.coafile'))
>        user_config = str(user_sections['default'].get(
>            'config', default_config))
>        config = os.path.abspath(
>            str(cli_sections['default'].get('config', user_config)))
>   ```
> I say we change default_sections to base_sections or similar.

**Comment by vijeth-aradhya** [comment]
I'd like to work on this issue, can you assign me?

**Comment by nemaniarjun** [comment]
Since you have already worked on a diff/Newcomer issue, you should move on to low issues. 
Newcomer issues are to give you a understanding of basic git and coala codestle :)

**Comment by vijeth-aradhya** [comment]
@nemaniarjun Alright then, I can try and review changes by newcomers as well :smile:

**Comment by ankit01ojha** [comment]
I would like to work on this can you assign me and tell me how should I start.

**Comment by Makman2** [comment]
You need to rename `default_sections` to `base_sections` in `ConfigurationGathering.py`, see above :)
