### ISSUE TITLE
ConsoleInteraction.py: Improve use of range builtin function for SourceRange

### ISSUE THREAD

**Issue by Abhisek-** [coala/coala#3398]
`range` is a builtin function. We should not use `range` for any other purpose other than iterating over the iterator(which is offered by python).

**Location:**

* `coalib/results/Diff.py:Diff.range`
* `coalib/output/ConsoleInteraction.py:print_results_formatted`
* `coalib/results/Result.py:Result.overlaps`
* `coalib/results/Result.py:Result:from_values` (suggested by @vijeth-aradhya )
* `coalib/processes/Processing.py:check_result_ignore`

**Comment by vijeth-aradhya** [comment]
Also, over [here](https://github.com/coala/coala/blob/master/coalib/results/Result.py#L151-L151)

**Comment by Abhisek-** [comment]
And over [here](https://github.com/coala/coala/blob/master/coalib/results/Result.py#L241) too. Ok I'll update my comment to get all the things in one place.

**Comment by kirankonduru** [comment]
I am new to coala. I would like to work on this issue.

**Comment by Makman2** [comment]
Though field names have the same python names like `range`, something like `x.range` does not override it as it always needs the context of the object, so this still makes sense and I would also not confuse that personally^^

Before you start, we need new (and especially meaningful!) names, so please suggest some here before you submit a PR^^

**Comment by Makman2** [comment]
@kirankonduru I've sent you an invitation, please also check out our gitter channel ;)

**Comment by sils** [comment]
@kirankonduru assigned you, let us know if you need help or if you'd like to be unassigned.

**Comment by kirankonduru** [comment]
@Makman2  we can use domain instead of range. Is it fine?

**Comment by sils** [comment]
I'd go for `source_range`, don't see how `domain` applies...

**Comment by kirankonduru** [comment]
So I'll use source_range then..

**Comment by Makman2** [comment]
phew domain... that's more for mathematics^^ I would consider the domain of a `SourceRange` the file it operates on^^

**Comment by Makman2** [comment]
@sils but `SourceRange.source_range`? okay, though quite oververbose :)

**Comment by schafle** [comment]
If this issue is still unresolved I would like to work on it. If so can someone please assign it to me.

**Comment by jayvdb** [comment]
If this is about renaming the property `range`, then no, I agree with Makman2 that this isnt a problem

However we definitely should not replace `range` (or any other builtin) , so these definitely need to be fixed.
```console
$ git grep ' range ='
coalib/bearlib/abstractions/Linter.py:                range = SourceRange.from_values(filename,
coalib/results/Diff.py:        >>> range = Diff([]).range("file")
coalib/results/Result.py:        range = SourceRange.from_values(file,
```
@macbox7, this could be a feature for your pyflakes plugins , or even for pyflakes (but we should check with @myint first).

**Comment by MacBox7** [comment]
Oh. Yes. The __builtins__ plugin. Haven't started yet working on it though.
