### ISSUE TITLE
Do integration testing with something like subprocess

### ISSUE THREAD

**Issue by Uran198** [coala/coala#3403]
I find current way of integration testing a bit hacky. In it we are relying a lot on the underlying structures (which makes it more of a unit testing of those structures than testing of the whole system from the user perspective), mocking stdout and stdin (which is prone to errors and complexities (for example with [logging](https://github.com/coala/coala/blob/a4d89ad3dd02d1c0f6fc5f5c00da5c231f2fd4d6/coalib/misc/Constants.py#L137))).

I propose to do it more from the user perspective by using [subprocess](https://docs.python.org/3/library/subprocess.html) python module. This should also eliminate the need to mock std* and entry points, simplify dealing with logging and hopefully make tests cleaner.

**Comment by Makman2** [comment]
Sounds cool, do you have something more precise? Like an example or so? :)

**Comment by Uran198** [comment]
https://github.com/coala/coala/pull/3422 - Here is an example, although I am not sure it will work as is, or it is the best possible way to do it.

**Comment by Makman2** [comment]
@Uran198 we have nice macros inside `coalib.Shell`, they take over setting up pipes etc.

```
from coalib.misc.Shell import run_shell_command, run_interactive_shell_command

# Though the name is run_*shell*_command, it's not executed inside a shell unless
# you provide `shell=True` (we should maybe change the name...)
stdout, stderr = run_shell_command(['coala', '-c', 'blub'])

# or if you need interactive behaviour
with run_interactive_shell_command(["echo", "TEXT"]) as p:
     stdout = p.stdout
     stdout_text = stdout.read()

# you can also write to stdin to emulate user input
with run_interactive_shell_command(["cat"]) as p:
    # Hope it works like this
    print('This is the content of my file', file=p.stdin)
```

You also don't need to escape file paths btw if you don't use `shell=True` :)

**Comment by Uran198** [comment]
@Makman2 Cool, thanks for pointing that out!

I think the question first is whether this should be implemented, or if there is no need to do it?

**Comment by Makman2** [comment]
On the one hand it's the better approach as it emulates from real user perspective, but on the other hand `execute_coala` is called quite on top of the stack, so we don't win that much doing this.

It's up to you if you want to invest time into that :)

**Comment by jayvdb** [comment]
No benefit in keeping this area.
We can add tests when they are called for.
