### ISSUE TITLE
Add a warning about the evil green button on the pull request template

### ISSUE THREAD

**Issue by adtac** [coala/coala#3406]

**Comment by Mixih** [comment]
He means the update branch button for those unenlightened :) .

**Comment by bharg** [comment]
Hi, I'd like to work on this bug. I'm just starting out and would like some pointers on how to proceed.

**Comment by adtac** [comment]
@bharg take a look at coala.io/newcomer if you haven't already. And if you get stuck anywhere, as mentioned above, come over to our gitter channel and ask :)

**Comment by bharg** [comment]
In progress. Sorry it took so long to get started.
