### ISSUE TITLE
Writing_Linter_Bear.rst -> add link to Linter module

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#3408]
In the section "Where to find more" we should add a link to 
http://api.coala.io/en/latest/coalib.bearlib.abstractions.html#module-coalib.bearlib.abstractions.Linter

**Comment by Makman2** [comment]
Right just at the bottom of the page^^

**Comment by rishikksh20** [comment]
Hello friends! I am a newcomer let me work on this.

**Comment by Makman2** [comment]
Before you start working on an issue, please wait to be assigned, so we don't have multiple people working on the same issue. To get assigned accept the invitation from us to our organization. Be also sure to checkout our gitter channel for help and everything related :)

**Comment by rishikksh20** [comment]
Ok @Makman2 ! Please assign this issue to me because I already raise a pull request for the same.

**Comment by Makman2** [comment]
though shall be assigned! :)
