### ISSUE TITLE
Linter_Bears.rst: --msg_template is not a valid pylint option

### ISSUE THREAD

**Issue by vijeth-aradhya** [coala/coala#3415]
STEPS TO REPRODUCE

Please go through the tutorial, and copy the _Finished Bear_ _Section_'s code for PylintTutorialBear and try to run it using `coala --bear-dirs=. --bears=PylintTutorialBear --files=sample.py` on a sample python file (possibly which has linting erros so that you can verify). Also, please have the `pylint` executable in the current directory (`.`).

EXPECTED OUTPUT

pylint should be run on the python file, and results should be shown.

ACTUAL OUTPUT

It is actually not run, and also does not throw an error. Only the default section is executed.

POSSIBLE FIXES

1. Do `pylint --help`
2. You can see that it is actually `--msg-template`
3. Modify the doc wherever necessary

**Comment by sils** [comment]
@vijeth-aradhya I think this is already fixed, I can't see any reference to `msg_template` in the latest files neither on http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html, reopen if my judgement is wrong please.

**Comment by vijeth-aradhya** [comment]
Oh I found it here - https://coala.readthedocs.io/en/stable/Users/Tutorials/Linter_Bears.html
Well, in the coala repo - https://github.com/coala/coala/blob/6e75b6a0c0d6393f2d6e613049b26bd7c2a6aff9/docs/Users/Tutorials/Linter_Bears.rst
@sils I hadn't seen the link you sent, but please look at them ^^

**Comment by sils** [comment]
the github link points to an old commit,
https://coala.readthedocs.io/en/stable/ is outdated as well - does it still
appear at google or somethin'?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by vijeth-aradhya** [comment]
Oh haha I see!
And yes, it does :P I think we need to do something about it because some users might actually look at that and waste unnecessary time.
