### ISSUE TITLE
Typo in variable name in LinterTest.py

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3418]
https://github.com/coala/coala/blob/master/tests/bearlib/abstractions/LinterTest.py#L32

Shall be `PARAM_TYPE_ERROR_RE`

EDIT: `PARAM_TYPE_ERROR` -> `PARAM_TYPE_ERROR_RE`

**Comment by ap916** [comment]
Can I take it.

**Comment by Makman2** [comment]
I've misspelled the new variable name, see description on top again @ap916
