### ISSUE TITLE
Extend exception message test regex in LinterTest.py

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3419]
In https://github.com/coala/coala/blob/master/tests/bearlib/abstractions/LinterTest.py#L32

The message should be extended to something like 
```
'[A-Za-z_]+ must be an instance of type [A-Za-z_]+'
```
Otherwise people who read the string
```
'[a-z_]+ must be an instance'
```
think the exception just tells that we need an instance and not a type. This is kind of misleading.

(As seen the regex shall also support upper-case letters for the variable name, as python variable names don't have to be lower-case only.)

**Comment by karansangha** [comment]
I would like to work on this 😄

**Comment by karansangha** [comment]
The test passes succesfully with PARAM_TYPE_ERROR_RE = '[A-Za-z_]+ must be an instance' at line 32
but fails if i add this instead: of type [A-Za-z_]+ at the end of line.

It fails with the following error:

============================================= FAILURES =============================================
____________________ LinterComponentTest.test_decorator_invalid_parameter_types ____________________
TypeError: severity_map must be an instance of one of (<class 'dict'>,) (provided value: [])

During handling of the above exception, another exception occurred:

self = <tests.bearlib.abstractions.LinterTest.LinterComponentTest testMethod=test_decorator_invalid_parameter_types>

    def test_decorator_invalid_parameter_types(self):
        # Provide some invalid severity maps.
        with self.assertRaisesRegex(TypeError, self.PARAM_TYPE_ERROR_RE):
            linter('some-executable',
                   output_format='regex',
                   output_regex='(?P<severity>)',
>                  severity_map=list())(self.EmptyTestLinter)
E           AssertionError: "[A-Za-z_]+ must be an instance of type" does not match "severity_map must be an instance of one of (<class 'dict'>,) (provided value: [])"

tests/bearlib/abstractions/LinterTest.py:159: AssertionError


Any hints on how to solve the issue? 😸

**Comment by karansangha** [comment]
hmm, copying line 165 to 159 (the line that's causing the previous error) seems to make the test pass. But I don't know what exactly fixes it.

Please advise.

**Comment by Makman2** [comment]
Oh yeah seems my suggestion for the regex is wrong, please adapt the test regex to match the test output :+1:

**Comment by aptrishu** [comment]
Are you working on this issue? @karansangha

**Comment by SanketDG** [comment]
unassigned due to inactivity

**Comment by kavyashare** [comment]
i want this issue to be assigned to me

**Comment by SanketDG** [comment]
@kavyashare you are assigned!

Come to https://coala.io/chat if you have any questions or just want to hang out!

**Comment by Nosferatul** [comment]
@kavyashare are you working on this?

**Comment by Nosferatul** [comment]
Unassigned due to inactivity.
