### ISSUE TITLE
Documentation Status image not showing in readme.md file

### ISSUE THREAD

**Issue by amarlearning** [coala/coala#3437]
Documentation Status image not showing in readme.md file.
here is the [link](https://camo.githubusercontent.com/4937579857e2226640ea6fa2e28488409d9f9205/68747470733a2f2f646f63732e636f616c612e696f2f70726f6a656374732f636f616c612f62616467652f3f76657273696f6e3d6c6174657374)

Thought I performed a CURL request and there I found that image status is `ok`
`$ curl -X PURGE https://camo.githubusercontent.com/4937579857e2226640ea6fa2e28488409d9f9205/68747470733a2f2f646f63732e636f616c612e696f2f70726f6a656374732f636f616c612f62616467652f3f76657273696f6e3d6c6174657374`

**Comment by Makman2** [comment]
Indeed can't see the doc status too :+1:
