### ISSUE TITLE
Support `+=` operator to add settings instead of overiding

### ISSUE THREAD

**Issue by nemaniarjun** [coala/coala#3439]
For example:
If `base_coafile` (or default_coafile) contains `ignore += *.txt`
and user coafile contains `ignore = *.js`
we want to ignore both js and txt files
Right now, we use `ignore = *.txt` which gets overriden by the js ignore.

**Comment by Flap-Py** [comment]
I would like to work on this

**Comment by Makman2** [comment]
@Flap-Py if you have doubts, questions, whatever, be sure to sync up with us maintainers, as this is some important core feature^^

**Comment by Flap-Py** [comment]
sure :)

**Comment by Flap-Py** [comment]
So here basically, we have to add up the settings with `+=` and override the settings with `=`. Also one doubt, do we also want if base_coafile has `ignore = *.txt` and user_coafile has `ignore=*.js`, ie situation is just reverse, now also it will ignore both right? (IMO it should).
Then about the way, first I need to edit LineParser.py where I can have a field (say non_override), and store fields with += in that. then finally append these `non_override` with the keys which we have right now.
Is this way fine? Anything to add or something else?

**Comment by Makman2** [comment]
Ah I'm not sure... @sils need your thoughts:

> do we also want if base_coafile has ignore = *.txt and user_coafile has ignore=*.js, ie situation is just reverse, now also it will ignore both right? (IMO it should).

As we are going to implement a flag to ignore defaults anyway, maybe we should do this^^

@Flap-Py and as our settings parsing is totally string based (it has no knowledges about types itself), you should also append `,` as delimiter when adding a setting via `+=`^^

**Comment by sils** [comment]
Ahm people, @Udayan12167 is working on this feature since quite a while, I haven't seen this issue yet but please don't work on this. Check out coala.io/cep5 for more info and Udayan's pull request to coala.
