### ISSUE TITLE
settings docs page formatting issues

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3449]
http://api.coala.io/en/latest/Developers/coala_settings.html

- [ ] Should not use raw url link
- [ ] `coala --show-bears` command line is not highlighted

**Comment by rishikksh20** [comment]
Let me take this issue

**Comment by Makman2** [comment]
@rishikksh20 you already got a newcomer issue assigned + Mariatta is already assigned :)

**Comment by rishikksh20** [comment]
Ok
