### ISSUE TITLE
Improve cobot Help Page

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3457]
Perhaps someone who's more familiar with cobot can provide more information about of how cobot help page can be further improved.
Thanks 😃 

Follow up from https://github.com/coala/coala/issues/3228

**Comment by jayvdb** [comment]
Where is the cobot Help Page?
Also see my comment at https://github.com/coala/coala/issues/3228#issuecomment-270802476

**Comment by jayvdb** [comment]
Closing per https://github.com/coala/coala/issues/3458#issuecomment-306744375
