### ISSUE TITLE
Fix cobot (gitter hubot adapter)

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3458]
Can anyone familiar with cobot/hubot provide more info of what they'd like fixed in cobot/hubot?
Thanks 😃 
Follow up from #3228

**Comment by Mixih** [comment]
Eh, it's an upstream fix, I woudn't mark difficulty yet.... Basically we need hubot's gitter2 adapter fixed to read mroe than 100 users

**Comment by Mariatta** [comment]
gotcha
is there an issue filed upstream about this yet?

**Comment by nemaniarjun** [comment]
Yes there is and there's a comment from someone in the gitter org about the skipping of pages to get list of all users. But the adapter does support paging, it's probably a bug.

**Comment by nemaniarjun** [comment]
https://github.com/huafu/hubot-gitter2/issues/23

**Comment by Mariatta** [comment]
Anyone up to the challenge to fix this upstream? 😀 Fork it, create your own PR, make everyone at coala happy 💪

**Comment by nemaniarjun** [comment]
I am trying it. Need some time to get coffee script right :P

**Comment by nemaniarjun** [comment]
Also @meetmangukiya is trying to make a Python cobot :D

**Comment by meetmangukiya** [comment]
Yeah, and anyone wanting to contribute is welcome :) https://github.com/meetmangukiya/cobot

**Comment by nemaniarjun** [comment]
Fixed :tada: Close this issue :)

**Comment by jayvdb** [comment]
This is a dup of https://gitlab.com/coala/cobot/issues/25 (and other issues should be filled there)

**Comment by jayvdb** [comment]
Actually ... lets track this here as an upstream problem as it isnt yet merged.

**Comment by jayvdb** [comment]
And now that we have http://github.com/coala/meta/ , this meta upstream tracker would go there, but we also have GSoC project https://github.com/coala/corobo/ , which will have an awesome help system I am sure.
So closing this one.
