### ISSUE TITLE
OpenEditorAction should log a warning for unknown editors

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala#3467]
This is an amendment to  #3443 where we defined a set of known editors.

For unknown editors we just pass all the filenames and hope for the best. The user should be warned about this and encouraged to file an issue requesting support for that editor.

**Comment by NiklasMM** [comment]
Can someone assign me please?

**Comment by nemaniarjun** [comment]
try `cobot assign <linktoissue>` on gitter
Also the warning can contain link to our github, so that we can add these editors
