### ISSUE TITLE
Error seen in autopep8 while executing Coala on Windows

### ISSUE THREAD

**Issue by varunamayya** [coala/coala#3470]
Hi,

I am new to github and am assuming this is the right place to ask for some help in an issue seen. I was looking for some static analysis tools for C project which allows user to define rules and came across coala. I installed python, coala in my windows machine and executed coala. However, I am seeing errors. Can somebody kindly help? I have followed the installation steps mentioned in the site.

C:\Users\100784123\AppData\Local\Programs\Python\Python36-32\Scripts>coala --files c:/**<codePath>**/*.c
Executing section Default...
Executing section python...
[INFO][11:10:47] Applied 'ApplyPatchAction' on '..\\..\\..\\..\\..\\..\\..\\..\\**<codePath>**\\modelHost.c' fro
m 'SpaceConsistencyBear'.
[INFO][11:10:47] Applied 'ApplyPatchAction' on '..\\..\\..\\..\\..\\..\\..\\..\\**<codePath>**\\modelHost.c' fro
m 'SpaceConsistencyBear'.
[INFO][11:10:47] Applied 'ApplyPatchAction' on '..\\..\\..\\..\\..\\..\\..\\..\\**<codePath>**\\modelHost.c' fro
m 'SpaceConsistencyBear'.
.... 
**Why does the same information come so many times. There must be >50 such messages for the same file.**

**ACTUAL ERROR**
Executing section autopep8...
[ERROR][11:10:48] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][11:10:48] Exception was:
Traceback (most recent call last):

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\site-pa
ckages\coalib\coala_main.py", line 110, in run_coala
    console_printer=console_printer)

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\site-pa
ckages\coalib\processes\Processing.py", line 702, in execute_section
    runner.start()

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

_pickle.PicklingError: Can't pickle <PycodestyleBear linter class (wrapping 'pyc
odestyle')>: attribute lookup PycodestyleBear on coalib.bearlib.abstractions.Lin
ter failed

C:\Users\100784123\AppData\Local\Programs\Python\Python36-32\Scripts>Traceback (
most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\100784123\appdata\local\programs\python\python36-32\lib\multipr
ocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

**Comment by varunamayya** [comment]
Kindly ignore the message. I changed the .coafile not to include PEP8 since I was working on C files.

**Comment by nemaniarjun** [comment]
@varunamayya is the issue resolved then?

**Comment by varunamayya** [comment]
I removed the pep8 section from .coafile and it worked fine.

**Comment by nemaniarjun** [comment]
Please close this issue then. Thanks :)
