### ISSUE TITLE
ConsoleInteraction.py: Replace log_printers with built-in logging.

### ISSUE THREAD

**Issue by tulphoon** [coala/coala#3472]

**Comment by aptrishu** [comment]
This would end up removing log_printer from some other places too. are we deprecating it ? @sils

**Comment by sils** [comment]
LogPrinter is already deprecated, it should be removed whereever possible

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by shreyans800755** [comment]
@sils Do we need ListLogPrinter ?
Is it needed by any bears or any other functionality ?
If so, we'll have to build it using logger instead of LogPrinterMixin.

**Comment by thisch** [comment]
@shreyans800755 I would remove ListLogPrinter, since it is only used in the tests
