### ISSUE TITLE
Codestyle.rst : Rephrase sentence

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala#3478]
In the Codestyle documentation the following sentence 

![screenshot from 2017-01-05 16-04-02](https://cloud.githubusercontent.com/assets/10217535/21678352/6c605c16-d364-11e6-9f5f-925d996bc92f.png)

should be
    

> This will raise a `TypeError` if `a` or `b` are not strings or `c` is not a string and not `None`

**Comment by sravi4701** [comment]
Hello,
I am newcomers. Can I work on this issue?

**Comment by marian-ald** [comment]
I think it's ok. You can make a pull request and a reviewer will ckeck if it's mergeable

**Comment by marian-ald** [comment]
So... squashing commits?

**Comment by sravi4701** [comment]
What is squashing commits ?

**Comment by marian-ald** [comment]
You have more commits to the same file, so you must have only one. For that you have to use:
git rebase -i HEAD~3 

It will open you an editor. You can follow these steps: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

In the future, when you make a commit use:
 git commit --amend

In this way you edit your last commit, whithout creating a new one.

**Comment by marian-ald** [comment]
Also body commit lines have max 72 characters

**Comment by Chhokra** [comment]
Can I work on this issue?

**Comment by Makman2** [comment]
@sravi4701 your state on this issue? Wanna make the last steps for merge? :)

@Chhokra sorry this one's also taken and already been worked on, normally I would wait a few days for a response, in this time you should pick another issue so you don't have to wait :)

**Comment by Nosferatul** [comment]
@sravi4701 are you working on this?

**Comment by Nosferatul** [comment]
Unassigned due to inactivity.

**Comment by nityeshaga** [comment]
I see no current assignees and I would like working on this issue. Assigning it to myself via cobot.
