### ISSUE TITLE
Newcomers_Guide.rst: There is a link typo

### ISSUE THREAD

**Issue by gaocegege** [coala/coala#3481]
There is a link typo in coala/docs/Developers/Newcomers_Guide.rst:

<img width="679" alt="2017-01-05 9 23 24" src="https://cloud.githubusercontent.com/assets/5100735/21682037/497250dc-d38d-11e6-9841-ec217497c22d.png">

**Comment by divyanshu-rawat** [comment]
Hello I am new Can I work on this issue ?

**Comment by satwikkansal** [comment]
@divyanshu-rawat This issue has already been fixed in the PR #3477  Please try other newcomer labeled issues :)

**Comment by divyanshu-rawat** [comment]
Oh okay thanks !
