### ISSUE TITLE
CachingUtilities: Not completely covered by py.test -k Caching

### ISSUE THREAD

**Issue by Shade5** [coala/coala#3492]
```
a@a ~/workspace/coala/coala $ py.test -k Caching --cov | grep CachingUtilities.py    
coalib/misc/CachingUtilities.py                                        75      1     20      1    98%   172, 169->172
```
Tests should be completely self-covering.

**Comment by adtac** [comment]
This is because we'd need to flush the cache to get 100% coverage. Remove your coala cache and retry - you should get 100% :)

**Comment by Shade5** [comment]
`coala --flush-cache`
followed by 
`py.test -k Caching --cov | grep CachingUtilities.py ` ?

Still not 100% for me

**Comment by adtac** [comment]
Try removing your entire cache directory (usually at `~/.local/share/coala` or something like that). `coala --flush-cache` will only remove that project's cache.

**Comment by jayvdb** [comment]
Maybe we can automatically clear the cache somewhere, or add a BIG BOLD NOTE if the test suite is being run with stuff in the cache.

**Comment by Shade5** [comment]
Yes, that seems logical. I'll close this then.

**Comment by jayvdb** [comment]
Can you create a new issue about the BIG BOLD NOTE ?
