### ISSUE TITLE
`py.test` fails due to version conflict of packages

### ISSUE THREAD

**Issue by Shade5** [coala/coala#3511]
Enhance `py.test` to first install the appropriate packages before starting the tests. 
Can prevent confusions.

**Comment by Mixih** [comment]
wait what is the problem here? py.test is a command not a script....

**Comment by Shade5** [comment]
Sorry, I meant while running `py.test`, it should first test if the appropriate packages were installed before continuing. 
Should add a test to check package versions.

**Comment by Makman2** [comment]
There's no feature for that in `py.test`. It collects and imports all files beforehand, if conflict errors arise already you will see them, regardless whether you have a test for checking package versions. But at least you see that there are conflict errors.

**Comment by Shade5** [comment]
I was suggesting to add a test to check the version of packages. This will prevent confusions like this https://github.com/coala/coala/issues/3502.
It was failing due to version conflict of a package, but the error was misdirecting.

**Comment by Makman2** [comment]
so an environment check. yes could be useful :+1:

**Comment by Shade5** [comment]
Are all the required packages mentioned in requirements.txt?

**Comment by Makman2** [comment]
should be, that's what `requirements.txt` is for ;)

**Comment by Shade5** [comment]
Which test file should I add the test to?
This is what I have in mind
```
with open('requirements.txt') as f:
	content = f.readlines()

y=[]

for x in content:
	if '=' in x:
		y.append(x[x.find('=')+1:-1])

import appdirs
import coala_utils
import colorlog
import dependency_management
import pygments
import pyprint

assert y[0] in appdirs.__version__		
assert y[1] in coala_utils.__version__	
assert y[2] in colorlog.__version__	
assert y[3] in dependency_management.__version__	
assert y[4] in pygments.__version__	
assert y[5] in pyprint.__version__	
```

**Comment by Shade5** [comment]
But `coala_utils.__version__` does not exist

**Comment by Makman2** [comment]
you should add the stuff to a unittest class. Otherwise py.test will just say that collection of a file filed, I think it's more intuitive to handle when you get a normal test error.

> Which test file should I add the test to?

I think it should go into the test root folder into `RequirementsTest.py` 👍 :)

**Comment by Shade5** [comment]
Seems like `colorlog.__version__` and `dependency_management.__version__` don't exist. How do I check the versions then?

**Comment by Makman2** [comment]
You can invoke `pip freeze` or use an according function from the `pip` module.

**Comment by Shade5** [comment]
```
import pip
pip.main(['freeze'])
```
This prints on the console, how do I turn it into a list?

**Comment by Makman2** [comment]
hm can't find something better... I think you should use `coalib.misc.Shell.execute_shell_command` with `[sys.executable, '-m', 'pip', 'freeze']` :+1:

**Comment by jayvdb** [comment]
Neat idea.
This should be built as a pytest plugin, so other projects can use it and help maintainance, and it doesnt suck up coala reviewers time.

**Comment by jayvdb** [comment]
Another instance of this is https://github.com/coala/coala/issues/4239#issuecomment-302105449

pytest-reqs does the trick, but has an annoying bug : https://github.com/di/pytest-reqs/issues/9
