### ISSUE TITLE
Definitions for the language CSharp not properly defined

### ISSUE THREAD

**Issue by Techievena** [coala/coala#3514]
Fields like  string_delimiters and comment_delimiters are missing  which is causing AnnotationBear to fail `coala/coalib/bearlib/languages/definitions/CSharp.py`

**Comment by rishikksh20** [comment]
Possible solution for this to add following lines to CSharp.py
```
comment_delimiter = '//' 
multiline_comment_delimiters = {'/*': '*/'} 
string_delimiters = {'"': '"'} 
```
If yes then please assign this issue to me.

**Comment by Techievena** [comment]
Refer this https://msdn.microsoft.com/en-us/library/5fz4y783.aspx
