### ISSUE TITLE
New Links Page 

### ISSUE THREAD

**Issue by CosminIcatoiu** [coala/coala#3515]
Through my experience as a newcomer i faced some problems in finding stuff on the site and I had to ask on gitter things that could easily be found anyway. So what i suggest is to have a stand alone page ( like the Newcomers Guide page for example) for Useful Links. Here it would be very easy for everybody ( especially for newcomers) to find links to tutorials( how to git, how to rebase how to work with rst docs), links to issues( by difficulty), etc. I understood that there is some kind of page with this but it`s not very accessible and not very known. 
So, i wanted to ask you if you believe this may be a good idea to implement and also ask you to come with some ideas for the links. What do you believe to be useful to be on this page.

**Comment by Makman2** [comment]
maybe we should add those links to the top of [api.coala.io](api.coala.io)

**Comment by aptrishu** [comment]
though we have git basics page for anything else in that matter you have to google and that is totally fine.
working with rst docs -> I think they should google.. you get to learn things this way plus its not that big thing or hard to find. and apart from that opinions on these things don't differ so IMO we don't need a separate page for this.
links to issues -> Yes we should include links like https://coala.io/low to newcomer guide which we already have at https://coala.io/newcomer .

**Comment by Mariatta** [comment]
Isn't "Get Help With Git" is already part of newcomer's guide?

How to work with rst is in this issue: https://github.com/coala/coala/issues/3521 :)

But I think these are good suggestions. If you as newcomer have difficulties with these, chances are others will face them too. 

So I think it's good if there is a "Useful Links" section there.

**Comment by CosminIcatoiu** [comment]
That were just examples. Not specifically that links. If anybody has other ideas, should feel free to say them. I dont know. Maybe it was just my experience. I just felt i had some issues with orientation throughout the site and felt that something like this would`ve helped. I finally found them by asking " is there a site to ... " but felt it would`ve been easier this way :)

**Comment by CosminIcatoiu** [comment]
And also don`t say  that most of the links cant be already found somewhere in the site( most of them can ) but sometimes hard to remember which is where . This is why i tought it was useful :)

**Comment by aptrishu** [comment]
Yeah as I said we can put useful links in the newcomer guide.

**Comment by CosminIcatoiu** [comment]
Or like this at the end of the Newcomer guide to add a section with this ? maybe it would be better

**Comment by aptrishu** [comment]
yeah, ofcourse put that under a section.

**Comment by Mariatta** [comment]
Yes. So:

1. Add a new Useful Links section under "For Developers" Section of the docs
2. Link to Useful Links from "Developers/Newcomers_Guide.html

**Comment by CosminIcatoiu** [comment]
So ? Separate section ( document in Developers ) or separate step of Newcomers cause i think @aptrishu  suggested it to be part of an existing document .

**Comment by Mariatta** [comment]
It should be a separate section outisde of Newcomers_Guide.html, so not to clutter it.
eg
/Developers/Useful_Links.rst

Then from Newcomers_guide.rst you'll mention something about "check the useful links section" 

I already envision that the Useful links section will grow over time, so best to have it's own page..

**Comment by Mariatta** [comment]
@CosminIcatoiu do you want to be assigned? :)

**Comment by aptrishu** [comment]
aah it's difficulty newcomer or low I think..

**Comment by CosminIcatoiu** [comment]
Also , what links do you think of? I tought of tutorials ( git, rebase, coala, python, rst) , of issues( by difficulty + coala git page ) , of chat . Anything else? I also believe it is low .

**Comment by Mariatta** [comment]
I think it's a little more complicated for newcomers. This will involve creating a new rst page and linking.

**Comment by Mariatta** [comment]
Start with what you find useful from your own experience.
We can review it, and new links can be added at later time :)

**Comment by CosminIcatoiu** [comment]
Ok . I will start writing it. :+1:
