### ISSUE TITLE
Add FileProxy

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3530]
See https://github.com/coala/cEPs/blob/master/cEP-0002.md#the-file-proxy

The `FileProxy` shall be responsible for providing files and their contents to the bears and bear-writers. It shall cache contents as efficient as possible, and also provide different interfaces to the file (like utf8-decoded with and without line-endings or a binary version).

**Comment by Mariatta** [comment]
Is this issue to track the implementation of it? Perhaps label accordingly. (Size? Difficulty?)
Thanks.

**Comment by palash25** [comment]
@Makman2 if FileProxy is going to be used to cache contents of the file I think we should also add the last modified timestamp (using `os.path.getmtime`) as a property of the FileProxy so that it can be used for caching purposes.
I looked into the cEP and it doesn't mention timestamp as a property.

**Comment by Makman2** [comment]
> I think we should also add the last modified timestamp (using os.path.getmtime) as a property of the FileProxy so that it can be used for caching purposes.

Exactly what I had in mind. This will significantly speed up the caching system. And yeah the cEP doesn't mention it, but it wasn't written with NextGen-Core in mind :)

**Comment by palash25** [comment]
@Makman2 I had a question about the `__hash__()` function in the proposed `FileProxy` for what purpose do we need a hash of the file. For caching currently we use modification timestamps of files using `os.path.gettime`. If its not for caching what is it for then?

**Comment by Makman2** [comment]
We actually don't need it for our purposes, but it still might be useful to implement the method. For our caching specifically what's important is to override pickling. The FileProxy is a persistent object and has to be treated carefully to make everything work properly.
