### ISSUE TITLE
Update Show bears' information

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3561]
`--show-description` does not give a large amount of information as specified in the bullets. Also replacing it with `--show-details` and adding a few points that `--show-details` covers would be a good idea.

**Comment by yash-nisar** [comment]
Moved to coala/documentation.

**Comment by Makman2** [comment]
@yash-nisar shall I close the issue?

**Comment by yash-nisar** [comment]
I haven't moved it yet. Doing it ATM. :)

**Comment by Makman2** [comment]
@yash-nisar could you put the link to the new issue here? :)

**Comment by yash-nisar** [comment]
https://github.com/coala/documentation/issues/397 @Makman2
