### ISSUE TITLE
Two line spanning in case of MAC users. 

### ISSUE THREAD

**Issue by HitRam** [coala/coala#3565]
The highlighted portion spans two lines unevenly. The issue of this poor highlighting is already mentioned here : https://github.com/coala/coala/issues/3544. 

<img width="548" alt="screen shot 2017-01-15 at 10 12 28 pm" src="https://cloud.githubusercontent.com/assets/19632768/21964315/c3e2bbba-db6f-11e6-89d6-71102c646937.png">

**Comment by jayvdb** [comment]
@HitRam , @rhemon , any chance you can diagnose the cause of this?

**Comment by jayvdb** [comment]
@hitram, what was the contents of `temp.py` ?

**Comment by jayvdb** [comment]
(these OSX issues might not be solved before the release, but I think we should try...)

**Comment by HitRam** [comment]
`def something():
    a = 5`

@jayvdb  This was the code. 
Yes I'll try to find the cause 😄

**Comment by HitRam** [comment]
@jayvdb  This comes only when there is some special character or number after a 
'''
def something():
    a . 
    a 7  
'''
This would lead to poor highlighting. Also not all special characters lead to poor highlighting. What could be wrong 😕

**Comment by sangamcse** [comment]
These too is working fine on my system. Tried [1](https://github.com/coala/coala/issues/3565#issuecomment-274596789) and [2](https://github.com/coala/coala/issues/3565#issuecomment-274307019) both. 
cc @Makman2, @HitRam @jayvdb 
Same as https://github.com/coala/coala/issues/3544#issuecomment-373498446

**Comment by sangamcse** [comment]
```
def something():
    a .
	a 7

def otherthing():
	a = 5
```
I used these on all my 10 terminals. It seems fine to me. 😄

**Comment by Makman2** [comment]
If someone encounters it again, feel free to comment.
