### ISSUE TITLE
Newcomers_Guide.rst: Improve "Review Process"

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3578]
Some things that should be improved there:
- Enclose `"difficulty/low"` in double backticks, not in double quotes
- > We highly encourage you to start reviewing other's "difficulty/low" or newcomer issues after you complete your newcomer issue as reviewing helps, you to learn more about coala and python.
  
  The comma after "helps" should moved before "as".
- > **Do not only fix a newcomer issue!** It is highly recommended that you fix one newcomer issue to get familiar with the workflow at coala and then proceed to a difficulty/low issues.

  Either do:
  - ... then proceed to difficulty/low issues
  or
  - ... then proceed to a difficulty/low issue

**Comment by harshit890** [comment]
thanx @Makman2
