### ISSUE TITLE
Link `bear writing tutorial` in website coala.io is invalid

### ISSUE THREAD

**Issue by Techievena** [coala/coala#3591]
As per https://github.com/coala/coala/pull/3549 `writing bears` was renamed `writing native bears` but this one was perhaps missed out. Provide valid URL in the link `bear writing tutorial`.

difficulty newcomer

**Comment by abhigyank** [comment]
Hey, I would like to be assigned to this issue. 
Cheers!

**Comment by Techievena** [comment]
Ask in gitter channel or assign yourself in gitter.

**Comment by abhigyank** [comment]
To address this issue  do I contribute to https://github.com/coala/website ?

**Comment by SiddharthKumar02** [comment]
@abhigyank  No, I think you should be contributing to https://github.com/coala/coala/tree/master/docs/Developers

**Comment by sils** [comment]
changed. THis is not a newcomer issue.
