### ISSUE TITLE
Remove call_without_output from Shell.py L7

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala#3600]
This line was used by the requirement classes, it isnt used anymore as they use sarge, so it should be removed.
difficulty/newcomer

**Comment by Trailblazerr1** [comment]
The change I made in my first commit, resulted in a number of issues, so I closed that [pull](https://github.com/coala/coala/issues/3601) request and am going to work again on it.

**Comment by Nosferatul** [comment]
you should solve the issues, if you have any problems drop on gitter and ask!

**Comment by arnab1896** [comment]
Hey @sils, could you please assign this issue to me.

**Comment by jayvdb** [comment]
This commit didnt have a proper URL in the commit message, and `call_without_output` should have been deprecated.as part of https://github.com/coala/coala/issues/3597
