### ISSUE TITLE
De-activate Travis OSX job for PRs

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3611]
The OSX job has been in the matrix long enough, with no issues found (there was one failed build I saw, by rhemon iirc, but it looked unrelated to coala).

After the 0.10 release, it will have been in place for most of a dev & release cycle, and should be deactivated at least for PRs, as it slows down merges, and doesnt add much value.

Maybe it should be re-added at the end of the 0.11 cycle, to ensure there are no regressions.

**Comment by jayvdb** [comment]
Note we have two OSX bugs recently created which were not caught by the OSX job:
1. https://github.com/coala/coala/issues/3544
2. https://github.com/coala/coala/issues/3565

**Comment by Mixih** [comment]
hmm we can't really catch UI problems in CI though can we?

**Comment by ankit01ojha** [comment]
@jayvdb How it can be done, can you please tell me?

**Comment by jayvdb** [comment]
Invoke coala as a subprocess and check the output.

**Comment by Mixih** [comment]
@ankit01ojha just remove the build please, we might want to re-enable in the future.
Also, rather important imo as this slows down build by ~1 hour on weekdays

**Comment by ankit01ojha** [comment]
@Mixih how should I just remove the build only from the matrix?

**Comment by Makman2** [comment]
@ankit01ojha https://github.com/coala/coala/blob/master/.travis.yml#L9

**Comment by jayvdb** [comment]
This has become quite urgent now, as we have many pending PRs with one job pending: OSX, and Travis has 1300+ pending OSX jobs.  This means no coala jobs (even on other coala repos) are started, as there are the coala osx jobs pending fill our quota of jobs (the osx jobs are in the queue first).
