### ISSUE TITLE
Grammatical errors in newcomers guide

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3619]
1. `there’s a few steps you need to complete`
   It should be: `there are a few steps` 

2. `The newcomer process is as it follows`:
Should be changed into: `The newcomer process is as follows`:

The file to be changed is at
/docs/Developers/Newcomers_Guide.rst

**Comment by Chhokra** [comment]
Kindly assign me this issue.

**Comment by Makman2** [comment]
@Chhokra as you can see the issue is already taken, feel free to pick another one :+1:

**Comment by ashwini0529** [comment]
@AlexandruGhimisi Are you still working on it?
