### ISSUE TITLE
Version mismatch with requests

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3630]
We had a version mismatch with requests, due to adding requests to `requests~=1.12.0`, while `requests~=1.12` was the direct dependency of coala-bears.

https://github.com/coala/coala/pull/3628 made the two version specifiers identical.

**Comment by Mixih** [comment]
fixed by 865b56f

**Comment by Mixih** [comment]
whoops, incorrect mention, I meant 284bd62180fb5ae3292af67b13dd701e0ea07316
