### ISSUE TITLE
[question] cache

### ISSUE THREAD

**Issue by rpau** [coala/coala#3640]
Hi, 

I would like to contribute with some ideas about git in that project and I would like to understand the logic beyond the cache. Specifically, when files become untracked.

Are the editors plugins calling that method ([untrack_files](https://github.com/coala/coala/blob/569d894ed485039ad0fa7f7be76518d715f43cb4/coalib/misc/Caching.py#L142)) after any modification?

**Comment by Makman2** [comment]
This is the code for our cache:
https://github.com/coala/coala/blob/master/coalib/misc/Caching.py

Editor plugins execute coala as a new process, so there's no need to manually handle the cache. Normally coala gets then executed after a file save so it picks up the new version.

@rpau You should rather ask such questions on our [gitter channel](https://gitter.im/coala/coala), as issues are intended for tasks^^
