### ISSUE TITLE
deploy.pypi.sh should have better error detection.

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3644]
https://github.com/coala/coala/blob/master/.misc/deploy.pypi.sh should have better error detection.

It should gracefully fail only if it is a server error(500), and not if it is any error.

**Comment by Shade5** [comment]
So should the `set +e ...  set -e` be removed?
Fail and exit only if error(500) ?

**Comment by jayvdb** [comment]
> So should the set +e ... set -e be removed?

yes, really easy ...

> Fail and exit only if error(500) ?

yes, and this is the harder part.
