### ISSUE TITLE
pycodestyle 2.3 reports E722 bare exception

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3660]
https://pypi.python.org/pypi/pycodestyle 2.3.0 was released on 30 Jan, causing many new code style errors.

https://travis-ci.org/coala/coala/jobs/196607369

```
coalib/output/ConfWriter.py

| 136| ············def_val·=·None
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

coalib/output/ConfWriter.py

| 149| ····················def_val·=·str(defaults[key])
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

[WARNING][14:53:36] PycodestyleBear (E306): This result has no patch attached.

coalib/settings/FunctionMetadata.py

| 176| ········defaults·=·()·if·argspec.defaults·is·None·else·argspec.defaults
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

[WARNING][14:53:40] PycodestyleBear (E306): This result has no patch attached.

[WARNING][14:53:40] PycodestyleBear (E306): This result has no patch attached.

[WARNING][14:53:40] PycodestyleBear (E306): This result has no patch attached.

tests/settings/SectionTest.py

|  41| ········defaults.append(Setting('tEsT',·1,·3))
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

tests/settings/SectionTest.py

|  42| ········defaults.append(Setting('·great···',·3,·8))
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

tests/settings/SectionTest.py

|  43| ········defaults.append(Setting('·great···',·3,·8),·custom_key='custom')
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

[WARNING][14:53:40] PycodestyleBear (E722): This result has no patch attached.

coalib/processes/BearRunning.py

| 105| ····except:
|    | [NORMAL] PycodestyleBear (E722):
|    | E722 do not use bare except''

[WARNING][14:53:46] PycodestyleBear (E306): This result has no patch attached.

coalib/output/ConsoleInteraction.py

| 309| ····default_format·=·('id:{id}:origin:{origin}:file:{file}:line:{line}:'
|    | [NORMAL] PycodestyleBear (E306):
|    | E306 expected 1 blank line before a nested definition, found 0'

[WARNING][14:53:55] PycodestyleBear (E302): This result has no patch attached.

coalib/misc/Constants.py

| 116| default_coafile·=·'.coafile'
|    | [NORMAL] PycodestyleBear (E302):
|    | E302 expected 2 blank lines, found 1'

[WARNING][14:53:55] PycodestyleBear (E722): This result has no patch attached.

coalib/bears/Bear.py

| 251| ········except:
|    | [NORMAL] PycodestyleBear (E722):
|    | E722 do not use bare except''
```

**Comment by jayvdb** [comment]
The requirement is currently `~=2.2`, which means 2.3 is acceptable.
The `PipRequirement` was added in coala/coala-bears@d8be55a9, to align with autopep8's development version which is [actually](https://github.com/hhatto/autopep8/blob/master/setup.py#L14) `>=2.2`, which of course would allow 3.x which would be bad.

autopep8's released version is [actually](https://github.com/hhatto/autopep8/blob/d9474e2fb30f0a719735b45ed8d3225a177d6d7d/setup.py#L14) `pep8>=1.5.7` , which is the deprecated `pep8`.
autopep8's next version will be 2.0, so it wont be used by coala due to our `autopep8~=1.2` requirement.
I strongly suspect that autopep8 2.0 will adopt pycodestyle 2.3.0 before their release.

We can change our requirement to `pycodestyle~=2.2.0`, to temporarily avoid these 2.3.0 problems.
We'll also need to fix our code style soon to comply with pycodestyle 2.3.0, which means we are ready for the autopep8 release 2.0 which is imminent.

**Comment by jayvdb** [comment]
coala-bears also has the same problem

https://travis-ci.org/coala/coala-bears/jobs/196688733
```
bears/js/JSHintBear.py

|  12| ····except:
|    | [NORMAL] PycodestyleBear (E722):
|    | E722 do not use bare except''

bears/js/JSHintBear.py

|  19| ····except:
|    | [NORMAL] PycodestyleBear (E722):
|    | E722 do not use bare except''

[WARNING][21:42:14] PycodestyleBear (E302): This result has no patch attached.

bears/c_languages/codeclone_detection/ClangFunctionDifferenceBear.py

|  27| default_cc_dict·=·counting_condition_dict(StringConverter(

|    | [NORMAL] PycodestyleBear (E302):
|    | E302 expected 2 blank lines, found 1'
```

**Comment by jayvdb** [comment]
Also interesting:

> E306 expected 1 blank line before a nested definition, found 0'

why do we have a trailing quotation mark at the end of that line.

> E722 do not use bare except''

And two! after that one.

**Comment by jayvdb** [comment]
The new E306 are not serious, but worth noting that E306 is an old code, and covers more than the current errors, and a new release 2.3.1 has come out with some bugfixes for E306. (I've confirmed the two error lists above were both with 2.3.0)
So we need to re-test with 2.3.1 to see if those E306 still exist.

**Comment by jayvdb** [comment]
E306 no longer occur with pycodestyle 2.3.1, but the E722 still exist, and given they are a serious problem, IMO we shouldnt prevent coala users from using 2.3.x just because we have some serious bugs.

**Comment by aptrishu** [comment]
ATM can we just change the pycodestyle version requirement ? to ~=2.2.0
codestyle changes can be made later, loads of PR are failing for this reason..

**Comment by jayvdb** [comment]
> ATM can we just change the pycodestyle version requirement ? to ~=2.2.0

These errors are real bugs, and the fix should be easy.
If it takes more than a day, then yes, changing it to ~=2.2.0 is sensible as a short term solution

**Comment by jayvdb** [comment]
The -bears errors is being addressed in  https://github.com/coala/coala-bears/pull/1374
