### ISSUE TITLE
Intermittant error installing coala-bears dependencies: ImportError: No module named 'packaging'

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3668]
First mention on gitter:

https://circleci.com/gh/coala/coala/10915

Then I encountered it twice in a short period:

https://travis-ci.org/coala/coala/jobs/197188789
https://travis-ci.org/jayvdb/coala/jobs/197191905

Last releases:
- pip 9.0.1: 2016-11-06
- packaging 16.8: 2016-10-29
- setuptools 34.1.0: 2017-01-29

It looks like the order of pip installing dependencies changes for each build, and whether this bug occurs depends somewhat on which order these packages are upgraded.

**Comment by jayvdb** [comment]
Also seen at https://travis-ci.org/coala/coala-eclipse/builds/197394365#L553 , which had trusty default pip 1.5.4 & setuptools 3.3 , and pip wouldnt uninstall them as they are owned by the OS.  I assume pip then believes it has met those upgraded dependencies, and continues to install other packages that depend on newer versions of pip and setuptools.

https://github.com/pypa/setuptools/issues/937 is about the same exception, and has lots of duplicate issues filed about it in that repo, and it has a few workarounds.

One worth trying is upgrading `packaging` first, and maybe appdirs also.
`pip3 install --upgrade packaging appdirs`

The background for it all is https://github.com/pypa/setuptools/issues/581 . pinning to an older version of setuptools may be a short term strategy, but it is unlikely that the problem will go away, as setuptools/pip teams have intentionally broken the old behaviour in a major release of setuptools, they will build out new functionality on top of this change, and reverting (or merging workarounds) wont be an option.

**Comment by aptrishu** [comment]
Fixed through https://github.com/coala/coala/pull/3680.

**Comment by jayvdb** [comment]
How does upgrading setuptools fix it?  Was there a new setuptools release that solved the problem?

Even so, that commit only fixes our CI.  We now need to at least update our documentation to say that is required for any .

**Comment by aptrishu** [comment]
Actually, upgrading pip is what solved it. setuptools can't build itsellf from source dist anymore from the latest version. So, recent version of pip is needed that supports wheel installs of setuptools.
