### ISSUE TITLE
CLI Markdown renderer

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3692]
We could try to output CLI text as markdown and try to render it as good as possible in the terminal :)

For example a code-block would be highlighted with gray or some different color (and the backticks would be removed), so it looks like rendered markdown in the browser.

Not sure there's a package out there for this, but I think it's still a quite cool idea ;)

**Comment by meetmangukiya** [comment]
Why'd we want that ?

Things that could not be used:
- Headings
- Images
- Links too

Things that could be used:
- Bullets(`ul`) --- Could be done with some unicode character :/ 
- Lists  --- Already could be done normally
- Code -- The __only__ one that is usable ?

**Comment by Makman2** [comment]
Good point... though I like code-highlighting :3

If you think it's not worth it @meetmangukiya feel free to close :+1:

**Comment by meetmangukiya** [comment]
I think we have syntax highlighting in place and implementing background color for that won't be an issue, I'll keep it open in case someone would want to implement it

**Comment by Makman2** [comment]
let's do it like this ;)

**Comment by meetmangukiya** [comment]
Didn't know we had that label.
