### ISSUE TITLE
:raises Error: in documentation comments

### ISSUE THREAD

**Issue by sils** [coala/coala#370]
Do we want that?

TODO: List of advantages/disadvantages.

**Comment by Makman2** [comment]
Advantage:
- Users can directly see what exceptions they need to catch and add specific handling for each exception type
Disadvantage:
- Slightly more documentation writing

**Comment by sils1297** [comment]
Slightly? But yeah, agreed. It's good for quality, so things that need to be done:

 * [ ] Specification (codestyle)
 * [ ] Implementation (add raises msg to all functions. Along with doc comments.)
 * [ ] Make documentation parser and FunctionMetadata classes aware of this
 * [ ] Just thinking a bit ahead, but can we use this to show the cause of the exception if a bear raises it and specified it this way?

**Comment by Makman2** [comment]
> Just thinking a bit ahead, but can we use this to show the cause of the exception if a bear raises it and specified it this way?
Super nice idea, would do that, that really helps finding errors.

**Comment by AbdealiJK** [comment]
question: If function A() may raise a AssertionError then we add this to A()'s docstring. Now, if function B() calls A() ... then should this be in function B()'s docstring also ?

**Comment by sils1297** [comment]
yes it should. This way we can make sure that we catch every exception we
throw meaning the user doesn't get to see so many exceptions which would be
a bug so I think doing this would be beneficial

2015-07-15 16:13 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
Would be a cool Bear that traverses down each function and checks for missing raises documentation^^

**Comment by sils1297** [comment]
indeed.

2015-07-15 18:37 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by abit2** [comment]
@sils1297 i would like to give it a try.

**Comment by AbdealiJK** [comment]
To summarize all the above discussion.

What this issue aims to do is improve documentation about which function throws which errors.

For example. Lets take a function:
```
def add_numbers(num1, num2):
    """
    Adds 2 numbers.
    :param num1: Left operand of addition
    :param num2: Right operand of addition
    """
    # Check if num1 and num2 are numbers
    # Add them
    # Return the sum
 ```
Now, a function like that has to check if num1 and num2 are intergers or floats. So, it may throw a `TypeError` if the type of the arg is wrong.
What we aim to do is add a new documentation line which tells us that the function may throw a `TypeError`.

We can do that by
```
def add_numbers(num1, num2):
    """
    Adds 2 numbers.
    :param num1: Left operand of addition
    :param num2: Right operand of addition
    :raises TypeError: when the args given are not intergers
    """
    # Check if num1 and num2 are numbers
    # Add them
    # Return the sum
 ```
Note the `:raises:`.

The steps involved in this are: 

 1. Modify our codestyle to say that we need to add that
 2. Add that to every function which throws an error.

**Comment by abit2** [comment]
@AbdealiJK thanks got it

**Comment by sils1297** [comment]
Removing difficulty label, it is misleading. This bug won't be solved without quite an amount of work - although it's trivial work it's an amount.

**Comment by Adrianzatreanu** [comment]
Hey @abit2 you still working on this?

**Comment by Adrianzatreanu** [comment]
Unassigning due to inactivity. @abit2 you can always find us on https://gitter.im/coala-analyzer/coala if you need any kind of help!

**Comment by Makman2** [comment]
I think we are trying this as good as possible now.
