### ISSUE TITLE
Improve emphasis of material in Newcomer's Guide

### ISSUE THREAD

**Issue by arvind-iyer** [coala/coala#3704]
There are too many "Notes" and "See Also" blocks all using the same pattern that subliminally make one(or atleast me) to just scroll past all of them. 

Couple of ideas:
* Multipage guide (navbar, index/contents links on side so people can jump to page
* Different color schemes for different types of blocks used currently
* at least changing notes to important or something that indicates urgency/importance

**Comment by arvind-iyer** [comment]
@sims1253

**Comment by sims1253** [comment]
thank you :)

**Comment by sils** [comment]
CC @Adrianzatreanu , docs lead

**Comment by yash-nisar** [comment]
This has been solved IMO, check http://api.coala.io/en/latest/Developers/Newcomers_Guide.html. Regarding the links part on the side of the page, a separate issue has been opened. I think this can be closed.

**Comment by kriti21** [comment]
Is this issue available? I would like to work on it.

**Comment by Makman2** [comment]
@kriti21 please check-up @yash-nisar's comment :+1:

**Comment by kriti21** [comment]
Let me break the task needed here and my queries also. Please provide your guidance @arvind-iyer @yash-nisar @Makman2 
1) The newcomer guide is still contained in a single page. Should I make it a multi page document even though the links are present to jump to the required section?
2) Please suggest the color scheme that should be followed to differentiate Notes and See Also blocks.
3) For notes, IMO tags like important and general-help would be sufficient.

**Comment by Makman2** [comment]
> The newcomer guide is still contained in a single page. Should I make it a multi page document even though the links are present to jump to the required section?

In that case imo we can keep it in a single document.

> Please suggest the color scheme that should be followed to differentiate Notes and See Also blocks.

What about something like:
- Very important -> red
- Normally important / caution / warning -> yellow
- Note and See Also -> Blue (like it is now I believe)

> For notes, IMO tags like important and general-help would be sufficient. Any other that you suggest?

"general-help" should be called "note" ;) But not that I can at least think of, please introduce as many as necessary / making sense :)
