### ISSUE TITLE
Add CSSLint installation to circleci

### ISSUE THREAD

**Issue by sils** [coala/coala#3707]
it's already happening in travis which we can't rely on ATM so we need to add this to the circle yml as well.

**Comment by damngamerz** [comment]
@sils I would like to work on this issue.So, basically i have to add a dependency in circle.yml?

**Comment by sils** [comment]
yes

**Comment by sils** [comment]
then make sure that the coala build step in the circle ci doesn't show the error it does right now anymore, that's the goal
