### ISSUE TITLE
Bear.check_prerequisites should support multiple ways to obtain an executable/package

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3713]
bear REQUIREMENTS is a `set` used by `coalib.bears.Bear.Bear.check_prerequisites` to check that all dependencies are available.

`Bear.check_prerequisites` requires that they are all 'installed'.

In addition to problems like https://github.com/coala/coala/issues/3712 , it doesnt allow a Bear to define that there are multiple ways that an executable or package could be obtained.

https://gitlab.com/coala/package_manager/issues/27 is one viable solution for this.

**Comment by jayvdb** [comment]
For our current needs, we rarely need multiple requirements.
From memory,..
pyyaml is the main case of needing two different requirements, as it is combined with an external linter written in another language.
The clang bears also require an external lib, a python wrapper, and then one also needs an additional python package.
There are also a few bears that need several requirements in one package manager.

One very important take away from the above is that defining REQUIREMENTS as a set is not ideal.
The external lib should to be installed before the python wrapper, and for similar reasons it is better to check that the external lib exists before the python wrapper, as the latter installs even if the external lib is missing. For this, a list would be better than a set.

Also as all of the items in REQUIREMENTS are needed, the user should be informed of all missing requirements, instead of only the first.

There is also a perf problem with multiple packages in the same package manager being queried individually, instead of as a batch.

**Comment by jayvdb** [comment]
A very quick solution is for REQUIREMENTS to be either a set or a list. If it is a set, only one of the members is required; a list requires them all, in the given order.

Also if we add pyyaml as a core requirement of coala-bears, it becomes implicitly available for all bears.

Finally we can create a MultiNpmRequirement for the bears which need multiple npm packages, which would do a more efficient check.

**Comment by sils** [comment]
@jayvdb valid points, in addition we have the ORring of reqs which is unsupported yet - maybe we could make a very small cEP defining this completely for those cases? Might help getting a clear plan before starting to code and waste time on things that may not work out conceptually.

**Comment by jayvdb** [comment]
Or'ing can be done using https://gitlab.com/coala/package_manager/issues/27

**Comment by jayvdb** [comment]
This is being done in package_manager.
