### ISSUE TITLE
Add git cherry-pick in Developer's Guide

### ISSUE THREAD

**Issue by Mariatta** [coala/coala#3720]
We need to provide guidance on how to cherry-pick changes.
It should become part of the developer's guide under git basics.

**Comment by Mixih** [comment]
Hmm, it's really more of a maintainer usecase that general users will not find much use of(unless they need to move things cross branch). It might be better to just link a guide.

**Comment by Mariatta** [comment]
Since developers might one day become a maintainer, maybe it's still worth documenting :thinking: ?
Or maybe there should be a separate Maintainer's Guide :)

**Comment by ashwini0529** [comment]
Separate maintainers guide sounds good. @Mariatta

**Comment by Mariatta** [comment]
Ok I will close this and create another issue about creating Maintainer's Guide :)
