### ISSUE TITLE
Change Fixes to Closes in Writing_Good_Commits.rst

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3737]
I have noticed that a lot of newcomers, without reading the details on https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst directly copy the format of the commit given in the example. However, most of the issues resolved are not bugs for which `Closes` should be used. I think we should change `Fixes` to `Closes` given in the examples on https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst so that even if the format of the commit is copied, we are good. :)
difficulty/newcomer

What are your opinions @Adrianzatreanu @Mariatta ?

**Comment by Nosferatul** [comment]
We should explain why we use Fixes/Closes

**Comment by prateeksingh0001** [comment]
Everytime I repush my code, for the PR, I face a certain error "Shortlog of HEAD commit does not match given regex: ([^:]|[^:]+[^ ]: [A-Z0-9].*)" and I am not able to figure out as to how to overcome it. I need help for that.
