### ISSUE TITLE
coala exits with 0 when bears do not fulfill all requirements

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#3749]
This makes CI look fine even though bears could not run and raised according `[ERROR]` messages. Just look at https://travis-ci.org/OpenNetworkingFoundation/CENTENNIAL/jobs/202208913

```
$ coala --ci
Executing section Default...
Executing section javascript...
[ERROR][11:20:25] The bear ESLintBear does not fulfill all requirements. 'eslint' is not installed.
Executing section yang...
The command "coala --ci" exited with 0.
Done. Your build exited with 0.
```

@sils

**Comment by sils** [comment]
duplicate of https://github.com/coala/coala/issues/3087 , patches very welcome!
