### ISSUE TITLE
Testing_Bears.rst: Enclose result in []

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3770]
In Example 3 on https://github.com/coala/coala/blob/master/docs/Developers/Testing_Bears.rst, the expected result(list) is passed as a parameter to `self.check_results()`. The expected result ie. `Result.from_values()` is a list and therefore it should be enclosed in `[]`
difficulty/newcomer

**Comment by dristybutola** [comment]
@yash-nisar  I think ` Result.from_values(["TooManyLinesBear",
                                   "Too many lines"
                                   settings={'max_number_of_lines': int=20}])) `  
                       should have  a comma  after the `"Too many lines"`?

**Comment by yash-nisar** [comment]
Yes, absolutely @dristybutola
