### ISSUE TITLE
Testing_Bears.rst: Properly format "Understanding through examples"

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3774]
Inside section `Understanding through examples`:

- Inside code example:
  - Enclose `max_number_of_lines` in double backticks instead of double quotes
    > Detects if a file has more than "max_number_of_lines" lines

  - > `if(len(file)>max_number_of_lines):`

    improve by adding spaces and remove redundant braces:

    `if len(file) > max_number_of_lines:`

  - > Detects if a file has more than "max_number_of_lines" lines

    Add a period at end of sentence.

  - > :param max_number_of_lines    Maximum number of lines to be
                                      allowed for a file. Default is 10.

    Properly format:
    - Add a colon after `max_number_of_lines`
    - Adjust layout, either
      ```
      :param max_number_of_lines: Maximum number of lines to be
                                  allowed for a file. Default is 10.
      ```
      or
      ```
      :param max_number_of_lines:
          Maximum number of lines to be allowed for a file. Default is 10.
      ```

  - > `yield Result(self, "Too many lines")`

    Use single quotes instead of double quotes.

**Comment by nealkarpe** [comment]
@Makman2 Hi! Since this issue has been inactive for quite some time, can I take it up?

**Comment by Makman2** [comment]
Haven't you already done a newcomer issue? ;)

**Comment by Makman2** [comment]
Anyway, unassigning due to inactivity.

**Comment by zhongLxyz** [comment]
Hi, if no one is assigned to this yet can I take this up?

**Comment by Makman2** [comment]
@zhongLxyz please accept the org invitation, then you can use `corobo` on the gitter channel to assign yourself to issues :)

**Comment by zhongLxyz** [comment]
Thank you, I will get started on this issue :)
