### ISSUE TITLE
Diff: deletion stats can be incorrect

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3782]
Since out of range deletions are allowed, the stats that will be created are incorrect
```py
In [1]: from coalib.results.Diff import Diff

In [2]: a = Diff(['1', '2'])

In [3]: a.delete_lines(2,10)

In [4]: a.modified
Out[4]: ['1']

In [5]: a.stats()
Out[5]: (0, 9)
```

Is this an intended behavior?

**Comment by Makman2** [comment]
hm looks indeed wrong...

**Comment by Techievena** [comment]
Should we allow out of range deletion or not?

**Comment by Techievena** [comment]
Should out of range deletion be allowed?

**Comment by meetmangukiya** [comment]
No, it shouldn't be, thats what this issue is about

**Comment by Techievena** [comment]
No I was bit confused about if `file_list` contains fragment of a file. Nvm figured out I was wrong. :sweat_smile:
