### ISSUE TITLE
CI: Avoid installing coala twice (latest PR + latest pre-release)

### ISSUE THREAD

**Issue by Makman2** [coala/coala#3786]
There were recent problems with documentation generation which exposed another coala installation in the CI that is not installed from the submitted PR, but is the latest pre-release. We should avoid it.

**Comment by jayvdb** [comment]
For this repo, does the docs depend on `coala-bears`?

If not, then CI can run `python setup.py docs` before running `pip install coala-bears...`

**Comment by Makman2** [comment]
Shouldn't depend on `coala-bears`^^ so we can just move the command or let https://github.com/coala/coala/issues/3785 fix the problem so `python3 setup.py docs` is independent from the installation.

So seems we can't really avoid the build as we need `coala-bears`.

**Comment by jayvdb** [comment]
Slightly left field, on a build on my fork of coala-bears, I added dependency "coala>=0.10.0.dev20170302".

At the moment https://pypi.python.org/pypi/coala lists coala 0.10.0.dev20170301175533 as the most recent.

So "coala>=0.10.0.dev20170302" should fail, as it cant be satisfied.

Instead, [we see](https://travis-ci.org/jayvdb/coala-bears/jobs/206699958) pip ignoring that quite happily. 

```
Collecting coala>=0.10.0.dev20170302 (from -r requirements.txt (line 3))
  Using cached coala-0.10.0-py34.py35.py36-none-any.whl
```

Surely that is not correct?  Am I forgetting something?

Looking at https://pypi.python.org/packages/e5/4e/496c6dd3fda4856e7fa97e50d6febafc2401fc115b5173cd6d8aea3b4dcd/coala-0.10.0.dev20170301175533-py34.py35.py36-none-any.whl#md5=d659e1df564be5cc406f0476e3cc173e , its METADATA includes `Version: 0.10.0.dev20170301175533`

Presumably other recent uploads of pypi also have similar version identifiers, so how is the cache ending up with a wheel which is able to satisfy "coala>=0.10.0.dev20170302" ?

**Comment by jayvdb** [comment]
Oh, ... 0.10 is released.  We need to bump the version to 0.11 .

**Comment by jayvdb** [comment]
As a bit better record, here is what was happening:

https://travis-ci.org/coala/coala/jobs/201214759

```
$ pip install ./dist/coala-*.whl
...
Processing ./dist/coala-0.10.0.dev99999999999999-py34.py35.py36-none-any.whl
...
Successfully installed coala-0.10.0.dev99999999999999

$ pip install coala-bears[alldeps] --pre -U
Collecting coala-bears[alldeps]
  Using cached coala_bears-0.10.0-py34.py35.py36-none-any.whl

Collecting coala~=0.10.0 (from coala-bears[alldeps])
  Using cached coala-0.10.0-py34.py35.py36-none-any.whl
...
  Found existing installation: coala 0.10.0.dev99999999999999
    Uninstalling coala-0.10.0.dev99999999999999:
      Successfully uninstalled coala-0.10.0.dev99999999999999
...
Successfully installed ... cmakelint-1.3.4.1 coala-0.10.0 coala-bears-0.10.0 cppclean-0.12 ...
```

Now

```
$ pip install ./dist/coala-*.whl
...
Processing ./dist/coala-0.11.0.dev99999999999999-py34.py35.py36-none-any.whl
...
Successfully installed coala-0.11.0.dev99999999999999

$ pip install coala-bears[alldeps] --pre -U
Collecting coala-bears[alldeps]
...
  Downloading coala_bears-0.11.0.dev20170409112734-py34.py35.py36-none-any.whl (171kB)
    100% ... 174kB 5.6MB/s 

Successfully installed ... cmakelint-1.3.4.1 coala-bears-0.11.0.dev20170409112734 cppclean-0.12 ...
```
coala isnt installed

This is fixed, and the culprit was very likely to https://github.com/coala/coala/issues/3825 , but the GitHub logs are hard to find to verify that it was that commit when coala didnt need to be installed a second time.
