### ISSUE TITLE
Diff: Implement new property that indicates whether actual changes exist

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3790]
EDIT (by @Makman2):
It's useful to check whether a diff has actually changes in it, and currently it can be only checked like this:
```python
if self.modified != self._file:
    ...
```
which is ugly because `self._file` is protected.
A property should be introduced, `Diff.has_changes` or `Diff.is_modified` (or similar), which indicates if there are actually changes.

**Comment by meetmangukiya** [comment]
In a bear, I was able to propose a result like this
```
def run(self, filename, file):
    diff = Diff(file)
    line = file[2]
    diff.delete_line(3)
    diff.add_line(3, line)
    # diff.stats = (1, 1)
    yield result(self, 'bug!', diffs = {filename: diff})
```

coala proposed the patch to me..
Show patch action didn't show anything as expected... but since the stats are not 0, 0 it showed the result like..
Not sure where the bug is, will dig deep...

Example
```
|    | [NORMAL] PyImportSortBear:
|    | Imports can be sorted.
|    | +11 -11 in /home/phoenista/Desktop/ghubby/coala/coala-bears/test.py
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Apply patch
|    |  3: Show patch
|    |  4: Add ignore comment
|    | Enter number (Ctrl-D to exit): 3
|    | Displayed patch successfully.
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Apply patch
|    |  3: Show patch
|    |  4: Add ignore comment
|    | Enter number (Ctrl-D to exit): 2
|    | Patch applied successfully.
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 

```

**Comment by meetmangukiya** [comment]
I had to use a dirty workaround, like `if diff.modified != diff._file` to propose the result for now..

**Comment by Makman2** [comment]
why `False`? `diff.modified` contains the changed file, so if there are no changes, `diff.modified` is equal to `diff._file`.

**Comment by meetmangukiya** [comment]
Actually, that is a different point, but https://github.com/coala/coala/issues/3790#issuecomment-282550148 this sure seems like a bug..Change the title if you feel so :)

**Comment by meetmangukiya** [comment]
> diff.modified contains the changed file, so if there are no changes, diff.modified is equal to diff._file

Exactly, diff.modified should be populated only if there **is** a modification IMO

**Comment by Makman2** [comment]
`diff.modified` contains the modified version of the file. So it's populated in the beginning with `self._file` itself. Imo this makes sense :O

**Comment by meetmangukiya** [comment]
@Makman2 want to close this? 
Also https://github.com/coala/coala/issues/3790#issuecomment-282933631 needs a response ?

**Comment by Makman2** [comment]
I think this issue is about a bug, not about returning False in `self.modified` if diff is not modified. Wondering why you entitled it like this :O

Anyway, why are the stats so weird? Is the file you provide the bear at least 3 lines long?

**Comment by meetmangukiya** [comment]
Actually that was meant as an example, and I don't remember where I spotted it, but the cause of bug is pretty clear, so I don't think it is necessary.

**Comment by meetmangukiya** [comment]
The bug is:
Say if I delete a line and add the same line, then the diff is actually considered a diff and a patch is generated, though applying it would not change the file. 

To avoid this is in PyImportSortBear https://github.com/coala/coala-bears/pull/1356 I had to do a check I.e. `self.modified != self._file` I proposed that we set self.modified as false is `self.modifed == self._file`, since this check is ugly, since we are accessing a variable starting with `_` meant for internal use only. This was meant as a possible solution to the issue, but the bug might as well be in the result actions.

I hope it is clear now, I'll change the title later (on mobile while writing this comment). Comment if still unclear :)

**Comment by Makman2** [comment]
Ah alright understood. So I think best is if we provide "public" access officially for `self._file` so you can check like this.

I was wondering just now btw why `Linter.py` never had such problems when generating patches from the corrected version. And it seems that `split_diff` does compensate this automatically.

**Comment by Makman2** [comment]
Maybe even better is a property for that kind of check.

Edited title accordingly + issue description.

**Comment by Makman2** [comment]
@meetmangukiya opinions? If you agree, we could release this issue and mark it as newcomer :+1:

**Comment by meetmangukiya** [comment]
Yeah, sounds good :+1:

**Comment by Makman2** [comment]
maybe `difficulty/low` as writing tests required :)

**Comment by Makman2** [comment]
I've just seen that `Diff` implements `__bool__` which seem to just do this. CC @meetmangukiya

**Comment by meetmangukiya** [comment]
Oh.. :( it is already merged.

**Comment by Makman2** [comment]
See https://github.com/coala/coala/issues/4178 for removing the duplicated functionality again.
