### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by yashLadha** [coala/coala#3810]
Whenever i try to launch the CLI it says like this.

> coala --show-bears --filter-by-language Python ?[33m[WARNING]?[0m[18:18:24] 'cli' is an internally reserved section name. It may have been generated into your coafile while running coala with--save. The settings in that section will inherit implicitly to all sections as defaults just like CLI args do.Please cha nge the name of that section in your coafile to avoid any unexpected behavior.?[0m ?[33m[WARNING]?[0m[18:18:24] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inher it all settings from 'all'.?[0m ?[31m[ERROR]?[0m[18:18:24] There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or runningpip install "coala~=0.10.0"`. Be aware that the latter
> solution might break other python packages that depend on the currently installed version.?[0m
> ?[34m[INFO]?[0m[18:18:24] Exception was:
> Traceback (most recent call last): File "c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg\coalib\coala.py", line 48, in main
> args.filter_by_language, log_printer)
> File "c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg\coalib\settings\ConfigurationGathering.py", line 331, in get_filtered_bears
> sections, log_printer)
> File "c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg\coalib\collecting\Collectors.py", line 269, in collect_all_bears_from_sections
> bear_dirs = sections[section].bear_dirs()
> File "c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg\coalib\settings\Section.py", line 117, in bear_dirs
> for bear_dir in collect_registered_bears_dirs('coalabears')]
> File "c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg\coalib\collecting\Collectors.py", line 307, in collect_registered_bears_dirs
> registered_package = ep.load()
> File "C:\Users\Yash Ladha\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources_init_.py", line 2301, in load
> self.require(*args, **kwargs)
> File "C:\Users\Yash Ladha\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources_init_.py", line 2324, in require
> items = working_set.resolve(reqs, env, installer, extras=self.extras)
> File "C:\Users\Yash Ladha\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources_init_.py", line 859, in resolve
> raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (coala 0.10.0.dev99999999999999 (c:\users\yash ladha\appdata\local\programs\python\python35\lib\site-packages\coala-0.10.0.dev99999999999999-py3.5.egg), Requirement.parse('coala~=0.10.0'))?[0m

**Comment by Techievena** [comment]
@yashLadha Have you asked about this in gitter channel?

**Comment by Makman2** [comment]
@yashLadha From what commit is the coala installation? Your coala-bears version? Any other modifications to coala? Maybe other installed coala versions which are grabbed instead?

**Comment by Makman2** [comment]
@yashLadha issue resolved? :)

**Comment by yashLadha** [comment]
Yes indeed it is. Thanks to community
