### ISSUE TITLE
Mention "acking" a commit is not as important in newcomer docs 

### ISSUE THREAD

**Issue by AGZ98** [coala/coala#3815]
Since some newcomers ack the same commit over and over again, it might be a good idea to mention that it's not as important in the newcomer's guide.

**Comment by jayvdb** [comment]
Can you give an example PR where this happened?

We definitely need an `ack`, but only one per commit, or even one per PR.

**Comment by yashLadha** [comment]
Is it pushing same commit over and over again? (what you mean by ack)

**Comment by yashLadha** [comment]
@AGZ98 i can work upon this. It would be great if you could specify where to Work.
