### ISSUE TITLE
Writing_Linter_Bears.rst: Add link to the @linter decorator

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3819]
While writing a bear, I wanted to look at the `@linter` decorator. I had to type it in the search box. It would be nice if we add http://api.coala.io/en/latest/coalib.bearlib.abstractions.html#module-coalib.bearlib.abstractions.Linter to the word `@linter` in the first paragraph of the file.
difficulty/newcomer
area/documentation

**Comment by shivam207** [comment]
I have created a pull request for this
#3836
