### ISSUE TITLE
Section.py: Remove redundant lines

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3822]
https://github.com/coala/coala/blob/master/coalib/settings/Section.py#L210-L213
The given lines need to be removed from the nested `if` block.
```
res.to_append = False
return res
```
difficulty/newcomer

**Comment by chaitaliSaini** [comment]
I would like to solve this issue.

**Comment by yash-nisar** [comment]
You can now assign issue to yourselves by using our very favourite cobot, with the command being `cobot assign full-issue-url`. Type `cobot help` for more details on our gitter channel. Please don't work on an issue without assignment.

**Comment by yashLadha** [comment]
cobot assign https://github.com/coala/coala/issues/3822

**Comment by yashLadha** [comment]
Can u please review my PR ?

**Comment by jayvdb** [comment]
@yashLadha , no.  I have closed https://github.com/coala/coala/pull/3828 .  You didn't follow the newcomers guide when you prepared that PR, so that PR has too many mistakes.  Hopefully you follow the newcomers guide, and your next PR is much better.

**Comment by jack17529** [comment]
@yash-nisar  assign me this issue it's very easy.

**Comment by yashLadha** [comment]
I had already implemented this. And it is also ack it

**Comment by yash-nisar** [comment]
@jack17529 This issue is already assigned to @yashLadha . Please find some other issue that is unassigned. :)
