### ISSUE TITLE
aspects: Typo error for classnames in pydoc

### ISSUE THREAD

**Issue by Techievena** [coala/coala#3827]
`:class:coalib.bearlib.aspectclasses.Taste.` This should be something like `:class:coalib.bearlib.aspects.Taste.` . Also replace similar instances of aspectclasses with aspects in the pydoc.

**Comment by jayvdb** [comment]
Is this newcomer or low @Techievena ?

**Comment by Gouenji** [comment]
can i take this

**Comment by Techievena** [comment]
It must be a newcomer. Only typo has to be fixed. :smile: @jayvdb

**Comment by yash-nisar** [comment]
difficulty/newcomer

**Comment by jayvdb** [comment]
@Gouenji, it is already assigned ; see above.

> dushyantRathore was assigned by coala-bot 11 hours ago
