### ISSUE TITLE
Writing_Linter_Bears.rst: Replace double quotes with single quotes

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3832]
File: https://github.com/coala/coala/blob/master/docs/Developers/Writing_Linter_Bears.rst
Line: `LANGUAGES = {"Python", "Python 2", "Python 3"}`
`"` should be replaced by `'`
difficulty/newcomer
area/documentation

**Comment by anu0012** [comment]
Can I take this issue ?

**Comment by sagark123** [comment]
Can I work on this???I am a newcomer

**Comment by Makman2** [comment]
@sagark123 the issue is already assigned. Please read our newcomer guides on how to contribute :+1:

**Comment by Ananthavijay** [comment]
Can I work on this issue?

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Makman2** [comment]
@Ananthavijay you already have a newcomer issue assigned, please pick a `difficulty/low` one ;)

**Comment by L-KID** [comment]
Hi, can I work on this issue?

**Comment by Makman2** [comment]
Please accept the org invite, then you can be assigned ;)

**Comment by L-KID** [comment]
org invite accepted
