### ISSUE TITLE
Git Basics: Mention Xcode for MacOS

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3843]
Following on from https://github.com/coala/coala/issues/3256 , the macos note should mention that git may be installed via Xcode.

https://www.atlassian.com/git/tutorials/install-git#mac-os-x

Xcode has other useful tools for developers, so it should be a preferred and recommended way to get these tools.

**Comment by Rddhima-R** [comment]
I would like to work on this issue

**Comment by ishanSrt** [comment]
Worth mentioning, the entire Xcode is not needed for the commands to work. Xcode command line tools does it all.
