### ISSUE TITLE
Detect unsupported clang and report a useful error message

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3847]
If the wrong clang version is installed, the error message is like "Please ensure that your python bindings are compatible with your libclang.so version" , which doesnt help the average user.

In addition to the exception message provided by the libclang python wrapper, we need a message which says something like "coala requires clang 3.4"

**Comment by yashLadha** [comment]
I can work upon this @jayvdb

**Comment by yashLadha** [comment]
Is the version checking should be os specific, or we are targeting only linux users.

**Comment by yashLadha** [comment]
How about showing user that the machine doesn't have necessary clang version instead of showing the whole stack trace which is not meant for an average user.

**Comment by proishan11** [comment]
Hello! @jayvdb . Does the code here <https://github.com/coala/coala-bears/blob/master/bears/c_languages/ClangBear.py#L11-L21> need to be changed?

**Comment by RaiVaibhav** [comment]
@proishan11 ping :smile:

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by nvzard** [comment]
https://github.com/coala/coala/blob/master/coalib/results/Diff.py#L159
Is this the part where I should be working on?

**Comment by jayvdb** [comment]
@nvzard , you've hit a slightly different problem (https://github.com/coala/coala/issues/3182) in the same location , but the error message is equally as bad and needs improvement (which is what this bug is about)  ;-)

the easiest approach is in `Diff.from_clang_fixit`, but there is also `SourceRange.from_clang_range`.  Catch the exception, and then emit a useful error message, and then re-raise the exception.

Another approach is to provide a handler in the bears.  I've been quite keen on moving this clang stuff into a new global bear which acts as a dependency (see BEAR_DEPS) for all the clang bears, so the core coala doesnt need to rely on clang.

```
$ git grep from_clang
bears/c_languages/ClangBear.py:            affected_code = tuple(SourceRange.from_clang_range(range)
bears/c_languages/ClangBear.py:                diffs = {filename: Diff.from_clang_fixit(fixits[0], file)}
bears/c_languages/ClangComplexityBear.py:                affected_code = (SourceRange.from_clang_range(cursor.extent),)
```
