### ISSUE TITLE
Developers/Writing_Tests.rst: unwanted quotes appear in text

### ISSUE THREAD

**Issue by blooops** [coala/coala#3855]
Unwanted back-quotes appear in the file due to the ** and the `` tags being used together. Link https://github.com/coala/coala/blob/master/docs/Developers/Writing_Tests.rst#actually-writing-a-test
Have a look at the emboldened setUp() and tearDown(). I don't think that was meant to appear that way.

**Comment by jayvdb** [comment]
@djokester, please fix your PR otherwise it will be closed because it does not comply with http://coala.io/commit .

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Saumay-Agrawal** [comment]
Hey! I would like to work on this issue. Can you please assign this to me?

**Comment by JoeSiew** [comment]
Hi, Can you please assign me to this issue? I would like to work on it

**Comment by jayvdb** [comment]
@JoeSiew , you need to accept the invitation to join @coala first.

**Comment by jayvdb** [comment]
was fixed
