### ISSUE TITLE
Testing_Bears.rst: Move settings out of the result list

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3859]
In example 3, http://api.coala.io/en/latest/Developers/Testing_Bears.html, the `settings` param is inside the `result` list. It is passed as a separate param to `check_results` and therefore should be moved out of the list.
difficulty/newcomer
area/documentation

**Comment by LongntLe** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
Please check out our newcomer guide
