### ISSUE TITLE
Testing_Bears.rst: Change settings snippet

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#3873]
Change `settings={'max_number_of_lines': int=20}` to `settings={'max_number_of_lines': 20}`
Can be done after https://github.com/coala/coala/issues/3859 is merged.
difficulty/newcomer
area/documentation
importance/medium

**Comment by acashmkj** [comment]
@yash-nisar Can this issue be assigned to me?

**Comment by aptrishu** [comment]
I have asked @roydipayan003 to update his PR, we'll unassign him if he doesnt respond. Meanwhile you can search for a different issue. :)

**Comment by acashmkj** [comment]
@aptrishu can i work on this issue if @roydipayan003 is not working on this issue

**Comment by Makman2** [comment]
Unassigning due to inactivity

**Comment by mohitkyadav** [comment]
Hi!, @Makman2 @aptrishu can I work on this?
