### ISSUE TITLE
Aspects/taste.py : typo in inline documentation

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala#3883]
Typo in the line
No need to specify name **an** cast type:

difficulty/newcomer

**Comment by Thanos983** [comment]
Just checking, the correction should be 'name **a** cast type' right ?

**Comment by satwikkansal** [comment]
@Thanos983 you'll easily come to know when you see the file :wink: 
```
No need to specify name an cast type:

        The taste name is defined by the taste's attribute name in an
        aspectclass definition.

        The value cast type is defined via indexing on class level.
```

**Comment by Techievena** [comment]
@satwikkansal I have already opened up an issue for this :smile:

**Comment by satwikkansal** [comment]
@Techievena Right, my bad :disappointed: 
@Thanos983 could you please try some other newcomer issue. Sorry for the inconvenience :(

**Comment by Thanos983** [comment]
@satwikkansal Don't worry about that :)

**Comment by jayvdb** [comment]
Dup
