### ISSUE TITLE
Fail to install and py.test on docker environment.

### ISSUE THREAD

**Issue by corona10** [coala/coala#3906]
When I try to install by `python setup.py install`, it is failed with this message.
`UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 15224: ordinal not in range(128)`
Also, the same happening when I try to run unit test on local.
It needs to be fixed.

**Comment by jayvdb** [comment]
Which docker image are you using?

**Comment by corona10** [comment]
@jayvdb I am using ubuntu by `docker pull ubuntu:latest`.

**Comment by Makman2** [comment]
Confirmed :+1:

Launch docker: `docker run -it ubuntu:latest bash`
Inside docker:
```
root@8fcd31b218fc:/# apt-get update
root@8fcd31b218fc:/# apt-get install -y git python3 python3-pip
root@8fcd31b218fc:/# git clone https://github.com/coala/coala
root@8fcd31b218fc:/# cd coala/
root@8fcd31b218fc:/coala# pip3 install -r requirements -r test-requirements.txt
root@8fcd31b218fc:/coala# python3 setup.py install
```

**Comment by Makman2** [comment]
That even happens on latest `fedora` image...

**Comment by corona10** [comment]
@Makman2 
I wrote little description why this happening on https://github.com/coala/coala/pull/3908.
It looks like that coala expected utf-8 setting locale on [this side](https://github.com/coala/coala/blob/master/setup.py#L18).
But unfortunately, They do not raise (ValueError, UnicodeError) but just return
`(None, None)`. 
This is why this issue is happening. Also, for the unit tests, there are some codes which are reading `utf-8` files. so it should be set locale before running unit tests.
