### ISSUE TITLE
tests/aspects: Closing braces must be in same line as the last line of block/condition

### ISSUE THREAD

**Issue by Techievena** [coala/coala#3931]
There are instances of 
```
if (
    condition
   ):
```
whereas coala always follows this codestyle
```
if (
    condition):
```

**Comment by RJ722** [comment]
Hi @Techievena 
Can you please help me out here as I am not able to find any such occurence. I ran:
```bash
grep 'if \(' -r *
```
(There were several results, but none of them violated the style guideline.)
```bash
grep 'if \\' -r *
```
(There were no results.)
What am I doing wrong? Thanks!

**Comment by RJ722** [comment]
Hi @Techievena 
Can you please help me out here as I am not able to find any such occurence. I ran:
```bash
grep 'if \(' -r *
```
(There were several results, but none of them violated the style guideline and none of them was in tests/aspects.)
```bash
grep 'if \\' -r *
```
(There were no results.)
What am I doing wrong? Thanks!

**Comment by Techievena** [comment]
Try with `git grep ' ):'` instead :wink:

**Comment by RJ722** [comment]
Thanks @Techievena 

Tried it, but nothing in there! :disappointed:

**Comment by Techievena** [comment]
Try it inside coala repository

**Comment by RJ722** [comment]
Sorry, had some confusion: added a space after the colon!
Thank you  @Techievena
