### ISSUE TITLE
Missing function in coalib/misc/Shell.py

### ISSUE THREAD

**Issue by madhukar01** [coala/coala#3940]
Fucntion call_without_output missing in shell.py 
Which is needed fot installation of cib
` File "/home/helios/coala_env/lib/python3.5/site-packages/coala_package_manager/installation_tool.py", line 29, in <module>
    from coalib.misc.Shell import call_without_output
ImportError: cannot import name 'call_without_output'
`

**Comment by jayvdb** [comment]
The comment later added here is correct

https://github.com/coala/coala/pull/3942#issuecomment-288910998

> Since cib is broken and fixing this issue will not be solving the problem, I'm closing this PR

This issue should also be closed.
