### ISSUE TITLE
deprecate_settings doesn't return __doc__ of the wrapping function

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3946]
Try:
```py
from bears.python.PyImportSortBear import PyImportSortBear
from coalib.settings.Section import Section
from queue import Queue

bear = PyImportSortBear(Section(''), Queue())
bear.__doc__ # is '', doc string is lost

from bears.python.PEP8NotebookBear import PEP8NotebookBear
bear = PEP8NotebookBear(Section(''), Queue())
bear.__doc__ # this has doc string
```

So this mostly confirms it is the decorator

**Comment by Makman2** [comment]
This is bad!

**Comment by all3fox** [comment]
Hey @Flap-Py, what progress have you made so far? Are you stuck/do you need help?

**Comment by Flap-Py** [comment]
@all3fox Sorry I got involved in my GSOC proposal. And thanks for your way to isolate the problem :smile: that was really helpful for me in getting a solution.
So I came up with a fix for the bug for the following [link](http://stackoverflow.com/questions/1782843/python-decorator-handling-docstrings#answer-1782888)
 @meetmangukiya check it out if its fine. I am creating a PR too. Let me know if something is wrong.

**Comment by yash-nisar** [comment]
@jayvdb I'm thinking of getting this opened again and undoing https://github.com/coala/coala/commit/017bcfc2 so we can get rid of [this](https://travis-ci.org/coala/coala-bears/jobs/215711108) bug introduced in coala-bears. I need your approval.

**Comment by jayvdb** [comment]
I would rather than this, and https://github.com/coala/coala/issues/3786, are fixed quickly, but if that doesnt happen, I agree that undoing 017bcfc is necessary

**Comment by meetmangukiya** [comment]
That yapf build failure was because of this :/ ?
