### ISSUE TITLE
Appveyor failing because curl doesn't exist

### ISSUE THREAD

**Issue by adtac** [coala/coala#3961]

**Comment by jayvdb** [comment]
Can you provide a log file.
This should be raised upstream.

The `appveyor DownloadFile` is not a good long term solution, which for example as a default timeout of 5 minutes according to https://www.appveyor.com/docs/how-to/download-file/#start-filedownload-cmdlet.

**Comment by adtac** [comment]
We can give a custom timeout (let's just set it to something arbitrarily large like 15 minutes). And if a 25 MB file is taking longer than 5 minutes, then we might as well restart that build (Appveyor has insanely fast internet).

All builds in coala/coala were failing (can't sign into Appveyor for whatever reason right now, but take a look at any of the builds before my build).

**Comment by adtac** [comment]
This is at least a temporary workaround. Obviously curl is a better option, I agree. If they fix it upstream (I didn't actually investigate it for too long - everybody was complaining their tests were failing), we can revert the commit.

**Comment by jayvdb** [comment]
http://help.appveyor.com/discussions/problems/6312-curl-command-not-found - already fixed ages ago.

**Comment by adtac** [comment]
Okay that was fixed three hours ago :D I'll make a new PR using that.

**Comment by jayvdb** [comment]
https://github.com/coala/coala/pull/3965 was the followup fix.
