### ISSUE TITLE
issubaspect()

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#3977]
We need some quick way of checking if an aspect is a subaspect of another aspect, to allow defining bear aspects by some parent, like...

```python
class AspectsBear(Bear, aspects={
    'detect': [CommitMessage],
}
```

... which means that our bear should support all subaspects of `CommitMessage`. Then we need to check if user-requested aspects, like `CommitMessage.Shortlog.ColonExistence`, are subaspects of the defined parent.

So I propose an `issubaspect` function to handle that task. It should basically work like python's builtin `issubclass` function, and also have those important two features:

* It should support aspectclasses as well as their instances as subaspect argument:

```python
>>> issubaspect(ColonExistence, CommitMessage)
True
>>> issubaspect(ColonExistence(shortlog_colon=False), CommitMessage)
True
```

* It should raise an exception if the arguments are no aspectclasses (or the first argument is neither class nor instance) and not just return `False` in that case:

```python
>>> issubaspect(ColonExistence, dict)
TypeError: <class 'dict'> is no aspectclass
```

And according to `issubclass`, every aspect should of course also be a subaspect of itself.

**Comment by Makman2** [comment]
Maybe we implement this function also for each aspect itself, so you can do something like this?
```
CommitMessage.issubaspect(ColonExistence)
```

**Comment by userzimmermann** [comment]
@Makman2 IMO something like `CommitMessage.issubaspect(ColonExistence)` would unnecessarily mess things up and cause confusion, since it is untypical in python and could also be read like check if `CommitMessage` is a subaspect of `ColonExistence`, whereby the argument order in the global function is always clear when you are used to builtin `issubclass`.

**Comment by Makman2** [comment]
@userzimmermann good point. Maybe a different name would work, though you are right. Then we would use different names -> things get more complicated -> user confused :)
