### ISSUE TITLE
DocumentationComment: Remove parameter documentation of language and docstyle parameter

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#3998]
From @SanketDG 
> instead of language and docstyle there is now a docstyle_definition

/cc @SanketDG

**Comment by adamgrieger** [comment]
Hi, I can take this! What should the parameter description for docstyle_definition be?

**Comment by meetmangukiya** [comment]
You can use `cobot assign` to get assigned, you can use `cobot help` to find more info of that command

**Comment by NiklasMM** [comment]
> You can use cobot assign to get assigned, you can use cobot help to find more info of that command

That is in our [Gitter](http://coala.io/chat) channels ;-)
