### ISSUE TITLE
Format the output of CI mode when is used both --format and --ci

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#3999]
https://github.com/coala/coala/pull/3750

**Comment by jayvdb** [comment]
@Nosferatul , isnt this a dup of https://github.com/coala/coala/issues/3154

**Comment by meetmangukiya** [comment]
This issue is about formatting the output of `--ci`

**Comment by sils** [comment]
this is hard to understand. Wrote an explanation on gitter after managing to wrap my head around it, documenting here:

ssentially when you run coala --format it will give you a custom formatted output but it might ask you questions in the beginning; when you run coala --ci you don't get any questions asked. Now this issue requires that coala --ci --format doesn't ask questions and uses the format string output.

**Comment by Nosferatul** [comment]
my bad @sils 😟

**Comment by MariosPanag** [comment]
--format is for continuous integration and it doesnt asky you questions so i guess what you want to implement is that when user gives both arguments then the mode.format() should be executed. Am i right ?
