### ISSUE TITLE
Check for `:` after closes/fixes in commit messages

### ISSUE THREAD

**Issue by RJ722** [coala/coala#4007]
When writing commit messages, the proper format would be to include closes/fixes <link to issue>, but if something like closes/fixes **:**  is written, it should be automatically detected.
An example is #3997

**Comment by supergr35** [comment]
Doesn't this issue belong on the coala-bears repo? I think GitCommitBear is what would check for this.

**Comment by Makman2** [comment]
So you want to forbid references like `Closes: XXXX`? @RJ722 
GitHub supports those, so I don't think this is necessary^^

@supergr35 I think he means our coafile :+1:

**Comment by NiklasMM** [comment]
Yes, but it seems to be at least the un-official convention in coala to not have it there. At least I've seen reviewers ask people to remove it.

**Comment by sils** [comment]
GitHub has not allowed the colon in the past so I required people to not do the colon, also consistency is nice but if both is ok mybe we should just allow both

**Comment by RJ722** [comment]
So, should we close this issue?

**Comment by Makman2** [comment]
Yeah think so, let's orientate on GitHub's features.
