### ISSUE TITLE
--files not following globbing patterns

### ISSUE THREAD

**Issue by vasramc** [coala/coala#4026]
`coala --bears=SpaceConsistencyBear --files=\*[^orig] --save` command should ideally not analyze `orig` files but it does nonetheless.

**Comment by userzimmermann** [comment]
@vasramc @mridubhatnagar Globbing exclusions unfortunately don't work that way :/ In glob syntax `*[^orig]` matches all files that end with either `^`, `o`, `r`, `i`, or `g`. You can define an exclusion list via `[!orig]` but that also only means none of the characters after `!` at a single position

Take a look at http://pubs.opengroup.org/onlinepubs/000095399/utilities/xcu_chap02.html#tag_02_13

We would have to extend globbing syntax...

cc @sils @jayvdb @Makman2 @adhikasp @nemaniarjun @ashwini0529 @kaustubhhiware

**Comment by mridubhatnagar** [comment]
Yes I knew it. Had taken up on this issue yesterday night itself. But I though of doing it 
this way 
coala --bears=SpaceConsistencyBear --files=\*[!orig] --save

**Comment by userzimmermann** [comment]
Hi @mridubhatnagar again :) To continue on https://github.com/coala/coala/issues/4026#issuecomment-299994442 and https://github.com/coala/coala/issues/4025#issuecomment-300245044 : 

`[^orig]` and `[!orig]` don't define sequences, just sets for matching a single character

So `*[!orig]` would also exclude file extensions like `.foo`, `.bar`, `.hi`, or `.log`

**Comment by mridubhatnagar** [comment]
Oh sorry . Saw this comment now. Understood. 
Some other alternative needs to be thought off then.

**Comment by userzimmermann** [comment]
@mridubhatnagar No problem ;) Yes, some alternative might be useful, whereby I still think that the `--ignore` flag is somehow enough

**Comment by mridubhatnagar** [comment]
do you mean as we have mentioned --save similarly we can add --ignore. Which would mean [orig] files are ignored?

coala --bears=SpaceConsistencyBear --files=\*[orig] --ignore

**Comment by mridubhatnagar** [comment]
@userzimmermann  hey what can be done on this one?

**Comment by Makman2** [comment]
I would close this one as invalid, as the glob `\*[^orig]` just means something different than what was expected in the beginning. The observed behaviour is correct.

As globs are very widely used and a common standard, we shouldn't fiddle with them too much. It seems that it's not possible to exclude complete string sequences, see https://stackoverflow.com/questions/20638040/glob-exclude-pattern. We have an `ignore` flag for this purpose :)

We could maybe also allow regular expressions for file-collection which are more powerful, though we would need an efficient glob-like implementation which is quite some work and imo not necessary now. But if you want it, feel free to file an issue :)

**Comment by userzimmermann** [comment]
@mridubhatnagar Regarding https://github.com/coala/coala/issues/4026#issuecomment-300425350 : 

Not that way ;) `--ignore` gets its own patterns, so to ignore `*.orig`, you have to for example:

`coala --bears=SpaceConsistencyBear --files=docs/* --ignore=*.orig`
