### ISSUE TITLE
Add SEE_MORE attribute to the "Writing Native Bears" page

### ISSUE THREAD

**Issue by rohanraju97** [coala/coala#4027]
A new attribute "SEE_MORE" has been recently added to the metadata of bears in coala. That should be mentioned in [this](https://api.coala.io/en/latest/Developers/Writing_Native_Bears.html#other-metadata) page under the "Other Metadata" section.

**Comment by rohanraju97** [comment]
@SanketDG This could be a newcomer issue. We're low on newcomer issues, apparently.

**Comment by SanketDG** [comment]
@rohanraju97 thank you! Just when I needed it!

**Comment by gopalgoel** [comment]
What should be the value of "SEE_MORE" attribute that one should add in the example?

**Comment by SanketDG** [comment]
The `SEE_MORE` attribute should link to the linter home page

**Comment by rohanraju97** [comment]
I think what you're asking is which specific link to add in the docs as an example. I'd say put in a real link to any linter tool of your choice. Maybe Pylint -> https://www.pylint.org/
CC @SanketDG

**Comment by Kaushal2612** [comment]
I want this issue to be assigned to me

**Comment by guptaRk** [comment]
link dijiye

**Comment by LuciferMV** [comment]
please provide me with the link of the page

**Comment by vikramsaha7** [comment]
send link

**Comment by rohanraju97** [comment]
Which page?

**Comment by vikramsaha7** [comment]
this page

**Comment by LuciferMV** [comment]
i mean "writing native bears" page

**Comment by rohanraju97** [comment]
I'm assuming that you want the link to the page that needs to be changed. The link is embedded in the first comment. It's not that hard to find.

**Comment by LuciferMV** [comment]
ok . i got it. Thank you

**Comment by rohanraju97** [comment]
Someone has already been assigned to this issue @LuciferMV . Try finding another newcomer issue?
