### ISSUE TITLE
DocumentationExtraction bug for java docstyle.

### ISSUE THREAD

**Issue by damngamerz** [coala/coala#4029]
DocumentationExtraction works good when java docstyle as given below is used.
```
/**
 * Returns an String that says Hello with the name argument.
 *
 * @param  name the name to which to say hello
 * @return      the concatenated string
 */
```
But if we remove that one space from that mid marker and end marker as follows
```
/**
* Returns an String that says Hello with the name argument.
*
* @param  name the name to which to say hello
* @return      the concatenated string
*/
```
DocumentationExtraction doesn't return anything. We need to throw a nice warning message for the above case.

**Comment by damngamerz** [comment]
CC @SanketDG

**Comment by NiklasMM** [comment]
Right now the documentation extraction functions can only return an identified docstring or None. Do deal with this issue, we should add an error state as a third possibility, when a start marker is found but the others aren't. I'm not sure if raising an Exception or returning some kind of error object is better.
