### ISSUE TITLE
Writing_Good_Commits: Add example for typo fix

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4034]
According to https://github.com/coala/coala/pull/4024#issuecomment-290406601 , we should add another example to https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst , showing a good commit message for fixing a typo in a doc string or comment or similar areas, like in case of https://github.com/coala/coala/pull/4024 : 

```
ConsoleInteraction.print_result: Fix docstring typo

wether --> whether

Fixes https://github.com/coala/coala/issues/4018
```

@sils @meetmangukiya @arjunsinghy96 @HyungKen

**Comment by HyungKen** [comment]
Cobot does not assign. Can you assign?

**Comment by meetmangukiya** [comment]
@HyungKen you already did a newcomer issue, lookout for difficulty/low issues now :)

**Comment by HyungKen** [comment]
Oh yes! I'll try to solve the low step.

**Comment by karansingh1559** [comment]
can anybody assign this issue to me?

**Comment by gopalgoel** [comment]
@karansingh1559 Hey! I see that you are making commits in the master branch of your forked repo. This is not the recommended way. Always create a new branch and make your commits in that branch and send a pull request from that branch. Please read [http://api.coala.io/en/latest/Developers/Newcomers_Guide.html](Newcomer's guide)
