### ISSUE TITLE
Change any occurrences of 'Aspect' or 'Aspects' in doc strings and comments to lowercase

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4039]
According to https://github.com/coala/cEPs/issues/69

@coala/aspects-developers Know any so-called *newcomer* to do this? :)

**Comment by Techievena** [comment]
Why not have a bear for this like the `coalaBear`?

**Comment by karansingh1559** [comment]
Can anybody assign this to me?

**Comment by Techievena** [comment]
Use cobot to assign yourself @karansingh1559

**Comment by karansingh1559** [comment]
A little help here please-- do I have to change all such instances in all files of the entire coala repo?

**Comment by arjunsinghy96** [comment]
@karansingh1559 yes

**Comment by arjunsinghy96** [comment]
You can find them using `git grep`
