### ISSUE TITLE
aspect for the aspectsYEAHBear

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4040]
The new `aspectsYEAHBear` as proposed in https://github.com/coala/coala-bears/issues/1573 based on @Techievena's idea from https://github.com/coala/coala/issues/4039#issuecomment-290886365 needs a new aspect for performing the task of checking that the terms *aspect* and *aspects* are always written lowercase according to https://github.com/coala/cEPs/issues/69

@coala/aspects-developers

**Comment by pratyushprakash** [comment]
So we could have `Spelling` as a sub-aspect of `Semantics` for this?

**Comment by userzimmermann** [comment]
@pratyushprakash Hmm... `Spelling` is not actually a matter of semantics. The combination of words is semantics. But as also @Asnelchristian proposed in https://github.com/coala/coala-bears/issues/1573#issuecomment-290928010 , a `Spelling` subaspect is basically a good idea. And the actual leaf subaspect should IMO be something like `Spelling.aspectsYEAH` :)

@coala/aspects-developers So the question is still open where to put `Spelling` in the aspects tree...

**Comment by adhikasp** [comment]
@userzimmermann I think we need to define some kind of standard on how to construct the aspects tree first ✨ 

IMO, for the time being we can make the current analyze categorization (defined in `can_fix` / `can_detect` metadata in bears) as a direct child of `Root`. So, based on [coalaBear ](https://github.com/coala/bear-docs/blob/master/docs/coalaBear.rst) that have `can_fix = spelling`, I propose `Root.Spelling.aspectsYEAH`.

**Comment by Asnelchristian** [comment]
@adhikasp, actually this is already part of [!cEP-0005](https://github.com/coala/cEPs/blob/master/cEP-0005.md) but instead we have fix_aspects and detect_aspect

**Comment by userzimmermann** [comment]
Yes @adhikasp, `Root.Spelling.aspectsYEAH` should be good for now. We can move `Spelling` to some deeper tree level later if it makes sense...

@coala/aspects-developers So let's create **coalib/bearlib/aspects/Spelling.py**
