### ISSUE TITLE
aspect: Convert string to aspect

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#4058]
In the future, aspect will be defined by user in coafile. But, currently there are no way to change a string (like from coafile) into an aspect object. Something like this:

```python
>>> str_to_aspect('CommitMessage')
<aspectclass 'Root.Metadata.CommitMessage'>
```

There are some design need to be fixed though:
- Do we need the string to be an exact match to the aspect? (`'CommitMessage'` or `'Root.Metadata.CommitMessage`')
  - If we choose the short style string to be enough, what happen if there are 2 or more aspect that have common name? (`Root.Something.CommitMessage` and `Root.Metadata.CommitMessage`).
- Should it be case sensitive?

@coala/aspects-developers 
area/aspect status/needs design

**Comment by userzimmermann** [comment]
@adhikasp Important topic! Good issue :) And I have some very fancy Pythonic idea for this :D 

@coala/aspects-developers Let me surprise you! It's been a while since I created my last PR...
