### ISSUE TITLE
Default action should be the last action taken by the user

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#4059]
Currently the default action is `0: Do nothing`. I think it'll be better to make default action as the last action taken by the user, if none taken, then it'll be default action anyway i.e. do nothing

**Comment by meetmangukiya** [comment]
@Nosferatul I think we need to discuss if we want this or not, so let's wait until we have some inputs herre :)

**Comment by Nosferatul** [comment]
sure :). also, this is part from https://github.com/coala/cEPs/pull/29/files

**Comment by Makman2** [comment]
Hm not sure. We need a voting I think.

**Comment by jayvdb** [comment]
Isnt this determined by a config setting?  Maybe we need a user-friendly way to change this default on the CLI, and change it whilst doing analysis.

**Comment by jayvdb** [comment]
Unassign due to being not ready for assignment and also due to inactivity, etc ;-)

**Comment by Makman2** [comment]
I'm currently not in for this feature. If the default can change, the user needs a bit of time to understand that feature. Also there might be actions that are not available for other results. We could fall back to "Do Nothing" again, but I can imagine the user then really starts to get confused what will be the default action.

**Comment by jayvdb** [comment]
There is probably some cases where repeating the same default action is very logical, but we need specific scenarios for that, or we need a UI project which collects requirements properly, and provides a well considered and accepted large CLI UI change.
