### ISSUE TITLE
Upgrade dependency_management

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4064]
We need all the bugs fixed in dependency_management , as they are blocking other work.

Release blocked on:
- https://gitlab.com/coala/package_manager/merge_requests/31 - Maven
- https://gitlab.com/coala/package_manager/merge_requests/34 - Julia

After that, [Appveyor](https://gitlab.com/coala/package_manager/merge_requests/23) should be easy to merge and then release.

**Comment by jayvdb** [comment]
A closely related blocker : https://github.com/coala/coala/issues/3712

**Comment by damngamerz** [comment]
@jayvdb This can be closed i guess. All issues are being resolved atm.

**Comment by jayvdb** [comment]
https://gitlab.com/coala/package_manager/merge_requests/34 was merged incomplete, with only mocks passing, so that other work could commence.  The follow-up https://gitlab.com/coala/package_manager/issues/56 is not completed, and my MR also has a problem which has an easy fix, which would still be incomplete .. ;-)

The coverage is still low, and includes many mocks, which is not good enough.

Milestone [0.4](https://gitlab.com/coala/package_manager/milestones/1) created.
