### ISSUE TITLE
Readme: Update twitter handle

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#4065]
currently it is set to `coala_analyzer` change it to `coala_io`

**Comment by shubhangiKishore** [comment]
I want to start contributing to Coala. Can I start with this?

**Comment by meetmangukiya** [comment]
@shubhangiKishore Hey, welcome! Accept the organization invite and we can assign you to this issue :)

**Comment by sils** [comment]
as part of the simplification I'll make a PR to remove the handle altogether, rather update the website properly

**Comment by meetmangukiya** [comment]
Website twitter handle looks good :+1:
