### ISSUE TITLE
test_caching_multi_results/test.py includes print at global level

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4071]
Very similar to https://github.com/coala/coala-bears/issues/1594

The sample package in `coala/tests/misc/test_caching_multi_results/test.py` uses `print(...)`.

As shown by https://github.com/coala/coala/issues/4060#issuecomment-292749818, this causes problems with the default test collection of `test*.py`.

This could be solved by removing the `print(..)`, or by renaming the file so it doesnt match `test*.py`.

**Comment by mariaandreicosmin** [comment]
Hello, I'd like to be assigned here.

**Comment by sils** [comment]
Unassigning due to inactivity

**Comment by jayvdb** [comment]
@gureks : @adhikasp was correct, at https://github.com/coala/coala/pull/4480/files#r128207768 , that the `a` should be added.  Otherwise, the `a` is an unused name.

**Comment by pradeepgangwar** [comment]
@jayvdb I would like to finish this up. Can i do it?

**Comment by vddesai1998** [comment]
If @gureks is not active, can anyone assign this issue to me? I am finding difficulty/low issue but most of them are already assigned so I have to ask here in comments :)

**Comment by Makman2** [comment]
@pradeepgangwar since you have a few issues already assigned at coala, I'm assigning @vddesai1998 ;)

**Comment by Makman2** [comment]
Reassigned due to inactivity.
