### ISSUE TITLE
Connect aspectlist with holder bear to match supported languages

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4094]
To be able to also check in `coalib.bearlib.aspects.collections.aspectlist.__contains__` if languages of aspectclass instances match with languages supported by the bear holding the `aspectlist`

@coala/aspects-developers

**Comment by jayvdb** [comment]
This is IMO very wrong.  An aspectlist could contain a list of languages, but it should not depend on bears.  Depending on bears creates a circular loop, and as far as I can see the only component of the bear that is needed is the bears languages.

**Comment by adhikasp** [comment]
Yes the aspectlist only need to use bear's language and I don't see any downside of changing it to avoid circular loop. :+1:

**Comment by userzimmermann** [comment]
@jayvdb @adhikasp IMO this is exactly what I proposed :) Having a back reference to the own holder is nothing unusual in OOP. But if you disagree, feel free! to only reference bear's languages accordingly...
