### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4097]
Our style follows the example given on http://editorconfig.org/ for Python and YAML
difficulty/newcomer

**Comment by Roshanjossey** [comment]
@jayvdb, I'd love to take this up.

I see configurations for python files in there but there is nothing for *.yml files.

Should I add something for *.yml?

**Comment by aryanshar** [comment]
If this issue still not resolved, I would like to take it up as i think i can fix it.

**Comment by aryanshar** [comment]
Please assign me this issue and if possible, guide me how can i fix this issue (I am new to open source) !

**Comment by Nosferatul** [comment]
you need to add an `.editorconfig` file that matches the example from  http://editorconfig.org/

**Comment by newbazz** [comment]
I would like to take this issue if it is not fixed yet.

**Comment by Makman2** [comment]
Unassigning due to closing the PR and inactivity.

**Comment by jayvdb** [comment]
Ugh, we also have https://github.com/coala/coala/pull/4679
