### ISSUE TITLE
Checking, asserting, and raising aspect

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#4099]
As @userzimmermann says in https://github.com/coala/coala/pull/4057#issuecomment-292713283

> Instead of checking `isinstance(obj, (aspectclass, aspectbase))` at several places, why not creating an `isaspect` function instead? And instead of explicitly raising the same `TypeError` with the same message again and again, why not creating a derived `aspectTypeError`, which only takes the wrong-typed object for instantiation. And finally, what about an `assert_aspect` function, which ties all of that together? :)

Ideally also update existing code with this new functions.

cc @Techievena ?
PS sorry @userzimmermann for stealing your issue.

@coala/aspects-developers 
area/aspect difficulty/low

**Comment by Techievena** [comment]
Thanks a lot @adhikasp for opening up an issue for me to work on.

**Comment by userzimmermann** [comment]
@adhikasp There is nothing like *"stealing*" in the aspects team. Just **one shared aspective consciousness** ;)
