### ISSUE TITLE
Coala exit with code 1 even when ignoring error

### ISSUE THREAD

**Issue by MartyHub** [coala/coala#4100]
Hello,

we plan to use Coala for our Python projects with the Pylint bear.

But even when ignoring Pylint error with comment, the Coala exit code is still 1 so our build is failed in CircleCI.

![image](https://cloud.githubusercontent.com/assets/1159991/25003850/abf9cf76-2051-11e7-90ee-d6ae1f69a13d.png)

Is there any workaround ?

Thanks and regards

**Comment by Makman2** [comment]
Seems like `pylint` emits messages when it encounters an ignore-directive. And `PylintBear` does take them up as `INFO`-severity messages. Looks for me like an issue with the bear itself, moving to the `coala-bears` repo :)

Thx for the report :+1:

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala-bears/issues/1608.
