### ISSUE TITLE
Allow to set minimum-severity per section

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4102]
Not sure coala currently supports to set a minimum-severity for each section.

Workaround: Invoke coala multiple times with different coafiles and different `-m` flags.

**Comment by Nosferatul** [comment]
We could also make a new variable for a section -> `severity`?

**Comment by Makman2** [comment]
yeah or `minimum_severity` (I think this name fits better)

**Comment by anctartica** [comment]
i would like to work on this feature

**Comment by Makman2** [comment]
Reassigned due to inactivity.

**Comment by anctartica** [comment]
If we add a setting `min_severity` to the section then the results are ignored based on this in `Processing.py`. Why do we need a new variable `minimum_severity` in the section?

**Comment by Makman2** [comment]
Oh so this feature already exists?

**Comment by anctartica** [comment]
Yes this feature already exists. I tested locally by adding different `min_severity` settings to different sections in my `coafile`. It was able to ignore the results accordingly :)

**Comment by Makman2** [comment]
Indeed! Good that you found it :) But it's not documented :)
I'm filing a new issue for that.

**Comment by Makman2** [comment]
Documentation issue at https://github.com/coala/documentation/issues/531
