### ISSUE TITLE
ContextManagers.py: Use arguments other than "0,1,2" in the inline documentation of simulate_console_inputs method

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala#4105]
Related snippet
```
with simulate_console_inputs(0, 1, 2) as generator:
            assert(input() == 0)
            assert(generator.last_input == 0)
            generator.inputs.append(3)
            assert(input() == 1)
            assert(input() == 2)
            assert(input() == 3)
            assert(generator.last_input == 3)
```

Argument should be changed to prevent confusion of mistaking generator.last_input as actual input value instead of the index value.

difficulty/newcomer

**Comment by prakashdanish** [comment]
But isn't the file removed [link](https://github.com/coala/coala/commit/0d1958c684785349f23de0ce364ef62ddf73165a) not sure if this is correct though

**Comment by Nosferatul** [comment]
@prakashdanish it was added after that :)

**Comment by prakashdanish** [comment]
@Nosferatul sorry I'm new to github, i can't seem to find the specific file.

**Comment by Nosferatul** [comment]
oh my bad, isn't. @satwikkansal where did you find ContextManagers?

**Comment by adhikasp** [comment]
https://gitlab.com/coala/coala-utils/blob/master/coala_utils/ContextManagers.py

Why is this issue in here? 😕

**Comment by Nosferatul** [comment]
i dunno, @prakashdanish go on gitlab and check it. I'll close this

**Comment by Makman2** [comment]
Please migrate the issue :+1:

**Comment by adhikasp** [comment]
Migrated https://gitlab.com/coala/coala-utils/issues/26

**Comment by satwikkansal** [comment]
@prakashdanish sorry for reporting the issue in wrong repository :sweat: Thanks for migrating @adhikasp
