### ISSUE TITLE
Analyse code through url's git

### ISSUE THREAD

**Issue by jihenee** [coala/coala#4118]
Hello,
I want to analyse a project that does not exist on my desktop but it exists on cloud (bitbucket).
# Actual Results
--files=https://name@bitbucket.org/name/project.git**/*.php
The requested section 'https://name@bitbucket.org/name/project.git**/*.php' is not existent. Thus it cannot be executed.
# Expected Results
--files=https://name@bitbucket.org/name/project.git**/*.php
the analyse was made succefuly
# Reproducibility
Add the possibility to analyse project existing on git

Thanks

**Comment by jayvdb** [comment]
Two options exist right now.  Either

1. Fetch the repository to your computer, or
2. run coala in the cloud (see https://github.com/coala/coala/wiki/Google-Code-In-Task-Use-coala)

Not sure we would want `coala` to be doing the fetch from the repo for you.

**Comment by Makman2** [comment]
Hm to analyze a git repo, it has to be fetched locally, as coala runs locally on a machine. So whether you do it manually or we add a feature to support this, the repo will be fetched to your machine in all cases.

Second: coala needs to find the `.coafile` somehow. You could use `-c` and point to an URL, though that needs support from our side again.

All in all I believe this is out of scope for us, as the behaviour can be easily achieved by a helper script that fetches the repo, performs the analysis, and removes it again. Like
```bash
#!/bin/bash
tmp = $(mktemp -d)
cd $tmp
git clone $1 .
coala
cd ..
rm -rf $tmp
```
As fetching a repo is task of the VCS used (like git, svn, etc etc) imo, not of coala^^

**Comment by satwikkansal** [comment]
I think it can be a nice feature to have in coala.io's [try online](http://coala.io/#!/tryonline) section.
User can provide the link to the files or complete repository, and pass in the settings using web interface. 
It can go further ahead by using `coala-quickstart` if user doesn't know exactly what bears and settings to use.

**Comment by jayvdb** [comment]
@satwikkansal, nice idea. you want to submit the issue in the correct repo?

**Comment by satwikkansal** [comment]
Done, https://gitlab.com/coala/landing/issues/38

**Comment by satwikkansal** [comment]
@hemangsk  Didn't knew that, even I proposed https://github.com/coala/coala/issues/4118#issuecomment-294913440 in my GSoC proposal :P

**Comment by hemangsk** [comment]
Yeah its a one super cool task ;)

**Comment by jayvdb** [comment]
OK, I think we're done here.  Have fun other there with that project ;-)

**Comment by hemangsk** [comment]
Done at https://coala.io/#!/coalaonline
