### ISSUE TITLE
Linter_Bears_Advanced.rst: Mention how returning `None` inside `generate_config` works

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4119]
Depending on user settings, sometimes you want to avoid creating a config-file, sometimes not. This can yield huge performance improvements.

This "feature" shall be described in the guide with an example.

Originated from https://github.com/coala/coala-bears/issues/1615

**Comment by yashLadha** [comment]
Going through the discussion, it seems that creating config file only yields performance improvements and there is no way it would be better if it is not there. Them it will create an overhead of managing a large amount of data at each instance.

**Comment by Makman2** [comment]
No, creating a config file is always an impact on I/O. Some bears do support setting an external config file, in those cases we don't have to create a coafile as it's redundant. So we want to omit it, and this is possible by returning `None` in `generate_config()` under this condition.
This issue is about mentioning this possibility to improve performance in those cases.

**Comment by yashLadha** [comment]
Got it! And is there an external parameter for a bear to look for a config file. I would like to work upon it.

**Comment by Makman2** [comment]
Eh sorry, not `coafile`, but a configuration file for the linter used by the bear. :/

I still haven't the feeling you understand the issue completely ;) Those external config files are supplied by settings the bear-writer defines. Read up on http://api.coala.io/en/latest/Developers/Linter_Bears_Advanced.html#supplying-configuration-files-with-generate-config

On that paragraph the feature description using `None` values shall be added btw :+1: It's already added with a single little sentence, but we should emphasize it a bit more in terms of performance.

**Comment by yashLadha** [comment]
Correct me if i am wrong. Config files sets up the parameter in which the bear will work and coafile sets what bears have to work. Means coafile picks up the bear and config sets those bears.

**Comment by Makman2** [comment]
A coafile normally provides already the settings a bear needs to run. But some bears do run external tools, which themselves require an own config file, because they are not designed to work with coala directly (or because of other reasons). In such cases `@linter` supports to generate such a tool-specific config file on the fly from settings provided inside the `coafile`, so coala keeps being the main interface for all settings.

Some people already use those external tools directly we wrap with our bears. Our bears do not support every feature the tool supports, thus we implemented another setting for convenience, and this is the path to the config file specific to that tool. So if someone wants to migrate to coala, he can still make use of all features of the tool and doesn't have to wait until we support all its features.

In some scenarios we generate the tool-specific config file if the user has chosen to use the settings we offer from coala side, and we don't generate it if the user wants to use his own tool-specific config, for performance reasons (where's the need to create the config file if the user just supplied one? :wink: ).
See https://github.com/coala/coala-bears/blob/master/bears/js/JSHintBear.py#L317-L391 (don't worry the big dictionary is not the important part, just the if)

So we should outline more the possibility to save performance if someone returns `None` in cases were applicable.

**Comment by Vedarth** [comment]
@Makman2 Should I modify create_arguments() example by returning `None` instead of a config file? Or create a new example altogether?

**Comment by Vedarth** [comment]
@Makman2 Kindly review my pr

**Comment by jschwarzwalder** [comment]
@Makman2  In attempting to review the pull request from @Vedarth  I must admit I don't know exactly what the change will be.

It sounds like by default no config file is created but if a developer is migrating to coala and needs/(has an existing) config file, there is an optional parameter that you can pass in to specify where the config file is located. 

Is this accurate?  

It also seems like we want to encourage developers to only use a config file if it is absolutely necessary since it can hinder performance.

Please clarify for @Vedarth and myself so we can ensure docs are accurate.

Thanks 😸

**Comment by Makman2** [comment]
> It sounds like by default no config file is created but if a developer is migrating to coala and needs/(has an existing) config file

This is only for writing bears and implementing features for them. When a developer migrates to coala he is usually not involved into bear writing, at least in the first time ;)

> It also seems like we want to encourage developers to only use a config file if it is absolutely necessary since it can hinder performance.

Exactly, this usually is the case, as generating files involves file-I/O (and consider coala running now on 1000 files, this is definitely an impact).

See https://api.coala.io/en/latest/Developers/Linter_Bears_Advanced.html#supplying-configuration-files-with-generate-config for the current documentation of `generate_config`.

However, to clarify again: I just want to have the possibility documented that you can return `None` there to conditionally generate a config file inside `generate_config`. Consider this case:
```python
# A linter has many settings, and we are going to implement 1 of them.
# However, this setting can be only given via a config file.

@linter(...)
class MyBear:
    def generate_config(filename, file, settingA: bool):
        if settingA:
            return 'A=true'
        else:  # for the sake of readability I explicitly return None here, but this else branch is redundant
            return None

    def create_arguments(filename, file, config_file, settingA: bool):
        args = ['--lint', '--mode', 'standard']
        if settingA:  # or `if config_file`
            args += ['--advanced', config_file]
        return args
```
If `settingA` is unused, we can avoid generating a file and having a useless performance impact, but if we want to use `settingA`, there's no other way but to generate a config file in that case.

The additional documentation can definitely have a little example like this (but more minimal and simpler) :+1:
