### ISSUE TITLE
Appveyor curl failing

### ISSUE THREAD

**Issue by supergr35** [coala/coala#4126]
curl throws the following error in appveyor ci:
`curl: (7) Failed to connect to releases.llvm.org port 80: Timed out`
Link to log: https://ci.appveyor.com/project/coala/coala/build/1.0.7427/job/dteq9w39v434i723
importance/high type/bug

**Comment by jayvdb** [comment]
It appears to only need a longer timeout.
That is the quick fix.

https://github.com/coala/coala/issues/3726 and https://github.com/coala/coala/issues/3854 are two alternative approaches which are close to completion.  ping @gaurav1911  and @Techievena

**Comment by jayvdb** [comment]
Consistently working again.
Re-open if it re-occurs.
