### ISSUE TITLE
Do not offer to add an ignore comment after the user chooses "Add ignore comment"

### ISSUE THREAD

**Issue by adtac** [coala/coala#4145]
That doesn't make much sense. It shouldn't be there in the second time the options are presented (if the user chose "Add ignore comment" the first time).

**Comment by mgracer48** [comment]
How would i go about fixing this

**Comment by mrtes** [comment]
We could change the return value of [ask_for_action_and_apply](https://github.com/coala/coala/blob/master/coalib/output/ConsoleInteraction.py#L608-L656) to the name of the applied action (or the action, or the action metadata) and use it to modify [the metadata_list](https://github.com/coala/coala/blob/master/coalib/output/ConsoleInteraction.py#L152) in the surrounding loop.

This would change the printed options for the current diff and we can decide if the behaviour should be consistent for all chosen options, or just for the ignore-action.

I would like to implement this, if someone agrees with my suggestion.

**Comment by RohanVB** [comment]
I guess this is a duplicate issue.
Ref: https://github.com/coala/coala/issues/3375

**Comment by adtac** [comment]
@RohanVB you're right. Closing in favor of https://github.com/coala/coala/issues/3375


CC @mrtes @mgracer48 - please move all discussion to that issue.
