### ISSUE TITLE
Add keyword-only languages= argument to meta bearclass

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4147]
According to https://github.com/coala/coala/pull/3966 the meta `bearclass` should also provide a keyword-only `languages=` argument, allowing:

```python
from coalib.bearlib.aspects import Redundancy
```

```python
class aspectsBear(Bear, aspects={
        'fix': [Redundancy.UnusedImport],
 }, languages=['Python']):
    ...
```

This is already getting implemented by #4111 

@coala/aspects-developers

**Comment by adhikasp** [comment]
@pratyushprakash are you still working on this?

**Comment by userzimmermann** [comment]
@adhikasp Please take this over for GSoC. I created https://gitlab.com/coala/GSoC-2017/issues/362 for this

@jayvdb
