### ISSUE TITLE
Diff: Remove has_changes field

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4178]
The better alternative to `has_changes` is using `__bool__`.
Task is to remove `has_changes` again by reverting commit https://github.com/coala/coala/commit/671e6a2e9fe1f5ab8bab5370c1848f00b3472030.

Sorry @lshobith, but your work is not in vain, now we know also thanks to you how to do it better ;)

See also https://github.com/coala/coala/issues/3790

**Comment by meetmangukiya** [comment]
@Makman2 are you sure, have a look at this:
```py
In [1]: from coalib.results.Diff import Diff

In [2]: diff = Diff([1,2,3])

In [3]: diff.delete_line(3)

In [4]: diff.add_line(3, 3)

In [5]: diff.has_changes
Out[5]: False

In [6]: bool(diff)
Out[6]: True
```

**Comment by meetmangukiya** [comment]
If you look at `has_changes` and `bool` they are quite different

**Comment by Makman2** [comment]
From the docstring of `__bool__`:

> False if the patch has no effect at all when applied.

Then `__bool__` has actually a bug imo^^

**Comment by mrtes** [comment]
The bug is that `self._changes`, which is queried in` __bool__` does still include the changes, even if they negate each other.

We could just incorporate the computation of `self.has_changes` to `__bool__ `instead of looking at the `self._changes` property

**Comment by Makman2** [comment]
yeah this is safer :)

**Comment by jayvdb** [comment]
in `__bool__` , `self.rename is not False or` looks suspiciously like it will return `True` way too often.

**Comment by Makman2** [comment]
@jayvdb `rename` is either a string labelling the new file name or it's `False`, meaning no rename shall happen. So imo it's alright^^
