### ISSUE TITLE
can't build docs due to multiple targets for cross-reference

### ISSUE THREAD

**Issue by thisch** [coala/coala#4180]
I can't successfully build the docs using `python setup.py docs` with Sphinx 1.5.5 due to the following error

```
Warning, treated as error:
/home/thomas/gitrepos/coala/coalib/core/DependencyTracker.py:docstring of coalib.core.DependencyTracker.DependencyTracker.check_circular_dependencies:None: WARNING: more than one target found for cross-reference 'CircularDependencyError': coalib.collecting.Dependencies.CircularDependencyError, coalib.core.CircularDependencyError.CircularDependencyError
```

I had a look at the implementation of the two CircularDependenyError classes and they are quite similar, can't they be merged?

**Comment by thisch** [comment]
This might be related to the sphinx-1.5.5, since the docs-requirements.txt 1.4.9 is hardcoded.

**Comment by Makman2** [comment]
Did you try to compile the docs with sphinx 1.4.9?

**Comment by Makman2** [comment]
Indeed those classes seem to be very similar. We should try to merge them :+1:

**Comment by thisch** [comment]
Should I create a PR out of my commit mentioned in https://github.com/coala/coala/pull/4183#issuecomment-299701304, so that we keep sight of my 'merge'-commit?

**Comment by Makman2** [comment]
Let's make a new issue ;)

**Comment by Makman2** [comment]
--> https://github.com/coala/coala/issues/4191. Mentioned your commit there :+1:
