### ISSUE TITLE
--no-color is ignored for loglines

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4185]
Migrated from https://github.com/coala/coala-bears/issues/1714.

From @thisch:

> The string '[WARNING]' is colored even if the --no-color (-N) flag is used.
>
> ```
> > coala -N --bears=VultureBear --files \*\*/\*.py --save
> [WARNING][11:57:36] 'cli' is an internally reserved section name. It may have been generated into your coafile while running coala with `--save`. The settings in that section will inherit implicitly to all sections as defaults just like CLI args do.Please change the name of that section in your coafile to avoid any unexpected behavior.
> Executing section cli...
> ```

**Comment by Makman2** [comment]
From @Makman2:

> Confirmed. Happens with latest version `0.12.0.dev20170507091731`.

**Comment by thisch** [comment]
Sry, I accidentally posted this issue in coala-bears

**Comment by shreyans800755** [comment]
I would like to work this issue.
I tried to replicate the scenario in my local environment. And I get colored output for the name of logging level. I'm not able to figure out, how only logging level is colored and not the whole logging message.

I tried to go through various files like LOG_LEVEL, LogPrinter, LogMessage, ConsoleInteraction, etc. But couldn't find the exact location, where color is set for log level name.

Can someone please guide me ?

**Comment by Makman2** [comment]
> I'm not able to figure out, how only logging level is colored and not the whole logging message.

We don't color the message itself on purpose, just the log level tag.

> I tried to go through various files like LOG_LEVEL, LogPrinter, LogMessage, ConsoleInteraction, etc. But couldn't find the exact location, where color is set for log level name.

Actually I don't know where we set colors, should be somewhere where we initialize logging I believe. See https://docs.python.org/3/library/logging.config.html. I think we use `dictConfig()`.

**Comment by mrtes** [comment]
The console_printer, which is configured with args.no_color, is currently only used in the ConsoleInteraction,py file, which explains why the argument does not do anything regarding logging colors.

For logging, the console_printer is not used at all. It is handed to the log_printer, but that uses the "logging" package internally. Additionally, the "logging" package is used directly in some cases in "ConfigurationGathering".

Both are configured with the dict you mentioned.

I guess there is a reason for separating those two interaction forms, but why is the console_printer passed to the log_printer and not used at all?

**Comment by Makman2** [comment]
Those log- and console-printers are deprecated. We haven't removed them completely yet, that's why you encounter those sometimes.
