### ISSUE TITLE
pytest executable is called pytest instead of py.test now -> update this in the docs

### ISSUE THREAD

**Issue by thisch** [coala/coala#4189]
In the docs we currently mention to use ``py.test`` to run the tests. Since pytest-3.0 the executable is called ``pytest`` (There is still a ``py.test`` legacy wrapper). We should update our docs and use the new executable to run pytest.

see http://stackoverflow.com/a/41893170

**Comment by shreyans800755** [comment]
@thisch It is already mentioned in http://api.coala.io/en/latest/Developers/Executing_Tests.html. It suggests using `pytest`, if `py.test` gives error.
But, I think it makes sense to remove that note, and use `pytest` everywhere, replacing `py.test`.

**Comment by thisch** [comment]
Yes it mentions to run  `python3 -m pytest`, but this is not recommended by many python projects (see, e.g., https://github.com/theochem/horton/pull/108).

**Comment by shreyans800755** [comment]
Makes sense. Please review https://github.com/coala/coala/pull/4198 and lemme know if anything to be changed.
