### ISSUE TITLE
Merge `coalib.collecting.Dependencies.CircularDependencyError` and `coalib.core.CircularDependencyError`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4191]
Those error classes are very similar and do serve the same purpose.

See https://github.com/thisch/coala/commit/e492cfd7f9e1dce221ce753ac8a919e0e9e2fb39 for a possible implementation.

**Comment by Makman2** [comment]
@thisch assigned you for now as you have already an implementation ;) feel free to continue or give this issue away ;)

**Comment by jayvdb** [comment]
I suspect the original intention was that `coalib.core` was not supposed to include any 'bears' type code, so it stays generic, so a `for_bears` would need to be in `coalib.collecting`.
Maybe someone just forgot to make `collecting.CircularDependencyError` a subclass of `core.CircularDependencyError`.
