### ISSUE TITLE
Git_Basics: Incorrect RST syntax

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4221]
Change 38206d090 introduced a number of RST syntax errors into Git_Basics.rst, which rstcheck bear reports as

```
docs/Developers/Git_Basics.rst

| 346| ::
|    | [INFO] RSTcheckBear:
|    | (INFO/1) Possible title underline, too short for the title.
[WARNING][05:49:58] RSTcheckBear: This result has no patch attached.
```

cc @SarthakNijhawan

**Comment by mridubhatnagar** [comment]
It shows an error in line 346 which seems to be :: . In the same block I tried changing the length of underline. But it didn't work out. Some other alternative should be thought off IMO.

**Comment by mridubhatnagar** [comment]
@jayvdb RSTcheckBear is not yet a part of .coafile. So whoever would work on this first will need to make changes in the .coafile.

**Comment by harirajk** [comment]
Hi I am a newcomer.Mind if I take care of it?

**Comment by mridubhatnagar** [comment]
@harirajk you can take care of this issue. You will have to ping on gitter channel https://gitter.im/coala/coala. And assign yourself to this task. 
By typing cobot assign https://github.com/coala/coala/issues/4221.
