### ISSUE TITLE
Add Statistics in bear aspects

### ISSUE THREAD

**Issue by shreyans800755** [coala/coala#4233]
As per discussion on thread https://github.com/coala/coala-bears/pull/1691#discussion_r116030569,
and comment by @sils
Add Statistics in bear aspects `CAN_DETECT`.

**Comment by jayvdb** [comment]
Personally, I think this is a mis-use of CAN_DETECT.  But @userzimmermann is responsible for the design in this area.

Note that @sils and I had a chat the design problems that `CLOCBear` causes at https://gitter.im/coala/coala?at=591185e0c89bb14b5ae5299a

**Comment by shreyans800755** [comment]
@jayvdb @sils I've pointed it out in comment https://github.com/coala/coala-bears/pull/1691#discussion_r116282711.
Either we have to add statistics related logic as suggested by @sils, or we can add CAN_COMPUTE or something like that, and than use it later when other design that uses statistics is ready.

**Comment by sils** [comment]
IMO either use CAN_DETECT or also an option would be to not list this
"aspect" at all. The CAN_DETECTs will be replaced by aspects at some time
anyway and the aspects should contain statistics as well, we'll need them.

**Comment by shreyans800755** [comment]
Then, I think PR for this issue should be good to merge along with https://github.com/coala/coala-bears/pull/1691 for CLOCBear.
