### ISSUE TITLE
Nextgen-Core: Don't use an asyncio event loop

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4237]
It seems that the `ProcessPoolExecutor` (and also all other executors) do provide the functionality we need by themselves: `submit()` and `shutdown(wait=True)`. As far as I understand an event loop provides only extra functionality on top of executors, like coroutine support and delayed execution (which we don't need).

Any reasons against using the executor only?

CC @Udayan12167

**Comment by Udayan12167** [comment]
It was only done keeping future expandability in mind. I don't know how much the overhead is though. I can see a use for coroutines when we output the results for a bear with each bear awaiting on another bear to output its result or each section awaiting on another to create order without the use of queues and sorting.

**Comment by Makman2** [comment]
> I can see a use for coroutines when we output the results for a bear with each bear awaiting on another bear to output its result or each section awaiting on another to create order without the use of queues and sorting.

So you want to start a dependent bear once a single result from its dependency is available? Sounds quite difficult to achieve that. Currently we wait until the bear finishes completely^^ Hm but yeah that would be a reason to keep it.

**Comment by Makman2** [comment]
Let's not take the overhead for now, if the need arises we use an event loop again.

**Comment by Makman2** [comment]
Tests do fail when using an executor alone:
```
RuntimeError: cannot schedule new futures after shutdown
```

To avoid this error, we have to deal manually with locks controlling the shutdown of an executor. It seems that an event-loop takes this over for us, so it definitely has now a reason to stay.
