### ISSUE TITLE
Appveyor fails: LLVM download timeout

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4246]
See build:
https://ci.appveyor.com/project/coala/coala/build/1.0.7838/job/ejeko4nuwlxt3dh6#L84

```
curl -fsSL http://llvm.org/releases/%LLVM_VERSION%/LLVM-%LLVM_VERSION%-win32.exe -o LLVM.exe
```
With `LLVM_VERSION=3.4.1`, the link becomes
```
http://llvm.org/releases/3.4.1/LLVM-3.4.1-win32.exe
```

It's also not working in my local browser.

CC @jayvdb

**Comment by Makman2** [comment]
Actually www.llvm.org is completely down it seems... Maybe it's a temporary issue.

**Comment by shreyans800755** [comment]
@Makman2 I think llvm is back online. And appveyor build is also being passed successfully.
This issue can be closed I believe.

**Comment by Makman2** [comment]
Yep, looks like it's back again :)
