### ISSUE TITLE
coalaTest: Unexpected assert for an actual error

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4249]
See https://github.com/coala/coala/blob/master/tests/coalaTest.py#L37

We assert that there's some error output which seem to be some kind of traceback which is bad.

Task:
1. Check what's actually going wrong
-> If it's reasonable, place a comment above to reason why this is done so nobody is going to be confused and raises an issue again (like me ;D)
-> If it can/should be fixed, fix it and remove assertion for stderr.

**Comment by jayvdb** [comment]
Ok, there are also three in `tests/misc/CachingTest.py`.  They were all introduced in cef20b6a7 (https://github.com/coala/coala/pull/3638), which at least confirms they are not a 'very recent' regression, but that commit was still within the 0.11 cycle, so it could still be a 0.11 regression that caused it.

**Comment by jayvdb** [comment]
The exception is

> OSError: reading from stdin while output is captured

It is raised from the pytest capture handler: https://github.com/pytest-dev/pytest/blob/d86c89e/_pytest/capture.py#L446

This is unlikely to be a regression.  The easy fix is to add `--ci` to all of these commands, so the tests dont ask the user for a value.
