### ISSUE TITLE
Newcomers_Guide: Merge first two steps by mentioning how hello world already invites you to the org

### ISSUE THREAD

**Issue by underyx** [coala/coala#4251]
The first two steps seem pretty outdated: http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-1-meet-the-community

difficulty/newcomer
area/docs

**Comment by Ciemaar** [comment]
Invalid, the guide is correct, invites are manual and require a maintainer to issue "cobot inv @user...".

**Comment by underyx** [comment]
Actually it seems like it's still not correct: hello world works *around every second try*. Filed issue at https://gitlab.com/coala/cobot/issues/93. We should still edit the docs and maybe mention how it's unstable right now and how you might need to retry once.

**Comment by Makman2** [comment]
> Invalid, the guide is correct, invites are manual and require a maintainer to issue "cobot inv @user...".

People can now write `Hello world` into the channel and they get automatically invited. No need to wait for a maintainer any more ;)
