### ISSUE TITLE
Add output examples to Tutorial

### ISSUE THREAD

**Issue by jrrickerson** [coala/coala#4254]
The tutorial mentions how to grab tutorial code and run coala against it for the first time, and includes command line snippets to clarify, but does not include any snippets or screenshots to clarify what the output of the tool should look like.  Consider adding output examples to set user expectations and clarify references (for example, the reference to "option 2").

**Comment by Hsankesara** [comment]
Hey everybody, can I go for this?

**Comment by adeora7** [comment]
Hey @Hsankesara  are you working on this issue?

**Comment by adeora7** [comment]
@jrrickerson @Makman2 can you assign this issue to me ?

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by adeora7** [comment]
@Makman2 @jrrickerson  Please refer to the PR. I was confused between snippets and screenshots but I preferred code snippets.

**Comment by Makman2** [comment]
@jrrickerson I hope that's what you've imagined, if not feel free to reopen :)
