### ISSUE TITLE
Improve English in Newcomers Guide

### ISSUE THREAD

**Issue by burrowdown** [coala/coala#4269]
Parts of the intro and section 0 of the Newcomers Guide have awkward and/or incorrect English. Rewrite these sections for readability and grammar.

**Comment by underyx** [comment]
Found two related issues: https://github.com/coala/coala/issues/3254 and https://github.com/coala/coala/issues/3858

**Comment by underyx** [comment]
Also, @li3n3 is working on this right now 😯

**Comment by li3n3** [comment]
Whoops! Learned an important lesson.

I have some changes but will need to resolve merge conflicts with @burrowdown's edits. Yay!

**Comment by nityeshaga** [comment]
@li3n3 has not updated the PR since May 24. IMHO someone should take over that PR (as @li3n3 himself suggested on 23rd May).
