### ISSUE TITLE
disturbing newlines when adding settings automatically

### ISSUE THREAD

**Issue by sils1297** [coala/coala#429]
assume we have a coafile like:

```
[sec1]
a = b
c = d

[sec2]
b = 2
```

when now doing `coala -s -S sec1.c=2b` we'll end up with the following:

```
[sec1]
a = b
c = d

c = 2b

[sec2]
b = 2
```

So that last newline in sec1 is a setting internally after that we add the setting. However it would be better if we detect that case so we have an output like:

```
[sec1]
a = b
c = d
c = 2b

[sec2]
b = 2
```

i.e. inserting the last setting after any *non-newline* settings in sec1.

**Comment by Makman2** [comment]
Using `sec1.c` again overrides the setting, but doing `coala -s -S sec1.d=2b` yields such a newline^^

**Comment by srisankethu** [comment]
suppose i have a .coafile like this one
``[sec1]

a = b
c = d

[sec2]

b = 2
``
and the output is like
``[sec1]
a = b
c = d
newkey=newvalue

[sec2]
b = 2
``
is that ok ?

**Comment by Makman2** [comment]
@srisankethu no you don't want to interfere with the old file, this would be correct (as far as I understand):
```python
[sec1]

a = b
c = d
newkey=newvalue

[sec2]

b = 2
```

**Comment by srisankethu** [comment]
@Makman2 Can you assign this to me ? I have come up with an idea to clear this! I will fix this as soon as [this](https://github.com/coala-analyzer/coala/issues/1916) finishes. I am having with my laptop right now. I will submit patches as soon as my laptop gets fixed :+1:

**Comment by srisankethu** [comment]
I have my exams in 2 days. I will resume work after May10. I made some progress with the issue but feel free to unassign me if its urgent.

**Comment by SanketDG** [comment]
@srisankethu Let us know if you are still working on this :smile:

**Comment by srisankethu** [comment]
Yes! I will start by this weekend. I am not at home right now! I have two other assigned issues too. Will complete it soon.

**Comment by Adrianzatreanu** [comment]
@srisankethu hey you still on this :) ? it's been a while after 10 may :)

**Comment by srisankethu** [comment]
Sorry for being soo late... I need a clarification on this issue. What if the user purposely introduces multiple lines between sections. For example,
``[sec1]
   
   a = b
   c = d



   [sec2]

   b = 2
``
What should be the output when ``coala -s -S sec1.d=2b`` is performed??
Should it be
``[sec1]
   
   a = b
   c = d
   d = 2b



   [sec2]

   b = 2
``

**Comment by Makman2** [comment]
these shall be preserved. Only addings settings automatically shall not have these disturbing newlines :)

and welcome back, long time no see :D

**Comment by srisankethu** [comment]
Could you give a simple input and output? an example

**Comment by Makman2** [comment]
look at the top of this issue :)

**Comment by srisankethu** [comment]
Ok! I get it. I was having a doubt but its clear :)

**Comment by srisankethu** [comment]
I have been checking an effective solution for this problem. Since i am not used to the coala code base and I have been taking breaks, it took me sometime. So to effectively solve this bug we need to know how many new keys are inserted(not updated) so that we can handle "comments"(blank lines) properly. This can be done by changing `Setting` by adding an new instance `key_status = enum(new, old)` and then make necessary changes in `write_section` method in ConfWriter.py file. This is my approach. It boiled down to `Setting` class after i checked all the dependencies.

Or else we could just neglect it as the newline is actually part of a .coafile which is treated as a "comment". We could just stop the printing of a new line after the new settings are written to .coafile.

**Comment by Makman2** [comment]
would you submit a PR? then it's easier to see what you mean exactly :)

**Comment by srisankethu** [comment]
The first idea involves a modifying `Setting`. So there might be some intricacies. The new instance `key_status` which i talked about will not be of use other the solving this issue.
The second idea is fairly simple.

So down to the point, my first idea needs really careful review and only useful to settle our case and the second idea is simple. I want to know what you guys think is better?

**Comment by Makman2** [comment]
I'm not really in into `Setting` parsing. So take the solution that's the simplest: Less code -> Simpler functionality :)

**Comment by srisankethu** [comment]
Yup and it is unnecessary too. Need to change the tests though :) Should I ?
