### ISSUE TITLE
typed_list/dict/ordered_dict(...) annotations look ugly in API docs

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4341]
Let's take `PEP8Bear.run()` as example. `sphinx` autodoc creates the following confusing signature:

> `run(filename, file, max_line_length: int = 79, indent_size: int = 4, pep_ignore: <function typed_list.<locals>.<lambda> at 0x000001CC99B73378> = (), pep_select: <function typed_list.<locals>.<lambda> at 0x000001CC99B73400> = (), local_pep8_config: bool = False)`

`coalib.settings.Setting.typed_list/dict/ordered_dict()` should better return converters with useful `__repr__` instead of `lambda` functions

@sils @Makman2 @jayvdb

**Comment by Makman2** [comment]
Let's override their `__repr__` then :+1: :)

**Comment by Makman2** [comment]
In the end I think it should look like
```
typed_list(str)
typed_list(int)
```
etc.

**Comment by userzimmermann** [comment]
@Makman2 Those were exactly my ideas :)
