### ISSUE TITLE
Nextgen Core: Port core functions to class methods

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4351]
This could be a performance gain as we don't have to pass always the same variables around. Instead we can access them from `self`.

**Comment by Makman2** [comment]
How this could look like can be seen here: https://github.com/coala/coala/tree/Makman2/NEXTGEN-to-classes

**Comment by shreyans800755** [comment]
@Makman2 
I would like to work on this issue.
Just needed clarification before I start working, correct me if I'm wrong:
We are supposed to move global functions core/Core.py to a class, to optimize it. As per my analysis, there should be 2 classes, one for group and one for the rest of the functions.

**Comment by Makman2** [comment]
Just one class is enough. I think we only need this for the functions that always pass some states around, like `running_tasks` or `dependency_tracker`. Everything else that is modular and can work on it's own should be still kept inside the module directly :)

So a list of functions I would consider to move to a class:
- `cleanup_bear`
- `schedule_bears`
- `finish_task`

And we can move maybe some mechanics of `run` into a class method too, so we can easily start a session with an instance easily.

About the name of the class: I don't know a proper name, but I have the feeling that calling it somehow a "session" or so is quite fitting^^

**Comment by shreyans800755** [comment]
@Makman2 I'm not able to find the references of any of the functions `initialize_dependencies` and `run` from `Core.py` (apart from CoreTest). Where are these functions used ?

**Comment by Makman2** [comment]
`initialize_dependencies` is used inside `run`, and `run` shall be used outside. `run` is the main entry-point for running bears. Everything else should not be touched by external users.

**Comment by shreyans800755** [comment]
So, right now, `run` is not used anywhere else ?

**Comment by Makman2** [comment]
No, not yet. It will be used by coala once the last step is completed, the integration :)

**Comment by shreyans800755** [comment]
> initialize_dependencies is used inside run, and run shall be used outside. run is the main entry-point for running bears. Everything else should not be touched by external users.

In that case, why do we have different tests for both `initialize_dependencies` and `run` ? Shouldn't the tests only for `run` should suffice ?

**Comment by Makman2** [comment]
Because `initialize_dependencies` features much functionality, this component is tested on its own. It's easier to test than through `run`.
