### ISSUE TITLE
coala --files does\not\support\backslash\paths\on\windows

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4356]
The backslashes are just discarded:

```
> coala -I --bears PEP8Bear --files docs\conf.py
Executing section cli...
[WARNING][17:14:44] No files matching 'C:\Users\Zimmermann\Projects\coala\lib\docsconf.py' were found. If this rule is not required, you can remove it from section [cli] in your .coafile to deactivate this warning.
```

@sils Funny that no one complained about that so far :D

**Comment by jayvdb** [comment]
I think you'll find this is the same rabbit hole as https://github.com/coala/coala/pull/4171 , and IMO the only sane solution is to use pathlib (https://github.com/coala/coala/issues/4358)

**Comment by Makman2** [comment]
Just escape the path. coala interpretes backslashes, so this is actually intended currently. I'm not sure if #4171 is good as we are starting to be inconsistent because we parse different settings differently.

**Comment by userzimmermann** [comment]
@Makman2 What's so bad about different value types for different settings, like normal string type (w/ escaping) or path type (w/o escaping)?

cc @jayvdb

**Comment by Makman2** [comment]
this makes stuff super inconsistent, and I can really feel that this is a bad idea and we will hit issues in the future^^

**Comment by Makman2** [comment]
Actually I'm for keeping our current escape sequence support (although not really mature right now) everywhere inside a coafile, regardless which setting.

**Comment by Makman2** [comment]
Changed priority, as there's a workaround (by using double backslashes).

**Comment by userzimmermann** [comment]
@Makman2 This is nothing but a torture for Windows cmdline users!

**Comment by userzimmermann** [comment]
@Makman2 
> this makes stuff super inconsistent, and I can really feel that this is a bad idea and we will hit issues in the future^^

We will hit even more issues in the future if we don't correct the mistakes of the past ;)

**Comment by userzimmermann** [comment]
@Makman2 Oh! BTW... Maybe we have some little misunderstanding ;)

> Actually I'm for keeping our current escape sequence support (although not really mature right now) everywhere inside a coafile, regardless which setting.

That's fine! I would never use backslashes as path separators in a `.coafile`

It's only about the `--files` cmdline flag

**Comment by Makman2** [comment]
> This is nothing but a torture for Windows cmdline users!

Your fault choosing windows 😅

> We will hit even more issues in the future if we don't correct the mistakes of the past ;)

That's no mistake of the past ;) We are currently trading a bit of windows user convenience for a more complicated coafile parsing functionality probably resulting in unintuitive exceptions in the syntax.

> It's only about the --files cmdline flag

Makes our CLI then complicated. We might miss other parameters that also accept files, and suddenly those don't support this convenience.
But: As everything is merged into a coafile from the CLI, you could also use slashes there for paths, however if you want to make use of shell-autocorrect, it will replace them immediately with backslashes^^

**Comment by userzimmermann** [comment]
@Makman2 @jayvdb Here comes the solution that should satisfy everybody: https://github.com/coala/coala/pull/4883

**Comment by userzimmermann** [comment]
@Makman2 
> That's no mistake of the past ;) We are currently trading a bit of windows user convenience for a more complicated coafile parsing functionality probably resulting in unintuitive exceptions in the syntax.

It's still not about `.coafile` parsing 😄

**Comment by Makman2** [comment]
Yeah I know, I just wanted to point out the trade off here 😅 sorry :P

**Comment by userzimmermann** [comment]
@Makman2 
> Your fault choosing windows

Your fault disappointing many other Windows users out there ;P

**Comment by userzimmermann** [comment]
@Makman2 
> Makes our CLI then complicated. We might miss other parameters that also accept files, and suddenly those don't support this convenience.

Just a matter of proper testing ;) And already addressed in https://github.com/coala/coala/pull/4883

**Comment by Makman2** [comment]
yeah you're right... I just have the feeling we are making our life a little bit more complicated with this feature^^

**Comment by userzimmermann** [comment]
@Makman2 When we will be old we will be happy that we did it ;)

**Comment by userzimmermann** [comment]
@Makman2 
> yeah you're right... I just have the feeling we are making our life a little bit more complicated with this feature^^

Believe me! Our life will get richer with this feature ;) No one will ever use an escape sequence in a file path :) And it's all and only about the cmdline here. Even every ported Unix tool interchangeably supports `/` and `\` from the Windows cmdline. MinGW and Cygwin do it... It feels just as normal as the BSoD ;P We shouldn't be the only exception!
