### ISSUE TITLE
Change ``prarses``->``parses``

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala#4365]
[here](https://github.com/coala/coala/blob/master/coalib/bearlib/languages/Language.py#L25)

**Comment by seven-binoche** [comment]
When I try to edit, it says 'You’re editing a file in a project you don’t have write access to.'. Do I need to be assigned to gain write access? New here. Please bear with me.

**Comment by Asnelchristian** [comment]
Hi @seven-binoche, and welcome :tada: :+1: .  This is the best place to get started with [coala](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html), trust me you can find all you need there...

And once again welcome to coala :smile:

**Comment by Asnelchristian** [comment]
Hi @seven-binoche, and welcome :tada: :+1: .  This is the best place to get started with [coala](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html), trust me you can find all you need there...

And once again welcome to coala :smile:

**Comment by adhikasp** [comment]
Why you close it @Asnelchristian?

**Comment by Makman2** [comment]
I think that was by accident.

**Comment by S2606** [comment]
Please assign me to this issue. I would love to contribute

**Comment by jayvdb** [comment]
None of the four people working on this issue have followed https://coala.io/newcomer .  I cant assign it to anyone until you have followed the process and become a member of the organisation "coala".
