### ISSUE TITLE
Typo `max_paramters` -> `max_parameters`

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#4380]
in [MethodSmell](https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/Smell.py#L95) aspect

difficulty/newcomer

**Comment by userzimmermann** [comment]
Thanks @adhikasp for finding this :)

cc @Asnelchristian

**Comment by userzimmermann** [comment]
Rest of `Smell` aspects cleanup happens in #4360
