### ISSUE TITLE
Replace all mentions of `pip` in the documentation with `pip3`

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4413]
Currently the documentation uses a mix of `pip` and `pip3`. Change all mentions of `pip` to `pip3` wherever required.

**Comment by adhikasp** [comment]
Missing info from title change:
Currently the documentation uses a mix of `pip` and `pip3`. Change all mentions of `pip` to `pip3` wherever required.

**Comment by troublemagnet** [comment]
Are you still working on it?

**Comment by SanketDG** [comment]
@S2606 Do you need help with this? Please come to https://coala.io/chat if you need help :)

PROTIP: Use the `git grep` tool, to find occurences of a string.

**Comment by S2606** [comment]
@troublemagnet Yes i am working on this

**Comment by S2606** [comment]
@SanketDG Thank you for your consideration, I shall ask for help when needed.
