### ISSUE TITLE
Newcomers_Guide.rst: Reason for not resolving issue on master of forked repository. 

### ISSUE THREAD

**Issue by mridubhatnagar** [coala/coala#4423]
As of now there is a Note in newcomers guide http://api.coala.io/en/latest/Developers/Newcomers_Guide.html which explicitly states that before resolving a issue you need to create a new branch and then resolve the issue.

But mistakenly first timers resolve the issue on master branch of there forked repository itself. IMO, we can add a note why issues should not be resolved on master branch. There are couple of PR's where issue is being resolved on master.

cc @jayvdb @meetmangukiya @userzimmermann

**Comment by mridubhatnagar** [comment]
As of now there is a Note in newcomers guide http://api.coala.io/en/latest/Developers/Newcomers_Guide.html which explicitly states that before resolving a issue you need to create a new branch and then resolve the issue. 

But mistakenly first timers resolve the issue on master branch on there forked repository itself.  IMO, we can add a note why issues should not be resolved on master branch. There are couple of PR's  where issue is being resolved on master.

**Comment by JohnMoutafis** [comment]
@mridubhatnagar If ever that issue receives a tag `difficulty/low` I will be happy to work on it!

I even have the explanation ready! :smile:

**Comment by meetmangukiya** [comment]
@JohnMoutafis go ahead, if you feel like it :smile:

**Comment by JohnMoutafis** [comment]
Gimme gimme 😄

**Comment by jayvdb** [comment]
@JohnMoutafis , @supergr35 , we have a bit of overlap between this issue (and its PR https://github.com/coala/coala/pull/4426 ) and https://github.com/coala/coala/issues/3253  , which has PR https://github.com/coala/coala/issues/3729 .  They are about different parts of the docs, but try to assist avoid the same sets of newbie mistakes.  You two should check each others work to find ways to make the two pages complement each other. ;-)
