### ISSUE TITLE
Add `sudo` to the installation guides

### ISSUE THREAD

**Issue by nityeshaga** [coala/coala#4428]
When installing things on Ubuntu/Debian sudo access is required. This is not mentioned in the guides. This might trip newcomers when getting started (tripped me :sweat_smile: ). So, we should add `sudo` when needed.

**Comment by sils** [comment]
@nityeshaga not if you're using a virtualenv?

**Comment by nityeshaga** [comment]
Oh okay.. then I must have messed up something else! :smile: 
Close it then?

**Comment by sils** [comment]
not sure, question is how can we avoid others having this problem

**Comment by nityeshaga** [comment]
I just checked.. somehow I got coala installed on both the virtualenv as well as without it. Don't know how that happened :worried:

**Comment by yukiisbored** [comment]
It depends really some Linux distributions (like Gentoo) doesn't allow installing it to the system wide sites-package and tells the user to use `--user` for using the user's sites-package instead

**Comment by aryanshar** [comment]
Hi @charul97 , I see you've got conflicts while rebasing.you have to keep only certain blocks of code in the conflict region
marked within >>>> and <<<<  
after resolving the conflicts.. you have to git add those files
and run git rebase --continue

**Comment by charul97** [comment]
Currently like I have made many commits accidentally where some are worth and some are not :(
So should I remove the unnecessary commits that i made and squash the ones which are worth?

**Comment by aryanshar** [comment]
Hey @charul97 just squash locally and force push to your earlier branch from which you opened the PR
it will automatically reflect in the existing PR

**Comment by charul97** [comment]
okay :)

**Comment by haripalbaluja** [comment]
I've made a PR regarding the issue.

**Comment by yukiisbored** [comment]
I don't think this is a good idea. We may break someone's global site-packages with this.

**Comment by jayvdb** [comment]
`sudo` is a bad idea, generally.
Open more specific issues if there are use cases for `sudo` rather than `virtualenv` and `--user`.
