### ISSUE TITLE
New argument `--show-settings` to explicitly show optional and non-optional settings of bears

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala#4432]
Currently, there is no way to see the optional and non-optional settings of a bear. It should be possible to see the settings in CLI, rather than having to visit the website.

**Comment by mridubhatnagar** [comment]
Interested to work. But will be busy this week. :/

**Comment by Makman2** [comment]
You can use `coala --show-bears --show-details`, but this displays all bears at all. Maybe we can enhance `--show-bears` itself to take additional bears that shall be shown?

**Comment by meetmangukiya** [comment]
It'd be better if it checked if any args were given to `show-details` i.e. change it or `show-bears` from a switch to a `nargs=+`(I think, haven't worked with argparse recently, might be wrong :sweat_smile: )

**Comment by mridubhatnagar** [comment]
@meetmangukiya @Makman2  Though as of now I am unable to figure out where changes are to be made. But, IMO  we can make this more user-friendly by adding Bear name as an argument.  So, in case the user adds language as Python. 
1) so all bears related to Python should be displayed.
2) Now, if the user selects Pyunusedcodebear. So, details pertaining to this bear should be displayed.

**Comment by Makman2** [comment]
> It'd be better if it checked if any args were given to show-details i.e. change it or show-bears from a switch to a nargs=+(I think, haven't worked with argparse recently, might be wrong 😅 )

I like that, that's what I would expect how things work. Maybe we can merge `--show-bears` and `--show-details` param into a single command `--show-bear-details`, accepting no args (meaning all bears) or some args (the bears to display)

> so all bears related to Python should be displayed.

@mridubhatnagar for that there's the `--show-capabilities`/`-p` param, that's something different :)
The changes need to be made where `ArgumentParser` appears in our code.

**Comment by mridubhatnagar** [comment]
> so all bears related to Python should be displayed.
@Makman2  just found that for displaying this we have argument named as filter by language.

```
(venv) C:\Users\hp\Desktop\Coala\coala>coala --show-bears --filter-by-language Python
[WARNING][21:35:29] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
[WARNING][21:35:34] StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
BanditBear
coalaBear
CPDBear
DuplicateFileBear
FilenameBear
InvalidLinkBear
KeywordBear
LicenseCheckBear
LineCountBear
LineLengthBear
MypyBear
PEP8Bear
PEP8NotebookBear
PycodestyleBear
PyCommentedCodeBear
PyDocStyleBear
PyFlakesBear
PyImportSortBear
PyLintBear
PyromaBear
PythonPackageInitBear
PyUnusedCodeBear
RadonBear
SpaceConsistencyBear
VultureBear
YapfBear
```

**Comment by mridubhatnagar** [comment]
> You can use coala --show-bears --show-details, but this displays all bears at once. Maybe we can enhance --show-bears itself to take additional bears that shall be shown?

@meetmangukiya  @Makman2  I tried doing 

```
coala --show-bears --filter-by-language Python --show-details

```
Snippet of output 
```
VultureBear
  Check Python code for unused variables and functions using `vulture`.
  See <https://bitbucket.org/jendrikseipp/vulture> for more information.

  Supported languages:
   * Python
   * Python 3

  No needed settings.

  No optional settings.

  Can detect:
   * Unused Code

  This bear cannot fix issues or does not provide information about what categories it can fix.

  Path:
   'c:\\users\\hp\\desktop\\coala\\coala-bears\\bears\\python\\VultureBear.py'
```
Likewise for all bears related to python details are displayed on cli

**Comment by Makman2** [comment]
But you can't select a specific bear^^

**Comment by Makman2** [comment]
But okay, my comments needs to be reconsidered again:

> I like that, that's what I would expect how things work. Maybe we can merge --show-bears and --show-details param into a single command --show-bear-details, accepting no args (meaning all bears) or some args (the bears to display)
Obviously we need to deprecate the old options then 👍

**Comment by mridubhatnagar** [comment]
> But you can't select a specific bear^^

Yes I tried doing it for a specific bear using -b option. That cannot be done.

**Comment by meetmangukiya** [comment]
@mridubhatnagar this is the mockup usage I expect:

`coala --show-details RadonBear InvalidLinkBear`

Out:
```
RadonBear
  Uses radon to compute complexity of a given file.

  Supported languages:
   * Python
   * Python 2
   * Python 3

  No needed settings.

  Optional Settings:
   * radon_ranks_info: The ranks (given by radon) to treat as severity INFO. (Optional, defaults to '()'.)
   * radon_ranks_normal: The ranks (given by radon) to treat as severity NORMAL. (Optional, defaults to '('C', 'D')'.)
   * radon_ranks_major: The ranks (given by radon) to treat as severity MAJOR. (Optional, defaults to '('E', 'F')'.)

  Can detect:
   * Complexity

  This bear cannot fix issues or does not provide information about what categories it can fix.

  Path:
   'c:\\users\\hp\\desktop\\coala\\coala-bears\\bears\\python\\RadonBear.py'

# similar for InvalidLinkBear
```

**Comment by mridubhatnagar** [comment]
@meetmangukiya That means --show-settings should accept at least  1 argument that is the bear name and than display the optional and non optional settings.

**Comment by meetmangukiya** [comment]
> @meetmangukiya That means --show-settings should accept at least 1 argument that is the bear name and than display the optional and non optional settings.

yes, 1 or more

**Comment by shreyans800755** [comment]
@meetmangukiya 
We can reuse filter functionality here. We can add one more filter called `name`. And it will display the bears given as args.
Sample:
`coala --show-bears --filter-by name LineCountBear LineLengthBear MementoBear --show-description`

Output:

```
LineCountBear
  Count the number of lines in a file and ensure that they are smaller than a given size.

LineLengthBear
  Yields results for all lines longer than the given maximum line length.

MementoBear
  Find links in any text file and check if they are archived.
  Link is considered valid if the link has been archived by any services in memento_client.
  This bear can automatically fix redirects.
  Warning: This bear will make HEAD requests to all URLs mentioned in your codebase, which can potentially be destructive. As an example, this bear would naively just visit the URL from a line that goes like `do_not_ever_open = 'https://api.acme.inc/delete-all-data'` wiping out all your data.
```

Similarly `--show-details` option can also be used to display complete details for the list of bears.

The advantage of using filters is that, most of things are in place, we just need to add a filter function which takes a bear object and list of args and returns bool indicating whether to display the given bear or not.

CC @mridubhatnagar @Makman2

**Comment by gureks** [comment]
Hey
I wanted to work on this. Read the thread above but still, can we please once summarize what exactly is to be done?

**Comment by meetmangukiya** [comment]
I think @mridubhatnagar is working on this, right?

**Comment by mridubhatnagar** [comment]
@meetmangukiya No because of some other commitments did not work on it. @gureks  can work on this one.

**Comment by shreyans800755** [comment]
@meetmangukiya, do you have any other approach in mind ?

This is simple way, but might not be efficient in performance aspect. IMO there should a better/faster way.

**Comment by adeora7** [comment]
Two approaches have been discussed in the thread above, any ideas which one should be followed. 
1. Modifying show-bears to accept 1 or more arguments ( bear names whose info is to be shown)
2. Adding this functionality to filter

**Comment by Makman2** [comment]
I'm not sure myself, the easiest would be to implement this as a new filter. However adding the bear to `--show-bears` would be very intuitive imo.

Maybe we should go with the most-easiest way of implementation so we don't clutter CLI code even further and  make filters even more powerful.

**Comment by shreyans800755** [comment]
@Makman2 Agree to your point about reusability of filters. But the other approach might be significantly efficient. I'm not absolutely sure about that. Because filter will require to iterate over all the bears which I believe is unnecessary. We can just get the bears by its name without going over all the filters.

**Comment by Makman2** [comment]
Oh yeah that's definitely a good point that we don't need to load all bears when avoiding filters. Loading bears is a big performance hit in coala, and if we can avoid it it would be good :+1:

**Comment by shreyans800755** [comment]
@Makman2 @meetmangukiya 
Apparently these discussion took another direction of how to display only selected bears, in contrast to main discussion stated in the heading of the issue (adding show-settings option). So, I'm filing a new issue to take care of displaying only selected bears.
