### ISSUE TITLE
Nextgen-Gen Bears: Make bear dependencies and requirements instance-bound, not class-bound

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4436]
Then we have the flexibility to choose dependencies depending on section settings. This could be beneficial for e.g. `TextLintBear` (introduced in https://github.com/coala/coala-bears/commit/d09c8f9f1f58ac39491caa2c36019067948bcf97). Depending on the settings, different plugins/rules are necessary.

Inspired by this comment on gitter:
> >     and maybe coala/coala#1079 should be re-opened; that would provide a fairly safe way to allow bears to add a optional 'language' setting which would default to whatever linguist detects
>
> what do you think about re-opening this? the problem is that bears usually start supporting only a single language, then a mandatory language parameter is added, which is a breaking change (we did this in 0.8 iirc for a few bears).
> I dont like the idea of running linguist in coala; the alternative would be to create a "missing setting bear dependency" so a setting can be pre-filled by a LinguistBear if not set in .coafile

But instead of adding a separate `missing_setting_dependency` field, we allow more flexibility by controlling the needed dependencies inside `__init__` of a bear.

**Comment by Makman2** [comment]
I think this needs still some discussion if we really want it.

**Comment by sils** [comment]
@Makman2 my opinion: do whatever is simpler in your architecture

**Comment by sils** [comment]
for language dependent stuff might make a lot of sense :+1:

**Comment by Makman2** [comment]
It would be something on top of the architecture, it's actually not next-gen-core-bound, but I thought to make it in one go (as this is another bear feature we could promote for next-gen).

**Comment by Makman2** [comment]
Actually some ideas how this would work:

Basically the core would access `bear.REQUIREMENTS` (or however the field is called) instead of `type(bear).REQUIREMENTS`. We can then use the old approach of static dependencies as well as dynamic dependencies.

However, we need to tweak `Bear` to copy the list of dependencies once we create a new bear, as class members are still class-bound even when accessed from an instance:
```
>>> class X:
...  reqs = [1,2,3]
... 
>>> X().reqs
[1, 2, 3]
>>> X().reqs.append(4)
>>> X.reqs
[1, 2, 3, 4]
>>> 
```
This would be little overhead on bear-instantiation-side, but acceptable imo (we are not going to instantiate 1 million bears with 1 million dependencies).

If performance improvement is needed, we can implement a copy-on-write list/set, only creating a new list/set when modifying it.

(PS: Interestingly Java has something like this built-in: `CopyOnWriteArraySet` or `CopyOnWriteArrayList`, see e.g. https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArraySet.html)

**Comment by Makman2** [comment]
The same would apply for `Bear.DEPENDENCIES`.

**Comment by Makman2** [comment]
(Actually I have mixed `Bear.REQUIREMENTS` and `Bear.DEPENDENCIES`, but it would definitely work for both. Flexible requirements and dependencies are both useful)

**Comment by Makman2** [comment]
I think we definitely want this, I've seen the need for it again in https://github.com/coala/coala-bears/pull/1919/commits/8ce30dde1970016e7c7fc4d69f47d34cdd286640. We should run bears only with most minimal package overhead as possible, so users have less to download + more space on disk + faster loading times.

**Comment by Makman2** [comment]
Split up into two issues:
- https://github.com/coala/coala/issues/4560
- https://github.com/coala/coala/issues/4561
