### ISSUE TITLE
Add AspectList.exclude

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#4438]
Extend AspectList class to have `excludes` attribute that hold list of aspect that marked as exception of the list. Trying to access aspect or subaspect of item in `excludes` will always give False/None.

```.python
>>> Metadata not in AspectList([Root], excludes=[Metadata])
True
>>> AspectList([Root], excludes=[Metadata]).get('metadata')
None
```

This feature will be used to excluding an aspect (to "deactivate") that was defined in user's coala configuration.

area/aspects

**Comment by userzimmermann** [comment]
@adhikasp @jayvdb Like mentioned in https://github.com/coala/coala/pull/4439#pullrequestreview-48442715 : Better `exclude` instead of `excludes`
