### ISSUE TITLE
Newcomers_Guide.rst: Step 6 out of place bold text

### ISSUE THREAD

**Issue by JohnMoutafis** [coala/coala#4442]
Out of place bold text exist in `Step 6` section of the `Newcomers_Guide.rst` documentation:

![screenshot from 2017-07-04 16-13-13](https://user-images.githubusercontent.com/2430971/27831667-56c189a4-60d4-11e7-88a2-fe723dcba1bc.png)

and shows in the navigation menu as well:

![screenshot from 2017-07-04 16-18-49](https://user-images.githubusercontent.com/2430971/27831731-97a4b1f8-60d4-11e7-8144-60d8d4aeb7a6.png)

**Comment by sidharthskumar** [comment]
can i work on this?

**Comment by JohnMoutafis** [comment]
@sidharthskumar remember to do a Pull Request for your commit!

**Comment by sidharthskumar** [comment]
i have just done my first pull request please let me know the status after reviewing them .
