### ISSUE TITLE
HiddenResult constructor should allow all parameters of Result

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4454]
The `HiddenResult` objects should work more like real `Result`.  i.e. if the data in the `HiddenResult` has a line/col, it should have an `affected_code`.

The suitability of the other `Result` constructor parameters should be evaluated on a case-by-case basis, but they should all be made available at once, so the order of the parameters is similar.

The missing parameters should be added after `contents` to be backwards compatible.
difficulty/low
Opened by @jayvdb

**Comment by jayvdb** [comment]
This is an intermediate step towards https://github.com/coala/coala/issues/2582 .
The current `HiddenResult` objects should work more like real `Result`.  i.e. if the data in the `HiddenResult` has a line/col, it should have an `affected_code`.

The suitability of the other parameters should be evaluated on a case-by-case basis.

**Comment by gurpreetsingh00885** [comment]
@jayvdb I wanna fix this one. Can you help me out on how to do this?

**Comment by gurpreetsingh00885** [comment]
"The suitability of the other Result constructor parameters should be evaluated on a case-by-case basis, but they should all be made available at once, so the order of the parameters is similar."

How do I do that @jayvdb ?

**Comment by gurpreetsingh00885** [comment]
@jayvdb please review #4667
