### ISSUE TITLE
Validate language setting

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4463]
The `language` setting is used for accessing the `Language` definitions.

Currently two bears use this, `AnnotationBear` (and three dependent bears) and `MypyBear`.  They have their own tests for this value.

Those bears currently define the setting as `language: str`.  They should be able to define a setting `language: Language` (or similar), and have automatic validation occur, with the tests for that validation being done in the coala repository.

Also as part of the aspects project, `language` will be used behind the scenes in coala even when bears do not explicitly use the `language` setting.  The validation of the setting needs to occur in a consistent location, with consistent error messages, whenever the `language` setting is *used* (but there should be no error if `language` has an invalid value but it isnt being used at all).

note there is more complicated work occurring elsewhere wrt aspects & languages (e.g. https://github.com/coala/coala/issues/4147).  This task is strictly about ensuring all `language` setting validation results in the same error message , and that validation only occurs once per `Section`.

**Comment by adhikasp** [comment]
Correction, as part of aspects project, `language` will always need to be validated (and shown error) IF coala is run under "aspect-mode" because it will become the basis of bear selection, even if none of the selected bear will use `language`.

**Comment by adhikasp** [comment]
Correction, in aspect-mode `language` should still thrown error if invalid because it will became the basis of bear selection (based by aspect capability and language supported by bear).

**Comment by jayvdb** [comment]
This was raised due to https://github.com/coala/coala/pull/4397#discussion_r127374759

**Comment by jayvdb** [comment]
See also https://github.com/coala/coala-bears/issues/1635

**Comment by adhikasp** [comment]
@jayvdb what is the preferred behavior if validation fail? Does we just throw error log or drop to interactive input for users to correct it?

**Comment by Makman2** [comment]
You don't have to deal with the error behaviour specifically, as you will write a type-converter function that will just check whether the passed language string is valid or not. If it's not valid, you throw some error (I don't know the exact error type now, you can look that up in other type-converter funcs), and coala will propagate the properly up to the user :+1:

**Comment by Makman2** [comment]
Ah it should be a `ValueError` I believe :+1:

**Comment by adhikasp** [comment]
Oh yeah right, I was thinking of doing it in `ConfigurationGathering` instead of type-converter

**Comment by adhikasp** [comment]
If I understand thing correctly, writing `language:my_language_converter` in bear `run` method will NOT automatically validate it using the converter function because that is just [function annotation that doesn't do anything](https://code.tutsplus.com/tutorials/python-3-function-annotations--cms-25689). [PEP 3107](http://legacy.python.org/dev/peps/pep-3107/)

So to validate it, we either need to call the converter inside run method (which is against this issue main point because it need to be done in coala) OR do it somewhere in coala's configuration phase. Am I correct?

**Comment by adhikasp** [comment]
^ disregard above. I am imagining things.
