### ISSUE TITLE
pip3 install coala-bears doesn't install coala binary

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4464]
No idea why.

Found in testing with @clstaudt
Opened by @sils

**Comment by sils** [comment]
@clstaudt can you give us your pip version?

**Comment by clstaudt** [comment]
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

**Comment by Makman2** [comment]
Can't reproduce in a docker environment. If problem still persists, feel free to reopen :)
(Maybe some virtualenv problem)
