### ISSUE TITLE
Newcomers_Guide.rst: Tell people to sign into Gitter with Github, not Twitter

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala#4466]
The Gitter section should tell people to log into Gitter with their Github account and not with Twitter, as we use the Github username for the automated stuff that corobo does.

**Comment by palash25** [comment]
I am a beginner and I would like to work on this. Do I need to make the proposed changes in the ** Step 1. Meet the Community and Get an Invitation to the Organization ** section of the ** Newcomers_Guide.rst ** file.

**Comment by Makman2** [comment]
Where it's appropriate @palash25 ;)
