### ISSUE TITLE
ConfigurationGathering.py: gather_configuration uses sys.argv directly

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala#4474]
`gather_configuration` uses `sys.argv` directly [here](https://github.com/coala/coala/blob/master/coalib/settings/ConfigurationGathering.py#L394). This creates problems, when using pytest with any kind of arguments. 

For example when targeting the tests directly with `pytest -k ConfigurationGatheringTest` we get: 

```
/usr/lib/python3.5/argparse.py:2381: SystemExit
---------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------
usage: coala [-h] [-v] [-C] [--ci] [--json] [--format [STR]] [-c FILE] [-F]
             [-I] [-s [FILE]] [--disable-caching] [--flush-cache]
             [--no-autoapply-warn] [-b NAME [NAME ...]] [-f FILE [FILE ...]]
             [-i FILE [FILE ...]] [--limit-files FILE [FILE ...]]
             [-d DIR [DIR ...]] [-V] [-L ENUM] [-m ENUM] [-N] [-B]
             [-l LANG [LANG ...]] [-p LANG [LANG ...]] [-D] [--show-details]
             [--log-json] [-o FILE] [-r [RELPATH]] [-S SETTING [SETTING ...]]
             [-a] [-j JOBS] [-n] [--debug]
             [TARGETS [TARGETS ...]]
coala: error: unrecognized arguments: -k
```

This makes it impossible to run the config gathering tests in a subset. 

I wonder if there is a way around using `sys.argv` directly here.

**Comment by khanchi97** [comment]
@NiklasMM I run that same command `pytest -k ConfigurationGatheringTest` and it's not throwing any error?

**Comment by NiklasMM** [comment]
Hm... it may have been fixed in the meantime.

**Comment by khanchi97** [comment]
So should we close this issue?
