### ISSUE TITLE
Newcomer_Guide.rst: Clarify push command

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala#4485]
The [newcomer guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes) asks people to push their stuff with `git push myfork`, which is not enough if they have never pushed before.

It needs to be `git push -u myfork <branchname>`

**Comment by susg** [comment]
I would like to be assigned to the issue.

**Comment by pulkonet** [comment]
@NiklasMM is this still open?

**Comment by NiklasMM** [comment]
No, the issue is assigned and there is an open pull request.
