### ISSUE TITLE
Command "corobo" not found.

### ISSUE THREAD

**Issue by susg** [coala/coala#4492]
### Coala bot replies : Command "corobo" not found

 In the [Newcomers_Guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes), in several places we find the use of command "corobo" to take the help of coala-bot. But in gitter chat when used "corobo" , it replied : Command "corobo" not found.

**Comment by Makman2** [comment]
CC @meetmangukiya

**Comment by Makman2** [comment]
Looks like a bug in corobo (have missed that this is the normal coala repository). Migrated issue to https://github.com/coala/corobo/issues/220.
