### ISSUE TITLE
Move @filter code into FilterHelper

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4494]
This avoids annotating filter functions with `@filter`. One file less to maintain.

**Comment by Makman2** [comment]
CC @shreyans800755

**Comment by shreyans800755** [comment]
@Makman2 Is label `area/core` appropriate ? Is this really part of core ?

**Comment by Makman2** [comment]
Maybe `area/cli`?

**Comment by meetmangukiya** [comment]
Am I reading this correctly: `@filter` :O filter is python standard function which anyhow takes two arguments, a function that indicates whether to include a entity or not, and another an iterable..

Did you override standard `filter` function :P ?

**Comment by Makman2** [comment]
yes the name was reused^^ however it is not the same as the built-in `filter` function. Another reason to remove our `@filter`.

**Comment by shreyans800755** [comment]
@meetmangukiya I wasn't aware of built-in filter. May be with this PR, we can rename it.

**Comment by Makman2** [comment]
> May be with this PR, we can rename it.

With this PR we remove it altogether ;)

**Comment by S2606** [comment]
@shreyans800755 should the code be inside filterhelper class?

**Comment by shreyans800755** [comment]
@S2606 
> should the code be inside filterhelper class?

No, no need to keep it inside the class. Keep it outside - at the module scope.
FYI: There's already another issue which is putting everything outside class.

**Comment by Makman2** [comment]
> No, no need to keep it inside the class. Keep it outside - at the module scope.
FYI: There's already another issue which is putting everything outside class.

Actually I thought to inline it into `FilterHelper.apply_filter`. Just moving this function to module scope still requires to annotate filter functions with `@filter`.

**Comment by shreyans800755** [comment]
@Makman2 
I still don't get the purpose behind removing `@filter` annotaion. Is it bad to have annotation ?

**Comment by Makman2** [comment]
- 1 line extra code for each new filter
- makes the functions not usable by anything else than the `FilterHelper` (as `@filter` totally changes the function signature)
- as @meetmangukiya mentioned, `filter` is a built-in name we shouldn't shadow
- the logic will be removed once nextgen comes (still takes a while, but less work to do by me once the time has come ;) )

**Comment by atultherajput** [comment]
@S2606 
Are you working on this issue? If not I would like too work on it.
CC: @Makman2

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by atultherajput** [comment]
@shreyans800755 @Makman2 
I am not sue what to do with @filter code as there is no FilterHelper class. Please guide for this patch.

**Comment by shreyans800755** [comment]
@atultherajput 
Have a look at https://github.com/coala/coala/issues/4494#issuecomment-320441279.
Another issue (closed now) has removed all the functions from `FilterHelper` class to module scope. So, the file `FilterHelper` is still there. You can move stuff to the same file.

**Comment by atultherajput** [comment]
@shreyans800755 
I had created a PR https://github.com/coala/coala/pull/4729 for this issue. I had moved code to `FilterHelper` but I didn't change function name. Please help on how to inline code to `FilterHelper.apply_filter`.

**Comment by Makman2** [comment]
Just put the insides of the function directly into the places where it's used, that's what inlining code means :)

**Comment by atultherajput** [comment]
New PR for this issue https://github.com/coala/coala/pull/4829

**Comment by anctartica** [comment]
please assign this to me @Makman2

**Comment by Makman2** [comment]
Reassigned due to inactivity.
