### ISSUE TITLE
InvalidFilterException: Add convenience methods generating messages

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4495]
The `__init__` method could take parameters that construct a message conveniently:
```
def __init__(self, filter_name=None, available_filters=None):
    pass
```
And use it accordingly where filters are present.

**Comment by Makman2** [comment]
CC @shreyans800755

**Comment by ayush1999** [comment]
I'd love to work on this.
@Makman2 @shreyans800755  Can you tell me how to proceed?

**Comment by Makman2** [comment]
The exception itself shall build the messages that are currently used inside the filter procedures. For that build an appropriate `__init__` function with appropriate parameters.

**Comment by newbazz** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
@ayush1999 you want to get it going again? Or can I reassign? ;)

**Comment by ayush1999** [comment]
I'm on it! Sorry for the delay.

**Comment by newbazz** [comment]
So are you woking on it? @ayush1999

**Comment by ayush1999** [comment]
Yeah! I'll amend the PR shortly. Sorry for the delay. (was caught up in some other work)

**Comment by aashutoshrathi** [comment]
@newbazz Should I create these files (tests/parsing/FilterTest.py, coalib/parsing/InvalidFilterException.py and coalib/parsing/FilterHelper.py) again?

**Comment by newbazz** [comment]
It sud have been created!!

**Comment by aashutoshrathi** [comment]
Can you explain what exactly needs to be changed, in which file?

**Comment by Makman2** [comment]
Please use `git grep` to look for the keywords mentioned in the issue description, then you'll find everything. If you don't understand an issue completely on your own, rather pick a new one :)

**Comment by jayvdb** [comment]
@shreyans800755 @Makman2 , we have two PRs here:
https://github.com/coala/coala/pull/4821
https://github.com/coala/coala/pull/4610
I'll let you guys sort this one out.
