### ISSUE TITLE
Put FilterHelper functions into module scope

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4497]
All `FilterHelper` functions are `classmethod`s, thus an instance is not necessary (and also never used), so a class is the wrong design approach. Another layer of indirection is not useful, so I would pledge to remove the class and put everything into the above module.

**Comment by Makman2** [comment]
CC @shreyans800755

**Comment by ayush1999** [comment]
@Makman2 There are various files. Can you tell me which one are you talking about?

**Comment by Makman2** [comment]
`FilterHelper.py` :+1:

**Comment by shreyans800755** [comment]
@ayush1999 Are you still working on this ?
If not, I can take it over. I think its better to close this asap as it is affecting public API for filtering bears.
