### ISSUE TITLE
Implement `--filter-by` in other coala entrypoints

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4499]
... like `coala --json`.

**Comment by Makman2** [comment]
@shreyans800755 assigned you as this is the next imminent step for filtering :)

**Comment by shreyans800755** [comment]
@Makman2  Isn't `coala-json` executable deprecated ? Or you're talking about `coala --json` ?

**Comment by Makman2** [comment]
oh yeah `coala --json` :+1:

(changed the issue description)

**Comment by shreyans800755** [comment]
Are there any other entrypoints that we are targetting ?

**Comment by Makman2** [comment]
`coala --ci`
`coala --json`
`coala --format`
that should be all of them ;)

**Comment by shreyans800755** [comment]
Do we really need to do anything for `coala --ci` ?
I think commands like `coala -B --filter-by ...` are always non-interactive.

**Comment by Makman2** [comment]
Good point :+1:
