### ISSUE TITLE
Root.Spelling aspect clean up

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala#4502]
Add Spelling.GeneralWordSpelling, Spelling.CompanySpecificWordSpelling. refactor Root.Spelling aspect and remove coalaCorrect and aspectsYEAH; `CompanySpecificWordSpelling` is a more generic aspect,
that can do what `coalaCorrect` and `aspectsYEAH` do and
even more given `specific_word`.

**Comment by jayvdb** [comment]
Spelling is part of natural language, so shouldnt we have a higher level in the tree for either NaturalLanguage or Readability?

We have long had LanguageToolBear which covers lots of natural language problems, and have other bears which can detect Grammar (TextLintBear & WriteGoodLintBear), translation errors (DennisBear), and AlexBear is about bad words.

**Comment by jayvdb** [comment]
I see Grammar is in [the cEP 10 tree](https://github.com/coala/cEPs/commit/3c5ec9785b03be715624e22873951a48b2aa035a#diff-dc65288ae3b8f48bf19e685ea3460ad6R107) as a separate sibling of Spelling.  Hmm.  But where does AlexBear and DennisBear fit into the tree?

**Comment by Asnelchristian** [comment]
Completely agree with that, i mean having Spelling and Grammar under the same aspect

**Comment by Asnelchristian** [comment]
hmm they do much more than Spelling and Grammar, maybe we should add something like TextQuality
