### ISSUE TITLE
DocBaseClass: Move the class to a different file

### ISSUE THREAD

**Issue by SanketDG** [coala/coala#4507]

**Comment by troublemagnet** [comment]
@SanketDG Which class are you talking about?

**Comment by SanketDG** [comment]
this https://github.com/coala/coala/blob/master/coalib/bearlib/languages/documentation/DocBaseClass.py

**Comment by SanketDG** [comment]
First this should be renamed to DocumentationExtraction.py then only the class `DocBaseClass` should be moved to a new file `DocBaseClass.py`

Each file should have different test files, so this will cause some redundant tests but that is okay.

Ping on gitter if you need help with this.
