### ISSUE TITLE
Newcomer_Guide.rst: some changes in step 4

### ISSUE THREAD

**Issue by susg** [coala/coala#4509]
Step 4 of [Newcomer_Guide.rst](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes) says :

> Before committing your changes, please check that you are indeed in a development branch created in  **step 4**.

 
It should be step 3 because in that step we are creating our development branch.

**Comment by snakevenom04** [comment]
I made a pull request with the change you specified.
I hope thats alright ?

**Comment by snakevenom04** [comment]
I split the two commits i put in that one pull request, and changed the heading of the pull request to a more informative one.
Thanks !

**Comment by rattandeep1998** [comment]
Hey,
Can I work on this issue ??

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Makman2** [comment]
@rattandeep1998 please ping me on gitter once you've accepted the org invitation.
