### ISSUE TITLE
Spelling mistake Alernative in gather_configuration docstring

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4518]
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=59732bd951915d962af6b31d)

**Comment by snakevenom04** [comment]
SHA for commit : 00ae92160be4a3c8abf79532949828262dbe9eb1
I made a pull request with the change you wanted.
I had made a pull request before this for a different issue ( #4509 ) so it merged the commit in that.
Is that alright ? or do I do something else ?

**Comment by AMR-KELEG** [comment]
@snakevenom04 I think you should create two separate pull requests for the issues https://github.com/coala/coala/issues/4518 and https://github.com/coala/coala/issues/4509.

**Comment by snakevenom04** [comment]
Done. I split the two commits into two different pull requests. 
All cool ?
