### ISSUE TITLE
Public API broken by PR 4240

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4519]
coala/coala#4240 broke `coala-quickstart`.

It removed public API functions

- `coalib.settings.ConfigurationGathering.get_filtered_bears` (replacing it with `get_all_bears`) and
- `coalib.collecting.Collectors.filter_section_bears_by_languages`

This needs to be fixed, or reverted.

cc @satwikkansal

**Comment by Makman2** [comment]
Definitely fixed, no reverted.

`filter_section_bears_by_languages` can be replaced with
```python
local_bears, global_bears = FilterHelper.get_filtered_bears(
    'language', ['language1', 'language2', ...])
```

**Comment by jayvdb** [comment]
This has also broken the docker:
https://travis-ci.org/jayvdb/docker-coala-base/builds/256362638#L9177

**Comment by jayvdb** [comment]
@Makman2 , this was part of a public API.  It shouldnt be broken; that breaks other peoples projects, which two days before a GSOC end of phase is quite serious.  Please can we patch coala to restore it?

**Comment by Makman2** [comment]
Hmm I haven't considered those functions being public API...

Okay let's revert, we implement compatability functions with deprecation notes :+1:

**Comment by Makman2** [comment]
CC @shreyans800755

**Comment by satwikkansal** [comment]
Thank you @jayvdb for fixing it quickly :)
