### ISSUE TITLE
Bear.py: Replace an by a in docstring

### ISSUE THREAD

**Issue by AMR-KELEG** [coala/coala#4520]
In the docstring of the Bear.py file - Line 31 (https://github.com/coala/coala/blob/master/coalib/bears/Bear.py#L31):

The indefinite article **a** should be used instead of **an** such that:
`This is the base class for every bear. If you want to write an bear, you`
is replaced by
`This is the base class for every bear. If you want to write a bear, you`

**Comment by anmol-1602** [comment]
I would like to work on this issue

**Comment by Makman2** [comment]
@Stropek still working on it?

**Comment by Stropek** [comment]
@Makman2 I'll wrap it up today.
