### ISSUE TITLE
load_configuration docstring has two "arg_list"

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4533]
difficulty/newcomer
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5973eb4f81cd9a5d7e9b5d7c)

**Comment by adeora7** [comment]
Can you please explain the issue a bit more. @jayvdb

**Comment by SanketDG** [comment]
@adeora7 In the documentation of the function load_configuration in ConfigurationGathering, `arg_list` is mentioned twice. Should be mentioned once with the appropriate description

**Comment by ayush1999** [comment]
I'd love to be assigned on this issue.

**Comment by ayush1999** [comment]
@adeora7 Sorry to say, But I have already opened a PR.

**Comment by adeora7** [comment]
@ayush1999  they clearly mention in the docs that you need to get the issue assigned to yourself. I doubt they will merge it. Anyway I will create a pull create, if yours gets merged, I will pick another. :)

**Comment by Makman2** [comment]
Yeah it seems like `args` was accidentally called `arg_list` again :+1:
