### ISSUE TITLE
Store "tests/bear_tests" bear count in a variable in tests.TestUtilities

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4545]
This number needs to be used in many locations. c.f. https://github.com/coala/coala/pull/4532
difficulty/low
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5975473542d2f6102587f2a5)

**Comment by adhikasp** [comment]
I'll take this one (gitter is down so I can't ask corobo)
