### ISSUE TITLE
documentation_extraction_testdata default.py incorrectly labels strings as docstrings

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4566]
`tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py` contains

```python

"""
Docstring with layouted text.
    layouts inside docs are preserved.
this is intended.
"""


""" Docstring inline with triple quotes.
    Continues here. """

```

That is incorrect based on the definition at https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring

Please revise the text to call them an unassigned string literals, and remove mention of 'doc' anywhere in the enclosed text, or just remove them as they are not particularly useful.

They are noops.  Junk.  Not readily available in the python model (even accessing them using `inspect` is going to be painful).  i.e. Dead code. cc @RJ722 & @jendrikseipp . This might be a good stretch goal, if vulture doesnt already do this.  It is hard, as it requires a good understanding of docstrings.

**Comment by ayush1999** [comment]
I'm working on this.

_Sent from my Lenovo P1a42 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jendrikseipp** [comment]
I think checking incorrect docstrings is out of vulture's scope. It probably should be done by https://pypi.python.org/pypi/pep257.

**Comment by shreyateeza** [comment]
Hello I am new here. Let me take this. Just me let me know what things I have to do next.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Makman2** [comment]
@shreyateeza I've raised the difficulty level as I think this issue is not so easy. Feel free to pick another one ;)

**Comment by RJ722** [comment]
So, are we going to add a `pep257` bear?

**Comment by Makman2** [comment]
No it's about improving our current documentation parsing facilities to conform with PEP257 :+1:

**Comment by ManthanKeim** [comment]
@jayvdb can it be assigned to me ?
