### ISSUE TITLE
Exit status not set when bear failed to run

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4567]
As seen with https://github.com/coala/coala-bears/issues/1955 , GitCommitBear fails but the exit status is not set.

```
[nltk_data] HTTP Error 403: Forbidden.
[WARNING][11:21:39] Bear GitCommitBear failed to run. Take a look at debug messages (`-V`) for further information.
```

https://travis-ci.org/jayvdb/coala/jobs/258099527#L1651

**Comment by NiklasMM** [comment]
This can probably be fixed quite easily by promoting the log entry from warning to error, since coala exits with an error status if more than 0 errors were logged. (See #3905 )

**Comment by jayvdb** [comment]
Ya, I think this case should be an error, not a warning, especially in --non-interactive mode.

**Comment by palash25** [comment]
I am interested in this issue. Could anyone direct me to the concerned files.

**Comment by NiklasMM** [comment]
A global search in the codebase for the warning message posted above reveals that it's likely raised about [here](https://github.com/coala/coala/blob/master/coalib/bears/Bear.py#L309)

**Comment by palash25** [comment]
So the `warn()` function in the `if`-`else` construct needs to be changed to `err()` function so that the bear terminates. Am I right?

**Comment by NiklasMM** [comment]
it has nothing to do with the bear terminating, but the rest is correct.

**Comment by palash25** [comment]
And the `err()` function will have the same message as the warning?

**Comment by NiklasMM** [comment]
If you think it still makes sense. I think it can be left unchanged.
