### ISSUE TITLE
FilterHelper.apply_filter: Add docstring

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4583]
`FilterHelper.apply_filters` has a docstring, but all the work is done in `FilterHelper.apply_filter`, which doesnt have a docstring yet.

See https://github.com/coala/coala/blob/master/coalib/parsing/FilterHelper.py#L9

**Comment by Makman2** [comment]
CC @shreyans800755

**Comment by Makman2** [comment]
Still on it @ShadowSphynx ?

**Comment by ShadowSphynx** [comment]
No, @Makman2 I am not. I just wanted some help on documentation, since it was my first time working on any kind of issue like that. But couldn't find any...

**Comment by Makman2** [comment]
If you generally need help with getting started feel free to ask on our [gitter channel](https://gitter.im/coala/coala) :) And reading our newcomer-guide is also a good start :+1:

**Comment by ShadowSphynx** [comment]
I did ask for help. But got no response.

**Comment by Makman2** [comment]
I would recommend to just retry ;)

**Comment by shreyans800755** [comment]
@ShadowSphynx May be your message was just missed. As makman2 said, please ask again. You can address it me or makman2 on gitter or here if you have any query regarding this issue so that its not missed again.

**Comment by Abishek10** [comment]
@Makman2 I would like to work on it. Can you reassign it to me ?

**Comment by Abishek10** [comment]
@ShadowSphynx Still working on it ?

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by ayush1999** [comment]
@Makman2 This looks to be inactive for a long time now. Can I take this up?

**Comment by Makman2** [comment]
@ayush1999 please assign yourself with corobo ;)

**Comment by RJ722** [comment]
@Abishek10 are you still working on it?
