### ISSUE TITLE
NextGen-Core: Document new features

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4584]
- `GlobarBear` now called `ProjectBear`, and `LocalBear` now called `FileBear`
- New bear type: `DependencyBear`
- How to work with dependency-bears
  - Dependency results can be accessed with `self.dependency_results`
  - Using `DependencyBear`
  - Writing a dependency bear
    - You don't need to provide actual `Result` instances, other picklable types do work
- Usage of instance-bound `Bear.BEAR_DEPS`
- ~~Usage of instance-bound `Bear.REQUIREMENTS`~~
- How to override `Bear` and define task scheduling yourself
- For external use: How to use `Core.run`
  - How to instantiate bears and how the core basically works (dependency-resolution, task scheduling, ...)
  - The `result_callback` and when it's called (not called on implicit dependency-results)
  - Using different executors
- Caching

EDIT by @Makman2:
"Usage of instance-bound `Bear.REQUIREMENTS`" is not ready yet and has conceptual problems.

**Comment by Makman2** [comment]
Blocked until the nextgen-core is completely done and merged.

**Comment by Makman2** [comment]
The issue is blocked, and I think you have not enough experience for this issue. It requires in-depth knowledge of the not yet completely developed nextgen core :)

**Comment by palash25** [comment]
Hey @Makman2 I have been reading a lot of code (especially your commits) related to the Nextgen-core so I would like to take this up once this is unblocked to get a deeper understanding of the core.

**Comment by Makman2** [comment]
You can actually already start. There's already plenty to document, and I would open new issues after that one to document specific changes still to be done.

**Comment by palash25** [comment]
Hey @Makman2 do you want me to make new rst fiiles in the docs/Developers folder for this or the coala/documentation repo because I already see some documentation about this on https://api.coala.io/en/latest/coalib.core.html#module-coalib.core.Core

**Comment by Makman2** [comment]
The API docs are auto-generated from the docstrings, those are already up-to-date. This issue is about a separate document in the docs/Developers folder describing all features, so it should serve as an entry-point for external readers :+1:

**Comment by Makman2** [comment]
And it can especially highlight some (or maybe all) key differences from the current, old core
