### ISSUE TITLE
Improve usage string for --filter-by option in coala help

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4597]
Opened by @shreyans800755 at [gitter/coala/coala](https://gitter.im/coala/coala?at=597e33841c8697534a72ec0d)

**Comment by shreyans800755** [comment]
`[--filter-by FILTER_BY [FILTER_BY ...]]` -> `[--filter-by FILTER_NAME FILTER_ARGS1 FILTER_ARGS2 ...]`

**Comment by shreyans800755** [comment]
CC @Makman2

**Comment by troublemagnet** [comment]
Isn't is that way only? For example in FilterTest.py, line no. 26, '--filter-by', 'language', 'java'?

**Comment by Makman2** [comment]
Currently it's the actual usage, but the issue is about improving the help string :) (rephrased the issue title :D)

**Comment by troublemagnet** [comment]
Since --filter-by-language is deprecated, should there be no instances of it at all?

**Comment by Makman2** [comment]
No `filter-by-language` is kept, although it's deprecated it shall appear in the help (it's I believe technically impossible with `argparse` to remove a parameters from help but still support it during parsing).

**Comment by troublemagnet** [comment]
So what exactly does help string mean?

**Comment by Makman2** [comment]
The help string appears when you type `coala --help` :) It's generated by `argparse.ArgumentParser` when you add arguments to coala (like `--filter-by` or `--non-interactive`).

**Comment by Makman2** [comment]
Refer to https://docs.python.org/3/library/argparse.html :)

**Comment by troublemagnet** [comment]
But the help string doesn't contain the usage of --filter-by! It contains the usage of -l and -p.

**Comment by troublemagnet** [comment]
Did the issue mean update usage of --filter0by-language?

**Comment by Makman2** [comment]
Yeah right it doesn't appear directly there, but at the beginning of the coala command usage.
> ```
> usage: coala [-h] [-v] [-C] [--ci] [--json] [--format [STR]] [-c FILE] [-F]
>              [-I] [-s [FILE]] [--disable-caching] [--flush-cache]
>              [--no-autoapply-warn] [-b NAME [NAME ...]] [-f FILE [FILE ...]]
>              [-i FILE [FILE ...]] [--limit-files FILE [FILE ...]]
>              [-d DIR [DIR ...]] [-V] [-L ENUM] [-m ENUM] [-N] [-B]
>              [-l LANG [LANG ...]] [--filter-by FILTER_BY [FILTER_BY ...]]
>              [-p LANG [LANG ...]] [-D] [--show-details] [--log-json] [-o FILE]
>              [-r [RELPATH]] [-S SETTING [SETTING ...]] [-a] [-j JOBS] [-n]
>              [-A] [--debug]
>              [TARGETS [TARGETS ...]]
> ```

**Comment by troublemagnet** [comment]
Oh okay, isn't this a new issue? Shouldn't like the other arguments it should be there too?

**Comment by Makman2** [comment]
That's what the issue is about.

> Shouldn't like the other arguments it should be there too?

What do you mean?

**Comment by troublemagnet** [comment]
The usage of filter-by should be explained in the usage string ?

**Comment by Makman2** [comment]
The `[--filter-by FILTER_BY [FILTER_BY ...]]` part shall be modified to something like `[--filter-by FILTER_NAME FILTER_ARGS1 FILTER_ARGS2 ...]`

**Comment by troublemagnet** [comment]
ya ya that I get. Shouldn't it's usage come when we do coala --help?

**Comment by Makman2** [comment]
yeah exactly

**Comment by shreyans800755** [comment]
@troublemagnet 
`--help` shows detailed description of all the options available. In contrast, `Usage` string only shows available options and format of args. We don't need to change help as part of this issue, we just need to fix `Usage` string.

**Comment by troublemagnet** [comment]
@shreyans800755 From what I understood about help string (which I'm guessing is same as usage string) appears when you type coala -h or coala --help. I don't know how to see the usage string you're talking about. Can you please tell me?

**Comment by shreyans800755** [comment]
@troublemagnet Hit `coala --help` in terminal and you'll see that `Usage` string is part of help and in fact it is the first thing being printed.

`Usage` string just suggests how args should be placed without describing its meaning. Meanwhile, `help` is much more verbose version of it, which not only contains `Usage`, but also describes all the options in details.

**Comment by Makman2** [comment]
Right there at the top, directly below where you've typed the `coala --help` command :)

**Comment by troublemagnet** [comment]
Yes and how do I see the screenshot that you posted?

**Comment by Makman2** [comment]
That's no screenshot ;)

**Comment by troublemagnet** [comment]
No the image that you posted earlier which comtained the usage of
filter-by, how do I see that?

**Comment by Makman2** [comment]
Can't follow you, the only larger snippet I've posted is here:
https://github.com/coala/coala/issues/4597#issuecomment-319675128

**Comment by troublemagnet** [comment]
Yeah that one. How can I see that?

**Comment by SanketDG** [comment]
Can you elaborate? What do you mean?

Do you meant how to see the usage string in the codebase? Or in the application?

**Comment by shreyans800755** [comment]
@troublemagnet It looks like you're viewing it only from email. Login to github and visit the link again. You should be able to view it then.

**Comment by troublemagnet** [comment]
I'm really sorry for being so confused. I was talking about this -
usage: coala [-h] [-v] [-C] [--ci] [--json] [--format [STR]] [-c FILE] [-F]
             [-I] [-s [FILE]] [--disable-caching] [--flush-cache]
             [--no-autoapply-warn] [-b NAME [NAME ...]] [-f FILE [FILE ...]]
             [-i FILE [FILE ...]] [--limit-files FILE [FILE ...]]
             [-d DIR [DIR ...]] [-V] [-L ENUM] [-m ENUM] [-N] [-B]
             [-l LANG [LANG ...]] [--filter-by FILTER_BY [FILTER_BY ...]]
             [-p LANG [LANG ...]] [-D] [--show-details] [--log-json] [-o FILE]
             [-r [RELPATH]] [-S SETTING [SETTING ...]] [-a] [-j JOBS] [-n]
             [-A] [--debug]
             [TARGETS [TARGETS ...]]
@Makman2 sir posted a screenshot if this. My question is - how can I view this string(the one that I pasted in this comment and whose picture sir had sent)?

**Comment by Makman2** [comment]
`coala --help`
The 10 first lines are this usage string:
`coala --help | head -10`

**Comment by troublemagnet** [comment]
![screen](https://user-images.githubusercontent.com/28952053/29034181-154abd96-7bb5-11e7-9beb-62fde2b02b8e.png)

This is what I'm confused about. Why are the strings different for both of us?

**Comment by Makman2** [comment]
Probably different versions of coala:
```
bash-4.4# coala --version
0.12.0.dev99999999999999
```

**Comment by troublemagnet** [comment]
Omg yes the different versions caused the confusion. :) The screenshot that you attached had the usage of --filter-by too and I wouldn't get. So all this time I was thinking that I did't get the usage string right!
Now I get it though, it's just I wanted to know the priority, because I've a few assignments from college too. Is it fine if I do it this weekend?

**Comment by shreyans800755** [comment]
@troublemagnet 
This should be very small change. This weekend is fine.
But if this issue remains inactive for long, you might be unassigned by one of the maintainers (just FYI) .

**Comment by troublemagnet** [comment]
You can review now :)
