### ISSUE TITLE
--no-color produces color in CLI

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4618]
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5985d5f2210ac2692057ad85)

**Comment by jayvdb** [comment]
The color appears only in Results with a diff.

**Comment by Nosferatul** [comment]
@jayvdb when I added the colors for letters i used the same function and the same color.
```
console_printer.print(letter, color='blue', end='')
```
It's not something new, this is used in other output (e.g filename, required setting)

**Comment by Nosferatul** [comment]
so i couldn't find evidence that `--no-color` doesn't work after my pr (on master). This is http://imgur.com/bw47yCo . On the left side `coala` is running on the master branch and on the right side, coala for users. http://imgur.com/XVe9yJI -> lxterminal for a user that uses `coala`. The color problem was before my prs.
