### ISSUE TITLE
Diff display doesnt show tabs

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4619]
I am 99% sure that tabs were previously visuallised using a unicode arrow, in results with a diff. Now they are gone.

Results without a diff do show the unicode arrow.

**Comment by Nosferatul** [comment]
can you give me a screenshot of it with the arrow? I don't think i saw arrows when I used it :)

**Comment by Nosferatul** [comment]
The problem is that whatever I deleted from output I added back in https://github.com/coala/coala/pull/4420

**Comment by Nosferatul** [comment]
You wanted to say `+` and `-` ?

**Comment by Nosferatul** [comment]
I couldn't find the arrows. http://imgur.com/8jHMSpW on the right is `coala` for users and on the left coala for developers. I can't find the arrows in the code either in the output. I'll close this, if you want to open it, please provide an screenshot with the arrows in the output.
