### ISSUE TITLE
ConfigurationGathering: Add option to silent warnings for get_filtered_bears method

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala#4621]
Required for https://github.com/coala/coala-quickstart/issues/163

**Comment by Makman2** [comment]
Looks like a dupe of #2775
And #2775 already has a PR: https://github.com/coala/coala/pull/3779

**Comment by satwikkansal** [comment]
#3779 doesn't add `silent` parameter to `get_filtered_bears` method which is used by coala-quickstart. I just need to pass an optional `silent` parameter to pass to `get_filtered_bears` method which is eventually passed to the function `load_config_file` which actually displays the warnings.

**Comment by satwikkansal** [comment]
Ah, https://github.com/coala/coala/pull/3779/files#diff-8ecc903ba7ecebebacc61f64149f8eb7R360 sets `silent` to `True`, which should be sufficient for https://github.com/coala/coala-quickstart/issues/163 I guess

**Comment by Makman2** [comment]
If you've something additional done that would be nice to solve this issue, maybe sync up with @incorrectusername to improve his/your PR :)

Anyway, can be closed then?

**Comment by satwikkansal** [comment]
Yep, I'll get in touch with @incorrectusername. Closing this :)
