### ISSUE TITLE
coala crashes when running it on Windows (TEST ISSUE, IGNORE IT)

### ISSUE THREAD

**Issue by sils** [coala/coala#4635]
Something with permissions... it just crashes, man!

(Information for others, we're staging this for a demo right now ;) this issue will be gone soon, we just needed high issue numbers)

**Comment by fneu** [comment]
Hey! I'm sorry you experienced a crash. Could you please send me the traceback, the command you ran, and your configuration?

**Comment by sils** [comment]
Hi @fneu ,

sorry got caught up in other stuff, you know how this happens...

Here's the traceback when I run `coala --files test.pl --bears=PerlCriticBear` without any additional configuration:

```
d:>Traceback (most recent call last):
File "", line 1, in 
File "c:\program files\python35\lib\multiprocessing\spawn.py", line 100, in spawn_main
new_handle = steal_handle(parent_pid, pipe_handle)
File "c:\program files\python35\lib\multiprocessing\reduction.py", line 86, in steal_handle
_winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
```

Although it's a similar error to #2911 as suggested by @gitmate-bot, the workarounds posted on that one don't seem to help in my case.
