### ISSUE TITLE
MalformedComment: line -> line number

### ISSUE THREAD

**Issue by SanketDG** [coala/coala#4644]
in the docstring of `__init__`

**Comment by aasiya13** [comment]
how can i fix this. need more detail..

**Comment by Nosferatul** [comment]
MalformedComment is a class in `DocumentationComment.py` file. please check it out and do the necessary changes.

**Comment by aasiya13** [comment]
i'm sorry. i'm really new to open source. please help me with what changes to do.

**Comment by SanketDG** [comment]
@aasiya13 Assuming you have found the `__init()__` method of `MalformedComment`, you need to change the description of `param line` in the docstring

**Comment by RJ722** [comment]
@aasiya13 You need to change the word `line` to `line_number` appearing here: https://github.com/coala/coala/blob/0f8158322cc2bedc14967ea8d3d03bfad908f659/coalib/bearlib/languages/documentation/DocumentationComment.py#L299-L312

If you need any help regarding git, github workflow hop onto the gitter channel. :)

**Comment by aasiya13** [comment]
yes

**Comment by sanketnavin** [comment]
@aasiya13 are you still working on this issue, since there has been no update since 19 days

**Comment by sanketnavin** [comment]
I would like to work on this issue. Can I get assigned to this?

**Comment by aasiya13** [comment]
sure. i'm really busy at this moment

**Comment by SanketDG** [comment]
@sanketnavin read the [Newcomer's Guide](https://coala.io/newcomer) and you can just assign this to yourself

**Comment by mansiagarwal451** [comment]
I am new to open-source. I tried cobot assign but it didn't work. Is there someone working on this? If not, can I get assigned to this issue?

**Comment by SanketDG** [comment]
@mansiagarwal451 you used `cobot`, you have to use `corobo`

**Comment by mansiagarwal451** [comment]
I tried `corobo assign coala/coala#4644` and got the following message:
`The issue is already assigned to someone. Please check if the assignee is still working on the issue, if not, you should ask for reassignment.`

**Comment by aptrishu** [comment]
Yeah it is already assigned to @aasiya13 , can you find another issue ?

**Comment by aptrishu** [comment]
Unassigned @aasiya13 due to inactivity.
