### ISSUE TITLE
DocstyleDefinition.py: Align docstring

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4645]
Align `__init__` docstring.
difficulty/newcomer
Opened by @damngamerz at [gitter//damngamerz](https://gitter.im//damngamerz?at=599708f3614889d47560e298)

**Comment by RJ722** [comment]
@utkarshmttl are you still working on it?

**Comment by ayush1999** [comment]
@utkarshmttl @Makman2 Can I take this up?

**Comment by khanchi97** [comment]
Hello @ayush1999 
@utkarshmttl is still assigned to this issue.I think before working on an issue and making a PR, first you should be assigned to that issue.

**Comment by ayush1999** [comment]
Sorry for the confusion, but it looks like he hasn't be active for some time now. Its better if this issue is reassigned to me for now. :)
