### ISSUE TITLE
Update coala help - Use `filter-by language` instead of `--filter-by-language` in examples

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4652]
`--filter-by-language` is deprecated in favor of the more universal `--filter-by` flag. The old flags needs to be changed in the code examples on all help pages.

Opened by @shreyans800755 at [gitter/coala/coala](https://gitter.im/coala/coala?at=5998ca7e80d90ca02418cee9)

EDIT by @Makman2:
Added a little description.

**Comment by shreyans800755** [comment]
`$ coala --show-bears --filter-by-language C Python` -> `$ coala --show-bears --filter-by language C Python`
because `--filter-by-language` is deprecated

**Comment by shreyans800755** [comment]
CC @Makman2  
Please mark it as newcomer.

**Comment by pancha13** [comment]
I'm new  to open source. please help me to understand this issue.

**Comment by Makman2** [comment]
@pancha13 I've updated the title and main description of the issue :+1:

**Comment by Dumidu921** [comment]
thanks @Makman2 .. Please help to find where is that?? which file?

**Comment by Nosferatul** [comment]
should be in `ConfigurationGathering.py`

**Comment by Dumidu921** [comment]
@Nosferatul  
        local_bears = filter_section_bears_by_languages...... is found instead to "filter-by language"

**Comment by Nosferatul** [comment]
sorry, coalib/parsing/DefaultArgParser.py

**Comment by Dumidu921** [comment]
@Nosferatul  found it. thanks...

**Comment by Dumidu921** [comment]
I have run the test and it gives this  result. 
================== 113 failed, 734 passed in 166.77 seconds ===================

**Comment by shreyans800755** [comment]
@Dumidu921 
Changes shouldn't break any of the tests. See if you're running it in proper environment. Make sure most of the tests pass before you make changes. (Some tests may fail depending on modules available on your local and also OS that you're running on)

However, you're stuck, feel free to push the changes and we can help you then.

**Comment by Nosferatul** [comment]
install `requirements.txt` and `test-requirements.txt` with `pip3 install -r requirements.txt` use venv http://api.coala.io/en/latest/Developers/Development_Setup.html

**Comment by Dumidu921** [comment]
I already push the changes.

**Comment by Makman2** [comment]
Btw: To not miss something, you can do `git grep "--filter-by-language"` so you can see all occurrences that appear in help files.

**Comment by shreyans800755** [comment]
@Dumidu921 
> I already push the changes.

Add link to this issue in the commit message to make it easily traceable from here.

**Comment by atultherajput** [comment]
Is this issue still open? If yes, then I would like work on it.

**Comment by Makman2** [comment]
@Dumidu921 still working on this?

**Comment by shreyans800755** [comment]
@atultherajput You can assign yourself now if you want to work on it.

**Comment by atultherajput** [comment]
Yeah sure. But how to assign this?

**Comment by shreyans800755** [comment]
@atultherajput 
On our https://gitter.im/coala/coala channel, enter `corobo assign https://github.com/coala/coala/issues/4652` and you should be assigned if you're member of the community. If not, please read http://coala.io/newcomer.

**Comment by atultherajput** [comment]
@shreyans800755 
Please review this PR https://github.com/coala/coala/pull/4709
