### ISSUE TITLE
Output message in json if args.json is true and no bears to show

### ISSUE THREAD

**Issue by shreyans800755** [coala/coala#4668]
Following ~~https://github.com/coala/coala/pull/4650~~ https://github.com/coala/coala/pull/4726.

With above PR, `--filter-by` option is enabled for json and format entrypoints of coala. But when there are no bears to show, following message is shown even if `json` flag given in the command:
```
No bears to show. Did you forget to install the `coala-bears` package? Try `pip3 install coala-bears`.
```

Update the message to be in proper format according to args given in the command - json or format or plaintext

CC @Makman2 

EDIT by @Makman2:
Point directly to blocking issue.

**Comment by Makman2** [comment]
Maybe we just put no message at all into the empty Json list?

**Comment by shreyans800755** [comment]
Should be good. What about `--format` ?

**Comment by Makman2** [comment]
hm maybe also no output? As it's some "systematic" output usually for other executables

**Comment by Asalle** [comment]
Why the status is `blocked`?

**Comment by Makman2** [comment]
Good point, I probably forgot to remove it.

**Comment by Makman2** [comment]
Ah wait no the relevant PR is still not merged.

**Comment by shreyans800755** [comment]
@Asalle This issue is waiting for https://github.com/coala/coala/issues/4499 to be resolved.

**Comment by nvzard** [comment]
Is this issue still blocked?

**Comment by shreyans800755** [comment]
@nvzard not any more. Please assign yourself and go ahead with the work. Ping me on PR or gitter for review once you have some progress to be shown

**Comment by shreyans800755** [comment]
Also feel free to ask doubts if you're not clear with something.

**Comment by nvzard** [comment]
Thanks for supporting :)

**Comment by nvzard** [comment]
Can you please tell me what message do you want it to show?

**Comment by nvzard** [comment]
Sorry I was busy with my exams. I've started working on this issue. Can you please tell me what message do you want it to show?

**Comment by Makman2** [comment]
☝️ https://github.com/coala/coala/issues/4668#issue-252743994
> With above PR, --filter-by option is enabled for json and format entrypoints of coala. But when there are no bears to show, following message is shown even if json flag given in the command:
> `No bears to show. Did you forget to install the `coala-bears` package? Try `pip3 install coala-bears`.`

> Maybe we just put no message at all into the empty Json list?

**Comment by shreyans800755** [comment]
@Makman2 Please remove the blocked label.
