### ISSUE TITLE
support ignoring whole directories

### ISSUE THREAD

**Issue by RJ722** [coala/coala#4673]
Currently, `ignore` in `.coafile` takes in glob patterns as input, but it does not ignore whole directory.

For example:
`.coafile` looks like this:

```
[Default]
ignore = tests/foo/test_files/*
```

and there is no need of test_files being a python package because it is not being loaded as a package, but `PythonPackageInitBear` would complain:
```
Project wide:
**** PythonPackageInitBear [Section: PythonPackageInit | Severity: NORMAL] ****
!    ! Directory "tests/foo/test_files" does not contain __init__.py file
```

Even passing `ignore = ignore = tests/foo/test_files/` or `ignore = ignore = tests/foo/test_files` does not works.

**Comment by RJ722** [comment]
CC @Makman2

**Comment by shreyans800755** [comment]
@RJ722 @Makman2 
We can ignore whole directory like this:
```
[Default]
ignore = tests/foo/test_files/**
```

It is used in coala project itself at https://github.com/coala/coala/blob/master/.coafile#L45.

But I think its nice to have it with single * (asterisk) at the end.

**Comment by Makman2** [comment]
Does this also work for the case described above @RJ722 ?

**Comment by Makman2** [comment]
I would say if someone wants to ignore the whole directory, I would also support doing
```
[Default]
ignore = tests/foo/test_files/
# or without slash
ignore = tests/foo/test_files
```

**Comment by RJ722** [comment]
> Does this also work for the case described above @RJ722 ?

Hmm No, not working. :-(

**Comment by himankpathak** [comment]
@RJ722 have you also tested the following changes as stated by Makman2 ?

```
[Default]
ignore = tests/foo/test_files/
# or without slash
ignore = tests/foo/test_files
```
Or should I test them?

**Comment by RJ722** [comment]
Yeah, tried it. Not working.

**Comment by Makman2** [comment]
It was a suggestion for what we should support, it's not working yet @himankpathak

**Comment by himankpathak** [comment]
@Makman2 oh okay, I will keep looking for a workaround.

**Comment by mrtes** [comment]
Well, there is a function `collect-dirs`, which seems to be intended for that purpose.
It is just unused currently. 
I guess we could first collect directories with this function (and ignore directory globs), then collect the files for the remaining directories and ignore the file patterns.

**Comment by mrtes** [comment]
Slightly more complicated than I imagined, but still doable.
Is there a reason we don't use the native "glob" and "fnmatch" modules?

**Comment by Makman2** [comment]
@mrtes there was some reason, I think some little syntax extensions which are very common (but maybe not standard glob?). However if you don't see we have to keep them (maybe Python 3.4+ do support what we need), let's have a different issue to remove our stuff :+1:

**Comment by mrtes** [comment]
I would have to investigate, but the functions provided by the "glob" and "fnmatch" modules _seem_ to match the solutions that are currently implemented.
-> I will open an issue for investigation/replacement.
