### ISSUE TITLE
FilterHelper.apply_filters: Correct parameter reference in docstring

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4694]
Currently states:
```
Returns bears after filtering based on ``args``. It returns
intersection of bears if more than one element is present in ``args``
list.
```
`args` should be replaced with `filters`.

**Comment by Raman1121** [comment]
I would like to work on this issue. Please assign this to me. @Makman2

**Comment by alphadose** [comment]
@Makman2 can I get re-assigned to this issue ?

**Comment by Makman2** [comment]
Seems there's a PR and it was approved, I'm just merging it. So the issue in fact done :)
