### ISSUE TITLE
DecoratorsTest: Undefined name `BEAR_KIND`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4702]
Invoking `RunDecoratedBear.kind()` raises a `NameError` due to `BEAR_KIND` not being imported. However, `RunDecoratedBear.kind()` is unused in test.

**Comment by Makman2** [comment]
@adhikasp, is `kind()` actually necessary?

**Comment by adhikasp** [comment]
I am using `bear.executed()` method in tests, and that requiring the `kind` method to be implemented. If there is better way to implement that then I guess the `kind` could be removed.

**Comment by Makman2** [comment]
Does using `LocalBear` work?

**Comment by Makman2** [comment]
ping @adhikasp :)

**Comment by Makman2** [comment]
Task: Either try to use `LocalBear` for the test-bear, or just import `BEAR_KIND` properly :+1:
