### ISSUE TITLE
Coala link redirects to the incorrect page.

### ISSUE THREAD

**Issue by stellargo** [coala/coala#4706]
There is a link on the Coala website home page (https://coala.io/#/home) "Need more powerful analysis? Check the available bears!" where check should lead to "https://coala.io/#/languages" but instead redirects back to the home page again.
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
![coala](https://user-images.githubusercontent.com/27735438/30169913-488a4d52-940b-11e7-9f4b-2199f7bbded4.png)

**Comment by dhumketu** [comment]
I am a newcomer here. How can I take up this issue?
