### ISSUE TITLE
Update correct URL of "Get Involved" page in README file.

### ISSUE THREAD

**Issue by atultherajput** [coala/coala#4710]
Currently "Get Involved" link is pointed to http://coala.io/#!/getinvolved in README.rst file and gets automatically redirected to https://coala.io/#/home . Therefore URL need to be updated and point to https://coala.io/#/getinvolved .

**Comment by Anirudh257** [comment]
I can work on this.

**Comment by pulkonet** [comment]
@atultherajput  is this still open?

**Comment by atultherajput** [comment]
@pulkonet 
No @IamRaviTejaG already submitted a patch for this issue with this PR https://github.com/coala/coala/pull/4718
