### ISSUE TITLE
LocalBearTestHelper.execute_bear: Remove final return statement

### ISSUE THREAD

**Issue by sims1253** [coala/coala#4735]
There is a yield in line 47 and a return in line 54. As long as the try block doesn't encounter an error, both are reached. 

Sonarcube counts this as a breaking bug.

**Comment by Makman2** [comment]
It's not a bug, but it's unnecessary, because:
1. returning values in a generator usually makes no sense, as the return value can't be catched (or I recall it's only possible in the occurring StopIteration when done iterating)
2. the `return` is placed at the end of the function

**Comment by sims1253** [comment]
So is the return just not called if a yield is present?
If the return is called together with the yield that sounds like a mess coming your way.

**Comment by psinghal20** [comment]
Hi,
I would love to work on this issue if it is still unassigned and open.
From what I understood is in the case of an exception, the error is raised and message printed so the return statement is not required. Am I correct?

**Comment by Makman2** [comment]
No it has nothing to do with exceptions (except this `StopIteration` thing). The `return` statement is just obsolete and can be removed. If you want to know why, you can read up on generators in python, specifically about the `yield` keword :)

**Comment by SunflowerPKU** [comment]
> Hi,
> I would love to work on this issue if it is still unassigned and open.
> From what I understood is in the case of an exception, the error is raised and message printed so the return statement is not required. Am I correct?

Hi @psinghal20 ,

I am a Ph.D. student. I am doing research about **helping newcomers participate in OSS projects**. I noticed that many projects are using labels such as 'good first issue/bug, difficulty/newcomer' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?


I am looking forward to hearing from you soon. Thank you very much!
