### ISSUE TITLE
Interactions.fail_acquire_settings: Deprecate parameter `section`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4740]
`section` is unused and should be deprecated.

**Comment by alphadose** [comment]
Hello . May I take up this issue ?

**Comment by Abhi-khandelwal** [comment]
Hello  Can I work on this issue?

**Comment by 15BCS047** [comment]
@alphadose @Abhi-khandelwal  go through [new commer guide](https://coala.io/newcomer), there its given how to get assign to any issus
