### ISSUE TITLE
Useful Links : Add link for short tutorial of regex

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#4748]

**Comment by Makman2** [comment]
Just curious, where did you have encountered the need for `regex` in coala? :)
(I mean it's everywhere, however I for example thought about including that into the bear-writing-tutorials as there it's really essential)

**Comment by khanchi97** [comment]
yeah, i have also encountered the need in bear-writing-tutorial, but when i was going through `Useful-Links` page i got a link for `issue tracker` if someone wants to add any useful-link and that link is pointing in `coala` repo .Is this issue should be in `coala-bears` repo.

**Comment by khanchi97** [comment]
Okk we can also add this in bear-writing tutorials.

**Comment by rpanczer** [comment]
Hi guys, mind if I get this one? I can search for a useful `regex ` tutorial and add it in. This is going in `coala` `Useful-Links`, right?

**Comment by khanchi97** [comment]
I think it should be in both place in `useful-links` and in `writing-native-bears`. what do you say @Makman2

**Comment by Makman2** [comment]
Maybe this issue should be only for putting it into useful-links :+1: Let's file another issue if you like for putting something like that into the writing-native-bears guide :) That's easier for now

**Comment by rpanczer** [comment]
@Makman2 Ok, sounds good.
