### ISSUE TITLE
Writing-native-bears guide: Add link for short tutorial of regex

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#4753]

**Comment by kartikeys98** [comment]
Can I work on this issue?

**Comment by khanchi97** [comment]
sure and don't forget to use corobo to assign yourself to this issue.

**Comment by kartikeys98** [comment]
Does this look fine?

**Comment by RaiVaibhav** [comment]
@kartikeys98  first assign yourself to this issue by using corobo bot on on gitter platform

**Comment by kartikeys98** [comment]
Done. Is it okay now?

**Comment by RaiVaibhav** [comment]
@kartikeys98  you have to make a PR Pull request of the things you have committed,and also add a commit message in that,but first please refer to [new comer guide](https://coala.io/newcomer) you will get to know about many things there

**Comment by kartikeys98** [comment]
Okay, I squashed the commits and changed the commit message.
