### ISSUE TITLE
Remove Glossary from Writing_Tests and Add it to Testing_Bears

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#4755]
As you can see that `Glossary` should be in [Testing_bears](http://api.coala.io/en/latest/Developers/Testing_Bears.html) page instead of [Writing_Bears](http://api.coala.io/en/latest/Developers/Writing_Tests.html)
page.

**Comment by sonali0901** [comment]
Hello, I am a new contributor here and I'd like to fix this up. As per my understanding, updating docs/Developers/Writing_Tests.rst  and docs/Developers/Testing_Bears.rst should do the needful. Let me know if it'll work.

**Comment by khanchi97** [comment]
Hello @sonali0901 you are right,now the only thing that you have to do is assign yourself to this issue using `corobo` and go for it :+1:
