### ISSUE TITLE
Modifying Newcomer's guide : Add a general command to label a PR as process/pending review

### ISSUE THREAD

**Issue by soumya-ranjan7** [coala/coala#4766]
Under the Picking up an Issue section of Newcomer's Guide add a general command to label a PR as process/pending review using corobo.

**Comment by prnvdixit** [comment]
That command would be
```corobo mark pending <full_url>```
😃

**Comment by Kanav-7** [comment]
@soumya-ranjan7 Can I work on this issue?

**Comment by prnvdixit** [comment]
@Kanav-7 Head over to [Gitter Channel](https://gitter.im/coala/coala) and just type ```Hello World``` - That will get you started 👍 😄
