### ISSUE TITLE
Clear anomaly between “Fixes” & “Closes”

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#4769]
The commit guide doesn't make it clear when to use "Fixes" and "Closes" for documentation changes. The commit guide should be modified to convey that “Fixes” should be used only for those issues that are labelled “bug” - “Closes” works for pretty much everything else.

Label: initiatives/gci

**Comment by Makman2** [comment]
Duplicate of https://github.com/coala/documentation/issues/465 :)

**Comment by prnvdixit** [comment]
@Makman2 I think https://github.com/coala/documentation/issues/465 is related to amending ```Newcomer's Guide``` - I found that distinction between keywords is not clear in ```Commit Guide``` [here](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference) too 😉

**Comment by Makman2** [comment]
Probably it's best to put it into commit guidelines only, not to clutter the newcomer's guide even more.
