### ISSUE TITLE
Single PR for an issue

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#4770]
The Newcomer guide doesn’t specify that the contributor should try to submit only a single PR for each issue. It should convey that otherwise, it makes it tough for reviewers to see if previous changes have been accommodated in current commit or not.

Label: initiatives/gci

**Comment by Makman2** [comment]
Yeah that's probably good, smaller PRs = less review times :+1:

**Comment by nealkarpe** [comment]
Can I take this up?

**Comment by prnvdixit** [comment]
@nealkarpe It's labelled initiatives/gci :smile:

**Comment by nealkarpe** [comment]
@prnvdixit Whoops, my bad! :)

**Comment by jayvdb** [comment]
I think Step 5 is the right spot for this.

Step 6 assumes the Pull Request is ready for review, which is almost never the case.

After the Pull Request is created, CI runs, and often CI fails.  And bots do an automated code review, and respond on the Pull Request.

Step 5 needs to say that the developer needs to watch these automated systems until they finish, and fix their own PR. 

Lets increase the scope of this issue a bit, to 'ram' home the 'do not close your PR'.  (And then step 5 can be expanded more afterwards)

Something a bit like

"After you have created your Pull Request, automated systems will review your Pull Request, and will add comments on your Pull Request."

"This is *your* Pull Request.   It is *never* necessary to close your Pull Request.  Never!  A Pull Request is only a unique number assigned to you, and your branch on your fork.  You may be required to enhance your Pull Request, by modifying your branch on your fork.

"You must not delete your fork, delete your branch, close your Pull Request, start a new Pull Request, etc. All of those actions will break your Pull Request, and create a mess.

"It is *always* possible to modify your pull request using `git`.  If you do not want to learn `git`, and instead create a second pull request for the same issue, a maintainer will close your second pull request and will remove you from the coala organisation.
