### ISSUE TITLE
Newcomer's guide should limit one newcomer issue per contributor

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#4771]
The current Newcomer's guide doesn't directly imply that everyone should do "only one" newcomer issue. Edit docs so as to make "you should do only one newcomer issue" more implied.

Label: initiatives/gci

**Comment by rpanczer** [comment]
@prnvdixit I can take care of this one

**Comment by wisn** [comment]
Hello! May I take up this issue?

I think we may use ordered number list instead of unordered point list.

**Comment by Makman2** [comment]
Sure, please read our newcomer guide to get started ;)

**Comment by Makman2** [comment]
However, this is an `initiatives/gci` issue which is reserved for coming Google Code-In participants. Feel free to pick another issue that is not marked with `initiatives/gci` :)

**Comment by wisn** [comment]
Ah didn't see that. Alright @Makman2

**Comment by theOriginalMuktaka** [comment]
May I take up this issue? I am a Google Code-In participant.

**Comment by prnvdixit** [comment]
@theOriginalMuktaka Please, claim the same on GCI dashboard first :wink:

**Comment by theOriginalMuktaka** [comment]
Sure. Google has yet to review my parental consent, so I can't claim this task right away. I'll claim it when it is approved.

**Comment by theOriginalMuktaka** [comment]
Please assign me to this issue. I have claimed the task.

**Comment by Makman2** [comment]
@theOriginalMuktaka invited you to the org, please ping me once you've accepted so I can assign you ;)
(however this can take a while, back again in a few hours^^)

**Comment by theOriginalMuktaka** [comment]
The current file says:
```
    - merge a ``difficulty/newcomer`` Pull Request
    - review at least a ``difficulty/newcomer`` Pull Request
```
Does "doing only one newcomer issue" mean that you can merge only one newcomer PR and review more than one? Or does it mean that you can merge only one and review only one?
I have a feeling it is the former, but I thought I should ask first.
