### ISSUE TITLE
Fix Typo Mistake

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala#4793]
1.) In `Note` of step 2 in [New commer Guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html)
Replace `To see all of the corobo commands,` with `To see all of the corobo commands:`<br />
2.) Replace `cobot` with `corobo` in `Review.rst`.

Note: Before submitting any PR first read [New commer Guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html)

**Comment by RaiVaibhav** [comment]
This issue is only for `GCI students`

**Comment by abhinay01** [comment]
can i fix this issue?
I am a newcomer and want to learn more about coala and it's bears.

**Comment by nguptaa** [comment]
i m a newcomer. can i fix the issue ?

**Comment by susg** [comment]
This issue is for pre-university students taking part in Google Code In.

**Comment by RaiVaibhav** [comment]
No i will not accept any PR, this is only for GCI student I specially mentioned in comment that this issue is only for GCI parrticipant

**Comment by Dhruvadityamittal** [comment]
Can I fix this issue because I am a newcomer and I want to know more about Coala.

**Comment by prnvdixit** [comment]
@Dhruvadityamittal Are you planning to participate in GCI? :wink:
In either case, you can't take up the issue for now. GCI participants can take up this issue after commencement of GCI. :+1:

**Comment by Dhruvadityamittal** [comment]
So what type of issues I can take..

**Comment by prnvdixit** [comment]
Head to https://coala.io/chat and type **Hello World** there... you would be guided from there 😄

**Comment by RaiVaibhav** [comment]
Closing it moved to https://github.com/coala/coala/issues/4840
