### ISSUE TITLE
AppVeyor build fails

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4794]
https://ci.appveyor.com/project/coala/coala/build/1.0.10140/job/6u27rtxt162q7e0h

It seems like an upstream package was broken.

Tried to test it in a fedora docker container, but like the other Linux builds indicate, I can't reproduce. coala installs successfully there. Maybe it's Windows only.

**Comment by Makman2** [comment]
Couldn't reproduce on a clean Windows 10 virtual machine with Python 3.6.3. `coala` and `coala-bears` install without problems.

**Comment by Makman2** [comment]
I hooked into an Appveyor build with RDP, but inside a PowerShell session I can't reproduce either, coala installs normally (from pip and with `python3 setup.py install`). `%CMD_IN_ENV%` is used with the failing command, probably it alters the environment in such a way so that this error appears. Using normally a shell won't enable the same build environment.

**Comment by Makman2** [comment]
It seems there was recently a change in AppVeyor builds, that also affects Python 3.6:
https://www.appveyor.com/updates/

I also read up on https://github.com/requests/requests/issues/4006. The solution was to upgrade to a newer pip like 9.0.1, however this version is already installed.
Like always, I doubted setuptools as it's often involved in such special install-breakages, and it seems I was right: AppVeyor has currently version 18.2 installed (maybe it changed since the AppVeyor update on October 22nd). Requiring coala to install version >=19 seems to work.

**Comment by RaiVaibhav** [comment]
@Makman2  I think we have to add `sudo pip install -U setuptools` in `travis.yml` instead changing everytime when they release new update or correct me if i am miising something :smile:

**Comment by acashmkj** [comment]
The latest version of `setuptools` should be used due to upstream bug in `setupools`

**Comment by Makman2** [comment]
setuptools 19 seems to work, so i think it's currently safe to make it at least v19. People can still use newer versions of setuptools of they like. However, do you have a specific bug in mind? @acashmkj 

> I think we have to add sudo pip install -U setuptools in travis.yml instead changing everytime when they release new update or correct me if i am miising something 

We do install the minimum version on purpose i believe (not sure why). And we don't have to change it every time, I've just changed the minimum version, latest setuptools with the newest updates are still accepted by coala.
