### ISSUE TITLE
Add note discouraging CircleCI on forks

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4820]
http://api.coala.io/en/latest/Developers/Adding_CI.html 
Circle CI should only be enabled on forks to debug problems with Circle CI.
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=59f99ace81cd9a5d7e9ffe76)

**Comment by supriyanta** [comment]
please guide me how to fix it?

**Comment by acashmkj** [comment]
@jayvdb the note is already there. Do you want to enhance it ?

Note

Please refrain from enabling CircleCI on your fork since they use shared build pools. You can use TravisCI instead if you need access to private builds.

**Comment by supriyanta** [comment]
Yes!

**Comment by d3vil0p3r** [comment]
@supriyanta are you still working on this?

**Comment by rattandeep1998** [comment]
Hey,

Can I work on this issue ?

**Comment by RaiVaibhav** [comment]
@supriyanta , ping 
please assign yourself only to one `newcomer` issue, if you are facing in understanding of `issue`, contact for help on `gitter`.
There is already a open PR of yours on newcomer issue https://github.com/coala/coala-bears/pull/2123

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by shashank-b** [comment]
Please assign this issue to me.

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala/issues/4006
