### ISSUE TITLE
Writing_Native_Bears.rst:  Fix documentation

### ISSUE THREAD

**Issue by palash25** [coala/coala#4823]
In the second line of the second point in the [Communicating with the User](https://github.com/coala/coala/blob/master/docs/Developers/Writing_Native_Bears.rst#communicating-with-the-user) section of Writing_Native_Bears.rst change the first word of that line from **This** to **There** 

difficulty/newcomer initiative/gci

**Comment by pradeepgangwar** [comment]
I am working on this.

**Comment by jayvdb** [comment]
@sks444 , someone already said they are working on it, and they have a PR .. see above.
