### ISSUE TITLE
Add meta folder of Visual Studio Code to .gitignore

### ISSUE THREAD

**Issue by mrtes** [coala/coala#4835]
We already ignore meta folders for other IDEs/editors (e.g. Sublime).
Extending the .gitignore to include the meta-folder for VSCode (.vscode) allows developers to use this editor painlessly, without having to worry about accidentally committing this folder :)

**Comment by amitsin6h** [comment]
hello am new here. let me take this. Just me let me know what things I have to add in meta folder

**Comment by mrtes** [comment]
@amitsin6h The issue is already assigned to @parthboricha.
@parthboricha If you are finished you need to create a pull request for this commit. Currently it is just sitting in your branch :)

**Comment by prnvdixit** [comment]
The other PR of current assignee is closed due to inactivity - Maintainers, please assign this issue to @bhavishyagopesh

**Comment by Makman2** [comment]
Unassigned due to inactivity.
