### ISSUE TITLE
docs/Developers: Fix typo in Newcomers_Guide.rst

### ISSUE THREAD

**Issue by IpshitaC** [coala/coala#4840]
In last `Note` of `Step 2` of [Newcomer's Guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html), change `To see all of corobo commands,` to `To see all of corobo commands:`
Relevant file can be found [here](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst)

labels: initiatives/gci

**Comment by Vedarth** [comment]
I would love to solve this issue.

**Comment by RaiVaibhav** [comment]
@IpshitaC please update the issue 
maintainers please make label `initaitives/gci`

**Comment by IpshitaC** [comment]
Hey @Vedarth This is a GCI task, so if you are planning to participate in GCI this year, then you can take it up once it commences, but not before that 😄

**Comment by Mariatta** [comment]
Let me know how I can help :)

**Comment by IpshitaC** [comment]
@Mariatta could you please label this issue as `initiatives/gci` ? Thanks 😄

**Comment by Mariatta** [comment]
@IpshitaC done!

**Comment by nealkarpe** [comment]
@IpshitaC There is another instance of the word `cobot` in the file [PULL_REQUEST_TEMPLATE.md](https://github.com/coala/coala/blob/master/PULL_REQUEST_TEMPLATE.md). I just stumbled upon it and thought it would be relevant to add to this issue! :smiley:

**Comment by prnvdixit** [comment]
This should be a ```repeatable task``` IMO as there are multiple such corrections needed in different repos. But, point to be kept in mind is that - Some of them are in code/old-docs too (which needn't be changed). So, ideally there should be a list of files to be changed (most of them are PR template files though). Advanced github search might come handy in that 😉.

**Comment by jayvdb** [comment]
The `cobot` in the `PULL_REQUEST_TEMPLATE.md` needs to be dealt with separately, as it appears in 6 different repositories, including this repository.
I think the `PULL_REQUEST_TEMPLATE.md` in this repository should be fixed before GCI, because we have a 'create PULL_REQUEST_TEMPLATE.md` task, and that task should involve the students copying from the `PULL_REQUEST_TEMPLATE.md` in this repository, which should be of the highest quality.

**Comment by prnvdixit** [comment]
It ^^ should actually be 6 other i.e. total 7 repos - coala/coala-bears, coala/documentation, coala/emacs, coala/landing-frontend, coala/coala, coala/coala-html, coala/projects. https://github.com/search?p=2&q=org%3Acoala+cobot&type=Code (Review.rst and PR template in coala/coala and PR template in others)

**Comment by RaiVaibhav** [comment]
@prnvdixit  I also think making list(like a spread sheet in which we can also add the link of file/documentation) will be best so that assignee will changes only that part which needed , not in one which don't needed??

**Comment by vrishank97** [comment]
Can I be assigned this issue?

**Comment by Makman2** [comment]
You already have two issues assigned (with one being a newcomer issue too ;D)

**Comment by adi23arora** [comment]
Can I work on this issue?

**Comment by Makman2** [comment]
@adi23arora please ping me on gitter once you've accepted the invitation ;)
