### ISSUE TITLE
FilterTest.test_filter_by_unknown wrongly uses assertRaisesRegex

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4845]
`FilterTest.test_filter_by_unknown` executes coala in non-debug mode, checks return code, and then tries to check an exception that can never occur at that point:

https://github.com/coala/coala/blob/539a4e5c626e7ee839793ce5f29c62a96284359b/tests/parsing/FilterTest.py#L101-L110

It passes anyway because `assertRaisesRegex` provides a context manager meant to be used via `with` statement. That way the whole expression is just useless. The actual error message has to be found in `stdout`

This blocks https://github.com/coala/coala/pull/4821

And BTW: There is no local `filter` variable defined. It just refers to the `builtins.filter` function ;)

cc @aashutoshrathi @shreyans800755

**Comment by Makman2** [comment]
My bad, totally missed that. 😟
