### ISSUE TITLE
mention smart questions in newcomers guide

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4847]
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=5a06f92bdf09362e67f65528)

**Comment by RaiVaibhav** [comment]
Please refer to http://www.catb.org/esr/faqs/smart-questions.html

**Comment by Vedarth** [comment]
Can I work on this issue?

**Comment by RaiVaibhav** [comment]
@44rdvark  ping

**Comment by 44rdvark** [comment]
I'll do it in the next two days if it's fine with everyone.

**Comment by newbazz** [comment]
IMO this http://sol.gfxile.net/dontask.html should also be added.
PS. It was helpful for me so i suggested

**Comment by newbazz** [comment]
@Makman2 a new issue for that? will it be ok?
