### ISSUE TITLE
allow bears to be written in other languages

### ISSUE THREAD

**Issue by sils** [coala/coala#485]
especially supporting C libs would be cool.
- How do we want such a bear to look like?
- How does the technical integration work?

**Comment by Makman2** [comment]
Just expose members I think,
see https://wiki.python.org/moin/IntegratingPythonWithOtherLanguages

**Comment by sils1297** [comment]
@Makman2 could you make an example?

**Comment by AbdealiJK** [comment]
I was looking at gedits plugin api and was reminded of this. Maybe one way to do it would be to use gobject-introspection

**Comment by sils1297** [comment]
@AbdealiJK could you elaborate?

**Comment by abhsag24** [comment]
so considering @Makman2 's idea, IMO the best way to go about this would be first , to create Bridge modules for Bear, LocalBear, GlobalBear that'd interact with the python code and the user's bear and later also provide an interface for our API's like _StringProcessing_ and so on

**Comment by Makman2** [comment]
I'm not sure we want to expose our stuff.
1. It's the other way around: The external code exposes interfaces we latch in from python code side. This is now exposing python code to the external interface.
2. The main intention is also speed behind using different languages, as in C you don't want to use our `StringProcessing` stuff, as that's far too slow for C ;)
Also the python-call overhead to such routines would incur performance penalties^^

At least this would need quite some design consideration in manners of efficiency, code duplication, type matching (tuples in python maybe don't have an immediate counterpart inside the other language) and other capabilities that depend on the target language.

This idea could even go into another issue^^

**Comment by abhsag24** [comment]
@Makman2  but wouldn't exposing the other way round limit these Bears on functionality? they'd miss out on our awesome API?

**Comment by Makman2** [comment]
@abhsag24 which functionality do you want to have from coala, for example when using C?

**Comment by abhsag24** [comment]
@Makman2 `Results, Diff, Source/TextRange` these wouldn't be directly usable, but we'd need a wrapper around these atleast? just exposing C/C++ would mean we have to convert their outputs into results, it'd be awesome if we could expose our members and they can use atleast some parts of these classes

**Comment by Makman2** [comment]
These objects need to be considered anyway, as they are the core for result-serving. Maybe we should wait for an implementation and then see what other interfaces we can make available for the writer^^

**Comment by AbdealiJK** [comment]
Is this done now ? Can this be closed ?

**Comment by Makman2** [comment]
CC @Redridge

**Comment by jayvdb** [comment]
We have a json result bridge.  That is probably enough.  It still requires a thin bear, which provides metadata, but avoiding that would be hard to maintain, as it would require a well defined memory data structure for the metadata, whereas coala regularly adds new fields to the bear metadata.  Maybe revisit this in a few years.

The other option would be to provide the scaffolding so that a bear invoking a C library routine is 'easy', but then why not have a Python wrapper around the C library?
