### ISSUE TITLE
Need tests/parsing/FilterHelperTest.py as companion to FilterTest.py

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4864]
`FilterTest.py` tests bear filtering on a very high level by executing `coala`. An additional `FilterHelperTest.py` should be created for testing the internal features of `coalib.parsing.FilterHelpers` on a lower level. For example, there is currently no test that specifically checks that `InvalidFilterException` (which is currently about to be renamed to `BearFilterTest` by #4856) is raised, which is just not possible in the way `FilterTest.py` performs tests (at least not before #4649 is merged)

@mohit2872 Interested? :)

cc @Makman2 @shreyans800755

**Comment by mohit2872** [comment]
yeah, i am interested.

**Comment by mohit2872** [comment]
Is this issue raised? If yes, can you tell me that issue number?

**Comment by userzimmermann** [comment]
@mohit2872 This issue exists... We are commenting in here... So yes... It was raised... And has a number... Or what do you mean? ;)

**Comment by mohit2872** [comment]
I mean the link to issue raised.

On Tue, Nov 14, 2017 at 3:10 PM, Stefan Zimmermann <notifications@github.com

**Comment by shreyans800755** [comment]
@mohit2872 
This is the issue @userzimmermann is asking you about if you're interested to work on.

**Comment by pradeepgangwar** [comment]
@userzimmermann If @mohit2872 is not working on this. Can i work on this?

**Comment by pradeepgangwar** [comment]
@mohit2872 any update?

**Comment by Makman2** [comment]
Reassigned due to inactivity.

**Comment by saurabhkgp21** [comment]
@Makman2 , this issue is inactive from long time, if no one is working on this I would like to work on this.

**Comment by Makman2** [comment]
Last update on the PR was 7 days ago so let's ask ;)

@pradeepgangwar still working on it? ;)

**Comment by pradeepgangwar** [comment]
@saurabhkgp21 You can work on this. I got busy with some other issues and other stuff. ;). @Makman2 Please reassign.

**Comment by saurabhkgp21** [comment]
ping @Makman2

**Comment by sangamcse** [comment]
@saurabhkgp21, working on it?

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by sangamcse** [comment]
Please assign this to me. 😃
