### ISSUE TITLE
ConsoleInteraction: Remove unnecessary parameters from show_bear

### ISSUE THREAD

**Issue by shreyans800755** [coala/coala#4868]
From the comment at https://github.com/coala/coala/pull/4817#discussion_r148143217 in 
```
def show_bear(bear,
              show_description,
              show_params,
              console_printer,
              args):
```
parameters `show_description` and `show_params` are redundent as both of these can be easily derived from `args`.
We need to clean up these.

**Comment by shreyans800755** [comment]
Blocked until https://github.com/coala/coala/pull/4817 is merged.

**Comment by anuyog1004** [comment]
Can I take this if no one is working on it?

**Comment by shreyans800755** [comment]
@alphadose Are you still working on this ? If not, we can reassign this to @anuyog1004

**Comment by alphadose** [comment]
@shreyans800755 yes I am working on this. I started working only after your PR got merged. Been about 3 days I guess :3

**Comment by shreyans800755** [comment]
No problem. @anuyog1004, please find some other issue to work on . This is already taken at the moment.

**Comment by shreyateeza** [comment]
@alphadose Are you still working on this?

**Comment by alphadose** [comment]
@shreyateeza  my work is finished , just waiting for review :P

**Comment by jayvdb** [comment]
c.f. my rants at

https://github.com/coala/coala/pull/4948#issuecomment-352404883
https://github.com/coala/coala/pull/4948#discussion_r157926973

If you cant improve existing functions without breaking them, create a new function and deprecate the old one.  This is why designing extensibility at the beginning is so important.
