### ISSUE TITLE
Change cobot to corobo in Review.rst

### ISSUE THREAD

**Issue by Pratul1997** [coala/coala#4879]
For changing label we do `corobo mark wip <url>` but in documentation it is given `cobot mark wip <url>`

Replace `cobot` with `corobo` in [Review](http://api.coala.io/en/latest/Developers/Review.html).
Relevant file can be found [here](https://github.com/coala/coala/blob/master/docs/Developers/Review.rst)

**Comment by prnvdixit** [comment]
@Pratul1997 Close this issue - Duplicate of https://github.com/coala/coala/issues/4840. Please, take a look at existing issues before making new issues (GitHub advanced search comes handy in such cases). :smile:

**Comment by jayvdb** [comment]
It is better to have one issue per each file for newcomer issues.

**Comment by kiryteo** [comment]
Can I take up this issue?

**Comment by jayvdb** [comment]
@yashraj-Dhanuka, only Google Code-in students should take this issue.
