### ISSUE TITLE
google form link for promotion request  in Newcomers_Guide.rst is not showing.

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala#4880]
[Go to the link](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html)

difficulty/newcomer

**Comment by yashraj-Dhanuka** [comment]
@RaiVaibhav i have corrected the raised issue. Created a PR also . Actually i am new to github,was my contribution successful .

**Comment by Nshul** [comment]
can i work on this??

**Comment by RaiVaibhav** [comment]
@sanjeevbitx ping

**Comment by Makman2** [comment]
Reassigned due to inactivity.

**Comment by prnvdixit** [comment]
@Makman2 I will just leave this here :stuck_out_tongue:
https://github.com/coala/coala/pull/4961

**Comment by Nshul** [comment]
@Makman2 sorry to disturb you. But I am a newcomer and just out of curiosity I want to know how much time can it take to merge a PR after all the tests and reviews have been passed? Really Sorry to disturb you

**Comment by RaiVaibhav** [comment]
@Nshul  there is queue of `PR` waiting for Review, and In last `maintainer` have to take a last look before merging any approved PR.
You can check it at [coala.io/review](https://github.com/pulls?q=is%3Aopen+user%3Acoala+label%3A%22process%2Fpending+review%22+sort%3Acreated-asc)

**Comment by Nshul** [comment]
@RaiVaibhav thanks a lot
