### ISSUE TITLE
coalaCITest.setUp() defines unused attributes self.unescaped_coafile and self.coafile

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4885]
Recognized while creating https://github.com/coala/coala/pull/4883

https://github.com/coala/coala/blob/9de6241bc8cebcf32bffe773c6ebbb5018bfad6b/tests/coalaCITest.py#L13-L16

Since they have no relevant side-effects, those unused attributes should be removed

**Comment by shreyateeza** [comment]
I am new here. let me take this. Just me let me know what I have to do next.

**Comment by Makman2** [comment]
@shreyateeza you already have a newcomer issue assigned ;)

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by clarammdantas** [comment]
Hi! :)
I'm a new contributor, can I be assigned to this issue?

**Comment by clarammdantas** [comment]
I removed the unused variables and did a PR but it is failing all tests. After my changes I tested coala in my computer and ran the pytest, it was working fine. Can someone help me with this please?

**Comment by Mixih** [comment]
see https://gitter.im/coala/coala?at=5a45affa232e79134da162f4
