### ISSUE TITLE
No tests for coala --ignore

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4886]
Recognized while creating https://github.com/coala/coala/pull/4883

There should be added some tests for this cmdline option. This is its definition:

https://github.com/coala/coala/blob/4e0c88e5d5e575e6fd20b5abb437d0ef54cb6077/coalib/parsing/DefaultArgParser.py#L148-L150

**Comment by Thekiddiejsandpython** [comment]
Hi! I'm a coala newbie 😄 Do I make a fork, then make a pull request? Thanks 🍦 🕶  😀

**Comment by Thekiddiejsandpython** [comment]
I'm doing a task 4 GCI - google code-in

**Comment by Vedarth** [comment]
I would like to work on this issue. Kindly assign it to me. 😄

**Comment by userzimmermann** [comment]
@Vedarth Thanks for your interested! But please take a look @ https://github.com/coala/coala/pull/4930#pullrequestreview-90337947 before starting work on this

cc @Makman2

**Comment by anctartica** [comment]
@Vedarth are you still working on this?

**Comment by Vedarth** [comment]
@anctartica Yes I am.

**Comment by Vedarth** [comment]
@userzimmermann Thanks for your advice. It was really helpful. In https://github.com/coala/coala/pull/4930#pullrequestreview-90337947 you were against using `LineCountTestBear`. Apparently all we need to check is only
```
Executing section cli...
```
should get printed. So should I use some other testbear or just by checking the `stdout`?
