### ISSUE TITLE
Don't use re.escape for making windows paths work as config setting values

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#4890]
Many coala config settings, like those in a `.coafile` are file system paths. Like the `files` that shall be analyzed :) Those paths can and should always be OS-independently defined `with/unix/style/forward/slashes`

But when it comes to working interactively with coala in a Windows shell with path auto-completion, or when it comes to run coala's own tests in a Windows environment, there are `windows\style\paths\with\backslashes` to deal with

But in coala settings processing, backslashes are interpreted as escaping syntax for special characters, like in a Python string literal. So the backslashes from Windows paths just get lost. So far, this problem is solved by escaping the backslashes themselves when needed, but unfortunately using `re.escape`, which not only escapes backslashes but all non-alphanumeric characters

https://github.com/coala/coala/pull/4883 removes most of those `re.escape`s since it makes them obsolete. But some of them remain and, depending on the use case, either the escaping should instead be done with `coala_utils.string_processing.escape` as @Makman2 suggested in https://github.com/coala/coala/pull/4883#issuecomment-345545475 or the backslashes should be turned into forward slashes like https://github.com/coala/coala/pull/4883 does it with cmdline arguments

BTW: https://github.com/coala/coala/pull/4883 should be merged before doing this ;)

**Comment by jayvdb** [comment]
There are lots of existing issues about this.

**Comment by userzimmermann** [comment]
@jayvdb For example? :)

**Comment by Makman2** [comment]
If there's an older issue and it's not actively worked on, I would like to keep this one open instead and close the other one as it's very good described here.

**Comment by ishanSrt** [comment]
I see 47 instances of `re.escape()` being used
> depending on the use case

can someone give me an example in which either of the case is not feasible to use i.e.
1.) We can use `coala_utils.string_processing.escape` but not convert to `/`
2.) We can use `/` but not `coala_utils.string_processing.escape`

**Comment by Makman2** [comment]
There's now also `PathArg` defined recently, which does this path conversion:
```
>>> PathArg('windows\path')
'windows/path'
```

**Comment by ishanSrt** [comment]
@Makman2 assign this issue to me. Also remove the `status/blocked` as the referenced PR has been merged

**Comment by ishanSrt** [comment]
@Makman2 couldn't find any documentation for `PathArg()`. What do I have to import to use that?

**Comment by ishanSrt** [comment]
Sorry for the confusion, you were talking about `DefaultArgParser.py`
