### ISSUE TITLE
Implement travieso

### ISSUE THREAD

**Issue by supergr35** [coala/coala#4891]
https://github.com/wizeline/travieso

This might be something useful to have on our repos, as it could save some time when we want to hunt for what actually went wrong.

Opinions would be appreciated concerning this, since I'm not sure what the cost of implementing it would be.

**Comment by jayvdb** [comment]
This is a devops thing.  It needs to be setup on our servers before we can use it.

**Comment by jayvdb** [comment]
Tracking this at https://github.com/coala/meta/issues/114
