### ISSUE TITLE
Add tests for bear attribute SEE_MORE

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4892]
Add tests for `SEE_MORE`, which was added in https://github.com/coala/coala/issues/3978

**Comment by newbazz** [comment]
Where do i need to add these tests, I mean in which file?

**Comment by jayvdb** [comment]
Probably `tests/bears/BearTest.py` is the best spot.

**Comment by newbazz** [comment]
i need not make a new class for this right?

**Comment by Makman2** [comment]
@jayvdb `SEE_MORE` is doctested in the docstring of `class Bear`.
