### ISSUE TITLE
Man page coala.1 installed in unaccessible location

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4894]
The man page is installed into `site-packages`, I believe.

This may be how it should be installed: https://github.com/nose-devs/nose/blob/master/setup.py#L109

More info at https://github.com/pypa/packaging-problems/issues/72

**Comment by pradeepgangwar** [comment]
@jayvdb as given in suggested link, will putting man page to `man/man1` make it accessible?

**Comment by Vedarth** [comment]
I would like to work on this issue. Kindly assign me to this issue.

**Comment by Vedarth** [comment]
The link points to just writing `man/man1` in data files. Is that enough or something more needs to be done?
