### ISSUE TITLE
Display command-line in `execute_bears` on test-fail when a linter is used

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala#4901]
For example : 
`pylint -c fileA.py --super-aggressive-lints`

(Disclaimer: Those are all invalid flags in pylint, use at own risk :P)

EDIT by @Makman2:
Remove obsolete label-keywords

**Comment by yash-nisar** [comment]
Why didn't gitmate label this issue ? Did we tweak its behaviour ?

**Comment by Makman2** [comment]
gitmate does autolabelling based on machine learning now, keyword based labelling is disabled ;)

**Comment by alphadose** [comment]
@yash-nisar @Makman2 can you please throw some more light on the requirement of this issue ? I am a bit confused here :(

**Comment by Makman2** [comment]
When a test fails with a `@linter`-bear, the test output doesn't display the command the underlying executable was invoked with. This should be implemented :+1:
