### ISSUE TITLE
docs: change git installation command

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4903]
In `docs/Developer/Git_Basics.rst`, change git installation command from `git-all` to `git`.
Opened by @mamat-rahmat at [Gitter](https://gitter.im/coala/coala-bears?at=5a1761db232e79134dc4effc)

**Comment by mamat-rahmat** [comment]
misprint. should be `docs/Developers/Git_Basics.rst`

`git` only includes main components with minimal dependencies. `git-all` contains all sub-packages.
`git` is enough for development.

reference : https://askubuntu.com/questions/796600/difference-between-installing-git-vs-installing-git-all

**Comment by jayvdb** [comment]
ftr, this was introduced in https://github.com/coala/coala/pull/1744 by @Adrianzatreanu

**Comment by nikhil-seth** [comment]
Can i do this ?
As i think that the person who has been assigned is inactive ?

**Comment by parthboricha** [comment]
@nikhil-seth I am busy with end sem exam and would be getting this PR done by next week

**Comment by prnvdixit** [comment]
@parthboricha You may want to unassign yourself from some of the newcomer issues you are assigned to 😛. Ideally, you should do only 1 newcomer issue, you can keep one which you think you would be comfortable solving (Please, unassign yourself from 2 other newcomer issues then :wink:).

**Comment by archit-p** [comment]
Can I take this issue up?

**Comment by Mixih** [comment]
reassigning issue due to multiple newcomer issues  assigned to @parthboricha (community policy is one newcomer issue per person as these issues are a net - ROI). As I don't see work on this issue, I think it will be ok to reassign.
