### ISSUE TITLE
docs: "tutorial" page doesn't exist in README.rst

### ISSUE THREAD

**Issue by Lavenderjiang** [coala/coala#4905]
In coala-html, the "ABOUT" section has a link to "tutorial", but that page doesn't exists.

**Comment by jayvdb** [comment]
@Lavenderjiang , could you please recreate this issue in the coala/coala-html repository.

**Comment by Lavenderjiang** [comment]
Sure :)

**Comment by Makman2** [comment]
@Lavenderjiang please reference it there so we can immediately navigate from here and see the history :+1:
