### ISSUE TITLE
Support `--files /dev/null`

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4916]
Opened by @adtac at [Gitter](https://gitter.im/coala/coala-bears?at=5a1d549dcc1d527f6bc4ff95)

**Comment by Makman2** [comment]
@adtac how is this useful? :D

**Comment by adtac** [comment]
The only use case is when you're running only global bears and you need to give a dummy --files value.

It's mostly just a matter to allowing a common practice in *nix.

**Comment by adtac** [comment]
>However we should allow coala running without files, instead of introducing such a workaround ;)

I agree. That's why I created the other issue (the one I mistakenly created in coala-bears). With both issues, we'll be covering all grounds :)

**Comment by Makman2** [comment]
hmm I'm still in doubt we need this... `--files /dev/null` is for me equally to just omitting `--files` altogether.

**Comment by newbazz** [comment]
what does this issue exactly is? is it only about ommiting --files while running coala on global bears?

**Comment by Makman2** [comment]
No that's what https://github.com/coala/coala/issues/4928 is for.

**Comment by Makman2** [comment]
It's about supporting `/dev/null` for `--files`.

**Comment by newbazz** [comment]
u mean `--files=/dev/null` ? if yes than what does that exactly does?

**Comment by Makman2** [comment]
Please read up on `/dev/null` ;)

**Comment by starlord1311** [comment]
can someone tell what i am supposed to do? @Makman2

**Comment by newbazz** [comment]
@starlord1311 do you know what /dev/null is?

**Comment by starlord1311** [comment]
in general what i am supposed to do for this issue and yeah what /dev/null is

**Comment by starlord1311** [comment]
i read about it but didnt understand its relation to the issue @newbazz

**Comment by Makman2** [comment]
I would then rather suggest to assign to a different issue ;)
However, this issue is still under discussion and not yet ready to work on anyway.

**Comment by Makman2** [comment]
Cite from @SanketDG (from gitter):
> seems like a temporary hack

**Comment by Makman2** [comment]
@adtac I would close the issue as wontfix, except you have some reasons why we really want this :)

**Comment by adtac** [comment]
:+1: closing
