### ISSUE TITLE
mention a link in smart question in newcomers guide

### ISSUE THREAD

**Issue by newbazz** [coala/coala#4929]

**Comment by newbazz** [comment]
http://sol.gfxile.net/dontask.html this link is to be mentioned.

**Comment by yashraj-Dhanuka** [comment]
@newbazz under which heading or section i should add that link in Newcomers_Guide.rst ?
Thankyou !

**Comment by K-jogiah** [comment]
Its My First Time To Contribute To Coala. But I Feel I Should Be Given Afirst Chance To Work On This Project

**Comment by Makman2** [comment]
Please accept the invitation @K-jogiah. Also please don't write every word's first letter upper-case, that kinda reads bad^^

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by priyanshsaxena** [comment]
Please assign this issue to me.

**Comment by Shubham189** [comment]
I want to work on this issue. can you assign me?
@Makman2

**Comment by newbazz** [comment]
@Shubham189 you are not a member of this org, write "hello world" in the gitter chat ;) https://gitter.im/coala/coala

**Comment by newbazz** [comment]
@priyanshsaxena neither are you ;P

**Comment by priyanshsaxena** [comment]
@newbazz updated.

**Comment by newbazz** [comment]
@priyanshsaxena ??

**Comment by Shubham189** [comment]
I am now a member of this org :D

**Comment by newbazz** [comment]
@Makman2 many wants this issue to be assigned to them ;)

**Comment by priyanshsaxena** [comment]
Joined the organisation.

**Comment by newbazz** [comment]
@priyanshsaxena you will soon be assigned.

**Comment by Makman2** [comment]
@priyanshsaxena was first.
