### ISSUE TITLE
API documentation: adding links to the homepage and user's guide

### ISSUE THREAD

**Issue by zhongLxyz** [coala/coala#4934]
I want to propose adding the links leading to the coala [homepage](https://coala.io/#/home) and the coala ['For users' guides](https://docs.coala.io/en/latest/) in the navigation panel of the [Coala API Documentation](http://api.coala.io/en/latest/index.html). 

I propose this because it will make it easier to look up other information when the users are only on the API documentation page. This is mainly for the sake of new developers for reasons I will explain below. As to my knowledge, currently there isn't a way to go from the newcomer's guide to the other places directly. In my experience, I often need to look up information on the homepage or user's guide when I am completing the tasks for the new developers. For example, in step 0 -  Run Coala, I imagine many new developers would need to install Coala. Besides, new developers might want to familiarize themselves with the usage of Coala. And now if I only have the API doc page open, I would have to either google to find the other pages (or retrieve from bookmarks).
 
At the top of the newcomer's guide, there is already a line saying "you might also want to look at our website" with a link of the coala homepage. But I found that it feels more natural to go to the navigation panel and look for a link when you want to jump to a different page.

**Comment by athulpn** [comment]
I am newcomer to opensource, can you help me do it? @zhongLxyz

**Comment by zhongLxyz** [comment]
@athulpn You should start with the newcomer's guide of Coala [here](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html. So first you should start with a "difficulty/newcomer" issue. I don't think this particular issue has been assigned a difficulty yet.

**Comment by d3vil0p3r** [comment]
@jayvdb can I work on this?
