### ISSUE TITLE
linter documentation: Use single quotes for strings instead of double quotes in docstrings

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4940]
... where applicable to conform with our style guides.
Sometimes double quotes shall be kept, for example when there's a single quote inside them. You can always check up the right representation py starting python and entering it:
```
>>> "A string"
'A string'
>>> "A string and '"
"A string and '"
>>> 
```

**Comment by starkblaze01** [comment]
Assign this to me

**Comment by starkblaze01** [comment]
@Makman2 Can you please point me to the directory where I have to make the changes

**Comment by Makman2** [comment]
`coalib/bearlib/abstractions/Linter.py`
