### ISSUE TITLE
Update `ASCIINEMA` of `GitCommitBear `

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala#4954]
Update `ASCIINEMA`:
Add detailed explanation of GitCommitBear, show working with the help of basic git commands(use `git log`) it will clear the workflow, as currently `GitCommitBear` runs only on HEAD of commit. It can't patch commit messages.

difficulty/low

**Comment by RaiVaibhav** [comment]
https://gitter.im/coala/coala?at=5a2a89ac3a80a84b5bd15665, will explain more

**Comment by Makman2** [comment]
Oh wrong repo.

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala-bears/issues/2159
