### ISSUE TITLE
Add docstring for coala_modes.py mode_normal

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4955]
This function should have a proper docstring, and indicate that `log_printer` is unused & deprecated.

**Comment by Subhash-Saurabh** [comment]
I am new to coala .Can I work on this issue?

**Comment by Makman2** [comment]
Please read our newcomer guide, and I would recommend you pick a `difficulty/newcomer` issue first ;) @Subhash-Saurabh

**Comment by vrishank97** [comment]
Hi. Can I work on this issue? There aren't many newcomer issues available and I have some experience with open source.

**Comment by Makman2** [comment]
Please drop by in our gitter channel and mention me once you accepted invitation :+1:
