### ISSUE TITLE
--apply-patches and ApplyPatchAction does not work as expected

### ISSUE THREAD

**Issue by blazeu** [coala/coala#4957]
# Steps to Reproduce

1. Using https://github.com/coala/gci-leaders codebase
1. With the following `.coafile` (minimal version of what's in the repo)
```
[all]
files = lib/*.js, static/js/*.js
eslint_config = .eslintrc
bears = ESLintBear
```
2. Run `coala --apply-patches`

# Actual Results
The problem was not fixed automatically, instead it's asking what to do, like the usual `coala` run.

# Expected Results
The problem is fixed automatically without user's intervention.

# Additional Information:
```
❯ coala --version         
0.12.0.dev20171202193440
```

- `default_actions = *: ApplyPatchAction` also does not work.
- Patching with `coala` using interactive CLI **does work as expected**.

**Comment by Makman2** [comment]
When running over the codebase of `gci-leaders` I don't get any errors. Could you post a file where `ESLintBear` fails?

**Comment by blazeu** [comment]
Oh, I forgot to explain.
I create my own error to test.

You can add semicolon in any of the js files for example.

**Comment by Makman2** [comment]
Confirmed.

**Comment by shreyateeza** [comment]
@blazeu or @Makman2 Can anyone please explain me more in detail?

**Comment by Makman2** [comment]
☝️ https://github.com/coala/coala/issues/4957#issue-280720415
I think the report is quite understandable :+1:
