### ISSUE TITLE
Error while running Writing linter bear Tutorial

### ISSUE THREAD

**Issue by parimatrix** [coala/coala#4964]
**Steps to Reproduce:** 
1. Copy final code for PylintTutorialBear from coala documentation [here](http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html).
2. Create any sample.py in the same folder.
3. Run the following
```
coala --bear-dirs=. --bears=PylintTutorialBear --files=sample.py --flush-cache -V
```
**Expected result:**
pylint to run on sample.py
**Actual result:**
error displayed with following logs
![screenshot 75](https://user-images.githubusercontent.com/25114873/33892664-57d93b1e-df7f-11e7-9ef5-a98941bce1ec.png)
**Extra details:**
Windows 10
coala v0.11.0

**Comment by Makman2** [comment]
Have you tried to use latest coala from master?

**Comment by parimatrix** [comment]
@Makman2 I did try running the latest pre-release mentioned in the docs. That did not work out. Later used latest master. That solved the problem. Thanks a lot for the help. Closing the issue.
