### ISSUE TITLE
Problem in the getting started with coala tutorial

### ISSUE THREAD

**Issue by Nshul** [coala/coala#4968]
### Getting Started with Coala Tutorial has some problems
I followed the link [Getting Started](https://docs.coala.io/en/latest/Users/Tutorial.html) and cloned the tutorial repo. 
# Steps to reproduce
1. cd coala-tutorial
2. coala --files=src/\*.c --bears=SpaceConsistencyBear --save

# Actual Results
```
[cli]
bears = SpaceConsistencyBear
files = src/*.c
use_spaces = True
```
# Expected Results
```
[Default]
bears = SpaceConsistencyBear
files = src/*.c
use_spaces = yeah
```

# Reproducability
It would be great if somebody can tell whether this is just with me or is occuring with others too

# Additional Information
I tried to change the 
```
[cli]
```
to 
```
[Default]
```
And then tested the implicit inheritance but instead received
```
[WARNING][22:48:11] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.

```

While I was filling up the survey of coala usabiltiy i read about this [cEPS](https://github.com/coala/cEPs/blob/master/cEP-0005.md). The proposal there is quite relevant to the problems i am facing. Am i facing these deviations from expected result because of this??

**Comment by Makman2** [comment]
Ah yes, `Default` section is now deprecated (--> its inheritance features), tutorial needs change ;)

**Comment by vedantc98** [comment]
I want to begin contributing to coala, can I take up this issue?

**Comment by Makman2** [comment]
Please ping me on gitter once you've accepted the invitation ;)

**Comment by Nshul** [comment]
Can i take up this issue??

**Comment by Makman2** [comment]
Sorry @Nshul , although you've filed the issue, @vedantc98 was claiming it first ;)

**Comment by vedantc98** [comment]
I've actually taken up another newcomer issue, so maybe @Nshul could take up this one after all?

**Comment by Nshul** [comment]
I have already posted a PR for another newcomer issue and thus i cannot take this as it would be unfair to other new comers

**Comment by Makman2** [comment]
Then I'm unassigning you anyway @vedantc98 :)

**Comment by Rahmeen14** [comment]
Hi! I am completely new to open source and would like to take this is as my first issue if nobody else is currently working on it. I tried to get it assigned to myself on gitter but apparently corobo is under maintenance.
Would be glad if it is assigned to me! 
Thanks for your time.

**Comment by Makman2** [comment]
Invitation out, please ping me on the coala gitter channel once you've accepted :+1: :)
