### ISSUE TITLE
coala_modes.py: Deprecate log_printer param for mode_normal

### ISSUE THREAD

**Issue by vrishank97** [coala/coala#4972]
# Issue
log_printer param is now deprecated and unused. 

## Proposal
Provide a deprecation warning (with `logging.warn`) if `log_printer` param is used.

EDIT by @Makman2:
Removed `DeprecationWarning` and rephrased to not confuse with the class from the `warnings` module (as we don't use those warnings, at least not yet)

**Comment by arpitsimt** [comment]
i want to take it . please assign and elaborate the issue

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by tusharGOEL1** [comment]
Hey @Makman2 i would like to solve this issue, help me get started

**Comment by khanchi97** [comment]
Hello @tusharGOEL1 read 👆 [comment](https://github.com/coala/coala/issues/4972#issue-282005038) and you will get to know what is need to be done ;)

**Comment by eeshan9815** [comment]
I'd like to be assigned to this issue if no one is actively working on it.

**Comment by arpitsimt** [comment]
i want to work on it

**Comment by Anonymous26** [comment]
i would like to work on this issue.

**Comment by Makman2** [comment]
@Anonymous26 please don't start working on issues without assignment. Especially you weren't the first one commenting here.

@eeshan9815 You've already commented on another newcomer issue iirc, so I hope you don't mind if I assign @arpitsimt :)

@arpitsimt Invitation is out, please accept.

**Comment by arpitsimt** [comment]
I am ready. I didn't get any invitation !

**Comment by Makman2** [comment]
Please check your mails @arpitsimt :)

**Comment by somnathrakshit** [comment]
@Makman2 Can I be assigned on this?

**Comment by Makman2** [comment]
@somnathrakshit
@arpitsimt first commented here, and I guaranteed him assignment now.

**Comment by arpitsimt** [comment]
@Makman2 I search everywhere in mail didn't find any invitation link or any mail.please help!

**Comment by gabi0348** [comment]
Can I be assigned on this?
