### ISSUE TITLE
Installation page should mention about versions of python and pip3.

### ISSUE THREAD

**Issue by aviral1701** [coala/coala#4973]
The home page for installation should mention about the minimum versions of python and pip required to install coala.The same is mentioned in the installation docs(Refer [#237)](https://github.com/coala/documentation/issues/237) but should also be there at [Home page](https://coala.io/#/home#installation).I think the new user would want to install coala in one go and since the details aren't mentioned on the home page,the same becomes difficult.

# Additional Information
I would like to work on this,if approved.

**Comment by Makman2** [comment]
Yeah I think this is definitely wanted :+1:

**Comment by aviral1701** [comment]
Thanks! Please assign this to me.
Sorry for late response.Didn't get the mail(?)

**Comment by aviral1701** [comment]
Is this the [repo](https://github.com/coala/landing-frontend) that I am supposed to make changes to?
Thanks for your help.

**Comment by Makman2** [comment]
Probably, please compare file contents there with contents on the installation page to find where to make the changes.

**Comment by Prabhat-IIT** [comment]
Hi if nobody is working on this issue I want to take it up!

**Comment by Makman2** [comment]
Unassigned due to inactivity.
