### ISSUE TITLE
Disambiguation in "Closes xyz" vs "Fixes xyz"

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4976]
See original issue for details:
https://github.com/coala/documentation/issues/465

**Comment by Makman2** [comment]
> Probably it's best to put it into commit guidelines only, not to clutter the newcomer's guide even more.

(https://github.com/coala/coala/issues/4769)

**Comment by shikhar-scs** [comment]
@Makman2 Can I make this change in the commit guidelines ? Or is @alphadose working on it because its already been 4 days

**Comment by Makman2** [comment]
ping @alphadose
