### ISSUE TITLE
Create Indentation aspects under Formatting.Spacing

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#4982]
Create an aspects named `Indentation` in files `Formatting.py`. The new aspects should have fullname of `root.Formatting.Spacing.Indentation`. It should have atleast the following taste:

- `indent_type` - what type of indentation used, could be `tab` or `space`
- `indent_size` - number of spaces per indentation level

**Comment by biscuitsnake** [comment]
hi, please assign the task to me :)
