### ISSUE TITLE
Git Basics: Incorporate http://ohshitgit.com/

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4985]
http://ohshitgit.com/ contains helpful git snippets when something has gone wrong.

**Comment by sourojit** [comment]
Hi I want to work on this.

**Comment by yash042** [comment]
Hello, I am completely new to Open Source and I want to contribute to coala. Can I take up this issue.

**Comment by Makman2** [comment]
@yash042 sorry @sourojit was first ;)

**Comment by Makman2** [comment]
**Note**: Changed title - This should rather go into Git Basics.

**Comment by Jai-Z** [comment]
Hello, I'd like a go at this issue. Do I have the permission?

**Comment by Makman2** [comment]
The issue is currently assigned and being worked on, please pick a different issue :)

**Comment by pkcod** [comment]
Can I work on this???

**Comment by yzgyyang** [comment]
May I work on this one?
