### ISSUE TITLE
Bears operating on directories

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4999]
Currently there's only `ProjectBear`, that works on all files at once. It's worth to have another bear base that only operates on directories, or maybe even both, files and directories! Maybe it can be even integrated into `ProjectBear`. In any way, a concept is needed to make it work properly, also with respect to caching it has to be developed carefully (once it's being implemented).

**Comment by ishanSrt** [comment]
I would like to take this up but this requires too many changes.
Tell me things that I am not supposed to change at all.
Also point me out where does coala infer the directories from the file paths given as you mentioned this on gitter

**Comment by Makman2** [comment]
>  Tell me things that I am not supposed to change at all.

I can't, because I don't know.

> Also point me out where does coala infer the directories from the file paths given as you mentioned this on gitter

You have to look out where the `file_dict` is filled up, there functions from `Globbing` should appear.

**Comment by ishanSrt** [comment]
@Makman2 I see bears like `PythonPackageInitBear` resolving directories from files with:
```
dirs = {os.path.split(filename)[0]
                for filename in self.file_dict.keys()
                if filename.endswith('.py')}
```
although I don't see `GitCommitBear` doing such a thing
Also while having a look at other global bears, I am not able to run `DuplicateFileBear`
when I run it like this: `coala --bears=DuplicateFileBear --files=test.py -I`
It shows me
```
[ERROR][16:42:58] Bear DuplicateFileBear failed to run. Take a look at debug messages (`-V`) for further information.
``` 
and the debug message shows me
```
[WARNING][16:43:09] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][16:43:09] coala will not run any analysis. Did you forget to give the `--bears` or `--aspects` argument?
```

**Comment by Makman2** [comment]
Problem is there might be directories without files, this is where this approach fails:

>  I see bears like PythonPackageInitBear resolving directories from files with:

Also one has to note that you can't commit directories inside git. Maybe we want to follow this "convention", in our case it means that our linting results only depend on *files*, not directories.

**Comment by ishanSrt** [comment]
hmmm.. need some time to ponder on that.
BTW why is DuplicateFileBear behaving that way?

**Comment by Makman2** [comment]
> Also while having a look at other global bears, I am not able to run DuplicateFileBear

Don't know, but that's a different issue. Please file one :+1:

**Comment by ishanSrt** [comment]
@Makman2  I want to work on this

**Comment by newbazz** [comment]
@Makman2 me too, if multiple assignes are possible ;)

**Comment by ishanSrt** [comment]
@Makman2 would be great if you assign the issue to both of us.

**Comment by Makman2** [comment]
Alright, please coordinate. Also please lookup the `coalib.core` module, and its relevant cEP https://github.com/coala/cEPs/blob/master/cEP-0002.md

**Comment by Makman2** [comment]
I finally found a good solution to this, without having code outside of the core complicating the setup of bears by treating files and directories differently. This is how it could work:
1. Our file-dict can be adjusted to work like this:
   Files don't have a trailing slash, directories do. As directories are no files, we can employ two possible meanings: The value is either `None`, meaning "no-content", or it contains a list (or whatever container) holding files and directories inside. 2nd option might be nicer because when bears need to traverse the file tree, they 1. would respect the `files` setting inside a coafile better (assume requesting again the list of files inside a directory and matching that against the glob pattern manually), and 2. they can "navigate" inside the file structure much better and easier.
2. The directory bear would parse the file-dict, and extract out all entries ending with a slash (indicating a directory).

A note on our idea to file-proxies/file-factories:
Instead of a dict, we will have those objects to gain access to files and their contents. We can similarly implement a "directory-proxy" (or just being called `Directory`), which exposes information about directories. The distinction inside bears can easily happen by using a type-check.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by palash25** [comment]
I love the idea of ``DirectoryProxy``. I was going to open an issue for it myself after I saw #3530 .
The ``DirectoryProxy`` will also be useful in implementing  #2541

**Comment by palash25** [comment]
We can use `_iter_relative_dirs` in Globbing.py to get all the subdirectories

**Comment by Makman2** [comment]
We want only to get directories we have selected with a glob, not all subdirectories available :)

**Comment by palash25** [comment]
We can have separate methods in `DirectoryProxy` to return path of the directory matching the glob and another to return all the subdirs matching that glob which I need for implementing the ignoring unmodified directories feature.

**Comment by Makman2** [comment]
Sounds nice :smile:
