### ISSUE TITLE
Development Setup Notes: redirecting link not woking properly

### ISSUE THREAD

**Issue by Mohit17067** [coala/coala#5001]
In [Development Setup Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html#installing-from-git), there is a link under 'Using venv' section [the next part](https://coala.io/devsetup#installing-from-git) which should redirect to 'installing from git' section but it is redirecting to some other Permalink.

**Comment by Mohit17067** [comment]
I would also love to work on this issue if this is a valid issue.

**Comment by Mohit17067** [comment]
Just for confirmation, To solve this issue I just need to change the URL in the appropriate documentation file.

**Comment by adi23arora** [comment]
Yes, just find the document containing URL and change it accordingly.
**Hint**:  You can use ``grep`` to find the appropriate document.
