### ISSUE TITLE
Development setup notes: 'installing from git ' link not working properly

### ISSUE THREAD

**Issue by Mohit17067** [coala/coala#5002]
In [Development Setup Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html#installing-from-git), there is a link under 'Using virtualenv' section [installing from git](https://coala.io/devsetup#installing-from-git) which should redirect to 'installing from git' section but it is redirecting at the top of the page.

**Comment by sachincool** [comment]
i would like to take the issue as a newcomer.
