### ISSUE TITLE
Testing_Bears.rst: Add `files` parameter in `Result.from_values()`

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#5003]
```
[Result.from_values('TooManyLinesBear',
                      'Too many lines')]
```
you can see that https://github.com/coala/coala/blob/master/coalib/results/Result.py#L153
`files` parameter is required by `from_values()` method which is non-optional.

area/documentation

**Comment by kriti21** [comment]
Please assign  this issue to me. Also if @khanchi97 could elaborate what needs to be done, it would be great help. Thanks.

**Comment by manankalra** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
@kriti21 was first ;)
