### ISSUE TITLE
Helper function to compare version of installed packages.

### ISSUE THREAD

**Issue by nvzard** [coala/coala#5009]
We need a helper function that returns a boolean value if the user has required version of a given package.

Something like:
```
>version_check('libclang-py3', '3.4.0')
true

>version_check('libclang-py3', '3.2.1')
false
```

Use Case:
In https://github.com/coala/coala/issues/3847 we need to check the clang version of the user.
We can use `pkg_resources` to get the version of installed modules.

**Comment by nvzard** [comment]
@Makman2  Can you please tell where exactly this method needs to be placed?

**Comment by Makman2** [comment]
Maybe in our `misc` module, or it could be useful for `coala_utils` too^^

**Comment by nvzard** [comment]
Let's put it in coala_utils for now.
And please assign this issue to me, I'd like to work on it.

**Comment by Makman2** [comment]
> Let's put it in coala_utils *for now*.

If you think it's temporary, it should be rather kept in coala itself then.

**Comment by nvzard** [comment]
Okay I'll add it to the `misc` module. I'll create a new file `helpers.py` and add the method `version_check`, we can add other helper method in the future to this module :)

**Comment by jayvdb** [comment]
no; belongs in https://gitlab.com/coala/package_manager/ , if it is still needed.
