### ISSUE TITLE
change glob of ApplyPatchAction in .coafile from * to **

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5013]
`result.origin` in case of many bears changes from their original name, eg. `ESLintBear` becomes `ESLintBear (prettier/prettier)` due to which the glob `*` may not match and ApplyPatchAction won't work.

Although it won't affect the result, but as many users often refer to this file for their own project they may find that some bears are not working if they exactly put this statement over there.

difficulty/newcomer

**Comment by ishanSrt** [comment]
Not quite sure if this needs to be done for ShowPatchAction too

**Comment by Makman2** [comment]
Marking `difficulty/low` as it seems there's some research left.

**Comment by clarammdantas** [comment]
Can I take this one?

**Comment by ishanSrt** [comment]
@clarammdantas 
http://docs.coala.io/en/latest/Users/Glob_Patterns.html
https://github.com/coala/coala/issues/5041
https://github.com/coala/coala/issues/4957
https://github.com/coala/coala/issues/4878

**Comment by Prabhat-IIT** [comment]
@clarammdantas  are you working on it?

**Comment by clarammdantas** [comment]
Hi! Yep, I just had some trouble with it, but think I'm almost done.

**Comment by clarammdantas** [comment]
Are you starting now too @Prabhat-IIT ? If you want to we could work together on this one. I'm not sure if I'm doing it right and would appreciate some help :)

**Comment by Prabhat-IIT** [comment]
Sure :) How should we collaborate?

**Comment by ishanSrt** [comment]
@clarammdantas if you are unsure whether you are going in the right direction, you can still submit a PR and let the code reviews guide you through it. ✌️

**Comment by clarammdantas** [comment]
@ishanSrt how do I test the ESLintBear after my modifications

**Comment by ishanSrt** [comment]
@clarammdantas if your installation was according to the developer's setup, then the changes you make in your local repository will be reflected in the coala command

**Comment by ishanSrt** [comment]
i.e. installation with the `-e` tag

**Comment by ishanSrt** [comment]
@clarammdantas regarding [January 14, 2018 6:30 AM](https://gitter.im/coala/coala?at=5a5aabb2290a1f4561865116)
were you able to replicate https://github.com/coala/coala/issues/4957 ?
if you were did you see that this PR https://github.com/coala/coala/pull/5017 fixes this (although not merged). So if `--apply-patches` when given as a cmd line argument now makes use of glob `**` instead of glob `*`.
But what happens when a user specifies like this in `.coafile`?
```
default_actions = *: ApplyPatchAction
```
here coala is again using the glob `*` and some bears won't match
so I have opened an issue for that i.e. https://github.com/coala/coala/issues/5041
So you don't need to solve the problem at all! 
This issue is intended to change the above type of lines into 
```
default_actions = **: ApplyPatchAction
```
in the .coafile! as simple as that! because users often refer to that when writing their own config file.

The rest thing you need to that is replicate https://github.com/coala/coala/issues/4957 for ShowPatchAction too. If there's no problem (don't think this would be the case) then you are good to go. If there is a problem then change the line for ShowPatchAction in .coafile too i.e. https://github.com/coala/coala/blob/b5d7973a73badda75ee362e2b3c25df3b0226db6/.coafile#L25
Hope that clears everything 😄

**Comment by ishanSrt** [comment]
and if you really need to see what's in result.origin then just print it out! ✌️
