### ISSUE TITLE
DefaultArgParser: Add type=PathArg to all remaining FILE and DIR args

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala#5022]
Oops :) In https://github.com/coala/coala/pull/4883 I didn't add the new `type=PathArg` to all cmdline arg definitions with file or directory path values. That needs to be completed...

Such args are basically all that define `metavar='FILE'` or `'DIR'`

**Comment by userzimmermann** [comment]
This blocks https://github.com/coala/coala/pull/5021

**Comment by userzimmermann** [comment]
@ishanSrt Interested in getting assigned to this, too? :)

**Comment by userzimmermann** [comment]
cc @Makman2

**Comment by ishanSrt** [comment]
Sure! assign me
