### ISSUE TITLE
ConfigurationGathering.py: Fix docstring of function warn_config_absent()

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5025]
return values of True and False are interchanged

difficulty/newcomer

**Comment by shikhar-scs** [comment]
If no one has been assigned this issue can I please work on it @ishanSrt

**Comment by ppatel221** [comment]
I've requested a PR here. https://github.com/coala/coala/pull/5032

**Comment by ishanSrt** [comment]
Sorry @shikhar-scs if you did not get assigned to this on time. Sometimes you gotta wait. Next time just ask a maintainer if you see him active on gitter.

**Comment by ishanSrt** [comment]
@ppatel221 you should wait for assignment to an issue, your PR may be rejected by the maintainers

**Comment by shikhar-scs** [comment]
@ishanSrt 

> Next time just ask a maintainer if you see him active on gitter.

Yeah sure I'll do that the next time

**Comment by prnvdixit** [comment]
@ppatel221 Please get assigned to any issue before starting working on that. :smile:

@shikhar-scs Say "Hello World" on gitter channel and ask any maintainer to assign you to this issue after accepting the invite sent. Also, don't submit a PR (that might waste your precious time) before you are assigned to the issue. :+1:
Meanwhile, go through https://coala.io/newcomer :smiley:

**Comment by shikhar-scs** [comment]
I am starting work here, will hardly take any time.

**Comment by jayvdb** [comment]
@ppatel221 is already working on this one.

**Comment by prnvdixit** [comment]
@jayvdb Then assign "somebody" :stuck_out_tongue:
(We had a discussion on channel for not reviewing unless someone is assigned to the issue :wink:)

**Comment by Jai-Z** [comment]
Hello Everyone, I would like to work on this issue. How do I proceed from here on?

**Comment by ishanSrt** [comment]
@Jai-Z 2 people are already battling for this. better pick a different issue 😅

**Comment by Jai-Z** [comment]
No problem, thanks for replying though. (y)

**Comment by shikhar-scs** [comment]
@jayvdb Can I please resume my work ?

**Comment by Makman2** [comment]
Please accept the invite via mail @shikhar-scs and then I'm going to assign you. You were first for this issue.

**Comment by shikhar-scs** [comment]
Accepted :smile:
