### ISSUE TITLE
FilterTest: Unused import `InvalidFilterException`

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5026]
Remove this import.

**Comment by firedranzer** [comment]
@Makman2 I want to take this issue. Please assign me this.

**Comment by yugeshk** [comment]
Hi I am new to open-source and wanted to take this issue seeing as there are no Assignees yet.
Have tried my best to abide by the [Newcomers guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html) and make a [good commit](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html).

**Comment by sangamcse** [comment]
@yugeshk First of all, this issue was not assigned to you. And as @firedranzer asked for it first, I think you are making it bad.

**Comment by yugeshk** [comment]
Will keep that in mind from next time. Sorry

**Comment by Makman2** [comment]
@firedranzer are you still interested in the issue?

**Comment by firedranzer** [comment]
I think @yugeshk has solved the issue. It's fine by me @Makman2 .
