### ISSUE TITLE
Remove LLVM dependency

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5027]
Only `Diff.from_clang_fixit` and `SourceRange.from_clang_range` need `libclang` and `LLVM` for the native binaries. These functions are only used in `ClangBear` inside coala/coala-bears, and are very specific for that particular bear. They should be moved there until the next coala release.

Although meaning it's an API break, it doesn't make sense to keep it due to this additional dependency.

EDIT by @Makman2:
- Changed issue description completely.
- Added another usage referencce for libclang

**Comment by jayvdb** [comment]
Why not use the [pre-installed LLVM](https://www.appveyor.com/docs/build-environment/#llvm)

**Comment by Makman2** [comment]
There's only one component needing the LLVM bindings: `Diff`
It has a special method to generate the diff from a "fixit". I think this belongs to the specific bear, then we can remove another dependency here, then we don't need to cache it at all :+1:
