### ISSUE TITLE
Add support for section ordering

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#5038]
.coafile
```
[a]
setting1...

[b]
setting2...

[c]
setting3...

[d]
setting4...
```
Now, if run
1. `coala a d c b`   => should run sections in order `a -> d -> c -> b`
2. `coala d c b a`   => should run sections in order `d -> c -> b -> a`

**Comment by khanchi97** [comment]
Although I would also like to work on this :)

**Comment by khanchi97** [comment]
@Makman2 what about labeling this issue 😉

**Comment by ishanSrt** [comment]
@khanchi97 tell me what is the need for this and https://github.com/coala/coala/issues/5037 
What functionality does this add and in what scenario a user would need such kind of feature.
I don't understand how does it matter whether a section is executed before the other and how would it change the outcome if the are executed in any other order.

Only thing I could think of right now is when two sections have two kinds of bears which perform a similar kind of function with subtle differences and change code in a way that is not recognised by the other. Can you give me some examples?

**Comment by khanchi97** [comment]
@ishanSrt go through this thread https://gitter.im/coala/coala?at=5a4d564f68d092bb621e90f9 and you will get the reason why we opened these issues :)

**Comment by Makman2** [comment]
Sometimes there are analysis methods you want to apply in sequence, especially if you like to apply patches and no conflicts shall occur.

> Only thing I could think of right now is when two sections have two kinds of bears which perform a similar kind of function with subtle differences and change code in a way that is not recognised by the other. Can you give me some examples?

So that's more or the less the usecase ;)
I don't have an example right now, however we already had cases where we needed the correct order to optimally run coala and don't get conflicts with patches I believe.

**Comment by khanchi97** [comment]
@Makman2 can you assign me to this issue :)
