### ISSUE TITLE
Document all available actions that can be used with `default_actions` setting

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5042]
Also no mention of any command line argument for the same (if it exists. If it does not exists should open a new issue to make one and then another issue to add that too to the docs) More newcomer issues 😃

**Comment by CaptainDaVinci** [comment]
I would like to work on this, but I am completely new to _coala_, I looked into the source code for `ShowPatchAction`, but did not understand it completely. It would be great if anyone could help me with it.

**Comment by ishanSrt** [comment]
@CaptainDaVinci this would be labelled a difficulty low issue. You should better start with a difficulty newcomer issue and move your way up as you understand more and more about coala.

**Comment by Makman2** [comment]
> this would be labelled a difficulty low issue

This definitely looks like a newcomer issue :O

**Comment by ishanSrt** [comment]
@Makman2 what's the cli arg for ShowPatchAction ?

**Comment by mrsaicharan1** [comment]
I'm a newcomer to coala. Can I take this issue up??

**Comment by ishanSrt** [comment]
request this on gitter

**Comment by ishanSrt** [comment]
never mind 
>Also no mention of any command line argument for the same (if it exists. If it does not exists should open a new issue

it doesn't exist and is neither needed

**Comment by mrsaicharan1** [comment]
Should I do it with corobo or do I request an admin?

**Comment by ishanSrt** [comment]
request admin. corobo not fully functional 👍

**Comment by mrsaicharan1** [comment]
Alright 👍

**Comment by mrsaicharan1** [comment]
Can you please help me out as to where the docs must be edited?

**Comment by ishanSrt** [comment]
find an appropriate place, probably some page where some other settings of coala are mentioned

**Comment by ishanSrt** [comment]
@Makman2 earlier I though that you must be able to provide ShowPatchAction to command line and its missing in the coala settings page but since you mentioned that there is nothing like `--apply-patches` for this, rather unsure where to add it. The only way a user gets to know about it is by looking at the docs for api

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/documentation/issues/518
