### ISSUE TITLE
.coafile Correct command

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5043]
`default_action: *: ShowPatchAction` this is not the correct format and should be changed to 
`default_actions = *: ShowPatchAction`

**Comment by yugeshk** [comment]
I would like to take this up.

**Comment by Makman2** [comment]
@yugeshk we are a bit low on newcomer issues and you've already opened a PR for another one, is it okay if you try to find a `difficulty/low` issue? :)

**Comment by yugeshk** [comment]
@Makman2 yes sure!

**Comment by Hynix07** [comment]
I would like to take this up!!

**Comment by ishanSrt** [comment]
@Hynix07 still working on it?

**Comment by Makman2** [comment]
Unassigning due to inactivity.
