### ISSUE TITLE
DiffTest failing on CI

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5045]
See build https://travis-ci.org/coala/coala/jobs/325392018

Seems there was a recent update to 0.5.5 of the `unidiff` module on 3rd January 2018. Fixing the version below 0.5.5 should fix ti.

**Comment by sils** [comment]
@Makman2 is there an upstream issue?

**Comment by Makman2** [comment]
Filed upstream issue: https://github.com/matiasb/python-unidiff/issues/50
