### ISSUE TITLE
Installing coala

### ISSUE THREAD

**Issue by claporslap** [coala/coala#5048]
Hello Everyone
I am new here.
I am trying to install coala. I have used all three steps.
But when I try to use coala, I get this error
"No command 'coala' found, did you mean:
Command 'cola' from package 'git-cola' (universe)
coala: command not found"

What is wrong here?

**Comment by Prabhat-IIT** [comment]
Please see my reply to you on gitter channel. If problem still persists then please furnish more details about your problem

**Comment by ishanSrt** [comment]
@claporslap still facing issues after you got help on gitter?

**Comment by Makman2** [comment]
I can install coala on a fresh docker image without problems. I highly guess that it's a problem in your environment / how you followed the steps ;)
