### ISSUE TITLE
Development Setup notes should also mention about seperate documentation repository

### ISSUE THREAD

**Issue by Prabhat-IIT** [coala/coala#5049]
I think [Development Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html#installing-from-git) should also have the mention of seperate documentation repository like in [Installation guide](http://docs.coala.io/en/latest/Users/Install.html) so that to any new comer it will be clear that he/she has to also clone the [documentation repository](https://github.com/coala/documentation) first and then install all the requirements and then `make` to generate the documentation locally.
###Additional Information
     I can take up this issue if any mentor agrees!

**Comment by sangamcse** [comment]
@Prabhat-IIT @Makman2, I think there is no need for this issue. It is already given here: https://api.coala.io/en/latest/Developers/Development_Setup.html#building-documentation,

>  also have the mention of seperate documentation repository like in Installation guide

**Comment by Prabhat-IIT** [comment]
Nopes @sangamcse  the link to Documentation repository is not given as in Installation guide!

**Comment by Prabhat-IIT** [comment]
Nopes @sangamcse  the link to Documentation repository is not given as in Installation guide!

**Comment by Makman2** [comment]
The API documentation and some related docs can be built with the coala repository only, you don't have to clone the `documentation` repo (if I understand you correctly). Also we use `python3 setup.py docs` to generate the docs, and not `make`.

I just see, it seems the documentation there is not up-to-date.

**Comment by Makman2** [comment]
The `documentation` repo is for user-documentation only.

**Comment by sangamcse** [comment]
Exactly, that's why I said the issue is not required.

On 09-Jan-2018 2:18 AM, "Mischa Krüger" <notifications@github.com> wrote:

The documentation repo is for user-documentation only.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coala/coala/issues/5049#issuecomment-356091765>, or mute
the thread

**Comment by Prabhat-IIT** [comment]
Sorry, but I thought documentation could only be built through `documentation` repo as a newcomer. I couldn't find generating docs by using `python3 setup.py docs` @Makman2 ?

**Comment by Makman2** [comment]
See https://github.com/coala/coala/issues/5062 ;)
