### ISSUE TITLE
No link for docs in coala api

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5051]
In coala docs, there is a link for the coala api, in the side bar, under **For Developers**

Implement vice-versa

i.e. a link in the sidebar in coala api for the docs

**Comment by namantw** [comment]
@ishanSrt if I get it correctly, the link has to be added in [docs/index.rst](https://github.com/coala/coala/blob/master/docs/index.rst). But where should I put it, under the `Home` subcategory or should I make a new subcategory?

**Comment by ishanSrt** [comment]
@namantw not quite sure. Figure it out. This issue expects a link for the docs in the side bar in https://api.coala.io/en/latest/

**Comment by firedranzer** [comment]
@namantw I think this is good. You can make a PR but read [writing good commits](https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst) once. It will be helpful for you :)

**Comment by ishanSrt** [comment]
@namantw 👍

**Comment by namantw** [comment]
@ishanSrt looks like there is already a link for user documentation in https://api.coala.io/en/latest/ under `For Developers` under the name `User's Guide` 😨

**Comment by ishanSrt** [comment]
☹️ well in that case, I don't think the issue is valid anymore and I think I will have to close this. Sorry for the trouble.
