### ISSUE TITLE
correct the installation instructions for the coala docs

### ISSUE THREAD

**Issue by Prabhat-IIT** [coala/coala#5062]
To generate the documentation of coala it is given in the [Installation guide](http://docs.coala.io/en/latest/Users/Install.html#generating-documentation) and [Development notes](https://api.coala.io/en/latest/Developers/Development_Setup.html#building-documentation) to use `make` instead of `python setup.py docs` which is now the right way to build the documentation. So, it needs to be updated.

**Comment by rohanbanerjee** [comment]
Can I take this up?

**Comment by scheswickfit** [comment]
@Makman2 Since this issue has been unfinished for 7 days would it be possible for me take this up instead?

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by K-jogiah** [comment]
I Was Asking To Take This Up

**Comment by Uditgulati** [comment]
I would like to work on this issue.

**Comment by Uditgulati** [comment]
Can anyone guide me about which files I need to edit to fix this issue. Actually, I'm new to coala and don't know much.

**Comment by Prabhat-IIT** [comment]
Checkout landing-frontend repo of Coala :)

**Comment by Makman2** [comment]
The user-guide needs modifications in the `documentation` repo, but the mentioned developer-guide is here. Please use `git grep` to find the file.

**Comment by Uditgulati** [comment]
https://github.com/coala/documentation/pull/520

**Comment by Uditgulati** [comment]
@Makman2  can you pls have a look at the PRs.

**Comment by pkcod** [comment]
Can I work on this???

**Comment by Makman2** [comment]
The PR was actually ready but not yet reviewed, sorry you have to find another issue @raduklb :/
