### ISSUE TITLE
Windows dependency getting installed in linux system

### ISSUE THREAD

**Issue by newbazz** [coala/coala#5063]
https://files.gitter.im/coala/coala/w2I2/image.png
This is what is being given while running coala 
type/bug

**Comment by newbazz** [comment]
@Makman2 assign it to me.

**Comment by Makman2** [comment]
Could you try on a fresh linux image (docker is probably easiest)? I want to confirm that this happens immediately on a fresh install of coala-bears. Could you also peek in our CI around a bit if `readline` is installed?

**Comment by newbazz** [comment]
@Makman2 I am facing some problems with installation using docker, I am working on it and till that time I have asked a newcomer who has joined the org yesterday to show me the output of command `coala` when run in the main coala repo ;P

**Comment by newbazz** [comment]
@Makman2 I am facing problem to run it behind the proxy

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/34814066-622882ae-f6d2-11e7-9d03-989226d77cd3.png)
I have installed using docker but then as i dont know how to use coala in docker.

**Comment by newbazz** [comment]
@Makman2 it works alright in the fresh installation, it is a bug in my system. 
Closing this issue, Sorry from my side ;P

**Comment by Makman2** [comment]
No worries, but good that we were able to sort it.
In case that this somehow sneaked in because of coala itself and you recognize that somewhen, please reopen 👍
