### ISSUE TITLE
`pip3 install coala-bears --pre` not working as expected

### ISSUE THREAD

**Issue by khanchi97** [coala/coala#5071]

**Comment by lollichop** [comment]
@khanchi97 Could you please be more specific? Is there any exception raised? If so, what error is it causing the process to halt? I've just tested `pip3 install coala-bears --pre` on a machine running Windows 10 and it runs fine.

**Comment by khanchi97** [comment]
@lollichop No, the command runs fine.But it's not installing the bears from `master` branch.

**Comment by yagyanshbhatia** [comment]
@khanchi97 i reinstalled coala from zero again today, and this command worked for me. 
i installed in a venv, with root privilages, pip3 version is 9.0.1
please tell the exact error you are facing?

**Comment by Makman2** [comment]
We aren't releasing development-versions on every merge any more since we have disabled rultor, and we don't plan to do so right now. Please use git-syntax for pip if you like to install coala from master-branch:

```
pip3 install git+https://github.com/coala/coala
```
