### ISSUE TITLE
Provide users an escape method for coala ignore lines if they want to use 'ignore' or 'noqa' in the programs

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5080]
### status: blocked by: https://github.com/coala/coala/issues/4854 status: needs discussion on what should be the keywords for escaping
the users may use it as a param name or somewhere in the comments or while defining a string

**Comment by Makman2** [comment]
Don't we ignore those keywords already, if `ignore` or `noqa` would be used as e.g. variable names?

**Comment by ishanSrt** [comment]
yeah that needed to be changed on the concerned issue because it was creating other problems like Ignore not working without a trailing space, but I found a workaround. don't think will need this issue but still, will crosscheck and tell.

**Comment by ishanSrt** [comment]
>Don't we ignore those keywords already, if ignore or noqa would be used as e.g. variable names?

Yes, its working fine 😛
