### ISSUE TITLE
Review.rst: rephrase a sentence

### ISSUE THREAD

**Issue by Kagamihime** [coala/coala#5085]
It would be nice to use `their` instead of `his` when refering to `someone` in the sentence
`Reviewing always involves saying someone that his code isn't right, be very careful not to appear rude even if you don't mean it!` to be more inclusive.

The page in question: http://api.coala.io/en/latest/Developers/Review.html
The file in question: `Review.rst`, at line 33.

**Comment by lollichop** [comment]
I'd be glad to take this up.
