### ISSUE TITLE
Add support for writing ignore comment in Jinja2

### ISSUE THREAD

**Issue by kriti21** [coala/coala#5107]

**Comment by ishanSrt** [comment]
@kriti21 can you give some steps to replicate this issue?

**Comment by kriti21** [comment]
@ishanSrt Just run Jinja2Bear on any jinja2 file. When coala is asked to write a comment choosing the option, it says Jinja2 is not supported yet.

**Comment by vaib10sai** [comment]
I want to work on this issue. Can I get this assigned?

**Comment by priyanshsaxena** [comment]
@Makman2 please assign this issue to me.

**Comment by Makman2** [comment]
@vaib10sai was first ;)

**Comment by jayvdb** [comment]
@kriti21, as you have been working on jinja2 support, maybe you can get this one done?

**Comment by kriti21** [comment]
Yes, please assign this to me @jayvdb
