### ISSUE TITLE
.editorconfig: Typo Error

### ISSUE THREAD

**Issue by jackthepirate6** [coala/coala#5108]
There's a typo: fies should be files at line no 15 in the file coala/.editorconfig

**Comment by EverWinter23** [comment]
Would like to work on it.

**Comment by monsij** [comment]
Hello There! I'm ready to work on this issue.Kindly assign it to me.
Thanks in Advance!

**Comment by sreejithsankar55** [comment]
I am a newcomer can I work on this issue

**Comment by newbazz** [comment]
@sreejithsankar55 theres already a PR for this issue. lookout for another newcomers issue.
