### ISSUE TITLE
Writing native bears tutorial: use the `format` string method in an example

### ISSUE THREAD

**Issue by Kagamihime** [coala/coala#5109]
In the first example code of the tutorial "Guide to Writing a Native Bear" (in the section "A Hello World Bear"), the call to `debug` should be passed one argument: a string that would be formatted using the methode `format`.

**Comment by pmathur5k10** [comment]
Hi !! I am new to Coala and open source in general and I would like to take up this issue. Thanks !!

**Comment by pmathur5k10** [comment]
@Kagamihime  If I am correct, debug call is the one in the hello world example in the line starting with logging.debug("Hello World! Checking file", filename, ".")

**Comment by Kagamihime** [comment]
Yes, exactly

**Comment by pmathur5k10** [comment]
Please assign me this issue as I would like to work on it. Thanks !!

**Comment by vaib10sai** [comment]
I want to work on this issue, can I get this assigned? :)

**Comment by firesans** [comment]
hey, I would like to work on this issue.

**Comment by Makman2** [comment]
@pmathur5k10 I've sent you an org invite, please accept, then you can be assigned.

**Comment by pmathur5k10** [comment]
@Makman2  I have accepted the invite. Thank You

**Comment by pkcod** [comment]
Can I work on this???

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by Makman2** [comment]
@pkcod please accept the invite.

**Comment by pkcod** [comment]
please assign me

**Comment by Makman2** [comment]
You haven't accepted the invite to the org via mail yet.

**Comment by pkcod** [comment]
okay i will do it now!!

**Comment by pkcod** [comment]
Sorry for delay I accept your invite!!

**Comment by ananyaarun** [comment]
Hi, can this be assigned to me if no one is working on it ?

**Comment by rishabhgarg25699** [comment]
Hello,can you assigned this work to me ?

**Comment by rishabhgarg25699** [comment]
Can you send me the link of source code of  this issue on github.

**Comment by ishanSrt** [comment]
already solved https://github.com/coala/coala/commit/499329026e392166ffcf742fc1bf6018e68f6cca
needs to be closed ping @jayvdb

**Comment by jayvdb** [comment]
Solved at https://github.com/coala/coala/issues/5509
