### ISSUE TITLE
RELEASE_NOTES.rst : Typo Error

### ISSUE THREAD

**Issue by richa208** [coala/coala#5123]
Spelling mistakes like 'availibility', 'ben', 'modifyable', 'seperation', 'libary' along with some grammatical errors are present in file coala/RELEASE_NOTES.rst

**Comment by richa208** [comment]
i would like to work on this

**Comment by newbazz** [comment]
@richa208 you are not assigned neither are you a part of this org.
@Makman2.

**Comment by richa208** [comment]
@Makman2 I have not got any invitation mail for joining.. Can you please see into it so that i can contribute further.. Thanks

**Comment by richa208** [comment]
Can I be assigned this issue?

**Comment by pkcod** [comment]
Can I work on this???

**Comment by richa208** [comment]
I have already submitted a PR on this.

**Comment by monsij** [comment]
@richa208  : You don't need to worry about it.
@pkcod : Kindly look for other unassigned issues.You will be surely able to find them.
