### ISSUE TITLE
FunctionMetadata.py: Typo Error

### ISSUE THREAD

**Issue by jackthepirate6** [coala/coala#5132]
There's a typo: deprecared should be deprecated at line no 38 in the file 
coala/coalib/settings/FunctionMetadata.py

**Comment by Sayak9495** [comment]
I'm new to coala. I can fix the typo. It would be great if I'm assigned to this issue.

**Comment by sachinmukherjee** [comment]
I can fix this error. This will be my first open source contribution if I 'm assigned to fix.

**Comment by arpitsimt** [comment]
i can also fix,this will also be my first contribution .please assign to me

**Comment by pavankrishna13** [comment]
Can I work on this issue?

**Comment by Ananthavijay** [comment]
This PR:https://github.com/coala/coala/pull/5142
fixes the issue.

**Comment by ouromoros** [comment]
I would like to fix this issue, can I be assigned?

**Comment by Makman2** [comment]
@Ananthavijay Please don't submit PRs without assignment. @ouromoros has properly asked for assignment, so going to assign him now once he has accepted the org invite :+1:

**Comment by ouromoros** [comment]
@Makman2 Accepted the invite. Can assign me now.
