### ISSUE TITLE
LocalBearTestHelper: Change the docstring indentation

### ISSUE THREAD

**Issue by newbazz** [coala/coala#5137]
difficulty/newcomer

**Comment by flaredragon** [comment]
Can I take up this issue?
Could someone please assign me this

**Comment by newbazz** [comment]
@flaredragon yes you can, start working on this issue and you will be assigned asap.

**Comment by flaredragon** [comment]
@newbazz Sir,I was unable to find any docstrings in LocalBearTest.py in tests/bears folder could you guide me where exactly the changes have to be done?

**Comment by newbazz** [comment]
ohh my bad.

**Comment by newbazz** [comment]
now check

**Comment by flaredragon** [comment]
sir even that file doesn't have any docstrings

**Comment by newbazz** [comment]
https://github.com/coala/coala/blob/master/coalib/testing/LocalBearTestHelper.py
it does check carefully. ;)

**Comment by nvzard** [comment]
I think its a duplicate of https://github.com/coala/coala/issues/5131

**Comment by Makman2** [comment]
Indeed. @flaredragon Sorry I have to close this one. I hope you don't mind.
