### ISSUE TITLE
Add Visual Studio Code to known editors for coala

### ISSUE THREAD

**Issue by kriti21** [coala/coala#5150]

**Comment by ayush9398** [comment]
I m new to coala, can I work on this?

**Comment by MacBox7** [comment]
Aiming for GSOC, don't see any unassigned issues. Can I work on this one ?

**Comment by sangamcse** [comment]
@MacBox7 @ayush9398, how would you like to approach this issue? Any Idea? 😉

**Comment by MacBox7** [comment]
I don't think it would be more than adding VSCode to [OpenEditorAction.py](https://github.com/coala/coala/blob/master/coalib/results/result_actions/OpenEditorAction.py#L8).

**Comment by kriti21** [comment]
@MacBox7 This one has been claimed by @ayush9398 first. He will get assigned to this one. You can use filters to search unassigned difficulty/newcomer issues. You will surely find one :)

**Comment by MacBox7** [comment]
Too bad, already had figured out what has to be done. If @ayush9398  doesn't mind can i take it up.

**Comment by ayush9398** [comment]
@MacBox7 don't mind but I would like to work on this. I am new to coala and really want to start contributing.

**Comment by ayush9398** [comment]
@kriti21 if I understand correctly,I have to add the code for 'vsc' in known_editors in  coala/coalib/results/result_actions/OpenEditorAction.py , right?

**Comment by kriti21** [comment]
@ayush9398 This does needs change in `OpenEditorAction.py` file but I am not familiar with its code. So that you have to figure out yourself. Ask for help on gitter if you are stuck. :)

**Comment by pkcod** [comment]
Can I work on this??

**Comment by kriti21** [comment]
@pkcod As you can see someone has already been assigned and work is  going on for this issue. Please find something else to work on. :)

**Comment by ayush9398** [comment]
sorry @pkcod , I am still working on this.

**Comment by amalrajan** [comment]
Squash your commits into a single one when it's done :)

**Comment by sourabh1031** [comment]
@jayvdb please assign me the issue as there is no response for a long time from earlier assigne
