### ISSUE TITLE
Inconsistency in output of coala -B --json & coala -B commands

### ISSUE THREAD

**Issue by shreyans800755** [coala/coala#5156]
Output of `coala -B` only displays the name of the bears. But `coala -B --json` displays all the details of the bears. Content of `coala -B --json` command matches the content of `coala -B --show-details`.

To keep the behaviour consistent, we should only display the name of the bears just like `coala -B` in json format .

**Comment by Makman2** [comment]
Blocked by https://github.com/coala/coala/issues/4881

**Comment by jayvdb** [comment]
I am not sure this is blocked by that one.
@anctartica ?
I think this can be very easily solved by having a special and very simple outputter for showing only the bear names, as json.

**Comment by anctartica** [comment]
if `coala -B --json` only shows the names of the bears in json, then do we have another command `coala -B --show-details --json` to print all the details in the json format?

**Comment by jayvdb** [comment]
`coala -B --json` throws an error because it is going deep into the objects. It should be just bear names. It needs a different algorithm: a simple one.
