### ISSUE TITLE
Add `tags` for VIM's tagfiles in .gitignore

### ISSUE THREAD

**Issue by nityeshaga** [coala/coala#5162]
vim users need to create tag files to jump around the codebase. This file must not be committed. Hence, must be included in `.gitignore` file.

**Comment by nityeshaga** [comment]
@Makman2 I know I asked for it on the chat but I have already completed one newcomer issue. Would it be okay if I do another one?

**Comment by Makman2** [comment]
In this case you quite need it to enhance your development workflow, so it's okay :)

**Comment by nityeshaga** [comment]
Yaay! Thanks a lot @Makman2 ! :smile:
