### ISSUE TITLE
persistent_hash: Missing support for collection types with not guaranteed iteration order

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5188]
Like `dict` and `set`. `sorted` can be used to sort the data beforehand.

**Comment by Makman2** [comment]
Blocked by https://github.com/coala/coala/issues/4350

**Comment by palash25** [comment]
@Makman2 would like to work on this once it is unblocked

**Comment by palash25** [comment]
although I'm not sure if it would work for nested dicts :confused:

**Comment by palash25** [comment]
@Makman2 from what I can gather from the `generate_tasks()` method is that the task objects are tuples of a tuple of args and a dict of kwargs . Tuples preserve order so there won't be any problem hashing them the current method is sufficient for that. However in case of the kwargs dict since the order is not preserved maybe we can change the dict to a frozenset`frozenset(dict.items())` (assuming there are no duplicates) and then serialize it using `pickle.dumps()` and then find the sha1 hash.
I tried it, converted the dict to a frozentset and it didn't give me `unhashable type error`

**Comment by palash25** [comment]
I am having trouble visualizing the task objects can you give me an example of one?

**Comment by Makman2** [comment]
But how do you intend to pass kwargs with a non-mapping type? And even if our task's args and kwargs wouldn't be dicts, they could themselves contain dicts. And even if you use `frozenset`, the order isn't preserved across machines, and also not guaranteed to be preserved across coala runs :)

**Comment by palash25** [comment]
I wasn't sure about the structure of kwargs and args. 

> And even if our task's args and kwargs wouldn't be dicts, they could themselves contain dicts.

This makes it even more difficult since now they could be nested dicts.

**Comment by Makman2** [comment]
`pickle` has to do something similar to pickle special objects, you can likely get some inspiration from there :+1:

**Comment by palash25** [comment]
Hey @Makman2 I found this module dill: https://github.com/uqfoundation/dill which is an extension of pickle and is under active development.

Your comment intrigued me about dill.

> And even if you use frozenset, the order isn't preserved across machines

 Their documentation states that 

>  In addition to pickling python objects, dill provides the ability to save the state of an interpreter session in a single command. Hence, it would be feasable to save a interpreter session, close the interpreter, ship the pickled file to another computer, open a new interpreter, unpickle the session and thus continue from the 'saved' state of the original interpreter session.

What I understand from this is that dill saves the state of the pickled object across machines thus providing us the capability to transfer pickled objects across machine. Maybe this could be beneficial to us in the long run when we think about running coala on distributed systems, across multiple machines. I just wanted to put it out there in case we might need it in the future.

What do you think? :smile:

**Comment by Makman2** [comment]
`attrs` uses the `repr` of objects, which won't work. Consider a class
```
class X:
    def __init__():
        self.a = 3
```
and now you change `a`, the `repr` of the state before and after wouldn't change. `persistent_hash` would generate a different hash for them.

**Comment by jayvdb** [comment]
iirc, it also uses metaprogramming, and lots of other voodoo, so it is possible that it works even if it looks like it wouldnt work.

**Comment by Makman2** [comment]
Their hashing works on all `attr`-annotated classes, because the `repr` function for them (that is autogenerated) contains all fields and their values. So once a value changes -> `repr()` changes -> `hash()` changes. But `hash()` wouldn't change on classes not annotated with `repr()` (because 1. the default `__hash__` implementation just doesn't use `repr()` but the instance address/id 2. because `repr()` is quite minimal and doesn't mention class fields and their values).

Anyway, filed an issue for this :)
https://github.com/coala/coala/issues/5336

**Comment by palash25** [comment]
@Makman2 should I continue my work on the PR and also investigate the use of attrs side by side or should I abandon this PR?

I think if I can get the tests to pass on this PR we can use it as a temporary solution till someone implements attrs in place of persistent_hash (if possible) in the future.

**Comment by Makman2** [comment]
Just continue and ignore `attrs`, this would be part of #5336 now.
