### ISSUE TITLE
After hitting option 4 Show Applied Patches, we get [ ] All actions have been applied which is misleading

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5192]
After hitting 4s, why am I getting [ ] All actions have been applied when they are actually not applied and I am just viewing the suggested patches
reference comment: https://github.com/coala/coala/issues/5167#issuecomment-365929147

**Comment by Naveenaidu** [comment]
@Makman2 I would like to work on this issue. Please assign me this.

**Comment by Naveenaidu** [comment]
I am really sorry for closing the pull requests. My brother had access to my computer and he messed up my fork. I had no other option other other than doing a hard reset on my fork. 
Won't repeat it again :worried:

**Comment by Makman2** [comment]
@Naveenaidu please be sure to secure your computer to a degree where nobody can immediately hijack your account ;)
