### ISSUE TITLE
Writing_Good_Commits.rst: Example 3 is misleading.

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5195]
Example 3 uses 'Fixes' instead of 'Closes' when fixing a typo. However, the common practice is to use 'Fixes' only when fixing a bug.
(ref: https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst)

**Comment by Anonymous26** [comment]
I would like to work on this

**Comment by pkcod** [comment]
I would like to work on it

**Comment by Makman2** [comment]
Assigning @pkcod as it's been already a day and @Anonymous26 hasn't accepted invitation yet.

**Comment by Anonymous26** [comment]
Sorry for the delay ..I've accepted the invitation and I would like to work

**Comment by Aquilll** [comment]
@Makman2, It seems like no one is working on it. Could you assign this to me?

**Comment by Makman2** [comment]
The PR is already approved.
