### ISSUE TITLE
Fix typo in the docstring of try_to_apply_section()

### ISSUE THREAD

**Issue by nityeshaga** [coala/coala#5201]
[Line 705](https://github.com/coala/coala/blob/a33b65d2e51a5eb006a9def194eebcdf143ce679/coalib/output/ConsoleInteraction.py#L705) says `choose_action` instead of `chosen_action`. Need to change it.

**Comment by mbiesek** [comment]
I would like to work on this

**Comment by harshhx17** [comment]
Can it be please be assigned to me....

**Comment by pkcod** [comment]
I will like to work on it

**Comment by shubhamivane** [comment]
I would like work on it.

**Comment by shubhamivane** [comment]
@nityeshaga Can you review it?

**Comment by nityeshaga** [comment]
Sorry @shubhamivane You need to be assigned to an issue before you start working on it. 

You should really read our Getting started tutorial first :wink: Then wait until a mentor assigns this issue to you. Only then should you submit a PR.

**Comment by shubhamivane** [comment]
sorry, I'll keep in mind next time. @nityeshaga

**Comment by jckw** [comment]
Is this issue actually stale? The relevant PR is closed.

**Comment by raduklb** [comment]
Hi! I would like to work on this issue!
