### ISSUE TITLE
CircleCI: Update to 2.0 syntax

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5218]
> Dear customer, 
>
> We wanted to let you know that we are planning on sunsetting CircleCI 1.0 on August 31st, 2018. Our goal as a company for 2018 is to invest in delivering more features and better performance on CircleCI 2.0, which unlocks faster builds and greater control. For more information, you can read our blog post on sunsetting CircleCI 1.0.
>
> ...
>
> [Config.yml translator.](http://go.circleci.com/UDKo04H0GM0Z20021k00071) Note: This will generate a baseline config.yml file that you can adjust to fit your needs.
> [1.0 to 2.0 migration documentation.](http://go.circleci.com/LD42HM0010800ZL1o0G020k)
> [Language-specific 2.0 tutorials.](http://go.circleci.com/hGo194M00Z000D20k020HM1)

**Comment by guilherme-p** [comment]
I'd like to work on this.

**Comment by Makman2** [comment]
@guilherme-p I've mistakenly tagged this as `difficulty/low`, but I guess more work is involved. I've assigned @alphadose because he knows the CI for a longer time.
