### ISSUE TITLE
The error message in ConsoleInteraction.py is not adequate.

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coala#5219]
The error message that get's printed when an invalid character is entered is as :- `Please enter a valid letter.` But this is not completely true as the user can also enter numbers to select Actions.

The error message must be changed to `Please enter a valid letter or number.`
For example:-
The output when i enter `10` as an option.
```
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. (A)pply patch
[    ]  3. Print (M)ore info
[    ]  4. Add (I)gnore comment
[    ]  5. Show Applied (P)atches
[    ]  6. (G)enerate patches
[    ] Enter number (Ctrl-D to exit):
[    ] Please enter a valid letter.
```

**Comment by Naveenaidu** [comment]
cc @Makman2  If this looks like a valid issue can i work on it?

**Comment by Naveenaidu** [comment]
@labirinto Sure please do continue working :')

**Comment by Naveenaidu** [comment]
But first ask a maintainer to assign an issue to you. Please don't start working on a issue until you are assigned to it.

**Comment by Labirinto** [comment]
@Makman2 can you assign me this issue, please?

**Comment by aramadsanar** [comment]
@Makman2 is this issue assigned already?

**Comment by Naveenaidu** [comment]
@aramadsanar I don't think so. :'). You can actually get to know if anyone is assigned to a issue or not  by seeing the `assignee` section in the issue page.

**Comment by aramadsanar** [comment]
yeah, but this issue passed thru the no:asignee filter :/

**Comment by Naveenaidu** [comment]
That means this issue is unassigned. Drop a message here to either @jayvdb  or @Makman2  and then also ping them on the gitter channel.

**Comment by aramadsanar** [comment]
@Makman2 please assign this issue to me please please please 😄

**Comment by jayvdb** [comment]
This is being worked on at https://github.com/coala/coala/issues/5219

**Comment by Naveenaidu** [comment]
@Jitender46559 Please go through the newcomer guide of coala. It'll help you understand the work flow at coala.

**Comment by Jitender46559** [comment]
can you share a link plzz

**Comment by Naveenaidu** [comment]
http://api.coala.io/en/latest/Developers/Newcomers_Guide.html. The link to
the NewComer's Guide. Please also ask for the invitation link in the gitter
channel https://gitter.im/coala/coala

P . Naveen Naidu

**Comment by sanjeethboddi** [comment]
assign this to me, please.

**Comment by kwsohn** [comment]
@jayvdb @Makman2 Is it possible that I could be assigned this issue? I'm trying to finish a newcomer issue so I can start moving onto more difficult issues. I've read through the newcomer's guide and already have Coala installed and my virtual environment set up.

**Comment by Makman2** [comment]
@kwsohn as you can see this issue is being worked on.
