### ISSUE TITLE
Fix typo in docstring of ResultAction.py

### ISSUE THREAD

**Issue by harshhx17** [coala/coala#5223]
Line 81 says :return 
It needs to be changed to :return:

**Comment by harshhx17** [comment]
@Makman2  Is this a valid issue?
If yes..Please assign this issue to me... :stuck_out_tongue: 
As my last newcomer issue https://github.com/coala/coala-bears/issues/2287 could not be merged...

**Comment by manankalra** [comment]
@harshhx17 
>As my newcomer issue coala/coala-bears#2287 could not be merged...

Why? You haven't yet opened a PR for the same!

**Comment by harshhx17** [comment]
I have(https://github.com/coala/coala-bears/pull/2292).. but the builds on circle ci were failing....
For reasons not related to the changes I had made(atleast thats what was concluded)
So it was just approved but not merged

**Comment by manankalra** [comment]
Oh, alright. I can't see a PR referencing that issue on the issue page.

**Comment by harshhx17** [comment]
Even I was thinking about the same, Why is that?
Is it because my first commit didnot contain the Closes line
If so why did it not update it afterwards

**Comment by harshhx17** [comment]
Needed to update the comment.. Done Now :smile:

**Comment by saran7188** [comment]
Hi! I am a newbie to coala, Can you assign me to this bug, I would love to work on it.

**Comment by saran7188** [comment]
Hi! I am a newbie, Can you assign this to me? I would love to work on it.

**Comment by sourojit** [comment]
Hi, can you assign this issue to me?

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by SubbulakshmiRS** [comment]
hey can i be assigned this issue ? I am a newcomer here.

**Comment by harshhx17** [comment]
@jayvdb  ^

**Comment by ChetanKhanna** [comment]
is this issue done with; else can i be assigned this one?

**Comment by ChetanKhanna** [comment]
corobo assign https://github.com/coala/coala/issues/5223

**Comment by ChetanKhanna** [comment]
@Makman2 can I be assigned this issue?
Oh and, sorry to ask something this simple, but where do I ask for issue assignment, here or on the main chat?

**Comment by jayvdb** [comment]
Assigned
