### ISSUE TITLE
CachinUtilities.py: Use cPickle instead of pickle

### ISSUE THREAD

**Issue by palash25** [coala/coala#5230]
In the file `coalib/misc/CachingUtilities.py` replace `pickle` with `cPickle` which can lead to a minor performance gain since `cPickle` is about 1000 times faster than `pickle`. We only using `pickle.dump()` and `pickle.load()` so it shouldn't have any compatibility issues since both the modules have identical functions for dumping and loading. 

I'm opening this issue with reference to the [optimize caching](https://projects.coala.io/#/projects?project=optimize_caching&lang=en) GSoC project. Even though it is a minor change it is a performance improvement nevertheless.
 
IMO it should remain blocked since its related to a GSoC project.

status/blocked difficulty/low type/performance

**Comment by karansingh1559** [comment]
@Makman2 can you assign this issue to me? seems fairly strightfoward :)

**Comment by palash25** [comment]
> IMO it should remain blocked since its related to a GSoC project.

read this :point_up: 

I am working on this project for GSoC. This is not just a standalone issue.
I know its easy but for now its blocked.

**Comment by Makman2** [comment]
Actually, I believe this issue is invalid, `cPickle` is the default implementation used by `pickle`.
