### ISSUE TITLE
ShowAppliedPatchesAction not working correctly, giving the same results as ShowPatchAction

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5238]
references: https://github.com/coala/coala/pull/5231#issuecomment-370233838
https://github.com/coala/coala/issues/5191
https://github.com/coala/coala/issues/5190

**Comment by Naveenaidu** [comment]
@ishansrt There is a similar issue open at https://github.com/coala/coala/issues/5232.

**Comment by ishanSrt** [comment]
@Naveenaidu oh didn't see that! its the same but can you tell me how's it related to `DIFF_EXCERPT_MAX_SIZE`. If the diff is less than that then what CLI args are given?

**Comment by Naveenaidu** [comment]
@ishansrt When `DIFF_EXCERPT_MAX_SIZE` is less than 4, then coala  doesn't show  `Show Patch Action`.

**Comment by ishanSrt** [comment]
If that is the case then this issue is invalid. 
status/invalid
duplicate of https://github.com/coala/coala/issues/5232
