### ISSUE TITLE
Add notepadqq to known editors

### ISSUE THREAD

**Issue by palash25** [coala/coala#5244]
[notepadqq](https://notepadqq.com/wp/) is the linux variant of notepad++

`OpenEditorAction.py` doesn't have notepadqq in its known list of gui editors it would be nice to have it.

**Comment by Naveenaidu** [comment]
@Makman2  Can i please be assigned to this issue. :smile:

**Comment by Makman2** [comment]
@Naveenaidu this one is too easy for you, you already had some newcomer issues ;)

**Comment by guilherme-p** [comment]
Can I have this one?

**Comment by Makman2** [comment]
See https://github.com/coala/coala/issues/5254#issuecomment-372198406

**Comment by Zimm** [comment]
@Makman2  Can you assign this issue to me?

**Comment by guilherme-p** [comment]
I did @Makman2 and fixed it yesterday

**Comment by Zimm** [comment]
@guilherme-p Ah, sorry.

**Comment by Makman2** [comment]
Please don't start to work on issues without assignments, apparently you haven't completed the other issue. Also this one is another `difficulty/newcomer` issue, and we try to encourage people to move to `difficulty/low` ones after they have solved a beginner issue.

**Comment by refactormyself** [comment]
@Makman2  I guess this issue is still unassigned, can I have it please.
