### ISSUE TITLE
Typo in the docstring of `modify_line()` in Diff.py

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coala#5245]
One of the example inside the docstring of `modify_line()` in `Diff.py` shows wrong output.

Original line:- 
```
 >>> diff = Diff(['Hey there! Gorgeous.\n',
        ...              "It's nice that we're here.\n"])
```

The example that needs to be changed:-
```
>>> diff.modify_line(1,
        ...                  'Hello. :( Gorgeous.\n')
        >>> diff.modified
        ['Hello. :( This is sad.\n', "It's nice that we're here.\n"]
```

**Comment by Naveenaidu** [comment]
@jayvdb @Makman2  Can i please be assigned to this issue :')

**Comment by Naveenaidu** [comment]
Sorry @gitmate-bot it's not a duplicate issue. :stuck_out_tongue:

**Comment by shubhamivane** [comment]
I would like to work on it.

**Comment by Makman2** [comment]
Actually I can't see your piece of text inside `Diff.py` :O Also it's doc-tested, so some invalid output would actually lead to a test fail and wouldn't be able to get merged (as long as our CI works properly, but I believe it does here ;) ).
I'm quite sure it's right as it is, in case I've missed something, please comment and reopen :)

**Comment by Naveenaidu** [comment]
@makman2 Please have a look at https://github.com/coala/coala/blob/master/coalib/results/Diff.py#L505 .
Please let me know if it's a mistake?

**Comment by Makman2** [comment]
>  We can even merge changes within one line:

That's what it's referring to, and that's why it looks a bit weird seeing only the latter `modify_line` without looking at the previous one :)

**Comment by Naveenaidu** [comment]
:O Now i get it. Sorry for opening an issue. I will be careful from next time.
