### ISSUE TITLE
Writing Linter Bears.rst: Contents of RESULT_SEVERITY are ambigous

### ISSUE THREAD

**Issue by manankalra** [coala/coala#5248]
Under https://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html#using-severities, it is mentioned that there are three severity levels: `INFO`, `NORMAL` & `MAJOR`. 

At the end of the same section it says:
> coalib.results.RESULT_SEVERITY contains three different values, `Info`, `Warning` and `Error` you can use.

The above line is misleading as the contents of `coalib.results.RESULT_SEVERITY` has the prior types of severities. This redundancy should be removed or changed to a rather clear explanation of whatever is intended here.

**Comment by Makman2** [comment]
If possible let's rather avoid the sentence if it fits :+1:

**Comment by manankalra** [comment]
@Makman2 Yeah, removing the whole sentence makes more sense as this info is already mentioned when the concerned section begins.

**Comment by SergeyGorbatyuk171** [comment]
Hello! I am a newcomer and I would like to proceed with this issue. As I understand, the goal is just to refactor the source .rst file by removing a sentence stated above. If I am right, please, assign this issue to me, if I am not, then explain it please a bit more :)

**Comment by refactormyself** [comment]
Hello, please assign this issue to me.

**Comment by RaiVaibhav** [comment]
IMO removing the line and adding 2-3 line explanation will be best for newcomer to understand it.

**Comment by refactormyself** [comment]
@RaiVaibhav Please, can you assign this issue to me?

**Comment by SergeyGorbatyuk171** [comment]
@refactormyself, dude, there are quite enough other issues, I spent some time trying to find issue that nobody's going to take (in comments), why don't you do the same, as I asked to assign it to me first? =)

**Comment by RaiVaibhav** [comment]
I can't assign anyone one maintainer can
and @SergeyGorbatyuk171  and @refactormyself  it's rule that the person who asked first and active then he will get assigned.
