### ISSUE TITLE
Remove clang related code

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5250]
After https://github.com/coala/coala/issues/5027 , there shouldnt have been any llvm,clang stuff in this repo, but there is ... cc @Makman2 

Remove clang stuff

```
tests/misc/ExceptionsTest.py:            'libclang-py3 0.3', 'libclang-py3==0.2')), 13)
tests/output/ConsoleInteractionTest.py:                [Result('ClangCloneDetectionBear',
tests/output/ConsoleInteractionTest.py:**** ClangCloneDetectionBear [Section:  | Severity: NORMAL] ****
```

If these tests are not already in coala-bears, they should be copied there.

Also there are a few bugs raised about clang.  They need to be opened as new issues in the coala-bears repo.

**Comment by Makman2** [comment]
Those tests are just using those names, but they don't require the actual libclang-package. I also stumbled upon those, but they are safe to keep.
@jayvdb you want to change those so it's not misleading?

**Comment by lalitmee** [comment]
I was going through the code in the mentioned files and I found the code related to **clang**. Do we need to remove those related codes from these files?

**Comment by Makman2** [comment]
I think if you just change those names to something else that's more clear, everyone's happy here ;)

**Comment by lalitmee** [comment]
@Makman2 you mean something that can clearly describe the meaning of those and why are those there in the file? Correct me if I am wrong. :innocent:

**Comment by Makman2** [comment]
Yes.

**Comment by lalitmee** [comment]
Hey @Makman2 , `libclang-py3` is referring to a package of clang. I searched in the listed issue [#5027](https://github.com/coala/coala/issues/5027) and found that this package is moved to **coala-bears**. So I think I can give any meaningful name there instead of this package name and its not going to effect anything in the tests.
