### ISSUE TITLE
Linter.py: correction in process_diff docstring

### ISSUE THREAD

**Issue by manankalra** [coala/coala#5251]
docstring of the `process_diff` function defines the parameter `diff` as *An instance of ``coalib.results.Diff`` object containing...*.
Either the word *object* should be removed or it should be replaced with the word *class*.

**Comment by Makman2** [comment]
Yeah good point, I would say we just say "A Diff object containing...", that's the shortest variant ;)

**Comment by luqmanulkhair** [comment]
I would like to work on the issue.
