### ISSUE TITLE
The `apply()` of DoNothingAction is not called in `ask_for_action_and_apply()`

### ISSUE THREAD

**Issue by nityeshaga** [coala/coala#5260]
The function `ask_for_action_and_apply()` just returns if the action chosen by the user is Do (N)othing. 
```
if apply_single == 'Do (N)othing':
  return False
```
Sure, it is conceptually the same as it would be if the `apply()` of `DoNothingAction` was called but IMHO its a bit weird and inconsistent that we don't try to `apply()` the `DoNothingAction`.

**Comment by nityeshaga** [comment]
Can I work on this issue?

**Comment by Makman2** [comment]
Agree, sounds weird.

**Comment by nityeshaga** [comment]
Completing this will also close #5202
