### ISSUE TITLE
Writing_Documentation.rst: reStructuredText link is not working

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5263]
The reStructuredText guide link (http://www.sphinx-doc.org/en/latest/rest.html) is not working. Change it to http://www.sphinx-doc.org/en/master/rest.html maybe.

(ref: https://github.com/coala/coala/blob/master/docs/Developers/Writing_Documentation.rst)

**Comment by lalitmee** [comment]
@Makman2 I can solve this issue. Please assign me to this. :innocent:

**Comment by MacBox7** [comment]
The link is working for me. Is the change really necessary?

**Comment by lalitmee** [comment]
@MacBox7, Actually the old link was not working until last 8 hours but I don't how it's working now. And I was assigned to this issue. So I did it. Maybe there is some problem with the old link. Hope that it will not happen with the modified one. :smiley:
