### ISSUE TITLE
Rename method _cleanup_bear in Core.py

### ISSUE THREAD

**Issue by palash25** [coala/coala#5266]
I think the name `_bear_cleanup()` would be more suited to this [method](https://github.com/coala/coala/blob/master/coalib/core/Core.py#L292) since `_cleanup_bear()` (this name is seems to be in line with our bear naming convention) sounds like a separate bear that does some cleanup rather than a method that removes a bear from the `running_tasks` dict.

cc @Makman2

**Comment by palash25** [comment]
This would make a nice newcomer or low issue

**Comment by palash25** [comment]
cc @Makman2

**Comment by Makman2** [comment]
I don't have a problem with the current name, it's "cleanup a bear". It's not a `CleanupBear` :smile: 
I think it doesn't make sense to change it due to that reason^^

**Comment by palash25** [comment]
Well if you think that the current name is fine then maybe we should close this?
