### ISSUE TITLE
Modify installing from git instructions in development_setup documentation

### ISSUE THREAD

**Issue by virresh** [coala/coala#5276]
https://github.com/coala/coala/blob/master/docs/Developers/Development_Setup.rst#installing-from-git

Change ```cd -``` to ```cd ..```
This makes it compatible with windows cmd as well
(and also will run in case the OLDPWD variable is not set by chance in any linux environment)

**Comment by sherrybai** [comment]
Hello! Can this issue be assigned to me?

Thank you!

**Comment by gabi0348** [comment]
Hello! Can this issue be assigned to me?
