### ISSUE TITLE
VSCode Syntax Highlighter Plugin for .coafile

### ISSUE THREAD

**Issue by palash25** [coala/coala#5277]
Is there an official .coafile syntax highlighter plugin for vscode?
If not then I would like to work on this as a mini project. :smile:

**Comment by Makman2** [comment]
I guess this can be done even in a separate repository.

@palash25 we'll create a new repo if you have a working prototype ;)

**Comment by palash25** [comment]
I don't have a prototype currently (busy with the assigned issue), I was thinking to make about making a private repo and once it is ready you can fork it, but it will take some time can't do it now :smile:

**Comment by Makman2** [comment]
We would rather like to take the ownership of such a repo to make it "officially supported and maintained" by our org. If you want to keep it it's also fine, but we won't fork it ;)

**Comment by palash25** [comment]
Okay if I can get started on the prototype in a few days, then I will let you know and you can create a new repo to which I will push otherwise if I can't get time for this then you can un-assign me and let someone else do it.

**Comment by jayvdb** [comment]
Not relevant to this repo.
Create in https://github.com/coala/meta/ if you want.
Or just do it and let us know when you want it listed as part of coala's editor plugins.
