### ISSUE TITLE
commits should not include WIP prefix.

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5287]
http://coala.io/commit should explicitly state that commits should not have a WIP prefix.

The PR title can include the WIP prefix, but ... we have labels for that.

**Comment by HyeockJinKim** [comment]
Hello! Can this issue be assigned to me?

**Comment by jayvdb** [comment]
ping me when you've accepted invite to join the org

**Comment by HyeockJinKim** [comment]
I joined.
