### ISSUE TITLE
Add support for writing ignore comment in some languages

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5295]
There is currently no ignore comment support for PHP.
> [    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. Add (I)gnore comment
[    ] Enter number (Ctrl-D to exit): 2
!    ! Please enter a value for the parameter 'language' (No description given.): php
[ERROR][12:50:23] Failed to execute the action IgnoreResultAction with error: There are no available attributes for this language..

Add corresponding attributes (e.g. comment delimiter) to coalib/bearlib/languages/definitions/PHP.py

Same issue for Fortran, ObjectiveC, PLSQL, Ruby, Scala and Swift. There are indeed thousands of languages, but these already have stub code in coalib/bearlib/languages/definitions, so I think it could be a quick fix.

**Comment by ishanSrt** [comment]
can you provide with the test case?

**Comment by li-boxuan** [comment]
@ishanSrt My thought is sometimes you may want to add ignore comments when using LineLengthBear. This can happen to all languages I guess.

**Comment by li-boxuan** [comment]
@jayvdb I am willing to do this.

**Comment by Makman2** [comment]
Oh actually we should file specific issues for specific languages, so we can progress better.

**Comment by Makman2** [comment]
@li-boxuan Please file them for all languages missing you can think of :)
