### ISSUE TITLE
.coafile: Replace default section with all

### ISSUE THREAD

**Issue by MacBox7** [coala/coala#5307]
Refer https://github.com/coala/coala-bears/issues/2397
difficulty/newcomer

**Comment by yzgyyang** [comment]
Can I get assigned to this one? It's my first newcomer issue.

**Comment by himanshuc3** [comment]
@Makman2 Can I take this one?

**Comment by jayvdb** [comment]
I've assigned one newcomer issue to @himanshuc3 , so this one is still up for grabs

**Comment by jayvdb** [comment]
See https://github.com/coala/coala-bears/pull/2402 ; which was the same change in a different repo

**Comment by sachinmukherjee** [comment]
@jayvdb can I solve this issue?

**Comment by sachinmukherjee** [comment]
@MacBox7 created a PR at https://github.com/coala/coala/pull/5384 can you review it?

**Comment by jayvdb** [comment]
Oh I see you've created a new PR.
Please dont do that again.

**Comment by sachinmukherjee** [comment]
@jayvdb I'm completely messed up with git commands. Sorry

**Comment by ishanSrt** [comment]
Duplicate of https://github.com/coala/coala/issues/4127
This needs to be opened in all the repos. Close one of these in this repo.

**Comment by jayvdb** [comment]
Duplicate of #4127

**Comment by jayvdb** [comment]
Actually we need to migrate .coafile to mobans to be maintainable.
