### ISSUE TITLE
Result.py: Add docstring regarding the case that line or column is None

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5310]
The output generated by coala can have ```line``` being ```None``` or ```column``` being ```None```.

```column = None``` means there is an error with the whole line.
```line = None``` means the whole file. The reason behind it is that it's an unknown line means it can occur anywhere in the file.

All combinations with None values and numbers for line and column are allowed, except ```line=None``` and ```column=<some number>```

This should be clarified in the documentation.

(ref: http://api.coala.io/en/latest/coalib.results.html#module-coalib.results.Result)

**Comment by newbazz** [comment]
@li-boxuan do you want to work on it?

**Comment by li-boxuan** [comment]
@newbazz I'm currently working on other issues. Take it if you want. :-)

**Comment by li-boxuan** [comment]
@hritikhks You need to get one newcomer issue merged/approved first.

**Comment by ananyaarun** [comment]
@li-boxuan , can i work on this ?

**Comment by ananyaarun** [comment]
@li-boxuan , in the Result.py file i see in line 155 ans 156 line and column have been set to none. Shall i add 2 docstrings below them ?

**Comment by li-boxuan** [comment]
@ananyaarun You can do as what you say first, create a PR and then reviewers can comment and discuss about what the best place should be.
