### ISSUE TITLE
Test the man page

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5321]
#4894 added man/man1 to setup.py, but who knows if it works.  We should have some test logic which verifies that `man` can load the man page correctly

In the referenced issue, a much more complex solution was used by a team who generally verify their stuff works.
https://github.com/wkentaro/wstool/blob/68003a95c2bde7b26101a9621de814ff82a73b64/setup.py#L21

**Comment by nikitavbv** [comment]
I am interested in working on this issue. Could you assign it to me please?

**Comment by jayvdb** [comment]
Done. Im actually 90% confident the current code is busted.

Also setup.py has 'moved' to gitlab coala/mobans. Create an issue there if you find it has a bug.

**Comment by nikitavbv** [comment]
> Im actually 90% confident the current code is busted.

You are right. Man pages are not installed properly. I created an issue for that: https://gitlab.com/coala/mobans/issues/33

**Comment by jayvdb** [comment]
Remove the moban sync stuff in `.travis.yml` to work on building a tested solution in this repo, which we can then migrate to the mobans repo.

I have a pending patch which removes the sync stuff, and will let you know when that is merged.

**Comment by nikitavbv** [comment]
Actually, I was wrong with some of my assumptions of how setup.py works here. Man pages are installed correctly. I closed the Gitlab issue.
Now I will add testing of man pages to the Travis build.

**Comment by jayvdb** [comment]
As noted on the PR, this isnt really solved yet.
