### ISSUE TITLE
Diff.py: Update ``split_diff`` docstring

### ISSUE THREAD

**Issue by manankalra** [coala/coala#5329]
In the docstring of ``split_diff`` function, [Line 323](https://github.com/coala/coala/blob/master/coalib/results/Diff.py#L323) should be updated to - `If ``-1`` is given, every change...`. 

This is needed to prevent bear developers from using any arbitrary negative value (and use a common value) in order to ease out the process of implementing changes to the current behavior in future.

difficulty/newcomer
area/documentation

**Comment by mohit2872** [comment]
can u assign this to me?

**Comment by frunkad** [comment]
This issue was left unupdated from quite some time so created a pull requests, https://github.com/coala/coala/pull/5679 

@jayvdb

**Comment by jayvdb** [comment]
#5679 closed.  Please finish https://github.com/coala/coala/pull/5661 @frunkad

**Comment by blindacai** [comment]
In the description, it says to update that line to `If ``-1`` is given`. Should it be literal \`\`-1\`\` or just -1 ?
