### ISSUE TITLE
FilterTest.py: change import

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5331]
tests/parsing/FilterTest.py imports ```available_filters``` from ```coalib.parsing.FilterHelper```
```python
from coalib.parsing.FilterHelper import available_filters
```

IMO it should be changed into
```python
from coalib.parsing.filters import available_filters
```

ref: 
FilterTest: https://github.com/coala/coala/blob/master/tests/parsing/FilterTest.py#L4
FilterHelper: https://github.com/coala/coala/blob/master/coalib/parsing/FilterHelper.py#L2
filters: https://github.com/coala/coala/blob/master/coalib/parsing/filters/__init__.py

**Comment by riddhyasona** [comment]
@li-boxuan and @jayvdb Sirs, I am new to coala and open source. Can I be assigned this issue and can you explain me the work detail and how to set up coala locally on virtualenv? I am currently getting a huge log of errors but setup gets completed

**Comment by palash25** [comment]
@riddhyasona any problems related to installation should be asked and not on the issue thread on the **coala/coala** gitter channel we would be able to help you better there .

And also no need to call anyone *Sir* here we are all peers.
