### ISSUE TITLE
Linter_Bears_Advanced.rst: Wrong indentation

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5337]
See https://github.com/coala/coala/blame/master/docs/Developers/Linter_Bears_Advanced.rst#L123
Sample code uses wrong indentation
```python
@linter(executable='my_tool')
class MyBear:
def process_output(self, output, filename, file):
    for issue in json.loads(output):
        yield Result.from_values(origin=self,
                                 message=issue["message"],
                                 file=filename)
```

**Comment by Polcat000** [comment]
@li-boxuan can I take a crack at this?

**Comment by li-boxuan** [comment]
@Polcat000 Only maintainers can assign issues. You can ask for some maintainer to assign this issue to you at Gitter channel: https://gitter.im/coala/coala. And then you can start working on that.
