### ISSUE TITLE
ambiguous comment

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5356]
https://github.com/coala/coala/blob/ca86eefe1f5b972f22f5ea793476445fd037184c/coalib/settings/ConfigurationGathering.py#L487 

no such thing as `default_list`

**Comment by jayvdb** [comment]
Can you dig into the `git blame` to find out when `default_list` was a thing, so we can see why this comment existed.

That will help determine what the appropriate course of action is.

**Comment by ishanSrt** [comment]
seems it was never anything, added out of nowhere in https://github.com/coala/coala/commit/41b99b81ba8f49793bbed0ef6c194cd4d7e943a2

**Comment by jayvdb** [comment]
Yup. Agreed there doesnt seem to be much to understand from the history.
Ping @AbdealiJK

**Comment by AbdealiJK** [comment]
https://github.com/coala/coala/commit/41b99b81ba8f49793bbed0ef6c194cd4d7e943a2

It's a 2-line comment:

    Note: arg_list can also be []. Hence we cannot use `arg_list = arg_list or default_list`

There were some discussions at the time about the fact that we should use `a  = a or <default value>` instead of mutable argument.

Hence this was a note that this should NOT be changed to `a  = a or <default value>` as that would cause it to get the default value for `[]` too - But that was being used in the tests at https://github.com/coala/coala/blob/f81c9763c9b9ad091b868e419371e24d681b79b4/tests/settings/ConfigurationGatheringTest.py#L114

Hence the commit fixes that and gives a warning not to change it to `a  = a or <default value>` as it will break tests.

Related discussion at the Issue: https://github.com/coala/coala/issues/1352 and the larger story at https://github.com/coala/coala/issues/452

**Comment by AkshJain99** [comment]
If no one is working on this issue i would like to work on this issue

**Comment by AkshJain99** [comment]
can anybody tell what actually we need to do in this issue???

**Comment by ishanSrt** [comment]
sorry @AkshJain99 I don't have a proper understanding of the concerned test case, maybe ping **AbdealiJk** to get a follow up and a better understanding.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.

**Comment by ishanSrt** [comment]
Closing this on the grounds of a valid explanation. @AkshJain99 if you still want to improve upon the comment and solve the issue, drop a comment.
