### ISSUE TITLE
Fix typo in docstring of Smell.py

### ISSUE THREAD

**Issue by pareksha** [coala/coala#5364]
There is a bracket typo at ``coalib/bearlib/aspects/Smell.py`` 
Change ``public class Customer…`` to ``public class Customer {``
Newcomers are welcome for this issue.

**Comment by sachinmukherjee** [comment]
@jayvdb please assign me this issue

**Comment by jschwarzwalder** [comment]
@pareksha would you like to apply this fix?

**Comment by Naman-Garg-06** [comment]
https://github.com/coala/coala/pull/5371
Have corrected the bracket typo and requested for a pull request.

**Comment by sangamcse** [comment]
@Naman-Garg-06, stop creating Pull Request for all newcomer issues.

**Comment by beisekenov** [comment]
@jayvdb, @Makman2 can I work on this issue?

**Comment by alaeddingurel** [comment]
Can you assign me this issue?

**Comment by Makman2** [comment]
@beisekenov invite sent, please accept so we can finally assign you.
@alaeddingurel as you see @beisekenov has requested first and already started ;)

**Comment by alaeddingurel** [comment]
Ok, Thank you :)

2018-04-26 20:37 GMT+03:00 Mischa Krüger <notifications@github.com>:

**Comment by pareksha** [comment]
@akshayg08 seems like @beisekenov is already working on this. You can have any other newcomer issue assigned. Find an issue and ask a maintainer on gitter to assign you. :)

**Comment by Ishaan28malik** [comment]
I want to contribute for this issue
https://github.com/coala/coala/issues/5364
