### ISSUE TITLE
Typo in Constants.py and ConfigurationGatheringTest.py

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5366]
Line 99 of [ConfigurationGatheringTest.py](https://github.com/coala/coala/blob/master/tests/settings/ConfigurationGatheringTest.py#L99)
Line 118 of [Constants.py](https://github.com/coala/coala/blob/master/coalib/misc/Constants.py#L118)

difficulty/newcomer

**Comment by li-boxuan** [comment]
The first link should be https://github.com/coala/coala/blob/master/tests/settings/ConfigurationGatheringTest.py#L99

**Comment by sangamcse** [comment]
Done @li-boxuan

**Comment by Naman-Garg-06** [comment]
https://github.com/coala/coala/pull/5370
https://github.com/coala/coala/pull/5369
I have corrected deafult to default (if that was the typo), and requested a pull request.

**Comment by Naman-Garg-06** [comment]
Also I don't know that whether these issues are assigned to individuals. I would love if anybody helps me out in this.

**Comment by sangamcse** [comment]
These are not assigned to anybody but you should have gone through the newcomer guidelines before creating any Pull Request and you didn't asked for any issue, you just created PR for the issues.

**Comment by jayvdb** [comment]
I've invited @Naman-Garg-06 to the org so we can assign him
