### ISSUE TITLE
PycodestyleBear checks are breaking the circleci and travis builds

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5372]
New checks are added in `pycodestyle 2.4.0` release on (2018-04-10) which are W504, W605, W606, and E252. These checks are breaking the builds of `coala`.
Here is a snapshot of the failure 
```
coalib/bearlib/aspects/docs.py
[  25] ·················fix_suggestions:·str=''):
**** PycodestyleBear (E252) [Section: autopep8 | Severity: NORMAL] ****
!    ! E252 missing whitespace around parameter equals

coalib/results/SourceRange.py
[ 194] ········return·(super().__contains__(item)·and
**** PycodestyleBear (W504) [Section: autopep8 | Severity: NORMAL] ****
!    ! W504 line break after binary operator

tests/coalaTest.py
[ 308] ················self.assertNotRegex(err,·'^\[WARNING\]')
**** PycodestyleBear (W605) [Section: autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\]'
```

It can be fixed by adding these new checks to `pycodestyle_ignore` list under `autopep8` section of `.coafile`.

Here is the build links. https://circleci.com/gh/coala/coala/16850 , https://travis-ci.org/coala/coala/jobs/365460326#L1562

**Comment by jayvdb** [comment]
Please include details of the problem.  Assume circle and travis go offline permanently tomorrow.

**Comment by sangamcse** [comment]
I can fix it. Please assign me. 😃

**Comment by jayvdb** [comment]
Not until you've done proper analysis, and there is a agreed upon direction to take.  Very likely anyone using coala bears master is facing these problems, not just us, so fixing the bear may be far more important than just fixing `coala/coala` by *ignoring* these issues.  Since when has ignoring problems been the first good option..?

Firstly, what is our bear dependency requirement?  Why does it allow 2.4 to be installed unexpectedly?

You mention four new rules but provide only three examples.

Find the PR/issues of each of these new rules which are causing errors.  Read them.

E252 is strange to be required in args.  Possibly a bug.

W504 is the inverse of what it used to be; previously the linebreak was required to be after the binary operator (`and`).

Are the W605 errors correctly detecting invalid escape sequences?

**Comment by sangamcse** [comment]
The builds are throwing three errors only.
> You mention four new rules but provide only three examples.

**Comment by RaiVaibhav** [comment]
Please add travis and Circle CI build link.

**Comment by jayvdb** [comment]
Can someone check bears builds and report back if they have additional errors.

**Comment by sangamcse** [comment]
No
> Are the W605 errors correctly detecting invalid escape sequences?

Here is an example which I think is not detected correctly https://travis-ci.org/coala/coala-bears/jobs/365232659#L5347

**Comment by sangamcse** [comment]
> E252 is strange to be required in args. Possibly a bug.

E252 is not required but recommended.
@jayvdb, https://github.com/PyCQA/pycodestyle/issues/692#issue-265378327

**Comment by jayvdb** [comment]
> Here is an example ... travis link

travis links are for evidence, but I need to see the problem reported here in GitHub for our records.

**Comment by jayvdb** [comment]
> pip is installing pycodestyle 2.4.0 from bear-requirements travis-ci.org/coala/coala-bears/jobs/365232659#L2741

a) that is coala-bears, but more importantly ... the technical answer is bear requirements includes `pycodestyle~=2.2` , so 2.4 is acceptable, which allows new rules to turn up unexpectedly.

If all the new rules are valid, then that may be ok.  If there are bugs in 2.4, we should prevent installation of 2.4

**Comment by sangamcse** [comment]
>> Here is an example which I think is not detected correctly https://travis-ci.org/coala/coala-bears/jobs/365232659#L5347

> travis links are for evidence, but I need to see the problem reported here in GitHub for our records.

```
tests/vcs/git/GitCommitBearTest.py
[ 278] ·····························body_regex=r'Fix\s+[1-9][0-9]*\s*'),
**** PycodestyleBear (W605) [Section: all.autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\s'
```
IMO, W605 is not detecting correctly.

**Comment by sangamcse** [comment]
> If all the new rules are valid, then that may be ok. If there are bugs in 2.4, we should prevent installation of 2.4

I found that:
- E252 check is recommended rule and `pycodestyle` is detecting it properly
- W504 checks line breaks **after** logical operators and is inverse of W503(Check for line breaks **before** logical operator)
- W605 is having a problem https://github.com/coala/coala/issues/5372#issuecomment-380748178
- W606 is for new syntax which is released with Python 3.7
  > Add W606 warning for ‘async’ and ‘await’ reserved keywords being introduced in Python 3.7

**Comment by sangamcse** [comment]
https://pycodestyle.readthedocs.io/en/latest/developer.html#id2
> Add W504 warning for checking that a break doesn’t happen after a binary operator. This check is ignored by default.

When I used `pycodestyle somefile.py`, It didn't checked W504 but when I used `pycodestle somefile.py --ignore=E501`, it checked for W504.
So it should be added in ignore list if we are allowing `pycodestyle 2.4`.

**Comment by jayvdb** [comment]
> IMO, W605 is not detecting correctly.

cross-check, double-check, look for issues upstream, if not report any problems (but maybe 'ask a friend' to double check before reporting)

This is a blocker.  Nothing else matters.  We should not allow our bear to be introducing new rules which are broken.

**Comment by sangamcse** [comment]
W605 is valid and also detecting correctly. 
This is what I cross-checked
```
Invalid escape sequences are deprecated in Python 3.6.
Okay: regex = r'\.png$'
W605: regex = '\.png$'
```
pycodestyle referred https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

In [tests/parsing/LineParserTest.py#L125](https://github.com/coala/coala/blob/master/tests/parsing/LineParserTest.py#L125)
```
        self.assertRegex(cm.output[0], 'WARNING:root:The parse method of '
                                       'LineParser is deprecated\.*')
```
pycodestyle detected: W605 invalid escape sequence `\.`
The valid code is 
```
        self.assertRegex(cm.output[0], 'WARNING:root:The parse method of '
                                       r'LineParser is deprecated\.*')
```
Conclusion: W605 is valid check. There is one problem with it right know i.e, it is not detecting the correct position. Here is the snapshot of it which shows Line 125 is having problem instead of Line 126.
```
tests/parsing/LineParserTest.py
[ 125] ········self.assertRegex(cm.output[0],·'WARNING:root:The·parse·method·of·'
**** PycodestyleBear (W605) [Section: cli | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\.'
```
There is one PR open for it https://github.com/PyCQA/pycodestyle/pull/747

**Comment by jayvdb** [comment]
So how many errors of each type do we have?

I'm pretty sure we would want to permanently ignore `W504` wrt logical binary operators `and` / `or`, as a rather senseless switch for no specific gain.  But does `W504` cover any other scenarios than `and` / `or`?  i.e. non-logical binary operators?

`W605` would be useful newcomer issues (and thus should be ignored initially), as they provide learning about regex, and are easy to check the patches are correct with this new rule.

`E252` is likely a set of changes we want to make, but also are useful newcomer issues  (and thus should be ignored initially).

**Comment by sangamcse** [comment]
No. of errors for:

- E252 = 180
- W504 = 120
- W605 = 34

> So how many errors of each type do we have?

---
No. (Ref: [PyCQA/pycodestyle#502/files](https://github.com/PyCQA/pycodestyle/pull/502/files#diff-f7a99c5fc1f03c3939f0b630fe0c20f6R1140))
> But does W504 cover any other scenarios than and / or? i.e. non-logical binary operators?

**Comment by jayvdb** [comment]
Note there is a bug in W605.  See https://github.com/coala/coala-bears/issues/2425

> But does W504 cover any other scenarios than `and` / `or`? i.e. non-logical binary operators?

The answer is yes.  It includes many many times of binary operators.  I suspect they skip `%` which could be binary or non-binary, and the python language makes it hard to determine which type it is statically, as the difference is mostly the types of the args from memory.

**Comment by jayvdb** [comment]
https://travis-ci.org/jayvdb/coala/jobs/366389285 is a log of only the W504.

Most concerning is the use of `+` for string concatenation.

`git grep "' +$"` also shows these.

What we are looking for is whether any of these W504 are not correct according to the pep8 style guide.

https://travis-ci.org/coala/coala-bears/jobs/366389709 also shows the same for the bears repo, which gives us another sample set to look for any erroneous results.

**Comment by jayvdb** [comment]
Due to https://github.com/coala/coala-bears/issues/2431 , there is nothing we can do here easily except add them all to the ignore list.

**Comment by jayvdb** [comment]
After this is merged, we can create a high importance low difficulty issue for each of the escape sequence problems.

And a low importance low difficulty issue to fix all of the `E252` (one big patch; removing the ignore at the same time)

And `W504` is not worth ever worrying about.
