### ISSUE TITLE
Typo in DocstyleDefinitionTest, TextPositionTest & TextRangeTest

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5373]
instantation -> instantiation

https://github.com/coala/coala/blob/master/tests/bearlib/languages/documentation/DocstyleDefinitionTest.py#L20
https://github.com/coala/coala/blob/master/tests/results/TextPositionTest.py#L8
https://github.com/coala/coala/blob/master/tests/results/TextRangeTest.py#L9

**Comment by corinv** [comment]
I'd happily pick this up, if possible.

Would a maintainer assign me?
