### ISSUE TITLE
Developers should have the option to run coala even if the files haven't changed at all

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5374]
not an extra tag which has to be provided always, something like give it once and forget it.
currently its frustrating to change the file everytime you run coala to test something,
of course one can use `sed` but that too gets irritating if you have to change the files being tested upon repeatedly.

**Comment by li-boxuan** [comment]
Did you try `--flush-cache` option?

**Comment by ishanSrt** [comment]
@li-boxuan what does it mean by the `DEBUG` message:
```
bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
```

**Comment by li-boxuan** [comment]
@ishanSrt You mean `messages from previous runs may not appear`? I don't know, it does not make much sense to me. :sweat_smile:
