### ISSUE TITLE
Change .coafile as circle.yml no more exists

### ISSUE THREAD

**Issue by harshhx17** [coala/coala#5375]
In the yml section of the .coafile we have circle.yml which no more exists
Change it to its new path

**Comment by harshhx17** [comment]
@jayvdb  Can you please assign this issue to me

**Comment by jayvdb** [comment]
@harshhx17 , this is a newcomer issue.

**Comment by harshhx17** [comment]
Oh! cool

**Comment by souravbadami** [comment]
@jayvdb -- Can you assign this to me ?
