### ISSUE TITLE
Remove W605 from ignore list and fix invalid escape sequence

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5383]
As per discussed in https://github.com/coala/coala/issues/5372#issuecomment-381314867

https://github.com/coala/coala-bears/pull/2432 can help.

importance/high
difficulty/low

**Comment by rohanrk** [comment]
@jayvdb is this still an issue? I removed W605 from my .coafile and coala doesn't return any errors.

**Comment by sangamcse** [comment]
@rohanrk have you upgraded `pycodestyle` to 2.4.0?

**Comment by yzgyyang** [comment]
Similar automation may be used from https://github.com/coala/coala/issues/5382#issuecomment-381878103.

**Comment by JameerBabu** [comment]
Hi, I would like to work on this issue. Can anyone please assign me

**Comment by seeeturtle** [comment]
@sangamcse 
Sorry I forgot to ask for assigning me.
I just checked that there is no PR for this issue, and started to work.

**Comment by JameerBabu** [comment]
@seeeturtle  I wanted to work on this issue and asked the owner to assign me, I am waiting for his decision.  In meanwhile you created PR also.

**Comment by seeeturtle** [comment]
@JameerBabu
also? do you mean that you have already created PR for this issue?
Then I should close my PR since it's duplicated.
