### ISSUE TITLE
Remove E133, E242 and E303 from pycodestyle_ignore list of .coafile

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5389]
These 2 checks are important to select and will not affect any code.

difficulty/newcomer

**Comment by sangamcse** [comment]
Remove E242 also.

**Comment by vishal3410** [comment]
hii , i am newcomer can you please assign this to me

**Comment by vishal3410** [comment]
i made a pr please review https://github.com/coala/coala/pull/5422

**Comment by Makman2** [comment]
@sangamcse what are those rules?

**Comment by sangamcse** [comment]
@Makman2 Sorry for the late reply. 
- E133 is closing bracket is missing indentation
- E242 is tab after ‘,’
- E303 is too many blank lines (3 or more lines)

**Comment by shashwatmishra76** [comment]
Can I be assigned to this issue?
