### ISSUE TITLE
Remove E241 check from pycodestyle_ignore list

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5391]
E241 check is for multiple spaces after ',' and is important code style check. This is should not be ignored. There is one line of code change required after removing this check. Both should be done on this issue.

difficulty/newcomer
type/codestyle

**Comment by lakhanshiva** [comment]
Hi, I would like to assign this issue to me. Asked a maintainer on git to assign it to me. 

Regards, 
Lakhan
