### ISSUE TITLE
"filters" rewrite

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5398]
Foremost,
```
[['language', 'c', 'java'], ['can_fix', 'syntax']]
```

is just wrong on every level.

Very worst case it should be tuples, not lists.

However it should be a dict, or OrderedDict if the order matters.
```
{'language': ['c', 'java'], 'can_fix': 'syntax'}
```

And better yet it should be a proper class, so that it can be used in type annotations.

In some places this 'structure' is given argument name `filters`, which hints it may contain multiple items.

In other places (e.g. apply_filter) it is `filter_name`.

And for `is_valid_filter`, the arg name is `filter`, which is a [builtin function](https://docs.python.org/3/library/functions.html#filter).

**Comment by sangamcse** [comment]
I would like to fix this @jayvdb

**Comment by mayokunthefirst** [comment]
@jayvdb can i be assigned to this?

**Comment by jayvdb** [comment]
no, you consistently failed to complete newcomer level issues.

**Comment by sanjeethboddi** [comment]
assign this to me
@jayvdb

**Comment by jayvdb** [comment]
@sanjeethboddi , this one is almost a medium difficulty issue.  I suggest you find an easier 'low' before doing this one.

**Comment by Utkarsh1308** [comment]
Can I be assigned to this please
