### ISSUE TITLE
Add git commit to Newcomers guide

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5403]
Part of [Step 4 (Sending Your Changes)](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes) is "create a commit"

But the command to do this is not shown.

**Comment by dorothykiz1** [comment]
Helo @jayvdb we would like to take on this issue ,i hope its open. We are  team  awesome coders from Pyladieskampala.

**Comment by jayvdb** [comment]
Sure. Invite sent.  Ping me again when you've accepted.  either here or on gitter.

**Comment by jayvdb** [comment]
Please be sure to read http://coala.io/commit .  Our newcomer issues are an opportunity for you to learn `git`.  If you dont follow our commit guideline, we close your Pull Request and re-assign the issue to someone else.

**Comment by dorothykiz1** [comment]
@jayvdb helo am here i saw your response on Here we are going to start working on the bug

**Comment by dorothykiz1** [comment]
i have accepted the invite

**Comment by jayvdb** [comment]
ok, great.  You are now assigned to this issue.  Read through http://coala.io/newcomer .

**Comment by dorothykiz1** [comment]
Thank you.


Regards, Dorothy

**Comment by dorothykiz1** [comment]
https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst @jayvdb i have tried to identify this file ,i understand its the one i need to work on .my issue is how to identify the file ( like the setup.py  in the example)to work on.

**Comment by dorothykiz1** [comment]
my exact issue if you can help me with leads on the files to document and write acommit to.

**Comment by monsij** [comment]
Try making changes in the local fork of coala at : coala/docs/Developers/Newcomers_Guide.rst

**Comment by jayvdb** [comment]
Ya, you have found the correct file.  I suggest you come onto gitter where we can walk you through the process step by step.

**Comment by dorothykiz1** [comment]
thanks @monsij am working on it

**Comment by jayvdb** [comment]
Anyone can join http://coala.io/chat .  Each issue can only be assigned to one username.

**Comment by sanshay** [comment]
@jayvdb  can you assign this issue to me

**Comment by jayvdb** [comment]
@sanshay this issue has an assignee.  Use http://coala.io/new to find your own.

**Comment by Naba7** [comment]
@jayvdb i want to contribute .... please send an invitation

**Comment by rishabhgarg25699** [comment]
@AkshJain99 Firstly you have you to solve your first issue that is assigned to you .No one takes two issues at a same time .

**Comment by shivank1234** [comment]
Can I take this one?
I am a newbie......

**Comment by rajdeepbharati** [comment]
@jayvdb May I work on this issue?

**Comment by li-boxuan** [comment]
Unassigned due to inactivity.

**Comment by li-boxuan** [comment]
@rajdeepbharati Can you go to our gitter channel and ask for an invite to the org? At the same time, you can start working on it.

**Comment by rajdeepbharati** [comment]
Sure, do I need to drop a message in the coala/coala room?
