### ISSUE TITLE
Newcomers Guide doesnt explicitly show how to test changes

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5404]
Part of [Step 3 (Creating a Fork and Testing Your Changes)](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-3-creating-a-fork-and-testing-your-changes) is obviously to test the changes.

There is a 'See also: Executing tests' pointing to http://api.coala.io/en/latest/Developers/Executing_Tests.html , which says to use `pytest`.

But the command `pytest` is not shown directly in the newcomers guide.

Running `pytest` should be a separate paragraph and code block, added before running `coala`,

**Comment by dorothykiz1** [comment]
Helo @jayvdb my teammate already submitted aPR on the previous issue YOU had assigned me so i have decided to move on and work on this 
since as earlier communicated that only one name can be assigned to an issue.
