### ISSUE TITLE
process_output_corrected should not treat \n as reason to empty a file

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5415]
If there is an error on stderr, usually stdout is `\n`.

`process_output_corrected` should not interpret `\n` as intended to be the corrected file being an empty file.  It should emit an INFO message to say `\n` was ignored.

Possibly an extra flag might be added to allow `\n` to really mean an empty file, if there is no way that the linter ever has an empty file except when it is recommending an empty file (but https://github.com/coala/coala/issues/2821 , that is almost never correct, which is why it is stupid to let empty files be created.)

c.f. https://github.com/coala/coala-bears/pull/2414#discussion_r181544974

Also this will probably fix the regular problems we have with `MarkdownBear`.

**Comment by Makman2** [comment]
We can make it even a `WARNING` message imo. In ideal cases the linter should always provide us a corrected version of a file, even if nothing has changed. If nothing was provided, this usually indicates a flaw where the tool has behaved in error-mode because of bear code.

**Comment by Mohit17067** [comment]
I would like to work on this. Please assign me.

**Comment by Naveenaidu** [comment]
Can i please be assigned to this issue.
