### ISSUE TITLE
COAFILE_OUTPUT is wrong for coarc

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5417]
The string `COAFILE_OUTPUT` provides instructions for generating a `.coafile` ; it is not suitable for generating a `.coarc`.

Change the message for ~~.coafile~~ `.coarc` or `default_coafile`/`system_coafile` errors

**Comment by PrajwalM2212** [comment]
Can i be assigned this issue

**Comment by PrajwalM2212** [comment]
Sure @jayvdb . Can you assign me https://github.com/coala/documentation/issues/554.

**Comment by PrajwalM2212** [comment]
Sure @jayvdb . Can this https://github.com/coala/documentation/issues/554 newcomer issue be assigned to me ?

**Comment by PrajwalM2212** [comment]
I have already sent PR to the newcomer issue assigned to me .
