### ISSUE TITLE
Add a note to reviewers

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#5420]
Add "Check that the changes haven't been pushed from master branch" as a note to reviewers in the reviewing guide.
The wording needs to be clear enough to convey that this isn't mandatory (so that reviewers don't advice newcomers to close even their mergeable good PRs) and is just a good practice.
label: difficulty/newcomer

**Comment by ShubhamBansal1997** [comment]
@prnvdixit Please assign this issue to me.

**Comment by satya-vinay** [comment]
Can I work on this issue?

**Comment by Makman2** [comment]
Oops sorry have missed @ShubhamBansal1997, however @ShubhamBansal1997 you have to accept the invite still^^

**Comment by Makman2** [comment]
@satya-vinay please pick a different issue ;)

**Comment by ShubhamBansal1997** [comment]
@Makman2 I have accepted the invite. Moreover, you have assigned and then unassigned @satya-vinay So Is this issue assigned or unassigned, if not assigned then assigned it to me.

**Comment by Makman2** [comment]
It's assigned to you, I've already assigned and unassigned him because I've somehow skipped your comment.

**Comment by ananyaarun** [comment]
@jayvdb , I would like to work on this issue can it please be assigned to me ?

**Comment by sanchit48** [comment]
I would like to work on this issue.

**Comment by li-boxuan** [comment]
Reassigned due to inactivity
