### ISSUE TITLE
Writing_Documentation.rst: root directory --> docs directory

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala#5432]
difficulty/newcomer

**Comment by vkartik97** [comment]
@jayvdb Please Assign this to me

**Comment by vkartik97** [comment]
@ishanSrt 
Writing_Documentation.rst is already in `docs/Developers/Writing_Documentation.rst`

**Comment by DhruvThakker** [comment]
@ishanSrt Please assign this issue to me.

**Comment by jayvdb** [comment]
the content of `Writing_Documentation.rst` needs fixing.

**Comment by vkartik97** [comment]
@jayvdb Please assign this issue.

**Comment by jayvdb** [comment]
Should be `python3 setup.py docs` in root directory

**Comment by shivank1234** [comment]
Is this issue still open?
