### ISSUE TITLE
Testing_Bears.rst: Ambiguous description of ``check_validity`` 

### ISSUE THREAD

**Issue by manankalra** [coala/coala#5439]
Under Example 2, it’s mentioned that ``check_validity`` **asserts if your bear yields any results** for a particular check with a list of strings. This is not at all true as ``check_validity`` asserts only when your bear **doesn’t** yield any results for a particular check. The text should be changed accordingly.

area/documentation
difficulty/newcomer

**Comment by JameerBabu** [comment]
Hello, I would like to work on this issue. Can anyone please assign me.

**Comment by manankalra** [comment]
@JameerBabu I'm not sure if this a `difficult/low`. Better pick up an issue which requires a little more effort. (as you've already solved one ``difficulty/newcomer`` and ``area/documentation`` issue)

**Comment by JameerBabu** [comment]
@manankalra  Thank you. I will start working on other issue.
