### ISSUE TITLE
Constants.default_coafile is confusing

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5440]
`coalib.misc.Constants` has a `default_coafile` which is now quite confusing because ~~it is the system coafile~~ there is also a file called `default_coafile`.

~~Create a new constant `system_coafile` which has the same value as `default_coafile`, and remove usages of `default_coafile`.~~

**Comment by PrajwalM2212** [comment]
At present `system_coafile` exists and handles both new( `system_coafile`) and deprecated (`default_coafile`) versions . 
But default_coafile also refers to `.coafile` . Should the issue be modified to change the variable name that refers to `.coafile`.

**Comment by jayvdb** [comment]
Ah, yes, I was mis-remembering the confusing part.

e.g. we have `test_default_coafile_deprecation` which tests the deprecated file `default_coafile`, not the variable `default_coafile` which contains `.coafile`.

(i'll have to think about this one a bit more...)

**Comment by jayvdb** [comment]
Maybe we could rename variable `default_coafile` to be `local_coafile` or `config_filename`.

**Comment by jayvdb** [comment]
No discussion?

Rename the variable!
