### ISSUE TITLE
Unnecessary imports on CachingUtilities.pickle_load docstring

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5441]
The docstring contains

```py
    >>> from pyprint.NullPrinter import NullPrinter
    >>> from coalib.output.printers.LogPrinter import LogPrinter
```

Those imports are not used, and should be removed.

**Comment by satya-vinay** [comment]
@jayvdb Can i take on this issue?

**Comment by jayvdb** [comment]
You have already completed a newcomer issue, but I'll let you do one more.  After this one, find a low difficulty issue to work on.

**Comment by satya-vinay** [comment]
Ya sure
