### ISSUE TITLE
CachingUtilities.pickle_load and .pickle_dump docstring refers to non-existant filename

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5442]
Docstring is

```py
def pickle_load(log_printer, identifier, fallback=None):
    """
    Get the data stored in ``filename`` present in the user
    config directory. Example usage:
    ...
    """
```

But `filename` is not a parameter.  A better description is needed to explain which file is loaded.

The same applies to `pickle_dump`.

**Comment by gabi0348** [comment]
please assign this issue to me

**Comment by gabi0348** [comment]
It's needed only a better description? changing filename with identifier?

**Comment by palash25** [comment]
@gabi0348 look into `coalib/misc/Caching.py` and `coalib/misc/CachingUtilites.py` and figure out how caching works.
Then make a PR and we'll review it. :+1:

**Comment by SubbulakshmiRS** [comment]
the comment has to be changed to
` 
"""
 Get the data stored in ``identifier`` ,if  present in the user
 config directory. Example usage:
...
""'
`

**Comment by SubbulakshmiRS** [comment]
right ?

**Comment by jayvdb** [comment]
Re-assigned due to inactivity
