### ISSUE TITLE
TypeScript aliases is not a tuple

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5463]
`aliases` in coalib/bearlib/languages/definitions/TypeScript.py needs to be a tuple.

**Comment by jgarciabu** [comment]
Can I have this one?

**Comment by ananyaarun** [comment]
@jayvdb can i work on this issue. I have made the required changes can i create a PR ?

**Comment by jayvdb** [comment]
Sure, sent you an invite

**Comment by ananyaarun** [comment]
@jayvdb i changed aliases = 'ts' to aliases = ('ts',) to make it a tuple. But i am facing some errors when i make a PR. Can u please guide me ?
