### ISSUE TITLE
Scroll in About page

### ISSUE THREAD

**Issue by rishiip** [coala/coala#5477]
![coala-about](https://user-images.githubusercontent.com/7964257/40475964-7cb94e72-5f60-11e8-8040-f3155740aaec.png)

#### I am assuming that website https://coala.io/#/about code maintained from here only. If not, please transfer issue to associated repo.

**Comment by Jitender46559** [comment]
What i want to do in this issue

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/landing-frontend/issues/279 :)
