### ISSUE TITLE
Update TypeScript keywords

### ISSUE THREAD

**Issue by cRAN-cg** [coala/coala#5490]
Add [abstract](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Classes.md#abstract-classes), [never](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Basic%20Types.md#never) and [object](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Basic%20Types.md#object)

**Comment by cRAN-cg** [comment]
@RJ722 update the labels please, can be a great new-commers issue

**Comment by Makman2** [comment]
The file to modify is `coalib/bearlib/languages/definitions/TypeScript.py`

**Comment by RJ722** [comment]
Sure @JonathanVillordo!

Just make sure to ask on https://gitter.im/coala/coala and a maintainer would assign you soon. Also if you hadn't already done so, you need to type in "Hello World" in the same channel to get an invite to the coala org.

**Comment by JonathanVillordo** [comment]
Yes, I did but I never get the invitation.

**Comment by JonathanVillordo** [comment]
Yes, I did but I never get the invitation. let me ask in gitter Thanks

**Comment by JonathanVillordo** [comment]
assign me this please.
