### ISSUE TITLE
Make `--files` optional (useful when only GitCommitBear is used)

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5499]
If I only want to run `GitCommitBear`, why bother adding `files` which GitCommitBear doesn't use at all?

Currently, running `coala --bears GitCommitBear` returns

```
[WARNING][15:34:52] coala will not run any analysis. Did you forget to give the `--files` argument?
```

**Comment by djmgit** [comment]
@jayvdb I would like to take this up. 
So should we go with a default value for files param?

**Comment by abhishalya** [comment]
Just another https://github.com/coala/coala/issues/4232?

**Comment by li-boxuan** [comment]
@abhishalya Thanks, I'll close this issue.

Replicate of https://github.com/coala/coala/issues/4232
