### ISSUE TITLE
Typo in parse_cli

### ISSUE THREAD

**Issue by CCInCharge** [coala/coala#5510]
docstring and function signature for parse_cli method uses variable name `comment_seperators`, should be `comment_separators` to fix spelling and to align with function signature of Setting class definition.

Probably a good newcomer issue.

**Comment by jayvdb** [comment]
```console
$ git grep seperators
coalib/parsing/CliParsing.py:              comment_seperators=(),
coalib/parsing/CliParsing.py:    :param comment_seperators:          Allowed prefixes for comments.
coalib/parsing/CliParsing.py:                             comment_seperators,
coalib/parsing/ConfParser.py:                 comment_seperators=('#',),
coalib/parsing/ConfParser.py:            comment_seperators,
```

Old name needs to be deprecated, so this is a bit more complicated than a newcomer issue.

**Comment by utkarsh2102** [comment]
Hi @CCInCharge @jayvdb,
I'd like to take up the task. 
If inferred correctly, I'll have to change the function name and then another 5 statements where this function is being called. Right?

**Comment by jayvdb** [comment]
@utkarsh2102, and you need to re-add the old name back, as a deprecated argument.
search closes PRs for examples of arg deprecation.
If you can find how it should be done, then you can be assigned.

**Comment by utkarsh2102** [comment]
Okay, will look through the same and would ping once I'm ready.

**Comment by JameerBabu** [comment]
Hi everyone, I would like to work on this issue. Can anyone assign me ?? @jayvdb

**Comment by jayvdb** [comment]
Unassigned as previous assignee had three weeks to do it.

**Comment by Naveenaidu** [comment]
@jayvdb Can I Please be assigned to this issue.

**Comment by shashwatmishra76** [comment]
Can I take this issue?

**Comment by jayvdb** [comment]
@shashwatmishra76, No you may not.  This is a low difficulty issue, and you must do a newcomer issue first.

Your PR  #5688 has a bad attempt at solving this in it.

**Comment by shashwatmishra76** [comment]
@jayvdb I guess in addition to correcting the typos I have to add the old argument back as a deprecated one right? I have found out how to add old argument back as a deprecated one.Can I be assigned to this issue now?
