### ISSUE TITLE
Review.rst: Rename `Github` to `GitHub`

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5512]
See https://github.com/coala/coala/blob/master/docs/Developers/Review.rst#manual-review-process
> Anyone can submit commits for review. These are submitted via Pull Requests on Github.

`Github` -> `GitHub`

**Comment by harvipan** [comment]
Is the issue still unassigned?

**Comment by jayvdb** [comment]
@harvipan, I've sent you an invite.  Please accept and come and https://coala.io/chat with us to be assigned to this issue.
