### ISSUE TITLE
Builds are failing due to pytest's plugins

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5525]
Traceback report says `timeout` plugin could not be loaded, which is causing builds failure.
```
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'timeout' could not be loaded: (pytest 3.1.3 (/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages), Requirement.parse('pytest>=3.6.0'))!
```
Here is the full Traceback report: https://pastebin.com/ChVhArnj

**Comment by NiklasMM** [comment]
From a failing [build's log](https://circleci.com/gh/coala/coala/17699?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

> pytest-timeout 1.3.0 has requirement pytest>=3.6.0, but you'll have pytest 3.1.3 which is incompatible.

A possible fix would be to pin `pytest-timeout` to the most recent working version.

**Comment by NiklasMM** [comment]
Or better yet: find out why pytest is pinned and see if we can remove the pin.

**Comment by sangamcse** [comment]
Agree with @NiklasMM. It is because of the recent release of the plugin.https://pypi.org/project/pytest-timeout/

**Comment by jayvdb** [comment]
Latest version of pytest doesnt work with all the plugins, especially not the plugins  created
