### ISSUE TITLE
Add module docstrings to core nextgen components

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5537]
As part of https://github.com/coala/coala/issues/5359 , nextgen core component (`coalib/core/`) needs module docstrings which explain the purpose of each module.

They should conform with pep257, and be tested with pydocstyle.

**Comment by palash25** [comment]
@jayvdb the Nextgen core modules reside in `coalib/core` but you have mentioned `coalib/settings` in the issue description, just so that we are on the same page, this issue is about `coalib/core` right?

**Comment by jayvdb** [comment]
(copy paste error; fixed; thx)
