### ISSUE TITLE
Newcomer Guide: Join GitLab newcomers group

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5546]
The newcomers guide should be updated to recommend that newcomers join

https://gitlab.com/coala/roles/newcomers

**Comment by jayvdb** [comment]
This shouldnt change the existing instructions.  There are already two mentions of GitLab in the guide , iirc, and my sugestion is this addition should be extra information somewhere near the first mention of GitLab.

**Comment by Simda93** [comment]
Wouldn't be more suitable position somewhere in Step 1 ? 
For instance above "Congratulations"

**Comment by dkopatz** [comment]
Before Step 2 there is a big note mentioning GitLab. I think the recommendation would there really well.
I would like to add this point if i could get some extra infromation on what this newcomer section on GitLab is about.
