### ISSUE TITLE
Fix broken links in Development_Setup.rst

### ISSUE THREAD

**Issue by stobis** [coala/coala#5556]
There are two broken links in  [Development Setup Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html):

1. In _venv_ section:
> Now you can activate the environment and start [the next part](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should probably point to _Repositories_ section(?)

2. In _Using virtualenv_ section:
> After this, you can start [installing from git](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should point to _Installing from Git_ 

It looks like issue for newcomers.

**Comment by starkblaze01** [comment]
Please assign this issue to me.

**Comment by starkblaze01** [comment]
Please assign this issue to me.

**Comment by 0110G** [comment]
Is this issue still pending ?

**Comment by hvp004** [comment]
If the issue is still up for grab, can I be assigned to the issue?
