### ISSUE TITLE
Add `escape_quotes` to language definitions

### ISSUE THREAD

**Issue by pareksha** [coala/coala#5567]
`escape_quotes` (like `\"`, `\'` and `""`, `''`) need to be added to the language definition as per the language compatibility and preference. This will be helpful for designing respective tastes for the `QuotesBear` as well as for the usage in the bear itself.

**Comment by jayvdb** [comment]
"escape quotes" is too limited a scope for this enhancement.
We must support string literal delimiter collision for languages which do not use quotes for string literals.
See issues created about m4 and Tcl
