### ISSUE TITLE
The setup.py is not in the docs direcotry

### ISSUE THREAD

**Issue by he1l0world** [coala/coala#5593]
When I try to install the coala by the "Development Setup Notes" I found the "setup.py" is not in the docs directory.
"setup.py" is in the coala direcotry.

<img width="715" alt="coala" src="https://user-images.githubusercontent.com/27997963/42255186-63a6a81c-7eff-11e8-99fb-d7b35582271d.png">

**Comment by jayvdb** [comment]
This is a duplicate of https://github.com/coala/coala/issues/5449
