### ISSUE TITLE
Add linter option to remove an error message if line/column number is 0

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5600]
For example, CheckStyle may report an error as follows:

`CheckstyleBad.java:0: Missing package-info.java file`

Line number 0 means it is unrelated to any particular line, but the whole file. When coala detects 0 line/column number, it should not generate an error message. Instead, drop that error and emit a warning (after stripping that number).

ref. https://gitter.im/coala/coala-bears?at=5b3cfbf17b811a6d63cf84fe

**Comment by li-boxuan** [comment]
Or maybe this shouldn't be an option, but mandatory? We don't allow coala to report 0 line/column number.

**Comment by li-boxuan** [comment]
Maybe instead of removing that message, we should change 0 to None?

See https://github.com/coala/coala/blob/4cb1a6c5bb85bc42a315d118a2f66123465ab4ed/coalib/bearlib/abstractions/Linter.py#L505

**Comment by li-boxuan** [comment]
Another question is, should that be an option or default behavior?

**Comment by jayvdb** [comment]
Just remove the erroneous line number.
I think it needs to be an override option only for checkstyle bear.

**Comment by li-boxuan** [comment]
As https://github.com/coala/coala-bears/issues/2393#issuecomment-377719050 suggests, `None` means whole file in coala context. CheckStyle uses 0 to represent whole file. That's why I think we should change 0 to None instead of removing the erroneous line number.

**Comment by jayvdb** [comment]
> That's why I think we should change 0 to None instead of removing the erroneous line number.

Those are the same thing.  Changing 0 to None is removing the erroneous line number.

Apologies for the misunderstanding.  We do want the `Result` emitted, but without it being pinned to a line.
