### ISSUE TITLE
Newcomers_Guide.rst: display "move on to more difficult issues" message as note block

### ISSUE THREAD

**Issue by nikitavbv** [coala/coala#5605]
On Newcomers Guide page there is a message saying:

> Note: After you have solved a difficulty/newcomer issue, please don’t take up any more. Instead, move on to more difficult issues.

As this message starts with "Note:", maybe it would be more logical to have this marked as "Note" block (similar to "Don’t just fix a newcomer issue!" message which is lower on that page).

**Comment by anubhavsinha98** [comment]
Hey can I solve this issue?

**Comment by ishucr7** [comment]
Hi @jayvdb , can i take this up?

**Comment by shivank1234** [comment]
Is this issue still open?

**Comment by pandyamarut** [comment]
if this issue is open by any chance, please assign.
