### ISSUE TITLE
class name docs should use CapWords convention

### ISSUE THREAD

**Issue by MacBox7** [coala/coala#5626]
Files to be fixed are Redundancy.py, Metadata.py, root.py, Formatting.py, Smell.py, Security.py, Spelling.py.

**Comment by MacBox7** [comment]
Other few pep8 naming violations found in aspects and that can be fixed here probably in separate commits are =>

- coala/coalib/bearlib/aspects/base.py:125:None: class name aspectbase should use CapWords convention
- coala/coalib/bearlib/aspects/root.py:121:None: first argument of a method should be named self
- coala/coalib/bearlib/aspects/__init__.py:33:None: class name aspectsModule should use CapWords convention
- coala/coalib/bearlib/aspects/Formatting.py:337:4: variable newline_at_EOF in class scope should not be mixedCase
- coala/coalib/bearlib/aspects/meta.py:13:None: class name aspectclass should use CapWords convention
- coala/coalib/bearlib/aspects/meta.py:71:12: variable Sub in function should be lowercase

**Comment by jayvdb** [comment]
The others are different and need much more analysis. Not now. Not in this issue. They are part of the public API, and may even be hard coded into the cEP.

These `docs` are a special case as they are documentation only, and should not have much impact if renamed, and/or deprecation should be easy.
