### ISSUE TITLE
CI build failure because of httpstat.us SSL certificate error

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala#5628]
https://travis-ci.org/virresh/coala/jobs/402970785#L1642
https://ci.appveyor.com/project/anctartica/coala
https://circleci.com/gh/virresh/coala/6

difficulty/low
importance/high

**Comment by jayvdb** [comment]
Yup.  Lets go with https://httpbin.org at the moment as it seems more reliable.

**Comment by jayvdb** [comment]
httpstat.us failing again/still : https://travis-ci.org/coala/coala/jobs/403314993

**Comment by jayvdb** [comment]
https://github.com/coala/coala/issues/5433 was switching from httpbin to httpstat.us .

We need a more reliable approach :/

**Comment by jayvdb** [comment]
I set up `pytest-httpbin`, and the result was. ... 

```py
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=45891): Max retries exceeded with url: /status/418 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))
```

I change it to https://www.google.com/teapot , which was the original plan behind https://github.com/coala/coala/pull/5435 , and will not surprise anyone that the Google servers did not have an SSL error :P 

IMO we use Google Teapot.
