### ISSUE TITLE
CachingUtilities.py: Remove unused local variable

### ISSUE THREAD

**Issue by MacBox7** [coala/coala#5642]
Difficulty: Newcomer

**Comment by MacBox7** [comment]
Pyflakes error report =>
```
./misc/CachingUtilities.py:48: local variable 'e' is assigned to but never used
./misc/CachingUtilities.py:89: local variable 'e' is assigned to but never used
```

**Comment by cypher-naman** [comment]
Hi, MacBox7 I couldn't find such bug in ./misc/CachingUtilities.py please check and verify.

**Comment by MacBox7** [comment]
Sorry for the confusion. The path was relative to coalib. Maybe that confused you. Here is the [link](https://github.com/coala/coala/blob/master/coalib/misc/CachingUtilities.py) to the file. Check exception.

**Comment by HemabhKamboj** [comment]
Hi MacBox7, I have removed the unused variable, pushed the code on my forked GitHub repository but when I tested the project on Travis-Ci, the Sentinel build failed.

**Comment by jayvdb** [comment]
So, you need to read the log to find out why

**Comment by jayvdb** [comment]
@palash25 @ksdme , do we want to remove this exception, or log it?

**Comment by palash25** [comment]
I think there is no harm in providing a little extra info about what kind of error occured. So I would go with logging.

I think the author of the module must have forgotten to log them, otherwise why did he/she used `e` anyway?

**Comment by HemabhKamboj** [comment]
@jayvdb Hi I have put down the PR. The tests on Github shows some error in some other file. Not in the CachingUtilities.py 
https://github.com/coala/coala/pull/5653

**Comment by palash25** [comment]
@HemabhKamboj I have left a comment on your PR take a look

**Comment by jayvdb** [comment]
@HemabhKamboj , you will be unassigned from this issue if you dont fix the PR this weekend.

**Comment by vaibhav9619** [comment]
please assign me this issue

**Comment by HemabhKamboj** [comment]
Thanks, everyone for helping and guiding me.
