### ISSUE TITLE
add profiling options

### ISSUE THREAD

**Issue by sils** [coala/coala#565]
we should make it bear writers easy to profile their bears. To do that we could use `cProfile.runctx("self.run(*args, **kwargs)", globals(), locals())` for bear execution and then show customized profiling results to the user.

I think this would be a cool thing. I'm playing around with this right now so maybe I get a half baked solution.

**Comment by sils1297** [comment]
so essentially we can do this like this hacky thing: http://pastebin.com/ucEPS0dA

However this would mean we'd have to execute it several times because we can't reuse the result. So we'd need to find a way to get the result and then add custom printing plus only do this conditionally. (I.e. check if `profiling` setting is True :))

**Comment by sils1297** [comment]
so to close this bug:

 * [ ] Add profile option to CLI
 * [ ] Add profiling setting
 * [ ] Give profiler results to the interactor/back via a callback (we're going to purge interactors)
 * [ ] Add profiling information to docs

**Comment by sils1297** [comment]
according to http://stackoverflow.com/questions/1584425/return-value-while-using-cprofile we can just do

```
import cProfile, pstats, sys
pr = cProfile.Profile()
pr.enable()
...
my_return_val = my_func(my_arg)
...
pr.disable()
ps = pstats.Stats(pr, stream=sys.stdout)
ps.print_stats()
```

**Comment by sils1297** [comment]
damn that actually works, here's prototype no 2: http://pastebin.com/3nF5RGxQ

**Comment by Makman2** [comment]
Just for interest: What kind of information the profiles supplies?

**Comment by sils1297** [comment]
Statistics mainly, how much time is spent in which function and how often
they are called.

2015-05-22 12:18 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Where would we display this ? 
So, Im assuming we have a `profile=True` option in the .coafile
Now, when the bears in this section are run you can profile them.

Do we show all the profiles for all the bears at the end of coala's execution ?
As soon as the bear completes running ?

I think the best option is to save the profilers output into a file and mention that in the terminal.
Its really difficult to read that data on a terminal IMO and this makes the data handling easier as we can just dump into a file as soon as the bear.run finishes

**Comment by sils1297** [comment]
A file seems sane, rather than a `profile=True` setting we could have a `profile=/path/to/dir` and create a file for each bear there with the data

**Comment by sils1297** [comment]
@Makman2 sayd possibly "prometheus" can help

**Comment by Makman2** [comment]
Reassigning due to inactivity.
