### ISSUE TITLE
Fix the API breakage problem because of `debugger` flag in bear base class

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala#5676]
For further information https://github.com/coala/coala/pull/5599/files#r203964627

**Comment by RaiVaibhav** [comment]
currently its block, it will be solved after Profiler interface PR gets merge so all the breakge problem gets solved in one PR 

Maintainer assign this to me.

**Comment by jayvdb** [comment]
I'd prefer that this is done first, and the profile PR doesnt create a breakage unnecessarily causing code churn.

**Comment by RaiVaibhav** [comment]
@jayvdb  The profiler Interface is in my GSoC and time is close so If I first wait for the API PR to get a review and merge then change the code of Profiler Interface PR and then get a further review and then merge the I am already failed because of time as I will also take my time to put all the work and make a document for the final evaluation

Hoping you will understand, as API breakage is also my concern and because of that I opened a PR asap.

**Comment by RaiVaibhav** [comment]
Also, all the previous review will get mixed and right now Profiler PR Github page becomes heavy so I will open same in next PR as sometimes I can't open with my internet connection.

**Comment by jayvdb** [comment]
This is a simple fix, it is implemented already, and can get pushed in.
Updating your other PR after that is not hard.
@Makman2 can hide comments on that PR if it is too large, marking them as 'Outdated'.
https://help.github.com/articles/managing-disruptive-comments/#hiding-a-comment

If your PR is still unusable, then create a new PR and close the old one.

The size of the PR comments is not a reason to merge problematic code.

**Comment by RaiVaibhav** [comment]
>If your PR is still unusable, then create a new PR and close the old one.

No this is not a case :stuck_out_tongue: 

Can you take a look at a comment https://github.com/coala/coala/pull/5677#discussion_r205954170

**Comment by RaiVaibhav** [comment]
Its already fixed

**Comment by RaiVaibhav** [comment]
https://github.com/coala/coala/pull/5677
