### ISSUE TITLE
Inappropriate prompt message

### ISSUE THREAD

**Issue by ksdme** [coala/coala#5685]
When coala is invoked with `--single-action`, a menu is shown with a prompt saying `[    ] Enter number (Ctrl-D to exit): ` but valid input is a letter, not a number.

 Needs a fix in:
```python
STR_ENTER_NUMBER = 'Enter number (Ctrl-{} to exit): '.format('Z' if platform.system() == 'Windows' else 'D')
```

Difficulty: Newcomer

**Comment by ksdme** [comment]
Difficulty: Newcomer

**Comment by Utkarsh1308** [comment]
What command did you type exactly?

**Comment by ksdme** [comment]
coala --single-action

**Comment by Utkarsh1308** [comment]
```
usage: coala [-h] [-v] [-C] [--ci] [--json] [--format [STR]] [-c FILE] [-F]
             [-I] [-s [FILE]] [--disable-caching] [--flush-cache]
             [--no-autoapply-warn] [-b NAME [NAME ...]] [-f FILE [FILE ...]]
             [-i FILE [FILE ...]] [--limit-files FILE [FILE ...]]
             [-d DIR [DIR ...]] [-V] [-L ENUM] [-m ENUM] [-N] [-B]
             [-l LANG [LANG ...]] [-p LANG [LANG ...]] [-D] [--show-details]
             [--log-json] [-o FILE] [-r [RELPATH]] [-S SETTING [SETTING ...]]
             [-a] [-j JOBS] [-n]
             [TARGETS [TARGETS ...]]
coala: error: unrecognized arguments: --single-action
```
I am facing this error message when I type the following command 

``` coala --single-action ```

**Comment by Naveenaidu** [comment]
@Utkarsh1308 Try using the `-A` Command.
For eg:- `coala --bears=PEP8Bear --files=thanosrocks.py -A`

**Comment by Utkarsh1308** [comment]
Can I be assigned to this issue please?

**Comment by RaiVaibhav** [comment]
install the latest version of coala, go through `coala.io/newcomer` everything is well documented here
