### ISSUE TITLE
Create separate language definitions for varieties of Shell

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5710]
There is one language 'Shell' in https://github.com/coala/coala/tree/master/coalib/bearlib/languages/definitions .

For https://github.com/coala/coala-bears/issues/2665 , we need at least the four varieties supported by ShellCheck

**Comment by shashwatmishra76** [comment]
@jayvdb Which are the 4 languages you want to add? Bash,Ksh and what else?

**Comment by jayvdb** [comment]
@shashwatmishra76 the four languages supported by ShellCheck.
