### ISSUE TITLE
Release notes not published at http://api.coala.io

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5724]
https://github.com/coala/coala/blob/master/RELEASE_NOTES.rst is not published in the api docs

(or in the user docs, but that will be a bit more effort)

**Comment by hritikhks** [comment]
Can you please explain how to work on this issue? I want to work on this issue.

**Comment by prekshajagetiya123** [comment]
can I contribute too to this issue?

**Comment by aaqaishtyaq** [comment]
@jayvdb what would be the correct position to list ```RELEASE_NOTES.rst``` in API Documentation.

here?
```
..  toctree::
    :caption: Home
    :hidden:

    Welcome <self>
    Homepage <http://coala.io/#/home>
    Code of Conduct <http://coala.io/coc>
```

**Comment by starlord1311** [comment]
@jayvdb can i take up this issue?

**Comment by DhruvThakker** [comment]
@jayvdb I would like to work on this issue.
