### ISSUE TITLE
Discard ** in ignore = foo/**

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5737]
An ignore glob of `ignore = foo/**` will walk the entire structure of `foo/`, which is silly.

That is https://github.com/coala/coala/issues/3655 .

But a quicker problem to solve : `ignore = foo/**` can be rewritten as `ignore = foo/` and suddenly it doesnt walk `foo/` .

coala should recognise `foo/** in the ignore and warn the user , and then remove the `**` internally.

**Comment by mach64** [comment]
I can work on this. If there's no problem, please assign it to me.

**Comment by jayvdb** [comment]
Thanks @mach64
