### ISSUE TITLE
Fix mistake in Writing_Good_Commits.rst

### ISSUE THREAD

**Issue by Utkarsh1308** [coala/coala#5738]
On line 36 it should be ```Closes``` instead of ```Fixes```

Probably a good newcomer issue.

**Comment by AvatarSenju** [comment]
Hi, I am new here at Coala and wanted to start with some easy issues, so can i take up this task or do I have to first request on gitter.
I saw the problem and it should be easy even if using only raw edit

**Comment by DhruvThakker** [comment]
@jayvdb The pull request for this issue seems to be having an error, can I work on fixing that?
Pull Request #5752

**Comment by atb00ker** [comment]
Hi! @DhruvThakker 
It's great that you are showing interest to contribute!
Thank You.
This issues has already been taken, you can see the assignee at the top right corner! :smile: 
Can you please find another issue that has not been assigned? 
open: coala.io/new to see the issues list for newcomers! :smile:

**Comment by prakashdanish** [comment]
@DhruvThakker you should look at other newcomer issues, PRs are meant to be progressive, meaning will be improved with time.

**Comment by DhruvThakker** [comment]
> Hi! @DhruvThakker
> It's great that you are showing interest to contribute!
> Thank You.
> This issues has already been taken, you can see the assignee at the top right corner! 
> Can you please find another issue that has not been assigned?
> open: coala.io/new to see the issues list for newcomers!

Sure, Will keep this in mind. Could you please send me an invite to coala as the gitter bot is not working.

**Comment by atb00ker** [comment]
> @atb00ker Sure, Will keep this in mind. Could you please send me an invite to coala as the gitter bot is not working.

Hi Dhruv, unfortunately, i can't sent you an invite.
Please consider asking javdb on Gitter.
Besides, i feel that for conversations other than issue related subjects, Gitter is a better place anyway.
Please consider joining the Gitter room here: gitter.im/coala/coala
