### ISSUE TITLE
Add language for SASS

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5740]
Like coalib/bearlib/languages/definitions/CSS.py

**Comment by pandyamarut** [comment]
@jayvdb please assign this issue to me.

**Comment by jayvdb** [comment]
Unassigning due to inactivity.

**Comment by abhishalya** [comment]
@jayvdb Please assign this to me, I'll be happy to work on it 😄

**Comment by Utkarsh1308** [comment]
Can I be assigned to this please

**Comment by utkarsh2102** [comment]
@Utkarsh1308, are you still working on it?
If so, please finish this at the earliest.
Else, I'm willing to do so.
CC: @gaocegege

**Comment by kushthedude** [comment]
@jayvdb Please assign the issue to me , Following PR is not updated for long , I would love to solve this  issue
