### ISSUE TITLE
AppVeyor is failing due to timeout

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala#5756]
https://ci.appveyor.com/project/coala/coala/build/job/6kuc6andh7qj12t4#L282

**Comment by li-boxuan** [comment]
I quickly changed https://github.com/coala/coala/blob/master/setup.cfg#L45 into 60 on my fork, and seems AppVeyor check is passing on my fork: https://ci.appveyor.com/project/li-boxuan/coala/build/1.0.40

Maybe changing 35 sec to 40 or even 36 would also work, I didn't try though.

**Comment by jayvdb** [comment]
We have had a few successful merges in a row; this looks to be good for now.

There were a few failures last week, so we need to keep an eye on this.

**Comment by li-boxuan** [comment]
AppVeyor is failing again due to timeout. Reopen this issue.
