### ISSUE TITLE
Unnecessary blank line

### ISSUE THREAD

**Issue by shashwatmishra76** [coala/coala#5762]
Remove the blank line in coala/coalib/bearlib/languages/definitions/CPP.py file between aliases and extensions.
Probably a good newcomer's issue.

**Comment by igniteeng000** [comment]
Please assign #5762 to me

**Comment by minhaj3** [comment]
Please assign this issue to me if igniteeng000 is not working on this.

**Comment by BugDiver** [comment]
Please assign this issue to me if no one working on this.

**Comment by anonymone** [comment]
May I ask a question, did this issue assigns to someone ?

**Comment by prnvdixit** [comment]
@sharma-kunal @Mah1ndra Sorry, but this issue seems to have a [WIP PR](https://github.com/coala/coala/pull/5774) already. Please, look for other [newcomer issues](https://coala.io/new) :smile: .

**Comment by Ishaan28malik** [comment]
hey please aasign me this ..

**Comment by ugurkanates** [comment]
If not assigned please let me know so i can be assigned.
