### ISSUE TITLE
Fix typo in Writing_Native_Bears.rst

### ISSUE THREAD

**Issue by srivama** [coala/coala#5766]
On line 205, `us` should be removed.

Issue for a newcomer.

**Comment by haxzie** [comment]
Can I pick this up?

**Comment by srivama** [comment]
Sure you can. Please join the coala gitter channel and ask a maintainer to assign it to you before you start working on it :smile:

**Comment by haxzie** [comment]
@srivama Sure! since corobo is down, I'm waiting for a maintainer to invite me to the org and assign this to me 😄

**Comment by shivank1234** [comment]
Is someone working on this?

**Comment by haxzie** [comment]
@srivama can you assign this to me. I was waiting for a maintainer to invite me to the Organization. Didn happen :(

**Comment by srivama** [comment]
@haxzie I'm sorry, I can't. Only maintainers are allowed to assign the issues. They are a bit occupied atm, please be patient :smile:

**Comment by ManthanKeim** [comment]
https://github.com/coala/coala/pull/5779
please check as this will close the issue.

**Comment by ManthanKeim** [comment]
https://github.com/coala/coala/pull/5780
I've worked on this issue, please take a look.

**Comment by Makman2** [comment]
@ManthanKeim please don't work on issues without assignment esp since someone already tried to claim it before you.

**Comment by ugurkanates** [comment]
If not assigned please let me know so i can be assigned.

**Comment by import-keshav** [comment]
can i work on it

**Comment by srivama** [comment]
Please ask on the gitter channel for getting the issue assigned before you begin working on it, except if you're the first one to claim it.

**Comment by AditiKatiyar** [comment]
is this issue still open? i would like to work on it.

**Comment by Ishaan28malik** [comment]
@srivama  please assign me this issue

**Comment by haxzie** [comment]
Since there's already a PR up for this issue, if that's not being considered, Since it wasn't asigned.. I'd like to leave the issue for others who want to work on it. @Makman2 :innocent:

**Comment by srivama** [comment]
@haxzie Since you've already worked on another newcomer issue, you can leave this one and go for a low issue this time. 
@shivank1234 If you want to work on this issue, you can get it assigned to you now :smile:

**Comment by haxzie** [comment]
@srivama Sure, Thanks :)

**Comment by shivank1234** [comment]
Thanks,I will surely do :)
