### ISSUE TITLE
Git_Basics.rst: Correct maximum line length of commit body

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5777]
Right now, it is mentioning 50 characters length for commit body which should be 72.

https://github.com/coala/coala/blob/master/docs/Developers/Git_Basics.rst#adding-the-files-and-commiting

**Comment by bhawesh96** [comment]
Please assign this issue to me

**Comment by Ishaan28malik** [comment]
can i contribute this ?

**Comment by shivank1234** [comment]
Can I help here?

**Comment by bhawesh96** [comment]
I have already submitted a PR for this issue.

**Comment by shivank1234** [comment]
Ok,NP😊😊
Then,why is the issue is not closed?🤗🤔

**Comment by 7princekumar** [comment]
Please assign if not yet solved.

**Comment by jayvdb** [comment]
It already has a PR @7princekumar .  I've assigned it to the PR author now.

**Comment by 7princekumar** [comment]
> It already has a PR @7princekumar . I've assigned it to the PR author now.

Okay. I will look for another issue to work on. :smile: There are very few newcomer issues left.
