### ISSUE TITLE
Typo in ConfParserTest.py

### ISSUE THREAD

**Issue by akshatkarani** [coala/coala#5785]
Multiple times omment is written instead of comment

**Comment by haxzie** [comment]
May I work on this?

**Comment by haxzie** [comment]
@akshatkarani can you give me a little more detail on this? please :smiley:

**Comment by Makman2** [comment]
Assigning you @haxzie , however please try only to claim an issue only when you have understood it/at least a rough understanding what the goal is (for next time).

**Comment by haxzie** [comment]
@Makman2 sorry, about that. I'll try to look more into the issue from now on. Thank You for assigning this to me :)

**Comment by Ishaan28malik** [comment]
please assign me this issue@akshatkarani

**Comment by li-boxuan** [comment]
This issue is assigned to someone else and there is already an opening pr. Please look for other issues. @pandyamarut
