### ISSUE TITLE
please close all the solved issues. 

### ISSUE THREAD

**Issue by pandyamarut** [coala/coala#5790]
it reduces labour.

**Comment by jayvdb** [comment]
Which open issues are solved with a merged PR?

p.s. sent you an invite to join @coala.

**Comment by pandyamarut** [comment]
#5777 This issue is solved and PR is already made.

**Comment by pandyamarut** [comment]
@jayvdb Also the issue #5785

**Comment by li-boxuan** [comment]
> #5777 This issue is solved and PR is already made.

It is not solved. PR is made but is still open. It would be closed automatically when the corresponding PR is merged.

**Comment by pandyamarut** [comment]
@li-boxuan

**Comment by li-boxuan** [comment]
No problem, I'll close this issue.
