### ISSUE TITLE
upgrade to click>=7.0

### ISSUE THREAD

**Issue by kamikaze** [coala/coala#5797]

**Comment by AkshJain99** [comment]
@kamikaze if u can please explain what we need to do in this issue???

**Comment by shivank1234** [comment]
What is this issue all about?

**Comment by kamikaze** [comment]
hey guys. Don't be selfish... this issue is about coala downgrades click package to version that is prior 7.0 while other packages require >=7.0. Is it hard to understand?

**Comment by kamikaze** [comment]
coala-bears 0.11.1 has requirement click==6.6, but you'll have click 7.0 which is incompatible.
crossbar 18.10.1.post1 has requirement autobahn>=18.10.1, but you'll have autobahn 18.9.2 which is incompatible.

**Comment by shivank1234** [comment]
Why the platform for this issue is windows?

**Comment by shivank1234** [comment]
Can anybody tell me why click(6.6) gets installed as a direct requirement of coala-bears even though it is not mentioned anywhere in the requirement file of coala or coala-bears?

**Comment by shashank-b** [comment]
@shivank1234, I tried to find this out and it turns out that 'Click(6.0)' is a direct requirement of 'safety' which is used in the PySafetyBear and is a requirement of coala-bears.

**Comment by shashank-b** [comment]
It turns out that Click(6.0) is required by 'proselint', 'dennis' and 'safety' but you're right, this doesn't explain why it's getting installed as a direct requirement.

**Comment by shivank1234** [comment]
That is what I am after....

**Comment by shivank1234** [comment]
I got it Shashank , the thing is that pip installs package requirements according to the requirements mentioned in the files in the Python Package Index and when I checked it the  bear-requirements file contained click==6.6 package
So,I guess now I have to change the Index file to solve the issue..... :-)

**Comment by shashank-b** [comment]
Great :)

**Comment by Makman2** [comment]
Seems resolved, coala should be compatible now with click>=7.
