### ISSUE TITLE
Newcomer guide: Verify issue exists

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5802]
Migrating from https://github.com/coala/documentation/issues/487

The newcomer guide should include a step for verifying that the issue exists.

**Comment by AditiKatiyar** [comment]
can i work on this issue

**Comment by AditiKatiyar** [comment]
I have a doubt. Besides checking whether an issue is closed/open, assigned/unassigned, PRs existing, what else one should need to verify for the existence of the issue?

**Comment by AditiKatiyar** [comment]
I am working on it.

**Comment by pilgrim2308** [comment]
Hi,
I would like to work on this. Kindly assign me.
If it's okay with the maintainers, I plan on improving upon the above PR #5866.
