### ISSUE TITLE
LocalBearTestHelper: Proper deprecation for timeout

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5812]
https://github.com/coala/coala/pull/5723 was an over-hasty way of removing the dependency on `pytest`.

The `assert not timeout` broke one of the bears which used the timeout.

The bear was updated to remove the unnecessary timeout, but the assert will break old versions of coala-bears being used with the current coalib, which needlessly complicates setting up an environment to investigate old bugs.

It should be properly deprecated with a warning that the timeout is ignored.

**Comment by mach64** [comment]
@jayvdb Could I have a go at this issue?

**Comment by jayvdb** [comment]
@mach64 & @aquatiko , In an experiement, I have assigned both of you two this.  It is fairly easy, so one of you can put up a patch fairly quickly I guess.  Whoever gets the PR up first, wins, and the other needs to do the code review ;-)
