### ISSUE TITLE
Writing Good Commits should use real commits as examples

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5819]
https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

The example commits include references to issues, however those issues are not the same as the examples.

e.g. https://github.com/coala/documentation/issues/573 is about a commit example which refers to https://github.com/coala/coala/issues/4018 , but that issue was solved in PR https://github.com/coala/coala/pull/4024 , and the commit https://github.com/coala/coala/commit/b4307554d8c5b6a23b12f52802e8b5cbda8b8db0 , which has a very different commit message than the one in the example.

For newcomers, that would be very confusing if they explore the examples.

**Comment by blossomica** [comment]
Can I work on this bug?

**Comment by akshatkarani** [comment]
@blossomica  ask on our gitter channel https://gitter.im/coala/coala

**Comment by blossomica** [comment]
@akshatkarani - The documentation says "Now pick an issue which isn’t assigned and which you would like to fix. Leave a comment that you would like to be assigned to the issue. This way we don’t have multiple people working on the same issue at the same time. Now you can start working on it!" it doesn't specify one should ask on gitter, so may I ask how you came to that conclusion?

**Comment by akshatkarani** [comment]
Corobo is down so assignment of issues is done by maintainers.

**Comment by blossomica** [comment]
@akshatkarani - Alright, I'll attempt then.
