### ISSUE TITLE
Remove unnecessary blank line

### ISSUE THREAD

**Issue by srivama** [coala/coala#5820]
https://github.com/coala/coala/blob/604072c35cf6482cd01d0af064804e5a730ada54/coalib/bearlib/languages/definitions/Python.py#L8

Newcomer Issue

**Comment by rpanczer** [comment]
I can take care of this one :)

**Comment by rpanczer** [comment]
@srivama Look at html.py in the same folder. The blank line is intentional.

**Comment by jayvdb** [comment]
A single blank line there is acceptable. It may not exist in all files.

I think this is a 'wontfix'.

**Comment by srivama** [comment]
@rpanczer Maybe! But it's only in two of the definitions, and in such small snippet, IMO blank line isn't required for enhancing readability. It's not that it will create any issues though :wink:

@jayvdb Agreed, it's only in two files and I thought this'll make an appropriate newcomer issue.. Anyways, I'll close it ;)
