### ISSUE TITLE
Add language definition for g4 files

### ISSUE THREAD

**Issue by virresh** [coala/coala#5822]
This g4 file refers to an ANTLRv4 grammar file.
See examples of g4 files and more information about them at: https://github.com/antlr/antlr4/blob/master/doc/getting-started.md

**Comment by Dhiraj240** [comment]
is it about adding generated lexer and parser of c,c++ etc. languages from grammar repo?

**Comment by virresh** [comment]
Nope.
See https://github.com/coala/coala/tree/master/coalib/bearlib/languages/definitions for examples
