### ISSUE TITLE
Update to Writing_Native_Bears and Writing_Linter_Bears

### ISSUE THREAD

**Issue by ayan-b** [coala/coala#5826]
Mention that,
- for language naming always consider the format that is used in the corresponding Wikipedia page, (**exception:** use `CPP` instead of `cpp` or `c++`);
- a language definition should be added while writing new bear;
- the alias used in LANGUAGES should be one of the names in the coala definition.

A `difficulty/low` issue.

**Comment by he1l0world** [comment]
Can I be assigned to solve this issue? Thank you!

**Comment by budukhyash** [comment]
@he1l0world  Hello if you have not solved your first issue can I take this one please ?

**Comment by he1l0world** [comment]
@li-boxuan I did solve a newcomer issue which I believe it is. [issue](https://github.com/coala/coala-ls/issues/20). Although it isn't merged because of the previous Travis failure, it was approved by another member...

**Comment by li-boxuan** [comment]
@he1l0world Sorry I was not aware of that. Could you find another difficulty/low issue to work on?

**Comment by he1l0world** [comment]
@li-boxuan No problem. I will find another

**Comment by budukhyash** [comment]
@ayan-b Hello please can you explain me the issue ?

**Comment by budukhyash** [comment]
@ayan-b  Thanks a lot
