### ISSUE TITLE
glob patterns with multiple ** incorrectly cause warnings

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#5856]
With a `.coafile` like

```
ignore =
  .git/,
  **/migrations/**,
```

warnings like the following occur:

[WARNING][02:36:51] Detected trailing globstar in ignore glob '/builds/.../**/migrations/**'. Please remove the unnecessary '**' from its end.

The trailing `**` are unnecessary only if the rest of the path is a canonical directory not containing any wildcards.

**Comment by mach64** [comment]
Would love to take this one up @jayvdb :D 
Seems like a natural continuation of my previous PR :stuck_out_tongue_closed_eyes:
