### ISSUE TITLE
Matlab extension is not a tuple

### ISSUE THREAD

**Issue by iamkroot** [coala/coala#5914]
`extensions` in coalib/bearlib/languages/definitions/Matlab.py needs to be a tuple.

**Comment by iamkroot** [comment]
difficulty/newcomer

**Comment by donosco98** [comment]
Can you pls assign me this issue

**Comment by mk1299** [comment]
Hey ! I want to work on this issue,can it be assigned to me?

**Comment by anand372** [comment]
i am interested could i work on this issue

**Comment by m-agboola** [comment]
Hi @iamkroot Can this issue be assigned to me?

**Comment by Purvanshsingh** [comment]
I am a newcomer, want to work on this issue can it be assigned to me?

**Comment by Saanidhyavats** [comment]
I want to work on this issue, can you please assign this issue to me.

**Comment by avats-dev** [comment]
Hey @abhishalya @iamkroot, I'm working on this. Please assign this to me. Will open the PR soon.
