### ISSUE TITLE
coala does not support Ignore in "subl"

### ISSUE THREAD

**Issue by anubhawbhalotia** [coala/coala#5917]
### Overview Description

# Steps to Reproduce
Run this inside coala's cloned remository
1.  `echo "int add ( a , b ) { return a + b; }" >> test.c
` 
2. `coala --files test.c --bears GNUIndentBear
`

# Actual Results
[WARNING][22:42:58] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
Executing section python...
Executing section flakes...
Executing section autopep8...
[WARNING][22:43:00] PycodestyleBear: Exit code 1
[INFO][22:43:00] Applied 'ApplyPatchAction' on 'test.c' from 'PEP8Bear'.

test.c
[   3] int·add·(·a·,·b·)·{·return·a·+·b;·}
**** PycodestyleBear (E211) [Section: autopep8 | Severity: NORMAL] ****
!    ! E211 whitespace before '('
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. Add (I)gnore comment
[    ] Enter number (Ctrl-D to exit): 

# Next input
1. Enter number (Ctrl-D to exit): 2
2. !    ! Please enter a value for the parameter 'language' (No description given.): subl

# Actual Results
**[WARNING][22:44:41] coala does not support Ignore in "subl". Consider opening an issue at https://github.com/coala/coala/issues so we can add support for this language.**
[    ] An ignore comment was added to your source code.
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ] Enter number (Ctrl-D to exit):

**Comment by frextrite** [comment]
If I interpret correctly, coala is asking you for the language of the source file ```test.c``` which is actually ```C```. So why would you enter ```subl``` instead of ```C``` in the ```! ! Please enter a value for the parameter 'language' (No description given.): ``` prompt?

**Comment by anubhawbhalotia** [comment]
Yes Right
I'm a newcomer
This was a mistake
Thanks
