### ISSUE TITLE
coalib/bearlib/aspects/Formatting.py: Typo in importance_reason =

### ISSUE THREAD

**Issue by anubhawbhalotia** [coala/coala#5922]
[https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/Formatting.py](url)
Typo in line number 21

**Comment by anubhawbhalotia** [comment]
Please assign me this issue.

**Comment by li-boxuan** [comment]
Where is the typo?
btw your link is wrong

**Comment by shashank-b** [comment]
@anubhawbhalotia 
You might want to make these changes in the description to correct it.
The correct link: https://github.com/coala/coala/blob/3eaae8875055d5340b707adaa53c289dd6b96725/coalib/bearlib/aspects/Formatting.py#L21 
Typo: `the of ...`
