### ISSUE TITLE
Expecting a comma for clarity in Newcomers_Guide.rst

### ISSUE THREAD

**Issue by roshnet** [coala/coala#5924]
In the [Newcomers_Guide.rst](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst) file,
in the following lines:
> When you say "Hello World" in chat `corobo` (our gitter bot) will invite ...

a comma looks better after "chat", like:
> When you say "Hello World" in chat, `corobo` (our gitter bot) will invite...

It sounds more clear with the comma in its place.

**Comment by kapurm17** [comment]
@jayvdb Can I be assigned this issue?
Please invite me to the organsiation too.

**Comment by rohanrajpal** [comment]
Hey, can I be assigned this issue? I haven't got an invite to be a member yet. I guess the maintainers are busy, so just dropping a comment here. 

Thanks :)

**Comment by Ishaan29** [comment]
hey ! can I be assigned to this issue ?

**Comment by shubhampal123** [comment]
Hi, I m new to Coala .I  completed newcomer's guide but did not get
the invitation to join the organisation.Can I work on this issue ?And how
to proceed to resolve this issue, means how to edit the documentation and
make pr .
