### ISSUE TITLE
Improvement in the Installation guide ( Docker Part )

### ISSUE THREAD

**Issue by rohanrajpal** [coala/coala#5925]
I tried to install coala via Docker using the following guide:
https://docs.coala.io/en/latest/Users/Install.html

Not being familiar with Docker, I would have saved some time if a link for the following page was in the install via Docker section:
http://docs.coala.io/en/latest/Users/Docker_Image.html

I can do the above work; please assign this issue to me if you guys find it worth working on, thanks!

**Comment by armanSingh** [comment]
+1

**Comment by PHANTOM956** [comment]
if no one is doing this , can i be assigned to this..??

**Comment by rohanrajpal** [comment]
@PHANTOM956 I've already asked to get this issue assigned to me, I guess people at coala are busy rn.

**Comment by rohanrajpal** [comment]
Thanks, @li-boxuan for assigning.
I have to make the changes in coala/documentation, so how do I transfer this issue there so that I can make a PR?
https://github.com/coala/documentation/blob/master/Users/Install.rst

**Comment by li-boxuan** [comment]
@rohanrajpal Can you migrate this issue to that repo? i.e. close this issue, open a new one in documentation repo and I can assign you there again.

**Comment by rohanrajpal** [comment]
Issue migrated to https://github.com/coala/documentation/issues/588
