### ISSUE TITLE
Comma typo in Writing_Good_Commits.html file

### ISSUE THREAD

**Issue by sanchit48** [coala/coala#5927]
In the following line in [Writing Good Commit Messages](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html), a comma is expected after`coala`.
like
`At coala we are looking heavily at the maintainability of the code.`
 should be
`At coala, we are looking heavily at the maintainability of the code.`

**Comment by mk1299** [comment]
Hey! Can I be assigned this issue?

**Comment by roshnet** [comment]
Hi, can I please be assigned to this issue?

**Comment by sambhavkaul** [comment]
Can  I be assigned to this issue if no one is working on this ?

**Comment by shashank-b** [comment]
@sambhavkaul, looks like mk1299 is working on this. You should look for another issue.

**Comment by sambhavkaul** [comment]
@shashank-b Okay... Thanks
