### ISSUE TITLE
Make the code coverage reach to 100%

### ISSUE THREAD

**Issue by he1l0world** [coala/coala#5931]
https://codecov.io/gh/coala/coala/src/master/coalib/processes/Processing.py#L65
https://codecov.io/gh/coala/coala/src/master/coalib/parsing/Globbing.py#L172

Maybe we can imporve code coverage to 100% by changing "# pragma posix: no cover" to "# pragma: no cover"

**Comment by he1l0world** [comment]
I saw the code coverage has reached 100% but somehow it failed in other parts. Can anyone guide me? Thank you.

**Comment by li-boxuan** [comment]
https://codecov.io/gh/coala/coala/compare/3eaae8875055d5340b707adaa53c289dd6b96725...3d80d91367cf416c020afa336efa1735fe967bc9/changes coverage reaches 100% after fixing Appveyor build failure https://github.com/coala/coala/pull/5937. Thx for reporting anyway :)
