### ISSUE TITLE
Typo in docstring

### ISSUE THREAD

**Issue by sanchit48** [coala/coala#5933]
In `coala/coalib/settings/Setting.py`,
In line 174, the word `of` should be replaced with `off`.

**Comment by budukhyash** [comment]
Please assign this to me

**Comment by sanchit48** [comment]
@budukhyash Ask in the [main channel](https://gitter.im/coala/coala) to get it assigned to you.

**Comment by PHANTOM956** [comment]
Can u please assign this to me.??

**Comment by sanchit48** [comment]
@PHANTOM956 This issue is already assigned to @budukhyash. Plz find another issue.

**Comment by rathore05** [comment]
I would like to work on this issue if this is still open ??
