### ISSUE TITLE
Writing_Good_Commits.rst:  Correction in the example

### ISSUE THREAD

**Issue by sanchit48** [coala/coala#5940]
In the starting of the [Writing_Good_Commits.rst](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html), second example of docstring typo contains the word `Fixes` in the issue reference which should be changed to `Closes` as we use `Fixes` for bugs only.  

A good newcomer issue

**Comment by sameshl** [comment]
I have not yet received an invitation after I communicated on gitter channel yesterday.Can I still work on this issue?

**Comment by sanchit48** [comment]
@sameshl you have to first get assigned to the issue and for that, you have to be a member of coala. Ask again for the invitation and to get this issue assigned on the gitter channel and tag makman2 this time

**Comment by li-boxuan** [comment]
https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html is not up-to-date. See code on GitHub, or https://coala-api.netlify.com/developers/writing_good_commits
The problem has been fixed.
