### ISSUE TITLE
Useful_Links.rst: Link to Basic rST is broken

### ISSUE THREAD

**Issue by shashank-b** [coala/coala#5947]
The link should be replaced by a working link. One of the working links is http://www.sphinx-doc.org/en/latest/usage/restructuredtext/basics.html. http://docutils.sourceforge.net/rst.html is also an option since http://www.sphinx-doc.org/en/latest has a link to it.

This can be a suitable issue for newcomers to work on.

**Comment by Hunter0098** [comment]
Please assign this issue to me.

**Comment by irinbanerjee** [comment]
Can I be assigned this issue?

**Comment by Yugandhartripathi** [comment]
I was looking to contribute and found this so I took the initiative. I am sorry if I violated any assignment protocols.

**Comment by li-boxuan** [comment]
http://www.sphinx-doc.org/en/stable/rest.html (current link) is working for me.

**Comment by shashank-b** [comment]
@li-boxuan, I am sorry, I was referring to the link here: https://api.coala.io/en/latest/Developers/Useful_Links.html#rst-links and I assumed that they are going to be the same. I should've checked first. Should I migrate this issue to somewhere else?

**Comment by li-boxuan** [comment]
@shashank-b That page is not up-to-date. You may want to check github version first next time 😉 I'll close this issue

**Comment by shashank-b** [comment]
alright @li-boxuan 
thanks :slightly_smiling_face:
