### ISSUE TITLE
Newcomers_Guide.rst: Link to meta-review is broken

### ISSUE THREAD

**Issue by shashank-b** [coala/coala#5953]
The link to `meta-review` in the file requires a little change for it to work properly. The `.html` should be changed to `.rst`.

A `difficulty/newcomer` issue.

**Comment by uds5501** [comment]
Working on it.

**Comment by li-boxuan** [comment]
I don't think the link is broken. Show me proof (e.g. screenshots) in case you think I am wrong. @shashank-b

**Comment by shashank-b** [comment]
@li-boxuan, Sorry, I guess I should've added this in the description itself.
Here are the screenshots:

The link that is actually there:
<img src="https://github.com/shashank-b/temp/blob/master/coala_metareview_broken_raw.png?raw=true" width="500">


On clicking on the link:
<img src="https://github.com/shashank-b/temp/blob/master/coala_metareview_broken_link.png?raw=true" width="500">


The actual link of the file:
<img src="https://github.com/shashank-b/temp/blob/master/coala_metareview_working_link.png?raw=true" width="500">

Please let me know if I missed something.

**Comment by li-boxuan** [comment]
See https://coala-api.netlify.com/developers/newcomers_guide.
