### ISSUE TITLE
Waffle.io not working

### ISSUE THREAD

**Issue by Anmolbansal1** [coala/coala#5959]
The Readme.md file the waffle.io integeration is not working 
![screenshot from 2019-01-19 01-53-43](https://user-images.githubusercontent.com/39100247/51411358-89ef2280-1b8d-11e9-8933-2426a778204e.png)

As it shows that there is not any pr or issues closed recently. 
![screenshot from 2019-01-19 01-40-24](https://user-images.githubusercontent.com/39100247/51411077-932bbf80-1b8c-11e9-9d5c-36fc3aed3b61.png)
but on browsing through issues and pull requests, we can see that there are some recently closed issues.

I think that there might be some problem with waffle.io . @li-boxuan @jayvdb please provide feedback. I would love to contribute on this issue.

**Comment by KVGarg** [comment]
Hi @Anmolbansal1 Can you please re-check whether this issue is still valid or not? because I have given a look by opening waffle.io. In my case, it's showing all the necessary data
Also, A sad news waffle.io is getting shut down by next month 😞

**Comment by anshalshukla** [comment]
I think the PR[6155](https://github.com/coala/coala/pull/6135) closes this issue as well.
