### ISSUE TITLE
Logging.py: Redundant import of the module logging

### ISSUE THREAD

**Issue by shashank-b** [coala/coala#5961]
In the file Logging.py, both `logging` and `logging.config` are being imported.
`difficulty/newcomer`

**Comment by AnimeshSinha1309** [comment]
Can I please be assigned this issue?

**Comment by Gromy1211** [comment]
Hi,can I be assigned to this?Thanks a lot! (●'◡'●)

**Comment by divc99** [comment]
Can I please be assigned this issue?

**Comment by anubhawbhalotia** [comment]
Please assign me this issue if it's still available. Thanks :)

**Comment by irinbanerjee** [comment]
Sorry if I am being silly...why is this a redundant import?

**Comment by irinbanerjee** [comment]
Can i issue a request?

**Comment by jayvdb** [comment]
Sorry but this isnt a valid enhancement.  It is correct that `import logging` could be removed, as there is an implicit import of `logging`, but it is not a good idea to rely on it.

Actually we should have CI check that sub-modules are always separately imported after the main module.

Created https://gitlab.com/coala/bears/coala-pyflakes/issues/10
