### ISSUE TITLE
Travis CI Sentinel build failing due to new version of pytest-xdist installed

### ISSUE THREAD

**Issue by KVGarg** [coala/coala#6009]
### Overview Description

# Steps to Reproduce

1. Clone the coala repository
2. Install test-requirements.txt
3. Figure out which version of `pytest-xdist` is installed. It must be `v1.28.0` but `v1.15.0` should be installed acc. to requirements.
4. Run pytest on coala to get the error log

# Actual Results
Travis CI Sentinel build [error log](https://travis-ci.org/coala/coala/jobs/518114133)

# Reproducibility
100%

# Additional Info
7 days back only `pytest-xdist` has released its new version v1.28.0
which is getting installed and has requirements of pytest>4.4.0

**Comment by KVGarg** [comment]
There are many other packages which are not installing a particular version as mentioned in requirements file.

**Comment by KVGarg** [comment]
@jayvdb @Makman2 Should I create a PR with just a change for library `pytest-xdist` or for all packages that are being installed with a different version from mentioned version in requirements file?

**Comment by abhishalya** [comment]
No, we don't want to change lot of requirements. Just do `pytest-xdist==1.15` and it should be fine imo.

**Comment by jayvdb** [comment]
xdist doesnt work, and should be removed, for all of our projects, which means this should be done in coala-mobans.

c.f. https://github.com/coala/coala/issues/4061
