### ISSUE TITLE
setup.py fails on old setuptools, etc.

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#6017]
```
python setup.py install
+tee setup.log
error in coala setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in moban~=0.3.3 ; python_version > '3.0' at  ; python_version > '3.0'
```
https://travis-ci.org/coala/coala/jobs/533336623

**Comment by jayvdb** [comment]
As this is our setup.py, the change needs to be done in the template , but the solution needs to be tested here.

Developing/Testing this is a bit complicated, as this job only runs on master -- so to test , edit .travis.yml to run this job on the developer fork branch .  Show the commit of it working (a comment here, with a maintainer checking it), then remove the .travis.yml edit from the commits before creating the PR.

**Comment by abhishalya** [comment]
Seems like we don't support conditional requirements in `read_requirements`. I would like to try this out @jayvdb

**Comment by abhishalya** [comment]
Ah, just a pip upgrade should do imo

**Comment by jayvdb** [comment]
This error message is a standard one coming out of older setuptools.

If so, the solution will be something like

- detect the older setuptools (with an older packaging vendored) and simplify the data we give to it, so it doesnt raise exceptions like this, but instead gives the error we want users to see
- detect and report the unsupported python version earlier

**Comment by jayvdb** [comment]
> Ah, just a pip upgrade should do imo

that fixes CI, and is a workaround for this bug, but it doesnt fix this bug.

**Comment by abhishalya** [comment]
>detect the older setuptools (with an older packaging vendored) and simplify the data we give to it, so it doesnt raise exceptions like this, but instead gives the error we want users to see

Ah, okay :+1:

**Comment by abhishalya** [comment]
Just to confirm, we should check for `pip < 9.0`?
I'm not sure when this syntax was added..

**Comment by abhishalya** [comment]
This seems to be a rough idea, let me know your thoughts @jayvdb 

```py
pip_version = tuple([int(x) for x in pip.__version__.split('.')[:3]])
if pip_version < (9, 0, 1):
    if ';' in line:
        req = line.split(' ; ')[1]
        if 'python_version' in req:
            cond = req.split(' ')[-2]
            ver = tuple([int(x) for x in req.split(' ')[-1][1:-1].split('.')])
            if '>' == cond:
                if sys.version_info > ver:
                    data.append(line.split(' ; ')[0])
                else:
                    yield('Python version not suitable')
            elif '<' == cond:
                if sys.version_info < ver:
                    data.append(line.split(' ; ')[0])
                else:
                    yield('Python version not suitable')
            elif '==' == cond:
                if sys.version_info == ver:
                    data.append(line.split(' ; ')[0])
                else:
                    yield('Python version not suitable')
            else:
                yield('Unexpected syntax')
        else:
            yield('Unexpected syntax')
    else:
        yield('Unexpected syntax')
else:
    data.append(line)
```

**Comment by jayvdb** [comment]
Likely that will be helpful, but not necessarily on this specific bug.

We have a minimum version of setuptools in coala's requirements.txt , which are *runtime* minimums.

We *should* also have a different minimum for setuptools (and pip?), which is lower than the runtime minimum , below which we will refuse to even try to run setup.  This is typically done using the new-ish `setup(.., setup_requires=...)` which is ignored by older versions of setuptools and is therefore quite useless.

If the version of python / setuptools / pip is too low, there is no benefit in parsing the requirements / test requirements / etc, as the installer should refuse to install.  For this specific issue, the version of python is too low, so the requirements are all irrelevant, and should be skipped.

This issue needs a very specific and isolated solution, because these CI jobs dont run on PRs, so will take extra effort to confirm they work and get them merged.  After this one is solved, the other related enhancements can be tested using CI on PRs.

(However, I have been thinking that these 'unsupported' jobs could all be replaced with a single job which installs multiple pythons in the same VM and uses tox to run tests on them all : next enhancement ..)

**Comment by abhishalya** [comment]
How about this @jayvdb 

```py
if __name__ == '__main__':
    pip_version = tuple([int(x) for x in pip.__version__.split('.')])
    if pip_version < (9, 0, 1):
        raise RuntimeError('Version of pip less than 9.0.1 breaking '
                           'Python version requirement')
    setup(name='coala',
```

**Comment by jayvdb** [comment]
yup, that looks better.  Also use distutils.version.LooseVersion , and store `'9.0.1'` in a moban yaml constant so it is easy to change in the future.
