### ISSUE TITLE
Running "coala --json --show-bears --show-details" is raising errors

### ISSUE THREAD

**Issue by KVGarg** [coala/coala#6033]
Build error:
`NotImplementedError: This platform doesn't have any of the specified package manager(s): brew`

OS System: Linux

**Comment by serhii73** [comment]
@KVGarg what the Linux distribution?
What the coala's version?
How are you install coala?

**Comment by KVGarg** [comment]
I guess I was using an earlier version of coala, running this command over latest version of coala and coala-bears master branch. The issue no more exists. It is logging all the bears with all the required information.
