### ISSUE TITLE
ConsoleInteraction.py: `color_letter` function is buggy

### ISSUE THREAD

**Issue by akshatkarani** [coala/coala#6034]
`color_letter` function in ConsoleInteraction module does not work as expected when there is an upper case letter after the upper case letter in parenthesis.
e.g. If input line is `Edit (C)ommit Message` then output is `Edit (M)ommit Message`

**Comment by akshatkarani** [comment]
The problem with the current function is that is loops over all the characters and the last uppercase letter in the line gets highlighted. But it could be the case that the uppercase letter in parenthesis is not the last uppercase letter.

**Comment by priyansh19** [comment]
Just wanna know that is this issue still open for contribution?

**Comment by akshatkarani** [comment]
@priyansh19 No this issue is reserved for GSoC
