### ISSUE TITLE
Setting.py: Include the memory location in all __repr__

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#6050]
The default `__repr__` on CPython emits the memory location of the object.  This should also be done for the coala overrides of `__repr__` in Settings.

**Comment by xiaoguizi87** [comment]
@jayvdb Hey, I'm new here and would like to work on this.

**Comment by imskr** [comment]
I would like to work on this @jayvdb

**Comment by Dilshaad21** [comment]
@jayvdb Can I work onthis issue?

**Comment by Dilshaad21** [comment]
@jayvdb are you asking to return `self.__class__.__name__` for all the `__repr__` functions.

**Comment by sameshl** [comment]
@jayvdb Can you assign me this?
Thanks!

**Comment by sameshl** [comment]
@jayvdb I would like to work on this. Could you elaborate a bit on how I could go about this?

Thanks!

**Comment by Apoorv01017** [comment]
can I work on this issue?

**Comment by Gromy1211** [comment]
Hi, can I be assigned to this?

**Comment by 123vivekr** [comment]
@jayvdb Please assign this issue to me.

**Comment by mitchell-frost** [comment]
I am new here and this issue seems open. Can I work on this?

**Comment by anshalshukla** [comment]
cobot assign https://github.com/coala/coala/issues/6050
