### ISSUE TITLE
Linter.py: Include the memory location in all __repr__

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#6051]
The default `__repr__` on CPython emits the memory location of the object. This should also be done for the coala overrides of `__repr__` in `Linter`.

**Comment by avirlrma** [comment]
@jayvdb Hey, I'm new here and would like to work on this.

**Comment by avirlrma** [comment]
@jayvdb from what I understand I just have to add `hex(id(self))` in all the overloaded implementations of `__repr__` in all the classes in `Linter.py`. Is this correct?

**Comment by jayvdb** [comment]
Yup, bingo.

**Comment by Apoorv01017** [comment]
Can I work on this issue?

**Comment by anshalshukla** [comment]
I'm taking this issue.
