### ISSUE TITLE
ConsoleInteractionTest.py: `test_ask_for_actions_and_apply` defined twice

### ISSUE THREAD

**Issue by akshatkarani** [coala/coala#6056]
Change the name of one of the function to something more appropriate.
difficulty/newcomer

**Comment by charfole** [comment]
Will there be difficulty/newcomer labels with this issue？
I‘m a newcomer so that I want to find the issues with this label to practice.

**Comment by akshatkarani** [comment]
Most probably, but you should only work on this issue after getting assigned. Please read our [Newcomers Guidelines](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html) and [Commit Guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#)

**Comment by charfole** [comment]
Copy that,THANKS!

**Comment by jayvdb** [comment]
@charfole , sorry for the delay - assigned now

**Comment by charfole** [comment]
@jayvdb ，It's OK. Thanks for your assigning.

**Comment by sameshl** [comment]
As there has not been any activity on this issue for more that 15 days, Can someone assign me this. I would love to work on it.

**Comment by RJ722** [comment]
seems like @charfole isn't working on this. assigning @sameshl

**Comment by sameshl** [comment]
@RJ722 I looked at https://github.com/coala/coala/blob/bcee2cd3a1c8e0350181ae58cf95d22953272ee6/tests/output/ConsoleInteractionTest.py#L552-L588 but was not able to figure out a better way to rename them. Could you please help me out?

Thanks!

**Comment by RJ722** [comment]
It seems like the both the functions are mostly identical and that the first function is also additionally testing with `DoNothingAction`. This leads to a lot of code being duplicated - we would ideally want only one test in which both of these conditions could be tested.

One idea off the top of my head to do so would be to have a list of `args` and run the `with` statement within a loop for every `arg` in `args`, but it might take a little poking around to do so.

I'm turning this into a difficulty/low issue. @sameshl you can continue working on this issue and if you face any difficulties, please let us know and we'd be happy to help. :-)

**Comment by Apoorv01017** [comment]
hello, can I  work on this issue

**Comment by Purvanshsingh** [comment]
I am a newcomer can you please assign me this issue?

**Comment by Sohaib03** [comment]
Is this issue open?

**Comment by tyajush** [comment]
Hi I would like to contribute to this issue, can someone please assign me. I am just getting started with open source contributions.

**Comment by sky3760000** [comment]
if the work is not completed, can u please assign me this issue?
