### ISSUE TITLE
Small typo in coalib/output/printers/LogPrinter.py

### ISSUE THREAD

**Issue by timgates42** [coala/coala#6087]
Should read responsibility instead of reponsibility.

**Comment by terminator0309** [comment]
@timgates42 please assign me this issue to me, i am new on github and this will greatly incourage me and will help me a lot...
Thanking you

**Comment by timgates42** [comment]
Oh sorry @terminator0309 I am not a member of coala so I don't believe I can assign issues - but I've actually submitted a fix for this in #6088

**Comment by terminator0309** [comment]
Sir,
I am new to open source development and want to contribute to organisations,
can you guide me how to start all this.
If you can help me, I will be very thankful to you.

**Comment by rajpratyush** [comment]
@abhishalya is this issue open for work
