### ISSUE TITLE
Include Gitter chat button in README.

### ISSUE THREAD

**Issue by Krythz43** [coala/coala#6092]
The current README contains a text hyperlink that links to the Gitter chat room. This could be replaced with a "Chat on Gitter" button. This could be considered a difficulty/newcomer issue.

**Comment by 2knal** [comment]
Hi there, I would like to work on this issue.

**Comment by Krythz43** [comment]
@jayvdb Am sorry for tagging you despite your busy schedule, can you please assign me to work on this and add me to the newcomer group?

**Comment by abhishalya** [comment]
Closing this as it's not really required.
