### ISSUE TITLE
How to join Coala?

### ISSUE THREAD

**Issue by KumarOjas** [coala/coala#6098]

**Comment by hedonhermdev** [comment]
If you are interested in contributing to Coala then check out https://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by abhishalya** [comment]
Here are few steps:
1. Join Gitter room: https://gitter.im/coala/coala
2. Request access to https://gitlab.com/coala/roles/newcomers
3. Read coala.io/newcomer
4. Ping me on the issue which you'd like to work on.
