### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by abhishalya** [coala/coala#6110]
Major blocker for now.

**Comment by reibelj** [comment]
This issue is currently being worked on by myself and another group of students. As part of a computer science course from Allegheny College, my team and I are working towards contributing to open source code and have chosen to contribute to this project.

**Comment by cathlinlord** [comment]
@abhishalya Our group (the group previously mentioned by reibelj) is wondering what the desired use of Travis is and if the inclusion of Python 3.4 is necessary for this project? We are hoping to get a better understanding of the overall goal, so we can contribute to solving this issue.

**Comment by abhishalya** [comment]
It's fine to drop Python 3.4, coala would get out of the dependency hell.
