### ISSUE TITLE
Update URL of Travis CI in Adding_CI.rst

### ISSUE THREAD

**Issue by anshalshukla** [coala/coala#6138]
Since we have migrated the repository from travis org to com, the link in [docs/Developers/Adding_CI.rst](https://github.com/coala/coala/blob/master/docs/Developers/Adding_CI.rst) should be updated.

Changes Requested
[https://travis-ci.org/coala/coala/](https://travis-ci.org/coala/coala/) -> [https://travis-ci.com/coala/coala/](https://travis-ci.com/coala/coala/) 
[https://travis-ci.org/coala/coala-bears/](https://travis-ci.org/coala/coala-bears/) -> [https://travis-ci.com/coala/coala-bears/](https://travis-ci.com/coala/coala-bears/)
[travis-ci.org](https://travis-ci.org) ->[travis-ci.com](https://travis-ci.com)

difficulty/newcomer

**Comment by athirai-s** [comment]
i would like to work on it

**Comment by Th3nn3ss** [comment]
I will like to assist with this.

**Comment by athirai-s** [comment]
okay :)
