### ISSUE TITLE
Link Does not exist

### ISSUE THREAD

**Issue by anshalshukla** [coala/coala#6160]
link present on line 77 of docs/Developers/Development_Setup.rst does not exist. Remove line 75-77 to fix this.

difficulty/newcomer

**Comment by erik-tastepe** [comment]
Hey what's up, I can take care of this

**Comment by anshalshukla** [comment]
Go ahead!

**Comment by DestroyerAlpha** [comment]
Added a PR for this issue. Please review @anshalshukla
