### ISSUE TITLE
Add pytest to requirements.txt

### ISSUE THREAD

**Issue by anshalshukla** [coala/coala#6161]
Exception raised while trying to collect bears:
ModuleNotFoundError: No module named 'pytest'

To reproduce the error install coala and bears with `pip install -e  .` and try to run coala

Add pytest to the requirements.txt file and make the same changes in mobans to keep the pipeline green. 

difficulty/newcomer

**Comment by pra17dod** [comment]
Hi @anshalshukla, I would like to work on this issue. Could you please assign me?

**Comment by anshalshukla** [comment]
@pra17dod you can start working on it

**Comment by pra17dod** [comment]
Hi @anshalshukla , can you please review the PR #6162.

**Comment by anshalshukla** [comment]
@pra17dod, I don't think this is sufficient; by moban, I meant moban repository on coala GitLab. Also, set up a Travis ci to test if the changes don't break the pipeline. You can find the steps to set up CI at your repo in docs/Developers/Adding_CI.rst

**Comment by pra17dod** [comment]
@anshalshukla Thanks for your review. I will set up Travis CI. Can you further elaborate what changes needed to be made for moban, I am not getting it.

**Comment by anshalshukla** [comment]
@pra17dod, start by making the changes on coala. Make sure you test the changes locally and fix the mentioned bug. Changes on requirements.txt needs to be made uniform with the [Moban](https://gitlab.com/coala/mobans/-/tree/master/) repository. You'll get the hint for moban changes by the error log of Travis CI.

**Comment by pra17dod** [comment]
@anshalshukla thank you. Will look into it.

**Comment by pra17dod** [comment]
@anshalshukla, @abhishalya [Here](https://travis-ci.com/github/pra17dod/coala/builds/222690798) is the Travis Build log on my fork. Please review it.

**Comment by anshalshukla** [comment]
@pra17dod NoModuleError is probably due to improper installation, you can refer to [this](http://docs.coala.io/en/latest/Users/Install.html).
Also before making changes I'd suggest try using coala locally on any of your projects or use the example given in the [tutorial](http://docs.coala.io/en/latest/Users/Tutorial.html)

**Comment by pra17dod** [comment]
@anshalshukla I meant to say everything is working fine locally. I have already followed the links you have mentioned.

**Comment by anshalshukla** [comment]
I think the screenshot here is unrelated. Your pipeline breaks because of the improper commit message. There should be a blank line between the shortlog and the body of the commit message.

**Comment by pra17dod** [comment]
Hi @anshalshukla, the PR passed the Travis CI build [here](https://travis-ci.com/github/pra17dod/coala/builds/222694545). Can you tell me what next to do?

**Comment by abhishalya** [comment]
Invalid issue, pytest would never be a part of requirements. It is only used to run tests and is not used to run coala.
