### ISSUE TITLE
Travis build failure due to setuptools-git

### ISSUE THREAD

**Issue by abhishalya** [coala/coala#6165]
From [build](https://travis-ci.com/github/coala/coala/jobs/505462177):

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-git')
```

**Comment by abhishalya** [comment]
@anshalshukla Can you take a look at this once? Not sure if this is an intermittent issue

**Comment by anshalshukla** [comment]
Yeah, definitely.
