### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by sils** [coala/coala#894]
I just tried out some gitlab stuff. It's great. I can even configure that a PR needs two approvals (one from the author, one from a reviewer). GitLab CI is just great, they have a Web UI that is very responsible and is configurable via an YML file and GitLab CI runs on all platforms - windows, linux mac - allowing us to unify everything to one configuration file.

Here comes the drawback: if we want multi platform builds we'll need an own server. I can provide that because it's cool. I imagine some solution where we have three VMs (one for each platform) running on my home server or even a dedicated machine in some future. This has a few nice performance benefits because we can pre install dependencies and we can _just_ run the tests, reducing build times by far.

Opinions? I'm happy to leave GitHub behind and finally be able to prevent people technically from pushing to master :)

**Comment by sils1297** [comment]
heh, I really like this:

```
lasse@lssteadarch ~/prog/PyPrint (git)-[sils/test] % g ce
[sils/test 916b46a] serarch
...
lasse@lssteadarch ~/prog/PyPrint (git)-[sils/test] % g pf
...
remote: GitLab: Commit message does not follow the pattern
To git@gitlab.com:coala-group/PyPrint.git
 ! [remote rejected] sils/test -> sils/test (pre-receive hook declined)
error: failed to push some refs to 'git@gitlab.com:coala-group/PyPrint.git'
```

**Comment by Makman2** [comment]
yeah GitLab is indeed cool.
Would be nice if you sponsor a server, I can help you with setting it up (I already have a working GitLab installation locally on Ubuntu Server 14.04).
But some things I would do:
- Mirror the local server/repositories on the public one so we have 24/7 access if something goes wrong
- And also mirror on github :)
If we have luck we maybe find a sponsor that gives us a completely configurable VM (maybe Koding), so we don't need to keep your LEDs on :)

**Comment by AbdealiJK** [comment]
Have you checked gitlab - CI ? It doesnt have public containers like travis
and so on. It has 4 linux systems - and everyone installs dependencies
there.

Unless you get your own server for gitlab-ci, it'll be pretty slow

**Comment by sils1297** [comment]
This migration would be nice, but we have more important stuff to do so this is something for some far future IMO. Just wanted to state that.

**Comment by jayvdb** [comment]
Regarding the drawback, does that mean that developer builds in forks (not PRs) need to provide their own workers if build is multi-platform/environment?

With GitLab, is it possible to use other CI environments?

Will the code still be replicated to GitHub?
As the code is in GitHub, I was able to do some [quick](https://travis-ci.org/jayvdb/coala/builds/159588840) Travis builds on precise, uncovering #2752 and #2751.
I can also do more bizarre testing using Bitrise (like testing it on Android). etc. etc.
IMO having other working CI services is better, even if the core team uses GitLab, and disables the other CI services as part of the PR process.

**Comment by sils1297** [comment]
When we migrate the core repositories there will definitely be a mirror (which might be lagging a few minutes behind and won't be used for development).

You can hook up other CI to GitLab, e.g. we use AppVeyor already for [PyPrint](https://gitlab.com/coala/PyPrint/).

You shouldn't need any own runners since GitLab.com provides unlimited runners for linux for free. Not sure about appveyor builds from forks.

**Comment by adtac** [comment]
Welp, Gitlab just had a major database issue - someone accidently ran `rm -rf` on their postgres database. And all five of their backup measures failed them. Doesn't help the case :(

**Comment by Makman2** [comment]
yeah never do `rm -rf` on production without copying it somewhere else... though this is the first incident I heard of^^ Still the features do justify a switch^^

**Comment by jayvdb** [comment]
I cant see this happening while we are using gitter as the primary chat system, as the usernames are only linked correctly on github, and our processes and tools rely on that.

**Comment by Makman2** [comment]
I would pledge to close this issue. As long as we really don't have a really important reason to switch, it's currently not worth it (also because of our publicity being on GitHub).

Feel free to reopen if someone disagrees and has a reason :+1:
