### ISSUE TITLE
coala-dbus: log the stuff to /var/log or so

### ISSUE THREAD

**Issue by sils** [coala/coala#913]
we want them to be accessible somehow, right?

**Comment by Makman2** [comment]
what exactly do you want to have logged? Some verbose messages or every communication?

**Comment by sils1297** [comment]
we should have a LogPrinter for that and then want to use that for coala dbus and so on. There are probably conventions about how to log that kind of stuff.

**Comment by sils** [comment]
not happening, we're throwing away dbus
