### ISSUE TITLE
Make use of the `logging` module

### ISSUE THREAD

**Issue by Makman2** [coala/coala#975]
This would allow to keep some components more standalone that issue warnings, because we don't need to pass a printer to them^^
The warning messages can be fetched in the coala analyzation process where they can be printed:

``` python
import warnings

with warnings.catch_warnings(record=True) as w:
    # No panic, after exiting the context manager the previous filter value is restored.
    warnings.simplefilter("always")
    a_task_that_can_issue_warnings(...)
    # 'w' contains now all warning messages (more precise, WarningMessage objects).
    # We can print them with some 'warnings' functions and redirect them to our
    # logprinter inside the coala toolchain.
    for warning in w:
        # Sadly this won't work, we need to pass each member of `warning` to formatwarning().
        log_printer.print(warnings.formatwarning(warning))
```

**Comment by sils1297** [comment]
@Makman2 can we put helper methods into the LogPrinter class to make warnings more convenient? I'm still not sure about this, it allows us to pass less parameters indeed, which is good, but IMO we should print warnings right when they occur.

**Comment by Makman2** [comment]
Maybe we can make our own module using `warnings` and implement something like a callback mechanism. Just an idea^^

**Comment by sils1297** [comment]
@Makman2 something like a ... LogPrinter!?

**Comment by Makman2** [comment]
but without needing a parameter :O (was just an idea...)

**Comment by fneu** [comment]
@Makman2 @sils1297 

well, a long time ago we were planning to use the [python logging}(https://docs.python.org/3.4/library/logging.html) module which would allow us to do a lot of fancy logging stuff without passing a printer around everywhere.

Might we worth another look, but this would probably be quite the task to introduce this everywhere.

**Comment by sils1297** [comment]
@fneu any advantage of the python builtin logging?

**Comment by fneu** [comment]
@sils1297 @Makman2 please take a look at [PEP282](https://www.python.org/dev/peps/pep-0282/) for a quick introduction and some examples of the [logging module](https://docs.python.org/3.4/library/logging.html). 

key features:

* different logging streams (main applications, bears, ...) 
    * separately configurable
    * hierarchically ordered, settings are propagated downwards
* no passing around of logger objects. 
    * `import logging; logging.getLogger(name)`
* levels of logging:
    * DEBUG
    * INFO
    * WARN
    * ERROR
    * CRITICAL

especially now after the removal of i18n this might be worth a though, although I'm not sure it is worth the effort. Might be more clean though :)

**Comment by fneu** [comment]
It can also be integrated with the warning module!

**Comment by sils1297** [comment]
I personally think this would be a good thing to do. Not that I'd have time
for it...

2016-01-06 15:46 GMT+01:00 Fabian Neuschmidt <notifications@github.com>:

**Comment by Makman2** [comment]
@fneu Looks cool. If you want you can assign me, though that's not priority for me now :)

**Comment by sils1297** [comment]
Ok, we probably can use `multiprocessing.get_logger()` to get loggers that work over processes, not sure how to get them named though... maybe we can just take a `logging` logger and pass it through to the other processes? Maybe we can just get a logger in the bears automatically associating it with the bear?

**Comment by sils1297** [comment]
```
>>> import logging
>>> def f(a):
...  logging.getLogger('f').warning(str(a))
... 
>>> f(2)
2
>>> import multiprocessing
>>> multiprocessing.Pool(4).map(f, [1,2,3,4])
1
2
4
3
[None, None, None, None]
>>> 
```

we should read up on logging being process safe or not

**Comment by sils1297** [comment]
```
>>> logger = logging.getLogger('f')
>>> logger.setLevel(logging.ERROR)
>>> logger.warning('test')
>>> multiprocessing.Pool(4).map(f, [1,2,3,4])
[None, None, None, None]
>>> 
```

**Comment by fneu** [comment]
I have no idea. Did not expect this to work at all, and we could still just 
pass messages back by queue and log them later, but multiprocess-logging 
would be really cool


Am 10. Januar 2016 18:13:03 schrieb Lasse Schuirmann 
<notifications@github.com>:

**Comment by Makman2** [comment]
@sils1297 In the PEP I remember that is possible to use a different logger-class when getting it via `getLogger`. So we just implement our own multiprocessing-capable one and we are good to go.

**Comment by Makman2** [comment]
No need for it in the next-generation bear design, log messages are still passed through the pipe, that's just easier^^

**Comment by Uran198** [comment]
What is the status on this one? It's very wrong that bears inherit from printers.

**Comment by fneu** [comment]
@Uran198 bears are getting reworked so let's see how that turns out. Generally I still think this is a good idea although I have no personal experience with the logging module.

**Comment by Uran198** [comment]
I think it would be even good just to use existing logger, but don't inherit bears from it. Should this issue have label blocked, or something?

**Comment by sils1297** [comment]
Hm, I don't really think this is blocked, it needs a concept first and @Makman2 s work on the next bear gen. will take a while.

**Comment by Makman2** [comment]
maybe we don't need the next-gen stuff. Let's try to implement it already^^

**Comment by Makman2** [comment]
@fneu are you willing to do this? otherwise I would take it over^^

**Comment by fneu** [comment]
@Makman2 feel free :D

**Comment by underyx** [comment]
If your main issue is that you don't want to pass around the printer everywhere, maybe you could just save it in thread local storage upon initialization and get it from there at the top of each module?

**Comment by sils1297** [comment]
well, I think changing to a builtin logging instead of an own custom thing
is a sane thing to do anyway, not?

**Comment by underyx** [comment]
It is, it just wasn't clear from the above discussion if that's what you
really want right now.

**Comment by sils1297** [comment]
prototype for a way we could switch: https://github.com/coala-analyzer/coala/pull/2314

**Comment by Uran198** [comment]
So, the default logging [supports threading](https://docs.python.org/3/library/logging.html#thread-safety).

To produce output with colours, we can write custom handlers, which isn't hard, though can be a little tricky. ([here](https://gist.github.com/Uran198/6b5bd73447108038b886660043fdc355) is a small gist, we can use ConsolePrinter's print for colour printing). Also, for json output, you can use for example [QueueHandler](https://docs.python.org/3/library/logging.handlers.html#queuehandler).
The hard part is that logging works differently then current coala logging.
logging wants you to have one logger or hierarchy of loggers, while with coala you can have random amount of loggers not related to each other in any fashion. Setting up new logger for each LogPrinter wouldn't make much sense. Another possibility is to configure logger once and then just use it every time in LogPrinter, but in this case all the parameters passed to it would make no sense, as we've already configured logger.
Also, I don't see much sense now in switching to the default logging. Well, I think it will be a good thing, but it's really a lot of effort. Are advantages that it will bring really worth it?
Maybe a good first step will be to have some default LogPrinter, so we won't have to carry that around.

**Comment by Uran198** [comment]
[Here](https://github.com/coala-analyzer/coala/pull/2409) is a possible way of implementing it.
Maybe there is better approach that I'm missing.

**Comment by Uran198** [comment]
For now I implemented the approach I mentioned above with the difference that there is logger for every type of printer and optionally for every instance.
Next I think would be good to do the following:

* Limit total number of different loggers (coloured, not coloured, list, queue)
* Move configuration of the loggers to the file. Probably have different files with configuration for coala, coala-ci, etc.
* Fix testing to use [`assertLogs`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertLogs).

But I think it's better to go toward it after merging current changes, so that logging can be used without passing logger around.

**Comment by AbdealiJK** [comment]
Just found a library to get colored output for python's logging already - https://pypi.python.org/pypi/colorlog
Possibly we can eliminate the need for pyprint's ColorPrinter, or add it to pyprint and make LogPrinters there ?

**Comment by Makman2** [comment]
@AbdealiJK very cool :+1:

**Comment by Uran198** [comment]
I don't feel very good about adding more dependencies. I've already implemented colored logging with the use of custom formatter, which do not depend on ColorPrinter, as well. The code is small and straight forward, not sure if there is a point in using library for that.

**Comment by Makman2** [comment]
if the library is small itself then this shouldn't hinder us. Also this moves maintenance work from our project to their's and should also raise the quality of our code, as their project deals completely with the colored-logging-problem :+1:

**Comment by sils** [comment]
the basic switch has been done, we're still using LogPrinter all over the place which we have to remove.

**Comment by sils** [comment]
and consoleprinter, @cylussec did I get it right that you have some pending work on this?

**Comment by cylussec** [comment]
I am doing some work related to this in ticket https://github.com/coala/coala/issues/2044#issuecomment-256189541. I just pushed some of my initial work to my fork... you mind taking a look at that issue and make sure I am going the right direction?

**Comment by nemaniarjun** [comment]
What's the status here? Which files are up next for removing `log_printer`? I would like to work on this.

**Comment by sils** [comment]
Uhm last  thing I knew was that @tulphoon was working on this.

**Comment by tulphoon** [comment]
Removing log_printer from ConsoleInteraction.py is crucial for some stuff that Makman has to do and if you want to take it, do it @nemaniarjun. I kinda don't have the time to do it right now ;(

**Comment by Makman2** [comment]
no hurry, actually it has turned out to be not so crucial^^

> if you want to take it, do it @nemaniarjun.

Assigning then ;)

**Comment by jayvdb** [comment]
This is mostly done iirc?

**Comment by tulphoon** [comment]
> This is mostly done iirc?

Take a look here: https://github.com/coala/coala/pull/4608

**Comment by jayvdb** [comment]
Done in https://github.com/coala/coala/pull/4608
